REM [000][MSTTEN_UPDKEY]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAIF.MSTTEN_UPDKEY(店舗基本マスタ更新キー) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAIF.MSTTEN_UPDKEY IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIF.MSTTEN_UPDKEY(店舗基本マスタ更新キー) ロード処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.MSTTEN_UPDKEY;INSERT IGNORE INTO INAIF.MSTTEN_UPDKEY SELECT TEN.TENCD FROM INAMS2.MSTTEN TEN WHERE TEN.SENDFLG IN (0, 9);COMMIT;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.MSTTEN_UPDKEY">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
