REM [000][SYSBATCHDT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAPARM.SYSBATCHDT MERGE処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INAPARM.SYSBATCHDT(SMODE, DT, DT_INT, DTTIME, DTTIME_INT, YOBI) SELECT * FROM (SELECT 'DAILY' AS SMODE, CAST(CAST(MAX(A.SHORIDT) AS CHAR) AS DATETIME) AS DT, MAX(A.SHORIDT) AS DT_INT, CAST(CAST(MAX(A.SHORIDT) AS CHAR) AS DATETIME) AS DTTIME, CAST(CAST(CAST(MAX(A.SHORIDT) AS CHAR) AS DATETIME) AS SIGNED) AS DTTIME_INT, WEEKDAY(CAST(CAST(MAX(A.SHORIDT) AS CHAR) AS DATETIME)) + 1 AS YOBI FROM (SELECT CAST(DATE_FORMAT(CAST(CAST(AA.SHORIDT AS CHAR) AS DATETIME) + INTERVAL 1 DAY, '%%Y%%m%%d') AS SIGNED) AS SHORIDT FROM INAAD.SYSSHORIDT AA) A) T2 ON DUPLICATE KEY UPDATE DT = T2.DT, DT_INT = T2.DT_INT, DTTIME = T2.DTTIME, DTTIME_INT = T2.DTTIME_INT, YOBI = T2.YOBI;COMMIT">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR




:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
