REM [000][SYSBATCHDT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2



SET MSG=%DATE% %TIME% INAMS2.MSTSIRGPSHN DELETE処理(仕入グループ商品マスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM 自データと一致情報を削除
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSIRGPSHN SGS WHERE SGS.SHNCD IN (SELECT SY.SHNCD FROM INAMS2.MSTSIRGPSHN_Y SY WHERE SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1));COMMIT;">>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME% INAMS2.MSTSIRGPSHN LOAD処理(仕入グループ商品マスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAMS2.MSTSIRGPSHN SELECT SHNCD, TENGPCD, YOYAKUDT, AREAKBN, SIRCD, HSPTN, SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAMS2.MSTSIRGPSHN_Y SGSY WHERE EXISTS (SELECT 1 FROM (SELECT SY.SHNCD, SY.YOYAKUDT FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1)) T2 WHERE SGSY.SHNCD = T2.SHNCD AND SGSY.YOYAKUDT = T2.YOYAKUDT);COMMIT;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAMS2.MSTSIRGPSHN_Y DELETE処理(仕入グループ商品マスタ_予約)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSIRGPSHN_Y SGSY WHERE EXISTS (SELECT 1 FROM (SELECT SY.SHNCD, SY.YOYAKUDT FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1)) T2 WHERE SGSY.SHNCD = T2.SHNCD AND SGSY.YOYAKUDT = T2.YOYAKUDT);COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


SET MSG=%DATE% %TIME% INAMS2.MSTBAIKACTL DELETE処理(売価コントロールマスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM 自データと一致情報を削除
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTBAIKACTL BC WHERE BC.SHNCD IN (SELECT SY.SHNCD FROM INAMS2.MSTBAIKACTL_Y SY WHERE SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1));COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME% INAMS2.MSTBAIKACTL LOAD処理(売価コントロールマスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAMS2.MSTBAIKACTL SELECT SHNCD, TENGPCD, YOYAKUDT, AREAKBN, GENKAAM, BAIKAAM, IRISU, SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAMS2.MSTBAIKACTL_Y BCY WHERE EXISTS (SELECT 1 FROM (SELECT SY.SHNCD, SY.YOYAKUDT FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1)) T2 WHERE BCY.SHNCD = T2.SHNCD AND BCY.YOYAKUDT = T2.YOYAKUDT);COMMIT;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAMS2.MSTBAIKACTL_Y DELETE処理(売価コントロールマスタ_予約)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTBAIKACTL_Y BCY WHERE EXISTS (SELECT 1 FROM (SELECT SY.SHNCD, SY.YOYAKUDT FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1)) T2 WHERE BCY.SHNCD = T2.SHNCD AND BCY.YOYAKUDT = T2.YOYAKUDT);COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


SET MSG=%DATE% %TIME% INAMS2.MSTSRCCD DELETE処理(ソースコード管理マスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM 自データと一致情報を削除
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSRCCD SC WHERE SC.SHNCD IN (SELECT SY.SHNCD FROM INAMS2.MSTSRCCD_Y SY WHERE SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1));COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME% INAMS2.MSTSRCCD LOAD処理(ソースコード管理マスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAMS2.MSTSRCCD SELECT SHNCD, SRCCD, YOYAKUDT, SEQNO, SOURCEKBN, SENDFLG, OPERATOR, ADDDT, UPDDT, YUKO_STDT, YUKO_EDDT FROM INAMS2.MSTSRCCD_Y SCY WHERE EXISTS (SELECT 1 FROM (SELECT SY.SHNCD, SY.YOYAKUDT FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1)) T2 WHERE SCY.SHNCD = T2.SHNCD AND SCY.YOYAKUDT = T2.YOYAKUDT) ; COMMIT ;">>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


SET MSG=%DATE% %TIME% INAMS2.MSTSRCCD_Y DELETE処理(ソースコード管理マスタ_予約)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSRCCD_Y SCY WHERE EXISTS (SELECT 1 FROM (SELECT SY.SHNCD, SY.YOYAKUDT FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1)) T2 WHERE SCY.SHNCD = T2.SHNCD AND SCY.YOYAKUDT = T2.YOYAKUDT);COMMIT;"  >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


REM 削除前データの保持
SET MSG=%DATE% %TIME% INAWK.MSTSHN LOAD処理(商品マスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.MSTSHN;INSERT IGNORE INTO INAWK.MSTSHN SELECT SHNCD, YOYAKUDT, TENBAIKADT, YOT_BMNCD, YOT_DAICD, YOT_CHUCD, YOT_SHOCD, URI_BMNCD, URI_DAICD, URI_CHUCD, URI_SHOCD, BMNCD, DAICD, CHUCD, SHOCD, SSHOCD, ATSUK_STDT, ATSUK_EDDT, TEISHIKBN, SHNAN, SHNKN, PCARDKN, POPKN, RECEIPTAN, RECEIPTKN, PCKBN, KAKOKBN, ICHIBAKBN, SHNKBN, SANCHIKN, SSIRCD, HSPTN, RG_ATSUKFLG, RG_GENKAAM, RG_BAIKAAM, RG_IRISU, RG_IDENFLG, RG_WAPNFLG, HS_ATSUKFLG, HS_GENKAAM, HS_BAIKAAM, HS_IRISU, HS_WAPNFLG, HS_SPOTMINSU, HP_SWAPNFLG, KIKKN, UP_YORYOSU, UP_TYORYOSU, UP_TANIKBN, SHNYOKOSZ, SHNTATESZ, SHNOKUSZ, SHNJRYOSZ, PBKBN, KOMONOKBM, TANAOROKBN, TEIKEIKBN, ODS_HARUSU, ODS_NATSUSU, ODS_AKISU, ODS_FUYUSU, ODS_NYUKASU, ODS_NEBIKISU, PCARD_SHUKBN, PCARD_IROKBN, ZEIKBN, ZEIRTKBN, ZEIRTKBN_OLD, ZEIRTHENKODT, SEIZOGENNISU, TEIKANKBN, MAKERCD, IMPORTKBN, SIWAKEKBN, HENPIN_KBN, TAISHONENSU, CALORIESU, ELPFLG, BELLMARKFLG, RECYCLEFLG, ECOFLG, HZI_YOTO, HZI_ZAISHITU, HZI_RECYCLE, KIKANKBN, SHUKYUKBN, DOSU, CHINRETUCD, DANTUMICD, KASANARICD, KASANARISZ, ASSHUKURT, SHUBETUCD, URICD, SALESCOMKN, URABARIKBN, PCARD_OPFLG, PARENTCD, BINKBN, HAT_MONKBN, HAT_TUEKBN, HAT_WEDKBN, HAT_THUKBN, HAT_FRIKBN, HAT_SATKBN, HAT_SUNKBN, READTMPTN, SIMEKAISU, IRYOREFLG, TOROKUMOTO, UPDKBN, SENDFLG, OPERATOR, ADDDT, UPDDT, K_HONKB, K_WAPNFLG_R, K_WAPNFLG_H, K_TORIKB, ITFCD, CENTER_IRISU FROM INAMS2.MSTSHN ; COMMIT ;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


SET MSG=%DATE% %TIME% INAMS2.MSTSHN DELETE処理(商品マスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSHN SHN WHERE SHN.SHNCD IN (SELECT SY.SHNCD FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1));commit" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME% INAMS2.MSTSHN LOAD処理(商品マスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAMS2.MSTSHN SELECT SHNY.SHNCD, SHNY.YOYAKUDT, SHNY.TENBAIKADT, SHNY.YOT_BMNCD, SHNY.YOT_DAICD, SHNY.YOT_CHUCD, SHNY.YOT_SHOCD, SHNY.URI_BMNCD, SHNY.URI_DAICD, SHNY.URI_CHUCD, SHNY.URI_SHOCD, SHNY.BMNCD, SHNY.DAICD, SHNY.CHUCD, SHNY.SHOCD, SHNY.SSHOCD, SHNY.ATSUK_STDT, SHNY.ATSUK_EDDT, SHNY.TEISHIKBN, SHNY.SHNAN, SHNY.SHNKN, SHNY.PCARDKN, SHNY.POPKN, SHNY.RECEIPTAN, SHNY.RECEIPTKN, SHNY.PCKBN, SHNY.KAKOKBN, SHNY.ICHIBAKBN, SHNY.SHNKBN, SHNY.SANCHIKN, SHNY.SSIRCD, SHNY.HSPTN, SHNY.RG_ATSUKFLG, SHNY.RG_GENKAAM, SHNY.RG_BAIKAAM, SHNY.RG_IRISU, SHNY.RG_IDENFLG, SHNY.RG_WAPNFLG, SHNY.HS_ATSUKFLG, SHNY.HS_GENKAAM, SHNY.HS_BAIKAAM, SHNY.HS_IRISU, SHNY.HS_WAPNFLG, SHNY.HS_SPOTMINSU, SHNY.HP_SWAPNFLG, SHNY.KIKKN, SHNY.UP_YORYOSU, SHNY.UP_TYORYOSU, SHNY.UP_TANIKBN, SHNY.SHNYOKOSZ, SHNY.SHNTATESZ, SHNY.SHNOKUSZ, SHNY.SHNJRYOSZ, SHNY.PBKBN, SHNY.KOMONOKBM, SHNY.TANAOROKBN, SHNY.TEIKEIKBN, SHNY.ODS_HARUSU, SHNY.ODS_NATSUSU, SHNY.ODS_AKISU, SHNY.ODS_FUYUSU, SHNY.ODS_NYUKASU, SHNY.ODS_NEBIKISU, SHNY.PCARD_SHUKBN, SHNY.PCARD_IROKBN, SHNY.ZEIKBN, SHNY.ZEIRTKBN, SHNY.ZEIRTKBN_OLD, SHNY.ZEIRTHENKODT, SHNY.SEIZOGENNISU, SHNY.TEIKANKBN, SHNY.MAKERCD, SHNY.IMPORTKBN, SHNY.SIWAKEKBN, SHNY.HENPIN_KBN, SHNY.TAISHONENSU, SHNY.CALORIESU, SHNY.ELPFLG, SHNY.BELLMARKFLG, SHNY.RECYCLEFLG, SHNY.ECOFLG, SHNY.HZI_YOTO, SHNY.HZI_ZAISHITU, SHNY.HZI_RECYCLE, SHNY.KIKANKBN, SHNY.SHUKYUKBN, SHNY.DOSU, SHNY.CHINRETUCD, SHNY.DANTUMICD, SHNY.KASANARICD, SHNY.KASANARISZ, SHNY.ASSHUKURT, SHNY.SHUBETUCD, SHNY.URICD, SHNY.SALESCOMKN, SHNY.URABARIKBN, SHNY.PCARD_OPFLG, SHNY.PARENTCD, SHNY.BINKBN, SHNY.HAT_MONKBN, SHNY.HAT_TUEKBN, SHNY.HAT_WEDKBN, SHNY.HAT_THUKBN, SHNY.HAT_FRIKBN, SHNY.HAT_SATKBN, SHNY.HAT_SUNKBN, SHNY.READTMPTN, SHNY.SIMEKAISU, SHNY.IRYOREFLG, SHNY.TOROKUMOTO, SHNY.UPDKBN, SHNY.SENDFLG, SHNY.OPERATOR, CASE WHEN SHN.SHNCD IS NULL THEN SHNY.ADDDT WHEN SHN.UPDKBN <> 1 THEN SHN.ADDDT ELSE SHNY.ADDDT END ADDDT, CAST(SHNY.YOYAKUDT AS DATETIME) AS UPDDT, SHNY.K_HONKB, SHNY.K_WAPNFLG_R, SHNY.K_WAPNFLG_H, SHNY.K_TORIKB, SHNY.ITFCD, SHNY.CENTER_IRISU FROM INAMS2.MSTSHN_Y SHNY LEFT OUTER JOIN INAWK.MSTSHN SHN ON SHNY.SHNCD = SHN.SHNCD WHERE SHNY.UPDKBN <> 1 AND SHNY.YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1);COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAMS2.MSTSHN_Y DELETE処理(商品マスタ_予約)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSHN_Y WHERE UPDKBN <> 1 AND YOYAKUDT = (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.ACTIVEFLG = 1);COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
