REM [000][MSTSIR_UPDKEY]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAIF.MSTSIR_UPDKEY(仕入先マスタ更新キー) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAIF.MSTSIR_UPDKEY IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIF.MSTSIR_UPDKEY(仕入先マスタ更新キー) ロード処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.MSTSIR_UPDKEY;INSERT IGNORE INTO INAIF.MSTSIR_UPDKEY WITH SIR AS (SELECT SIR.SIRCD FROM INAMS2.MSTSIR SIR LEFT OUTER JOIN INAPRE.MSTSIR SIR_PD ON SIR.SIRCD = SIR_PD.SIRCD WHERE SIR_PD.SIRCD IS NULL OR SIR.SIRAN <> SIR_PD.SIRAN OR SIR.SIRYOTOKBN <> SIR_PD.SIRYOTOKBN OR SIR.DF_VANKBN <> SIR_PD.DF_VANKBN OR SIR.DF_DENPKBN <> SIR_PD.DF_DENPKBN OR SIR.DF_SHUHKBN <> SIR_PD.DF_SHUHKBN OR SIR.DF_PICKDKBN <> SIR_PD.DF_PICKDKBN OR SIR.DF_PICKLKBN <> SIR_PD.DF_PICKLKBN OR SIR.DF_WAPNKBN <> SIR_PD.DF_WAPNKBN OR SIR.DF_ZDENPKBN <> SIR_PD.DF_ZDENPKBN OR SIR.DF_ZSHUHKBN <> SIR_PD.DF_ZSHUHKBN OR SIR.DF_ZPICKDKBN <> SIR_PD.DF_ZPICKDKBN OR SIR.DF_ZPICKLKBN <> SIR_PD.DF_ZPICKLKBN), AHS AS (SELECT CASE WHEN SIRCD IS NULL THEN SIRCD_1 ELSE SIRCD END AS SIRCD FROM (SELECT AHS.SIRCD AS SIRCD, AHS_PD.SIRCD AS SIRCD_1, AHS.HSPTN AS HSPTN, AHS_PD.HSPTN AS HSPTN_1, AHS.TENGPCD AS TENGPCD, AHS_PD.TENGPCD AS TENGPCD_1, AHS.DENPKBN AS DENPKBN, AHS_PD.DENPKBN AS DENPKBN_1, AHS.SHUHKBN AS SHUHKBN, AHS_PD.SHUHKBN AS SHUHKBN_1, AHS.PICKDKBN AS PICKDKBN, AHS_PD.PICKDKBN AS PICKDKBN_1, AHS.PICKLKBN AS PICKLKBN, AHS_PD.PICKLKBN AS PICKLKBN_1, AHS.WAPNKBN AS WAPNKBN, AHS_PD.WAPNKBN AS WAPNKBN_1 FROM INAMS2.MSTAREAHSPTNSIR AHS LEFT OUTER JOIN INAPRE.MSTAREAHSPTNSIR AHS_PD ON AHS.SIRCD = AHS_PD.SIRCD AND AHS.HSPTN = AHS_PD.HSPTN AND AHS.TENGPCD = AHS_PD.TENGPCD UNION ALL SELECT AHS.SIRCD AS SIRCD, AHS_PD.SIRCD AS SIRCD_1, AHS.HSPTN AS HSPTN, AHS_PD.HSPTN AS HSPTN_1, AHS.TENGPCD AS TENGPCD, AHS_PD.TENGPCD AS TENGPCD_1, AHS.DENPKBN AS DENPKBN, AHS_PD.DENPKBN AS DENPKBN_1, AHS.SHUHKBN AS SHUHKBN, AHS_PD.SHUHKBN AS SHUHKBN_1, AHS.PICKDKBN AS PICKDKBN, AHS_PD.PICKDKBN AS PICKDKBN_1, AHS.PICKLKBN AS PICKLKBN, AHS_PD.PICKLKBN AS PICKLKBN_1, AHS.WAPNKBN AS WAPNKBN, AHS_PD.WAPNKBN AS WAPNKBN_1 FROM INAMS2.MSTAREAHSPTNSIR AHS RIGHT OUTER JOIN INAPRE.MSTAREAHSPTNSIR AHS_PD ON AHS.SIRCD = AHS_PD.SIRCD AND AHS.HSPTN = AHS_PD.HSPTN AND AHS.TENGPCD = AHS_PD.TENGPCD WHERE AHS.SIRCD IS NULL AND AHS.HSPTN IS NULL AND AHS.TENGPCD IS NULL) MT WHERE (SIRCD IS NULL AND (DENPKBN_1 NOT IN ('0', ' ') OR SHUHKBN_1 NOT IN ('0', ' ') OR PICKDKBN_1 NOT IN ('0', ' ') OR PICKLKBN_1 NOT IN ('0', ' ') OR WAPNKBN_1 NOT IN ('0', ' '))) OR (SIRCD_1 IS NULL AND (DENPKBN NOT IN ('0', ' ') OR SHUHKBN NOT IN ('0', ' ') OR PICKDKBN NOT IN ('0', ' ') OR PICKLKBN NOT IN ('0', ' ') OR WAPNKBN NOT IN ('0', ' '))) OR (SIRCD IS NOT NULL AND SIRCD_1 IS NOT NULL AND (DENPKBN <> DENPKBN_1 OR SHUHKBN <> SHUHKBN_1 OR PICKDKBN <> PICKDKBN_1 OR PICKLKBN <> PICKLKBN_1 OR WAPNKBN <> WAPNKBN_1))), HS AS (SELECT CASE WHEN SIRCD IS NULL THEN SIRCD_1 ELSE SIRCD END AS SIRCD FROM (SELECT HS.SIRCD AS SIRCD, HS_PD.SIRCD AS SIRCD_1, HS.HSPTN AS HSPTN, HS_PD.HSPTN AS HSPTN_1, HS.DENPKBN AS DENPKBN, HS_PD.DENPKBN AS DENPKBN_1, HS.SHUHKBN AS SHUHKBN, HS_PD.SHUHKBN AS SHUHKBN_1, HS.PICKDKBN AS PICKDKBN, HS_PD.PICKDKBN AS PICKDKBN_1, HS.PICKLKBN AS PICKLKBN, HS_PD.PICKLKBN AS PICKLKBN_1, HS.WAPNKBN AS WAPNKBN, HS_PD.WAPNKBN AS WAPNKBN_1 FROM INAMS2.MSTHSPTNSIR HS LEFT OUTER JOIN INAPRE.MSTHSPTNSIR HS_PD ON HS.SIRCD = HS_PD.SIRCD AND HS.HSPTN = HS_PD.HSPTN UNION ALL SELECT HS.SIRCD AS SIRCD, HS_PD.SIRCD AS SIRCD_1, HS.HSPTN AS HSPTN, HS_PD.HSPTN AS HSPTN_1, HS.DENPKBN AS DENPKBN, HS_PD.DENPKBN AS DENPKBN_1, HS.SHUHKBN AS SHUHKBN, HS_PD.SHUHKBN AS SHUHKBN_1, HS.PICKDKBN AS PICKDKBN, HS_PD.PICKDKBN AS PICKDKBN_1, HS.PICKLKBN AS PICKLKBN, HS_PD.PICKLKBN AS PICKLKBN_1, HS.WAPNKBN AS WAPNKBN, HS_PD.WAPNKBN AS WAPNKBN_1 FROM INAMS2.MSTHSPTNSIR HS RIGHT OUTER JOIN INAPRE.MSTHSPTNSIR HS_PD ON HS.SIRCD = HS_PD.SIRCD AND HS.HSPTN = HS_PD.HSPTN WHERE HS.SIRCD IS NULL AND HS.HSPTN IS NULL) MT WHERE (SIRCD IS NULL AND (DENPKBN_1 NOT IN ('0', ' ') OR SHUHKBN_1 NOT IN ('0', ' ') OR PICKDKBN_1 NOT IN ('0', ' ') OR PICKLKBN_1 NOT IN ('0', ' ') OR WAPNKBN_1 NOT IN ('0', ' '))) OR (SIRCD_1 IS NULL AND (DENPKBN NOT IN ('0', ' ') OR SHUHKBN NOT IN ('0', ' ') OR PICKDKBN NOT IN ('0', ' ') OR PICKLKBN NOT IN ('0', ' ') OR WAPNKBN NOT IN ('0', ' '))) OR (SIRCD IS NOT NULL AND SIRCD_1 IS NOT NULL AND (DENPKBN <> DENPKBN_1 OR SHUHKBN <> SHUHKBN_1 OR PICKDKBN <> PICKDKBN_1 OR PICKLKBN <> PICKLKBN_1 OR WAPNKBN <> WAPNKBN_1))), CORE AS (SELECT CAST(TRIM(SIR.SIR_CODE) AS SIGNED) AS SIRCD FROM INAAD2.CORESIIRE SIR LEFT OUTER JOIN INAPRE.CORESIIRE SIR_PD ON SIR.SIR_CODE = SIR_PD.SIR_CODE WHERE SIR_PD.SIR_CODE IS NULL OR COALESCE(SIR.SIR_TORI_CODE, '') <> COALESCE(SIR_PD.SIR_TORI_CODE, '') OR COALESCE(SIR.SIR_NAME, '') <> COALESCE(SIR_PD.SIR_NAME, '') OR COALESCE(SIR.SIR_NAME_S, '') <> COALESCE(SIR_PD.SIR_NAME_S, '') OR COALESCE(SIR.SIR_YUBIN_NO, '') <> COALESCE(SIR_PD.SIR_YUBIN_NO, '') OR COALESCE(SIR.SIR_ADR_1, '') <> COALESCE(SIR_PD.SIR_ADR_1, '') OR COALESCE(SIR.SIR_ADR_2, '') <> COALESCE(SIR_PD.SIR_ADR_2, '') OR COALESCE(SIR.SIR_ADR_3, '') <> COALESCE(SIR_PD.SIR_ADR_3, '') OR COALESCE(SIR.SIR_TEL_NO, '') <> COALESCE(SIR_PD.SIR_TEL_NO, '') OR COALESCE(SIR.SIR_FAX_NO, '') <> COALESCE(SIR_PD.SIR_FAX_NO, '') OR COALESCE(SIR.SIR_SAKI_BMN_NAME, '') <> COALESCE(SIR_PD.SIR_SAKI_BMN_NAME, '') OR COALESCE(SIR.SIR_SAKI_SYA_NAME, '') <> COALESCE(SIR_PD.SIR_SAKI_SYA_NAME, '') OR COALESCE(SIR.SIR_JISYA_BMN_CODE, '') <> COALESCE(SIR_PD.SIR_JISYA_BMN_CODE, '') OR COALESCE(SIR.SIR_JISYA_SYA_CODE, '') <> COALESCE(SIR_PD.SIR_JISYA_SYA_CODE, '') OR COALESCE(SIR.SIR_APPSTR_DATE, '') <> COALESCE(SIR_PD.SIR_APPSTR_DATE, '') OR COALESCE(SIR.SIR_APPEND_DATE, '') <> COALESCE(SIR_PD.SIR_APPEND_DATE, '') OR COALESCE(SIR.UPDT_ID, '') <> COALESCE(SIR_PD.UPDT_ID, '') OR COALESCE(SIR.UPDT_TAN, '') <> COALESCE(SIR_PD.UPDT_TAN, '') OR COALESCE(SIR.UPDT_DATE, '') <> COALESCE(SIR_PD.UPDT_DATE, '')) SELECT DISTINCT SIRCD FROM (SELECT SIRCD FROM SIR UNION ALL SELECT SIRCD FROM AHS UNION ALL SELECT SIRCD FROM HS UNION ALL SELECT SIRCD FROM CORE) MT;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
LOAD.BAT 呼び出しコード
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.MSTSIR_UPDKEY" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
