REM [002][AEA82]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0002
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO005

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(仕入グループ商品)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e " WITH SGSY AS (SELECT SGSY.* FROM INAMS2.MSTSIRGPSHN_Y SGSY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE SGSY.YOYAKUDT = SBD.DT_INT AND EXISTS (SELECT 1 FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SGSY.SHNCD = SY.SHNCD AND SGSY.YOYAKUDT = SY.YOYAKUDT)), SGS AS (SELECT SGS.* FROM INAMS2.MSTSIRGPSHN SGS WHERE EXISTS (SELECT 1 FROM INAMS2.MSTSHN SHN WHERE SHN.SENDFLG IN (0, 9) AND SHN.UPDKBN <> 1 AND SGS.SHNCD = SHN.SHNCD) AND NOT EXISTS (SELECT 1 FROM SGSY WHERE SGS.SHNCD = SGSY.SHNCD)) SELECT CASE WHEN B_SGS.YOYAKU_FLG = 1 THEN 2 WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END || SUBSTR(RPAD(B_SGS.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_SGS.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_SGS.SHNCD, 14, ' '), 9, 6) || LPAD(B_SGS.TENGPCD, 4, 0) || LPAD(B_SGS.YOYAKUDT, 8, 0) || LPAD(B_SGS.AREAKBN, 1, 0) || LPAD(B_SGS.SIRCD, 6, 0) || LPAD(B_SGS.HSPTN, 3, 0) || '       ' || RPAD(B_SGS.OPERATOR, 20, ' ') || LPAD(B_SGS.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(B_SGS.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_SGS.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM (SELECT 0 AS YOYAKU_FLG, SGS.* FROM SGS UNION ALL SELECT 1 AS YOYAKU_FLG, SGSY.* FROM SGSY) AS B_SGS LEFT OUTER JOIN (SELECT SHNCD FROM INAPRE.MSTSIRGPSHN_PD T1 WHERE EXISTS (SELECT * FROM INAPRE.MSTSHN_PD T2 WHERE UPDKBN <> 1 AND T1.SHNCD = T2.SHNCD) GROUP BY SHNCD) PRE ON B_SGS.SHNCD = PRE.SHNCD ORDER BY B_SGS.SHNCD, B_SGS.TENGPCD;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
