REM [007][AIA59]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0007
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO021

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(平均パック単価)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT SUBSTR(RPAD(APT.SHNCD, 14, ' '), 1, 8) || SUBSTR(RPAD(APT.SHNCD, 14, ' '), 9, 6) || LPAD(APT.AVGPTANKAAM, 5, 0) || '    ' || LPAD(APT.SENDFLG, 1, 0) || RPAD(APT.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(APT.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(APT.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2.MSTAVGPTANKA APT ORDER BY APT.SHNCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
