REM [008][MSTSHN_Y_PD]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAMS2.MSTSHN_Y → INAPRE.MSTSHN_Y_PD ロード処理（商品マスタ_予約(前日処理結果)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAPRE.MSTSHN_Y_PD;INSERT IGNORE INTO INAPRE.MSTSHN_Y_PD SELECT SHNCD, YOYAKUDT, TENBAIKADT, YOT_BMNCD, YOT_DAICD, YOT_CHUCD, YOT_SHOCD, URI_BMNCD, URI_DAICD, URI_CHUCD, URI_SHOCD, BMNCD, DAICD, CHUCD, SHOCD, SSHOCD, ATSUK_STDT, ATSUK_EDDT, TEISHIKBN, SHNAN, SHNKN, PCARDKN, POPKN, RECEIPTAN, RECEIPTKN, PCKBN, KAKOKBN, ICHIBAKBN, SHNKBN, SANCHIKN, SSIRCD, HSPTN, RG_ATSUKFLG, RG_GENKAAM, RG_BAIKAAM, RG_IRISU, RG_IDENFLG, RG_WAPNFLG, HS_ATSUKFLG, HS_GENKAAM, HS_BAIKAAM, HS_IRISU, HS_WAPNFLG, HS_SPOTMINSU, HP_SWAPNFLG, KIKKN, UP_YORYOSU, UP_TYORYOSU, UP_TANIKBN, SHNYOKOSZ, SHNTATESZ, SHNOKUSZ, SHNJRYOSZ, PBKBN, KOMONOKBM, TANAOROKBN, TEIKEIKBN, ODS_HARUSU, ODS_NATSUSU, ODS_AKISU, ODS_FUYUSU, ODS_NYUKASU, ODS_NEBIKISU, PCARD_SHUKBN, PCARD_IROKBN, ZEIKBN, ZEIRTKBN, ZEIRTKBN_OLD, ZEIRTHENKODT, SEIZOGENNISU, TEIKANKBN, MAKERCD, IMPORTKBN, SIWAKEKBN, HENPIN_KBN, TAISHONENSU, CALORIESU, ELPFLG, BELLMARKFLG, RECYCLEFLG, ECOFLG, HZI_YOTO, HZI_ZAISHITU, HZI_RECYCLE, KIKANKBN, SHUKYUKBN, DOSU, CHINRETUCD, DANTUMICD, KASANARICD, KASANARISZ, ASSHUKURT, SHUBETUCD, URICD, SALESCOMKN, URABARIKBN, PCARD_OPFLG, PARENTCD, BINKBN, HAT_MONKBN, HAT_TUEKBN, HAT_WEDKBN, HAT_THUKBN, HAT_FRIKBN, HAT_SATKBN, HAT_SUNKBN, READTMPTN, SIMEKAISU, IRYOREFLG, TOROKUMOTO, UPDKBN, SENDFLG, OPERATOR, ADDDT, UPDDT, K_HONKB, K_WAPNFLG_R, K_WAPNFLG_H, K_TORIKB FROM INAMS2.MSTSHN_Y;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAPRE.MSTSHN_Y_PD" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
