REM [008][AEA81]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0008
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO003

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品基本マスタ(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SY AS (SELECT SY.* FROM INAMS2.MSTSHN_Y SY WHERE SY.SENDFLG IN (0, 9)), JNL1 AS (SELECT SHNCD, YOYAKUDT, MAX(PCARD_OPFLG) AS PCARD_OPFLG FROM INAAD2.JNLSHN WHERE INF_TABLEKBN = 1 AND SENDFLG IN (0, 9) GROUP BY SHNCD, YOYAKUDT), PRE AS (SELECT SHNCD, YOYAKUDT FROM INAPRE.MSTSHN_Y_PD WHERE UPDKBN <> 1) SELECT CASE WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END || COALESCE(JNL1.PCARD_OPFLG, 0) || SUBSTR(RPAD(B_SY.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_SY.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_SY.SHNCD, 14, ' '), 9, 6) || LPAD(B_SY.YOYAKUDT, 8, 0) || LPAD(B_SY.TENBAIKADT, 8, 0) || LPAD(B_SY.YOT_BMNCD, 3, 0) || LPAD(B_SY.YOT_DAICD, 2, 0) || LPAD(B_SY.YOT_CHUCD, 2, 0) || LPAD(B_SY.YOT_SHOCD, 2, 0) || LPAD(B_SY.URI_BMNCD, 3, 0) || LPAD(B_SY.URI_DAICD, 2, 0) || LPAD(B_SY.URI_CHUCD, 2, 0) || LPAD(B_SY.URI_SHOCD, 2, 0) || LPAD(B_SY.BMNCD, 3, 0) || LPAD(B_SY.DAICD, 2, 0) || LPAD(B_SY.CHUCD, 2, 0) || LPAD(B_SY.SHOCD, 2, 0) || LPAD(B_SY.SSHOCD, 1, 0) || LPAD(B_SY.ATSUK_STDT, 8, 0) || LPAD(B_SY.ATSUK_EDDT, 8, 0) || LPAD(B_SY.TEISHIKBN, 1, 0) || RPAD(B_SY.SHNAN, 20, ' ') || RPAD(B_SY.SHNKN, 20, '　') || RPAD(B_SY.PCARDKN, 20, '　') || RPAD(B_SY.POPKN, 20, '　') || RPAD(B_SY.RECEIPTAN, 20, ' ') || RPAD(B_SY.RECEIPTKN, 20, '　') || LPAD(B_SY.PCKBN, 1, 0) || LPAD(B_SY.KAKOKBN, 1, 0) || LPAD(B_SY.ICHIBAKBN, 1, 0) || LPAD(B_SY.SHNKBN, 1, 0) || RPAD(B_SY.SANCHIKN, 20, '　') || LPAD(B_SY.SSIRCD, 6, 0) || LPAD(B_SY.HSPTN, 3, 0) || LPAD(B_SY.RG_ATSUKFLG, 1, 0) || LPAD(CAST(B_SY.RG_GENKAAM * 100 AS SIGNED), 8, 0) || LPAD(B_SY.RG_BAIKAAM, 6, 0) || LPAD(B_SY.RG_IRISU, 3, 0) || LPAD(RPAD(B_SY.RG_IDENFLG, 1, ' '), 1, 0) || LPAD(RPAD(B_SY.RG_WAPNFLG, 1, ' '), 1, 0) || LPAD(B_SY.HS_ATSUKFLG, 1, 0) || LPAD(CAST(B_SY.HS_GENKAAM * 100 AS SIGNED), 8, 0) || LPAD(B_SY.HS_BAIKAAM, 6, 0) || LPAD(B_SY.HS_IRISU, 3, 0) || LPAD(RPAD(B_SY.HS_WAPNFLG, 1, ' '), 1, 0) || LPAD(B_SY.HS_SPOTMINSU, 2, 0) || LPAD(RPAD(B_SY.HP_SWAPNFLG, 1, ' '), 1, 0) || RPAD(B_SY.KIKKN, 23, '　') || LPAD(B_SY.UP_YORYOSU, 5, 0) || LPAD(B_SY.UP_TYORYOSU, 3, 0) || LPAD(B_SY.UP_TANIKBN, 2, 0) || LPAD(B_SY.SHNYOKOSZ, 4, 0) || LPAD(B_SY.SHNTATESZ, 4, 0) || LPAD(B_SY.SHNOKUSZ, 4, 0) || LPAD(CAST(B_SY.SHNJRYOSZ * 10 AS SIGNED), 6, 0) || LPAD(B_SY.PBKBN, 1, 0) || LPAD(B_SY.KOMONOKBM, 2, 0) || LPAD(B_SY.TANAOROKBN, 2, 0) || LPAD(B_SY.TEIKEIKBN, 1, 0) || LPAD(B_SY.ODS_HARUSU, 4, 0) || LPAD(B_SY.ODS_NATSUSU, 4, 0) || LPAD(B_SY.ODS_AKISU, 4, 0) || LPAD(B_SY.ODS_FUYUSU, 4, 0) || LPAD(B_SY.ODS_NYUKASU, 4, 0) || LPAD(B_SY.ODS_NEBIKISU, 4, 0) || LPAD(B_SY.PCARD_SHUKBN, 1, 0) || LPAD(B_SY.PCARD_IROKBN, 1, 0) || LPAD(B_SY.ZEIKBN, 1, 0) || LPAD(B_SY.ZEIRTKBN, 3, 0) || LPAD(B_SY.ZEIRTKBN_OLD, 3, 0) || LPAD(B_SY.ZEIRTHENKODT, 8, 0) || LPAD(B_SY.SEIZOGENNISU, 3, 0) || LPAD(B_SY.TEIKANKBN, 1, 0) || LPAD(B_SY.MAKERCD, 9, 0) || LPAD(B_SY.IMPORTKBN, 2, 0) || LPAD(B_SY.SIWAKEKBN, 2, 0) || LPAD(B_SY.HENPIN_KBN, 1, 0) || LPAD(B_SY.TAISHONENSU, 2, 0) || LPAD(B_SY.CALORIESU, 5, 0) || LPAD(B_SY.ELPFLG, 1, 0) || LPAD(B_SY.BELLMARKFLG, 1, 0) || LPAD(B_SY.RECYCLEFLG, 1, 0) || LPAD(B_SY.ECOFLG, 1, 0) || LPAD(B_SY.HZI_YOTO, 1, 0) || LPAD(B_SY.HZI_ZAISHITU, 1, 0) || LPAD(B_SY.HZI_RECYCLE, 1, 0) || LPAD(RPAD(B_SY.KIKANKBN, 1, ' '), 1, 0) || LPAD(B_SY.SHUKYUKBN, 2, 0) || LPAD(B_SY.DOSU, 3, 0) || LPAD(RPAD(B_SY.CHINRETUCD, 1, ' '), 1, 0) || LPAD(RPAD(B_SY.DANTUMICD, 2, ' '), 2, 0) || LPAD(RPAD(B_SY.KASANARICD, 1, ' '), 1, 0) || LPAD(B_SY.KASANARISZ, 3, 0) || LPAD(B_SY.ASSHUKURT, 2, 0) || LPAD(RPAD(B_SY.SHUBETUCD, 2, ' '), 2, 0) || LPAD(B_SY.URICD, 6, 0) || RPAD(B_SY.SALESCOMKN, 30, '　') || LPAD(B_SY.URABARIKBN, 1, 0) || LPAD(B_SY.PCARD_OPFLG, 1, 0) || LPAD(SUBSTR(B_SY.PARENTCD, 1, 8), 8, 0) || LPAD(SUBSTR(B_SY.PARENTCD, 9, 6), 6, ' ') || LPAD(B_SY.BINKBN, 1, 0) || LPAD(B_SY.HAT_MONKBN, 1, 0) || LPAD(B_SY.HAT_TUEKBN, 1, 0) || LPAD(B_SY.HAT_WEDKBN, 1, 0) || LPAD(B_SY.HAT_THUKBN, 1, 0) || LPAD(B_SY.HAT_FRIKBN, 1, 0) || LPAD(B_SY.HAT_SATKBN, 1, 0) || LPAD(B_SY.HAT_SUNKBN, 1, 0) || LPAD(B_SY.READTMPTN, 3, 0) || LPAD(B_SY.SIMEKAISU, 1, 0) || LPAD(B_SY.IRYOREFLG, 1, 0) || LPAD(B_SY.TOROKUMOTO, 1, 0) || '      ' || LPAD(B_SY.UPDKBN, 1, 0) || LPAD(B_SY.SENDFLG, 1, 0) || RPAD(B_SY.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(B_SY.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_SY.UPDDT, '%%Y%%m%%d'), 8, 0) as '1' FROM (SELECT * FROM SY) B_SY LEFT OUTER JOIN JNL1 ON B_SY.SHNCD = JNL1.SHNCD AND B_SY.YOYAKUDT = JNL1.YOYAKUDT LEFT OUTER JOIN PRE ON B_SY.SHNCD = PRE.SHNCD AND B_SY.YOYAKUDT = PRE.YOYAKUDT WHERE (PRE.SHNCD IS NOT NULL AND B_SY.UPDKBN = 1) OR B_SY.UPDKBN <> 1 ORDER BY B_SY.SHNCD, B_SY.YOYAKUDT;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
