REM [009][AEA82]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0009
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO008

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(仕入グループ商品(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SY AS (SELECT SY.* FROM INAMS2.MSTSHN_Y SY WHERE SY.SENDFLG IN (0, 9)), SGSY AS (SELECT * FROM INAMS2.MSTSIRGPSHN_Y SGSY WHERE EXISTS (SELECT 1 FROM SY WHERE SY.UPDKBN <> 1 AND SGSY.SHNCD = SY.SHNCD AND SGSY.YOYAKUDT = SY.YOYAKUDT)), PRE AS (SELECT SHNCD, YOYAKUDT FROM INAPRE.MSTSIRGPSHN_Y_PD T1 WHERE EXISTS (SELECT 1 FROM INAPRE.MSTSHN_Y_PD T2 WHERE T2.UPDKBN <> 1 AND T1.SHNCD = T2.SHNCD AND T1.YOYAKUDT = T2.YOYAKUDT) GROUP BY SHNCD, YOYAKUDT) SELECT CASE WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END || SUBSTR(RPAD(B_SGSY.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_SGSY.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_SGSY.SHNCD, 14, ' '), 9, 6) || LPAD(B_SGSY.TENGPCD, 4, 0) || LPAD(B_SGSY.YOYAKUDT, 8, 0) || LPAD(B_SGSY.AREAKBN, 1, 0) || LPAD(B_SGSY.SIRCD, 6, 0) || LPAD(B_SGSY.HSPTN, 3, 0) || '       ' || RPAD(B_SGSY.OPERATOR, 20, ' ') || LPAD(B_SGSY.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(B_SGSY.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_SGSY.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM (SELECT * FROM SGSY) B_SGSY LEFT OUTER JOIN PRE ON B_SGSY.SHNCD = PRE.SHNCD AND B_SGSY.YOYAKUDT = PRE.YOYAKUDT ORDER BY B_SGSY.SHNCD, B_SGSY.TENGPCD, B_SGSY.YOYAKUDT;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
