REM [010][MSTBAIKACTL_Y_LT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAMS2.MSTBAIKACTL_Y → INAPRE.MSTBAIKACTL_Y_LT ロード処理（売価コントロールマスタ_予約(前回処理結果)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAPRE.MSTBAIKACTL_Y_LT;INSERT IGNORE INTO INAPRE.MSTBAIKACTL_Y_LT SELECT SHNCD, TENGPCD, YOYAKUDT, AREAKBN, GENKAAM, BAIKAAM, IRISU, SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAMS2.MSTBAIKACTL_Y;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAPRE.MSTBAIKACTL_Y_LT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
