REM [010][AEA83]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0010
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO014

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(売価コントロール(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SY AS (SELECT SY.* FROM INAMS2.MSTSHN_Y SY WHERE SY.SENDFLG IN (0, 9)), BCY AS (SELECT BCY.* FROM INAMS2.MSTBAIKACTL_Y BCY WHERE EXISTS (SELECT 1 FROM SY WHERE SY.UPDKBN <> 1 AND BCY.SHNCD = SY.SHNCD AND BCY.YOYAKUDT = SY.YOYAKUDT)), JNL1 AS (SELECT JNLSHN.SHNCD, JNLSHN.YOYAKUDT, MAX(JNLSHN.PCARD_OPFLG) AS PCARD_OPFLG FROM INAAD2.JNLSHN JNLSHN WHERE JNLSHN.INF_TABLEKBN = 1 AND JNLSHN.SENDFLG IN (0, 9) GROUP BY JNLSHN.SHNCD, JNLSHN.YOYAKUDT), PRE AS (SELECT SHNCD, YOYAKUDT FROM INAPRE.MSTBAIKACTL_Y_PD T1 WHERE EXISTS (SELECT 1 FROM INAPRE.MSTSHN_Y_PD T2 WHERE T2.UPDKBN <> 1 AND T1.SHNCD = T2.SHNCD AND T1.YOYAKUDT = T2.YOYAKUDT) GROUP BY SHNCD, YOYAKUDT) SELECT CASE WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END || COALESCE(JNL1.PCARD_OPFLG, 0) || SUBSTR(RPAD(B_BCY.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_BCY.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_BCY.SHNCD, 14, ' '), 9, 6) || LPAD(B_BCY.TENGPCD, 4, 0) || LPAD(B_BCY.YOYAKUDT, 8, 0) || LPAD(B_BCY.AREAKBN, 1, 0) || LPAD(SUBSTR(B_BCY.GENKAAM, 1, LOCATE('.', B_BCY.GENKAAM) - 1), 6, 0) || SUBSTR(B_BCY.GENKAAM, LOCATE('.', B_BCY.GENKAAM) + 1) || LPAD(B_BCY.BAIKAAM, 6, 0) || LPAD(B_BCY.IRISU, 3, 0) || '         ' || RPAD(B_BCY.OPERATOR, 20, ' ') || LPAD(B_BCY.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(B_BCY.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_BCY.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM (SELECT * FROM BCY) B_BCY LEFT OUTER JOIN JNL1 ON B_BCY.SHNCD = JNL1.SHNCD AND B_BCY.YOYAKUDT = JNL1.YOYAKUDT LEFT OUTER JOIN PRE ON B_BCY.SHNCD = PRE.SHNCD AND B_BCY.YOYAKUDT = PRE.YOYAKUDT ORDER BY B_BCY.SHNCD, B_BCY.TENGPCD, B_BCY.YOYAKUDT" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
