REM [026][AEA83]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0612
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO012

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(売価コントロール)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH STG0 AS (SELECT STG.TENGPCD FROM INAMS2.MSTSHNTENGP STG WHERE STG.GPKBN = 2 AND STG.AREAKBN = 0 AND STG.SENDFLG IN (0, 9) AND STG.UPDKBN <> 1 AND STG.PCARD_OPFLG = 1 GROUP BY STG.TENGPCD), STG1 AS (SELECT STG.BMNCD, STG.TENGPCD FROM INAMS2.MSTSHNTENGP STG WHERE STG.GPKBN = 2 AND STG.AREAKBN = 1 AND STG.SENDFLG IN (0, 9) AND STG.UPDKBN <> 1 AND STG.PCARD_OPFLG = 1 GROUP BY STG.BMNCD, STG.TENGPCD), BCY0 AS (SELECT BCY.* FROM INAMS2.MSTBAIKACTL_Y BCY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE BCY.AREAKBN = 0 AND BCY.YOYAKUDT = SBD.DT_INT AND EXISTS (SELECT 1 FROM STG0 WHERE STG0.TENGPCD = BCY.TENGPCD)), BCY1 AS (SELECT BCY.* FROM INAMS2.MSTBAIKACTL_Y BCY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE BCY.AREAKBN = 1 AND BCY.YOYAKUDT = SBD.DT_INT AND EXISTS (SELECT 1 FROM STG1 WHERE STG1.BMNCD = CAST(SUBSTR(BCY.SHNCD, 1, 2) AS SIGNED) AND STG1.TENGPCD = BCY.TENGPCD)), BC0 AS (SELECT * FROM INAMS2.MSTBAIKACTL BC WHERE BC.AREAKBN = 0 AND EXISTS (SELECT 1 FROM STG0 WHERE STG0.TENGPCD = BC.TENGPCD) AND NOT EXISTS (SELECT * FROM BCY0 WHERE BC.SHNCD = BCY0.SHNCD)), BC1 AS (SELECT * FROM INAMS2.MSTBAIKACTL BC WHERE BC.AREAKBN = 1 AND EXISTS (SELECT 1 FROM STG1 WHERE STG1.BMNCD = CAST(SUBSTR(BC.SHNCD, 1, 2) AS SIGNED) AND STG1.TENGPCD = BC.TENGPCD) AND NOT EXISTS (SELECT * FROM BCY1 WHERE BC.SHNCD = BCY1.SHNCD)), BC AS (SELECT * FROM BC0 UNION ALL SELECT * FROM BC1 UNION ALL SELECT * FROM BCY0 UNION ALL SELECT * FROM BCY1) SELECT '5' || '1' || SUBSTR(RPAD(BC.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(BC.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(BC.SHNCD, 14, ' '), 9, 6) || LPAD(BC.TENGPCD, 4, 0) || LPAD(BC.YOYAKUDT, 8, 0) || LPAD(BC.AREAKBN, 1, 0) || LPAD(SUBSTR(BC.GENKAAM, 1, LOCATE('.', BC.GENKAAM) - 1), 6, 0) || COALESCE(SUBSTR(BC.GENKAAM, LOCATE('.', BC.GENKAAM) + 1), '') || LPAD(BC.BAIKAAM, 6, 0) || LPAD(BC.IRISU, 3, 0) || '         ' || RPAD(BC.OPERATOR, 20, ' ') || LPAD(BC.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(BC.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(BC.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM BC ORDER BY BC.SHNCD, BC.TENGPCD;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
