REM [027][AEA82_Y]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0610
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO009

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(仕入グループ商品(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH STGT AS (SELECT STGT.BMNCD, STGT.TENGPCD FROM INAMS2.MSTSHNTENGPTEN STGT WHERE STGT.GPKBN = 1 AND STGT.SENDFLG IN (0, 9) AND EXISTS (SELECT 1 FROM INAMS2.MSTSHNTENGP STG WHERE STG.UPDKBN <> 1 AND STG.GPKBN = STGT.GPKBN AND STG.BMNCD = STGT.BMNCD AND STG.TENGPCD = STGT.TENGPCD) GROUP BY STGT.BMNCD, STGT.TENGPCD), SGSY AS (SELECT SGSY.* FROM INAMS2.MSTSIRGPSHN_Y SGSY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE SGSY.AREAKBN <> 0 AND SGSY.YOYAKUDT <> SBD.DT_INT AND EXISTS (SELECT 1 FROM STGT WHERE STGT.BMNCD = CAST(SUBSTR(SGSY.SHNCD, 1, 2) AS SIGNED) AND STGT.TENGPCD = SGSY.TENGPCD)) SELECT '4' || SUBSTR(RPAD(SGSY.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(SGSY.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(SGSY.SHNCD, 14, ' '), 9, 6) || LPAD(SGSY.TENGPCD, 4, 0) || LPAD(SGSY.YOYAKUDT, 8, 0) || LPAD(SGSY.AREAKBN, 1, 0) || LPAD(SGSY.SIRCD, 6, 0) || LPAD(SGSY.HSPTN, 3, 0) || '       ' || RPAD(SGSY.OPERATOR, 20, ' ') || LPAD(SGSY.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(SGSY.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(SGSY.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM SGSY ORDER BY SGSY.SHNCD, SGSY.TENGPCD, SGSY.YOYAKUDT;"  >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
