REM [027][AEA82]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0608
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO006

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(仕入グループ商品)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH STGT AS (SELECT STGT.BMNCD, STGT.TENGPCD FROM INAMS2K.MSTSHNTENGPTEN STGT WHERE STGT.GPKBN = 1 AND STGT.SENDFLG IN (0, 9) AND EXISTS (SELECT 1 FROM INAMS2K.MSTSHNTENGP STG WHERE STG.UPDKBN <> 1 AND STG.GPKBN = STGT.GPKBN AND STG.BMNCD = STGT.BMNCD AND STG.TENGPCD = STGT.TENGPCD) GROUP BY STGT.BMNCD, STGT.TENGPCD), SGSY AS (SELECT SGSY.* FROM INAMS2.MSTSIRGPSHN_Y SGSY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE SGSY.AREAKBN <> 0 AND SGSY.YOYAKUDT = SBD.DT_INT AND EXISTS (SELECT 1 FROM STGT WHERE STGT.BMNCD = CAST(SUBSTR(SGSY.SHNCD, 1, 2) AS SIGNED) AND STGT.TENGPCD = SGSY.TENGPCD)), SGS AS (SELECT SGS.* FROM INAMS2.MSTSIRGPSHN SGS WHERE SGS.AREAKBN <> 0 AND EXISTS (SELECT 1 FROM STGT WHERE STGT.BMNCD = CAST(SUBSTR(SGS.SHNCD, 1, 2) AS SIGNED) AND STGT.TENGPCD = SGS.TENGPCD) AND NOT EXISTS (SELECT 1 FROM SGSY WHERE SGS.SHNCD = SGSY.SHNCD AND SGS.TENGPCD = SGSY.TENGPCD)) SELECT '4' || SUBSTR(RPAD(B_SGS.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_SGS.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_SGS.SHNCD, 14, ' '), 9, 6) || LPAD(B_SGS.TENGPCD, 4, 0) || LPAD(B_SGS.YOYAKUDT, 8, 0) || LPAD(B_SGS.AREAKBN, 1, 0) || LPAD(B_SGS.SIRCD, 6, 0) || LPAD(B_SGS.HSPTN, 3, 0) || '       ' || RPAD(B_SGS.OPERATOR, 20, ' ') || LPAD(B_SGS.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(B_SGS.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_SGS.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM (SELECT * FROM SGS UNION ALL SELECT * FROM SGSY) B_SGS ORDER BY B_SGS.SHNCD, B_SGS.TENGPCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
