REM [027][AIA58]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0027
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO020

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品店グループ店舗)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(STGT.GPKBN, 1, 0) || LPAD(STGT.BMNCD, 3, 0) || LPAD(STGT.TENGPCD, 4, 0) || LPAD(STGT.TENCD, 3, 0) || '  ' || RPAD(STGT.OPERATOR, 20, ' ') || LPAD(STGT.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(STGT.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(STGT.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM INAMS2.MSTSHNTENGPTEN STGT WHERE EXISTS (SELECT 1 FROM INAMS2.MSTSHNTENGP STG WHERE STG.UPDKBN <> 1 AND STG.GPKBN = STGT.GPKBN AND STG.BMNCD = STGT.BMNCD AND STG.TENGPCD = STGT.TENGPCD) ORDER BY STGT.GPKBN, STGT.BMNCD, STGT.TENGPCD, STGT.TENCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
