REM [066][AEP20]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0066
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEEUO008

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(プライスカードデータ要求データ（本部）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT CASE WHEN COALESCE(T1.MST_YOYAKUDT, 0) = 0 THEN '0' ELSE '1' END || LPAD(COALESCE(T1.MST_YOYAKUDT, 0), 8, 0) || LPAD(T1.SAKUBAIKAKB, 1, 0) || CASE WHEN COALESCE(T1.MAISUHOHOKB, 0) IN (1, 3) THEN 1 ELSE 2 END || CASE WHEN COALESCE(T1.SAKUBAIKAKB, 0) = 1 THEN 0 WHEN COALESCE(T2.KOSEPAGE, 0) <> 0 THEN 1 WHEN COALESCE(T2.BMNCD, 0) <> 0 THEN 2 WHEN T2.TENCD <> 0 THEN 3 ELSE 4 END || LPAD(COALESCE(T2.TENCD, 0), 3, 0) || RPAD(COALESCE(T2.SHNCD, '0'), 8, 0) || '      ' || LPAD(COALESCE(T2.KOSEPAGE, 0), 8, 0) || LPAD(COALESCE(T2.BMNCD, 0), 3, 0) || LPAD(COALESCE(T1.PCARDSZ, 0), 1, 0) || LPAD(CASE WHEN COALESCE(T1.MAISUHOHOKB, 0) IN (1, 3, 4) THEN T2.MAISU WHEN COALESCE(T1.MAISUHOHOKB, 0) = 2 THEN T1.COPYSU ELSE 1 END, 3, 0) || LPAD(T1.UPDKBN, 1, 0) || RPAD(T1.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 8, 0) || RPAD(T1.COMAN, 15, ' ') AS '1' FROM INAMS2.TRNPCARD T1 INNER JOIN INAMS2.TRNPCARDSU T2 ON T1.INPUTNO = T2.INPUTNO AND T1.UPDKBN <> 1 AND T2.UPDKBN <> 1 ORDER BY T1.INPUTNO, T2.SEQ" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
