REM [151][MSTSIR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAMS2.MSTSIR → INAPRE.MSTSIR ロード処理（仕入先マスタ(前日分)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "TRUNCATE TABLE INAPRE.MSTSIR;INSERT IGNORE INTO INAPRE.MSTSIR SELECT SIRCD, SIRAN, SIRKN, ADDRKN_T, ADDRKN_S, ADDRKN_M, ADDR_B, BUSHOKN, YUBINNO_U, YUBINNO_S, TEL, NAISEN, FAX, DSIRCD, DOYASIRCD, STARTDT, EDI_RKBN, EDI_SKBN, SIRYOTOKBN, INAZAIKOKBN, KAKGAKEKBN, NOZEISHANO, SYORTANKAAM, KHNRYOKINAM, STOPFLG, DOHOCD, DDENPKBN, DSHUHKBN, DWAPNKBN, DF_IDENKBN, DF_TENDENFLG, DF_VANKBN, DF_UNYOKBN, DF_DENPKBN, DF_SHUHKBN, DF_PICKDKBN, DF_PICKLKBN, DF_WAPNKBN, DF_IDENPKBN, DF_KAKOSJKBN, DF_RYUTSUKBN, DF_ZDENPKBN, DF_ZSHUHKBN, DF_ZPICKDKBN, DF_ZPICKLKBN, DF_RSIRCD, DF_YKNSHKBN, DF_YDENPKBN, DF_YSHUHKBN, UPDKBN, SENDFLG, OPERATOR, ADDDT, UPDDT, BMSKBN, AUTOKBN FROM INAMS2.MSTSIR;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "ANALYZE TABLE INAPRE.MSTSIR;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
