REM [151][MSTHSPTNSIR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAMS2.MSTHSPTNSIR → INAPRE.MSTHSPTNSIR ロード処理（配送パターン仕入先マスタ(前日分)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAPRE.MSTHSPTNSIR;INSERT IGNORE INTO INAPRE.MSTHSPTNSIR SELECT SIRCD, HSPTN, TENDENFLG, VANKBN, UNYOKBN, DENPKBN, SHUHKBN, PICKDKBN, PICKLKBN, WAPNKBN, IDENPKBN, KAKOSJKBN, RYUTSUKBN, ZDENPKBN, ZSHUHKBN, ZPICKDKBN, ZPICKLKBN, RSIRCD, YKNSHKBN, YDENPKBN, DSHUHKBN, SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAMS2.MSTHSPTNSIR;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAPRE.MSTHSPTNSIR;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
