REM [463][A11SHOJ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0463
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO045

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(ジャーナル_商品マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(SEQ, 9, 0) || LPAD(CAST(CAST(INF_DATE AS DATETIME) AS SIGNED), 14, 0) || RPAD(INF_OPERATOR, 20, ' ') || LPAD(INF_TABLEKBN, 1, 0) || LPAD(INF_TRANKBN, 1, 0) || RPAD(COALESCE(SHNCD, ''), 14, ' ') || LPAD(COALESCE(YOYAKUDT, 0), 8, 0) || LPAD(COALESCE(TENBAIKADT, 0), 8, 0) || LPAD(COALESCE(YOT_BMNCD, 0), 3, 0) || LPAD(COALESCE(YOT_DAICD, 0), 2, 0) || LPAD(COALESCE(YOT_CHUCD, 0), 2, 0) || LPAD(COALESCE(YOT_SHOCD, 0), 2, 0) || LPAD(COALESCE(URI_BMNCD, 0), 3, 0) || LPAD(COALESCE(URI_DAICD, 0), 2, 0) || LPAD(COALESCE(URI_CHUCD, 0), 2, 0) || LPAD(COALESCE(URI_SHOCD, 0), 2, 0) || LPAD(COALESCE(BMNCD, 0), 3, 0) || LPAD(COALESCE(DAICD, 0), 2, 0) || LPAD(COALESCE(CHUCD, 0), 2, 0) || LPAD(COALESCE(SHOCD, 0), 2, 0) || LPAD(COALESCE(SSHOCD, 0), 1, 0) || LPAD(COALESCE(ATSUK_STDT, 0), 8, 0) || LPAD(COALESCE(ATSUK_EDDT, 0), 8, 0) || LPAD(COALESCE(TEISHIKBN, 0), 1, 0) || RPAD(COALESCE(SHOHINAN, ''), 20, ' ') || RPAD(COALESCE(SHOHINKN, ''), 20, '　') || RPAD(COALESCE(PCARDKN, ''), 20, '　') || RPAD(COALESCE(POPKN, ''), 20, '　') || RPAD(COALESCE(RECEIPTAN, ''), 20, ' ') || RPAD(COALESCE(RECEIPTKN, ''), 20, '　') || LPAD(COALESCE(PCKBN, 0), 1, 0) || LPAD(COALESCE(KAKOKBN, 0), 1, 0) || LPAD(COALESCE(ICHIBAKBN, 0), 1, 0) || LPAD(COALESCE(SHNKBN, 0), 1, 0) || RPAD(COALESCE(SANCHIKN, ''), 20, '　') || LPAD(COALESCE(SSIRCD, 0), 6, 0) || LPAD(COALESCE(HSPTN, 0), 3, 0) || LPAD(COALESCE(RG_ATSUKFLG, 0), 1, 0) || LPAD(CAST(COALESCE(RG_GENKAAM, 0) * 100 AS SIGNED), 8, 0) || LPAD(COALESCE(RG_BAIKAAM, 0), 6, 0) || LPAD(COALESCE(RG_IRISU, 0), 3, 0) || RPAD(COALESCE(RG_IDENFLG, ''), 1, ' ') || RPAD(COALESCE(RG_WAPNFLG, ''), 1, ' ') || LPAD(COALESCE(HS_ATSUKFLG, 0), 1, 0) || LPAD(CAST(COALESCE(HS_GENKAAM, 0) * 100 AS SIGNED), 8, 0) || LPAD(COALESCE(HS_BAIKAAM, 0), 6, 0) || LPAD(COALESCE(HS_IRISU, 0), 3, 0) || RPAD(COALESCE(HS_WAPNFLG, ''), 1, ' ') || LPAD(COALESCE(HS_SPOTMINSU, 0), 2, 0) || RPAD(COALESCE(HP_SWAPNFLG, ''), 1, ' ') || RPAD(COALESCE(KIKKN, ''), 23, '　') || LPAD(COALESCE(UP_YORYOSU, 0), 5, 0) || LPAD(COALESCE(UP_TYORYOSU, 0), 3, 0) || LPAD(COALESCE(UP_TANIKBN, 0), 2, 0) || LPAD(COALESCE(SHN_YOKOSZ, 0), 4, 0) || LPAD(COALESCE(SHN_TATESZ, 0), 4, 0) || LPAD(COALESCE(SHN_OKUSZ, 0), 4, 0) || LPAD(CAST(COALESCE(SHN_JRYOSZ, 0) * 10 AS SIGNED), 6, 0) || LPAD(COALESCE(PBKBN, 0), 1, 0) || LPAD(COALESCE(KOMONOKBM, 0), 2, 0) || LPAD(COALESCE(TANAOROKBN, 0), 2, 0) || LPAD(COALESCE(TEIKEIKBN, 0), 1, 0) || LPAD(COALESCE(ODS_HARUSU, 0), 4, 0) || LPAD(COALESCE(ODS_NATSUSU, 0), 4, 0) || LPAD(COALESCE(ODS_AKISU, 0), 4, 0) || LPAD(COALESCE(ODS_FUYUSU, 0), 4, 0) || LPAD(COALESCE(ODS_NYUKASU, 0), 4, 0) || LPAD(COALESCE(ODS_NEBIKISU, 0), 4, 0) || LPAD(COALESCE(PCARD_SHUKBN, 0), 1, 0) || LPAD(COALESCE(PCARD_IROKBN, 0), 1, 0) || LPAD(COALESCE(ZEIKBN, 0), 1, 0) || LPAD(COALESCE(ZEIRTKBN, 0), 3, 0) || LPAD(COALESCE(ZEIRTKBN_OLD, 0), 3, 0) || LPAD(COALESCE(ZEIRTHENKODT, 0), 8, 0) || LPAD(COALESCE(SEIZOGENNISU, 0), 3, 0) || LPAD(COALESCE(TEIKANKBN, 0), 1, 0) || LPAD(COALESCE(MAKERCD, 0), 9, 0) || LPAD(COALESCE(IMPORTKBN, 0), 2, 0) || LPAD(COALESCE(SIWAKEKBN, 0), 2, 0) || LPAD(COALESCE(HENPIN_KBN, 0), 1, 0) || LPAD(COALESCE(TAISHONENSU, 0), 2, 0) || LPAD(COALESCE(CALORIESU, 0), 5, 0) || LPAD(COALESCE(ELPFLG, 0), 1, 0) || LPAD(COALESCE(BELLMARKFLG, 0), 1, 0) || LPAD(COALESCE(RECYCLEFLG, 0), 1, 0) || LPAD(COALESCE(ECOFLG, 0), 1, 0) || LPAD(COALESCE(HZI_YOTO, 0), 1, 0) || LPAD(COALESCE(HZI_ZAISHITU, 0), 1, 0) || LPAD(COALESCE(HZI_RECYCLE, 0), 1, 0) || RPAD(COALESCE(KIKANKBN, ''), 1, ' ') || LPAD(COALESCE(SHUKYUKBN, 0), 2, 0) || LPAD(COALESCE(DOSU, 0), 3, 0) || RPAD(COALESCE(CHINRETUCD, ''), 1, ' ') || RPAD(COALESCE(DANTUMICD, ''), 2, ' ') || RPAD(COALESCE(KASANARICD, ' '), 1, ' ') || LPAD(COALESCE(KASANARISZ, 0), 3, 0) || LPAD(COALESCE(ASSHUKURT, 0), 2, 0) || RPAD(COALESCE(SHUBETUCD, ''), 2, ' ') || LPAD(COALESCE(URICD, 0), 6, 0) || RPAD(COALESCE(SALESCOMKN, ''), 30, '　') || LPAD(COALESCE(URABARIKBN, 0), 1, 0) || LPAD(COALESCE(PCARD_OPFLG, 0), 1, 0) || RPAD(COALESCE(PARENTCD, ''), 14, ' ') || LPAD(COALESCE(BINKBN, 0), 1, 0) || LPAD(COALESCE(HAT_MONKBN, 0), 1, 0) || LPAD(COALESCE(HAT_TUEKBN, 0), 1, 0) || LPAD(COALESCE(HAT_WEDKBN, 0), 1, 0) || LPAD(COALESCE(HAT_THUKBN, 0), 1, 0) || LPAD(COALESCE(HAT_FRIKBN, 0), 1, 0) || LPAD(COALESCE(HAT_SATKBN, 0), 1, 0) || LPAD(COALESCE(HAT_SUNKBN, 0), 1, 0) || LPAD(COALESCE(READTMPTN, 0), 3, 0) || LPAD(COALESCE(SIMEKAISU, 0), 1, 0) || LPAD(COALESCE(IRYOREFLG, 0), 1, 0) || LPAD(COALESCE(TOROKUMOTO, 0), 1, 0) || ' ' || LPAD(COALESCE(UPDKBN, 0), 1, 0) || LPAD(COALESCE(SENDFLG, 0), 1, 0) || RPAD(COALESCE(OPERATOR, ''), 20, ' ') || LPAD(DATE_FORMAT(ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM INAAD2.JNLSHN WHERE SENDFLG <> 1 ORDER BY SEQ;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
