REM [465][A11BCMJ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0465
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO047

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(ジャーナル_売価コントロールマスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(JNLBAIKACTL.SEQ, 9, 0) || LPAD(JNLBAIKACTL.RENNO, 5, 0) || RPAD(COALESCE(JNLBAIKACTL.SHNCD, ''), 14, ' ') || LPAD(COALESCE(JNLBAIKACTL.TENGPCD, 0), 4, 0) || LPAD(COALESCE(JNLBAIKACTL.YOYAKUDT, 0), 8, 0) || LPAD(COALESCE(JNLBAIKACTL.AREAKBN, 0), 1, 0) || LPAD(COALESCE(CAST(JNLBAIKACTL.GENKAAM * 100 AS SIGNED), 0), 8, 0) || LPAD(COALESCE(JNLBAIKACTL.BAIKAAM, 0), 6, 0) || LPAD(COALESCE(JNLBAIKACTL.IRISU, 0), 3, 0) || '     ' || RPAD(COALESCE(JNLBAIKACTL.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(JNLBAIKACTL.SENDFLG, 0), 1, 0) || LPAD(DATE_FORMAT(JNLBAIKACTL.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(JNLBAIKACTL.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM INAAD2.JNLBAIKACTL JNLBAIKACTL WHERE JNLBAIKACTL.SENDFLG <> 1 ORDER BY JNLBAIKACTL.SEQ, JNLBAIKACTL.RENNO" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
