REM [466][A11SRCJ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0466
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO048

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(ジャーナル_ソースコード管理マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(JNLSRCCD.SEQ, 9, 0) || LPAD(JNLSRCCD.RENNO, 5, 0) || RPAD(COALESCE(JNLSRCCD.SHNCD, ''), 14, ' ') || RPAD(COALESCE(JNLSRCCD.SRCCD, ''), 14, ' ') || LPAD(COALESCE(JNLSRCCD.YOYAKUDT, 0), 8, 0) || LPAD(COALESCE(JNLSRCCD.SEQNO, 0), 1, 0) || LPAD(COALESCE(JNLSRCCD.SRCKBN, 0), 1, 0) || ' ' || RPAD(COALESCE(JNLSRCCD.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(JNLSRCCD.SENDFLG, 0), 1, 0) || LPAD(DATE_FORMAT(JNLSRCCD.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(JNLSRCCD.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM INAAD2.JNLSRCCD JNLSRCCD WHERE JNLSRCCD.SENDFLG <> 1 ORDER BY JNLSRCCD.SEQ, JNLSRCCD.RENNO" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
