@echo off
cls

rem 初期値()
set event_output=0

rem 接続情報取得
set curpath=%~dp0..\
call %curpath%._init.bat

rem フォルダ名取得
set folderpath=%~dp0
set folderpath=%folderpath:~0,-1%
for /F "delims=" %%a in ('echo "%folderpath%"') do set foldername=%%~nxa

rem I/F リスト
set readlist=%~dp0list_load.txt
rem I/F 格納先フルパス
set input=%~dp0data
rem I/F 確認用バッチファイル
set checkfile=%~dp0checkfile.bat

rem I/F バックアップ用日時(YYYYMMDDHHMM)取得
set ltime=%date:~-10,4%%date:~-5,2%%date:~-2%%time:~0,2%%time:~3,2%
set ltime=%ltime: =0%

rem 日付取得
set days=%date:~8,2%

rem ログファイル
set outfile=%~dp0logs\setup.log
set outtime=%~dp0logs\time.log
set findfile=%~dp0logs\setup.find.log

rem ログフォルダ作成
if not exist %~dp0logs mkdir %~dp0logs

rem データフォルダ作成
if not exist %input% mkdir %input%

rem エクスポートフォルダ作成
if not exist %~dp0exp mkdir %~dp0exp


rem ログフォルダ・ローテーション
for %%F in (%outfile%) do if %%~zF GEQ 10485760 move /Y %outfile% %outfile%.old
for %%F in (%outtime%) do if %%~zF GEQ 10485760 move /Y %outtime% %outtime%.old

echo %DATE% %TIME% 日次処理(xx.Load_data)の開始 >> %outfile%

rem ================ <プロセス切断> ==============
rem SET callbat=bat\000.DISCONNECT.bat
rem >> %outfile% ECHO %callbat%
rem CALL %~dp0%callbat%
rem IF "%ERRORLEVEL%" EQU "1" GOTO ERROR

REM 25:00

REM ===== 052 店別B/M送信状況 ==
SET CALLBAT=BAT\052.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 053 店別B/M送信状況_商品 ==
SET CALLBAT=BAT\053.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 054 店別B/M送信状況_店舗 ==
SET CALLBAT=BAT\054.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 055 アンケート結果_店グループ ==
SET CALLBAT=BAT\055.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 056 アンケート結果_店舗 ==
SET CALLBAT=BAT\056.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 057 アンケート結果_商品 ==
SET CALLBAT=BAT\057.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 058 全店特売(アンケート有)_販売 ==
REM SET CALLBAT=BAT\058.LOAD.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 059 事前発注 ==
SET CALLBAT=BAT\059.MERGE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 060 事前発注_平均パック単価 ==
SET CALLBAT=BAT\060.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 061 事前発注_商品 ==
SET CALLBAT=BAT\061.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 070 全店特売(アンケート有)_納入日 ==
REM SET CALLBAT=BAT\070.LOAD.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 071 全店特売(アンケート有)_納入日 ==
REM SET CALLBAT=BAT\071.MERGE.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 072 事前発注_店舗 ==
REM SET CALLBAT=BAT\072.LOAD.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 073 全店特売(アンケート無)_納入日 ==
REM SET CALLBAT=BAT\073.LOAD.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 074 全店特売(アンケート無)_納入日 ==
REM SET CALLBAT=BAT\074.MERGE.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 075 全店特売(アンケート有)_商品 ==
REM SET CALLBAT=BAT\075.MERGE.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 076 全店特売(アンケート無)_商品 ==
REM SET CALLBAT=BAT\076.MERGE.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 080 全店特売(アンケート有)_納入日 ==
REM SET CALLBAT=BAT\080.MERGE.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 082 全店特売(アンケート無)_納入日 ==
REM SET CALLBAT=BAT\082.MERGE.BAT
REM >> %OUTFILE% ECHO %CALLBAT%
REM CALL %~DP0%CALLBAT%
REM IF ERRORLEVEL 1 GOTO ERROR

REM ===== 083 アンケート再作成日シフト(基本) ==
SET CALLBAT=BAT\083.UPDATE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 084 アンケート再作成日シフト(店グループ) ==
SET CALLBAT=BAT\084.UPDATE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 085 事前発注リスト作成済フラグセット ==
SET CALLBAT=BAT\085.UPDATE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 086 PLU配信済セット ==
SET CALLBAT=BAT\086.UPDATE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 026 定量定期削除 ==
SET CALLBAT=BAT\026.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 088 正規定量_商品 物理削除 ==
SET CALLBAT=BAT\088.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 089 正規定量_店別数量 物理削除 ==
SET CALLBAT=BAT\089.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 090 次週定量_店別数量 物理削除 ==
SET CALLBAT=BAT\090.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 091 定期削除 予約発注 ==
SET CALLBAT=BAT\091.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 092 定期削除 新店改装店発注 ==
SET CALLBAT=BAT\092.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 093 定期削除 催し関連 ==
SET CALLBAT=BAT\093.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 094 定期削除 冷凍食品 ==
SET CALLBAT=BAT\094.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 095 定期削除 事前発注 ==
SET CALLBAT=BAT\095.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 096 定期削除 重複チェック関連 ==
SET CALLBAT=BAT\096.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 097 定期削除 CSV取込トラン ==
SET CALLBAT=BAT\097.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 098 定期削除 実績率パタン ==
SET CALLBAT=BAT\098.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 099 定期削除 実績率パタン ==
SET CALLBAT=BAT\099.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 100 定期削除 ログ ==
SET CALLBAT=BAT\100.DELETE.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR


REM ===== 050 催し検索ロード ==
SET CALLBAT=BAT\050.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 064 催し検索_商品 ==
SET CALLBAT=BAT\064.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

REM ===== 065 催し検索_店舗 ==
SET CALLBAT=BAT\065.LOAD.BAT
>> %OUTFILE% ECHO %CALLBAT%
CALL %~DP0%CALLBAT%
IF ERRORLEVEL 1 GOTO ERROR

rem 他で使用しないＷＫの場合、１つのバッチ内に記載


:SUCCESS
echo %DATE% %TIME% 処理が正常に終了しました >> %outfile%

:LAST
EXIT /B 0

:ERROR
ECHO %DATE% %TIME% %callbat% エラーが発生しました(RC=1) >> %outfile%
EXIT /B 1
