REM [][D2WK_PRAM_READTMCNV]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% 各マスタ → INAWK.D2WK_PRAM_READTMCNV ロード処理（リードタイムパターン変換パラメータ(CCR用)作成）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.D2WK_PRAM_READTMCNV ;INSERT IGNORE INTO INAWK.D2WK_PRAM_READTMCNV SELECT CAST(DAYS.SYORDT AS SIGNED) AS '1', PRRTC.BMNCD, PRRTC.READTMPTN_BE, PRRTC.READTMPTN_AF FROM (SELECT BMNCD, READTMPTN_BE, READTMPTN_AF, APL_STDT, APL_EDDT FROM INAPARM.PRAM_READTMCNV WHERE BMNCD BETWEEN 1 AND 999) PRRTC INNER JOIN (SELECT DATE_FORMAT(DATE_ADD(SBD.DTTIME, INTERVAL (NUM.SEQ - 30) DAY), '%%Y%%m%%d') AS SYORDT FROM INAPARM.SYSBATCHDT_TK SBD INNER JOIN INAPARM.MSTNUMS NUM ON 1 = 1 AND NUM.SEQ < 430 AND SBD.SMODE = 'DAILY') DAYS ON 1 = 1 AND DAYS.SYORDT BETWEEN PRRTC.APL_STDT AND PRRTC.APL_EDDT INNER JOIN (SELECT DAYS.SYORDT, PRRTC.APL_STDT, PRRTC.APL_EDDT, PRRTC.BMNCD, PRRTC.READTMPTN_BE, ROW_NUMBER() OVER (PARTITION BY PRRTC.BMNCD, PRRTC.READTMPTN_BE, DAYS.SYORDT ORDER BY PRRTC.APL_STDT DESC, PRRTC.APL_EDDT) AS ODRNO FROM (SELECT BMNCD, READTMPTN_BE, READTMPTN_AF, APL_STDT, APL_EDDT FROM INAPARM.PRAM_READTMCNV WHERE BMNCD BETWEEN 1 AND 999) PRRTC INNER JOIN (SELECT DATE_FORMAT(DATE_ADD(SBD.DTTIME, INTERVAL (NUM.SEQ - 30) DAY), '%%Y%%m%%d') AS SYORDT FROM INAPARM.SYSBATCHDT_TK SBD INNER JOIN INAPARM.MSTNUMS NUM ON 1 = 1 AND NUM.SEQ < 430 AND SBD.SMODE = 'DAILY') DAYS ON 1 = 1 AND DAYS.SYORDT BETWEEN PRRTC.APL_STDT AND PRRTC.APL_EDDT) VAL ON PRRTC.BMNCD = VAL.BMNCD AND PRRTC.READTMPTN_BE = VAL.READTMPTN_BE AND DAYS.SYORDT = VAL.SYORDT AND PRRTC.APL_STDT = VAL.APL_STDT AND PRRTC.APL_EDDT = VAL.APL_EDDT AND VAL.ODRNO = 1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"ANALYZE TABLE INAWK.D2WK_PRAM_READTMCNV;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
