REM [177][D2WK28_ZZQ102_Z2]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAWK.D2WK28_ZZQ102_Z2 → INAPRE.D2WK28_ZZQ102_Z2 ロード処理（店別定量特売ファイル(全店特売)2(前回分)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAPRE.D2WK28_ZZQ102_Z2;INSERT IGNORE INTO INAPRE.D2WK28_ZZQ102_Z2 SELECT REC_HAN_KBN, MISE, SHOHNC, FILLER01, SYOKBN, BINK, NOKAIS, NOSYUR, HAKAIS, HASYUR, NNYNOB, NONYB, HACHBI, HACYB, JZNGENKA, TUIGENKA, GENFU, GENFUK, A_SOBAIFG, B_SOBAIFG, C_SOBAIFG, A_SOBAIFP, B_SOBAIFP, C_SOBAIFP, A_SOBAIFK, B_SOBAIFK, C_SOBAIFK, A_BAIKA_SOTO, B_BAIKA_SOTO, C_BAIKA_SOTO, HEKINP, MISIR, BD1SU, BD2SU, A_BDBAIKA, A_BD1BAIKA, A_BD2BAIKA, B_BDBAIKA, B_BD1BAIKA, B_BD2BAIKA, C_BDBAIKA, C_BD1BAIKA, C_BD2BAIKA, SIIRCD, NENMAT, TEISEK, TRTEISEK, TTKBN, KZKBN, TEFTEI, BETUDEN, WAPENK, IKKATK, JIZNUT, SIDENF, TEICUTK, HOUZAI, DSEIK, PCKBN, HIGAWAK, HGEBATFL, REDMYFL, DATAK, SEISUR, HENSUR, SEITK, NONSJ, ATARA, RDHMHYO, RDHMMON, RDHMTUE, RDHMWED, RDHMTHU, RDHMFRI, RDHMSAT, RDHMSUN, NONSU, BUNBMC1, BUNDIC, BUNCHC, BUNSHC, BUNSSC, MSSIRE, MSIR, MSIKK, MSWAP, MSBIN, MOYOK, MOYOKA, MOYORE, BUNBMC2, KANBAN, EDABAN, SHUNO, SMISECD, KZCUT, KOUCUT, TEICUT, TOKCUT, KYUCUT, HACCUT, NONCUT, HSSCUT, ZERO, FILLER02, SYORIK, TOKCOME, KIKMKJ, SANTIMKJ, JIZNB, JZHCB, JZHCSUB, SIHCSYB, TTENRANK, HCUSU, BAISNKB, KZKUBETU, SYUFLG, HYSYUFLG, JZNLSKSKB, ANKUMUKB, FILLER03, SAKSEIB FROM INAWK.D2WK28_ZZQ102_Z2;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAPRE.D2WK28_ZZQ102_Z2;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
