REM [177][D2WK20_ZZQ102]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET TBNAME=D2WK20_ZZQ102
SET SCNAME=INAWK
SET INDEX=%~DP0..\index\%TBNAME%


SET MSG=%DATE% %TIME% INAWK.D2WK20_ZZQ102(店別定量特売ファイルワーク1) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "TRUNCATE TABLE INAWK.D2WK20_ZZQ102;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INAWK.D2WK20_ZZQ102(店別定量特売ファイルワーク1)  INDEX詳細出力
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e  "SELECT INDEX_NAME, GROUP_CONCAT(COLUMN_NAME SEPARATOR ',') AS COLUMN_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_NAME = '%TBNAME%' AND TABLE_SCHEMA = '%SCNAME%' AND INDEX_NAME <> 'PRIMARY' GROUP BY INDEX_NAME"  >%INDEX% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INAWK.D2WK20_ZZQ102 INDEX削除
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
FOR /F %%D IN (%INDEX%) DO ( "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DROP INDEX %%D ON %SCNAME%.%TBNAME%;COMMIT;" >>%OUTFILE% 2>&1 )


SET MSG=%DATE% %TIME% INAWK.D2WK20_ZZQ102(店別定量特売ファイルワーク1) ロード処理（ワークテーブル作成）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv   <  %~dp0177.D2WK20_ZZQ102.LOAD.sql >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INAWK.D2WK20_ZZQ102 INDEX 再作成
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
FOR /F "tokens=1,2 delims=	" %%D IN (%INDEX%) DO ( "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "CREATE INDEX %%D ON %SCNAME%.%TBNAME%(%%E);COMMIT;" >>%OUTFILE% 2>&1 )


"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "ANALYZE TABLE INAWK.D2WK20_ZZQ102;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
