REM [181][ZZQ104]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0181
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=MDMUR026

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(生活応援_部門)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(SBMNT2.REC_HAN_KBN, 1, 0) || LPAD(SBMNT2.MOYSKBN, 1, 0) || LPAD(SBMNT2.MOYSSTDT, 6, 0) || LPAD(SBMNT2.MOYSRBAN, 3, 0) || LPAD(SBMNT2.BMNCD, 3, 0) || LPAD(SBMNT2.UPDKBN, 1, 0) || LPAD(SBMNT2.SENDFLG, 1, 0) || RPAD(SBMNT2.OPERATOR, 20, ' ') || DATE_FORMAT(SBMNT2.ADDDT, '%%Y%%m%%d') || DATE_FORMAT(SBMNT2.UPDDT, '%%Y%%m%%d') AS '1' FROM (SELECT CASE WHEN SBMNT.MOYSKBN IS NOT NULL AND SBMNT.MOYSKBN_1 IS NOT NULL THEN 2 WHEN SBMNT.MOYSKBN_1 IS NULL THEN 1 ELSE 9 END AS REC_HAN_KBN, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.MOYSKBN ELSE SBMNT.MOYSKBN_1 END AS MOYSKBN, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.MOYSSTDT ELSE SBMNT.MOYSSTDT_1 END AS MOYSSTDT, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.MOYSRBAN ELSE SBMNT.MOYSRBAN_1 END AS MOYSRBAN, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.BMNCD ELSE SBMNT.BMNCD_1 END AS BMNCD, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.UPDKBN ELSE SBMNT.UPDKBN_1 END AS UPDKBN, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.SENDFLG ELSE SBMNT.SENDFLG_1 END AS SENDFLG, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.OPERATOR ELSE SBMNT.OPERATOR_1 END AS OPERATOR, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.ADDDT ELSE SBMNT.ADDDT_1 END AS ADDDT, CASE WHEN SBMNT.MOYSKBN IS NOT NULL THEN SBMNT.UPDDT ELSE SBMNT.UPDDT_1 END AS UPDDT FROM (SELECT MT.MOYSKBN AS MOYSKBN, MT.MOYSSTDT AS MOYSSTDT, MT.MOYSRBAN AS MOYSRBAN, MT.BMNCD AS BMNCD, MT.UPDKBN AS UPDKBN, MT.SENDFLG AS SENDFLG, MT.OPERATOR AS OPERATOR, MT.ADDDT AS ADDDT, MT.UPDDT AS UPDDT, MZ.MOYSKBN AS MOYSKBN_1, MZ.MOYSSTDT AS MOYSSTDT_1, MZ.MOYSRBAN AS MOYSRBAN_1, MZ.BMNCD AS BMNCD_1, MZ.UPDKBN AS UPDKBN_1, MZ.SENDFLG AS SENDFLG_1, MZ.OPERATOR AS OPERATOR_1, MZ.ADDDT AS ADDDT_1, MZ.UPDDT AS UPDDT_1 FROM INATK2.TOKSO_BMN MT LEFT OUTER JOIN INAPRE.TOKSO_BMN MZ ON MT.MOYSKBN = MZ.MOYSKBN AND MT.MOYSSTDT = MZ.MOYSSTDT AND MT.MOYSRBAN = MZ.MOYSRBAN AND MT.BMNCD = MZ.BMNCD AND MZ.UPDKBN <> 1 WHERE MT.UPDKBN <> 1 UNION SELECT MT.MOYSKBN AS MOYSKBN, MT.MOYSSTDT AS MOYSSTDT, MT.MOYSRBAN AS MOYSRBAN, MT.BMNCD AS BMNCD, MT.UPDKBN AS UPDKBN, MT.SENDFLG AS SENDFLG, MT.OPERATOR AS OPERATOR, MT.ADDDT AS ADDDT, MT.UPDDT AS UPDDT, MZ.MOYSKBN AS MOYSKBN_1, MZ.MOYSSTDT AS MOYSSTDT_1, MZ.MOYSRBAN AS MOYSRBAN_1, MZ.BMNCD AS BMNCD_1, MZ.UPDKBN AS UPDKBN_1, MZ.SENDFLG AS SENDFLG_1, MZ.OPERATOR AS OPERATOR_1, MZ.ADDDT AS ADDDT_1, MZ.UPDDT AS UPDDT_1 FROM INATK2.TOKSO_BMN MT RIGHT OUTER JOIN INAPRE.TOKSO_BMN MZ ON MT.MOYSKBN = MZ.MOYSKBN AND MT.MOYSSTDT = MZ.MOYSSTDT AND MT.MOYSRBAN = MZ.MOYSRBAN AND MT.BMNCD = MZ.BMNCD AND MT.UPDKBN <> 1 WHERE MZ.UPDKBN <> 1 ORDER BY ADDDT) SBMNT) SBMNT2 LEFT OUTER JOIN (SELECT * FROM INAPRE.TOKSO_BMN WHERE UPDKBN <> 1) SBMNZ2 ON SBMNT2.MOYSKBN = SBMNZ2.MOYSKBN AND SBMNT2.MOYSSTDT = SBMNZ2.MOYSSTDT AND SBMNT2.MOYSRBAN = SBMNZ2.MOYSRBAN AND SBMNT2.BMNCD = SBMNZ2.BMNCD AND SBMNT2.UPDKBN = SBMNZ2.UPDKBN AND SBMNT2.SENDFLG = SBMNZ2.SENDFLG AND SBMNT2.OPERATOR = SBMNZ2.OPERATOR AND SBMNT2.ADDDT = SBMNZ2.ADDDT AND SBMNT2.UPDDT = SBMNZ2.UPDDT WHERE (SBMNT2.REC_HAN_KBN = 1 AND SBMNT2.SENDFLG <> 1) OR (SBMNT2.REC_HAN_KBN = 2 AND SBMNZ2.MOYSKBN IS NULL AND SBMNT2.SENDFLG <> 1) OR (SBMNT2.REC_HAN_KBN = 9) ORDER BY SBMNT2.MOYSKBN, SBMNT2.MOYSSTDT, SBMNT2.MOYSRBAN, SBMNT2.BMNCD" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
