REM [182][D2WK24_ZZQ112_SSHNT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INATK2.TOKSO_SHN → INAWK.D2WK24_ZZQ112_SSHNT ロード処理（生活応援_商品1SSHNT）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.D2WK24_ZZQ112_SSHNT; INSERT IGNORE INTO INAWK.D2WK24_ZZQ112_SSHNT SELECT TEN.TENCD, SSHN.MOYSKBN AS MOYOK, SSHN.MOYSSTDT AS MOYOKA, SSHN.MOYSRBAN AS MOYORE, SSHN.BMNCD AS BUNBMC, SSHN.KANRINO AS KANBAN, SSHN.SHNCD AS SHOCD, SSHN.MAKERKN AS MAKRNMKJ, SSHN.SHNKN AS SHOMKJ, SSHN.KIKKN AS KIKMKJ, SSHN.IRISU AS MISIR, SSHN.MINSU AS SAITEISU, SSHN.GENKAAM AS GENKA, SSHN.A_BAIKAAM AS A_SOBAIFG, SSHN.B_BAIKAAM AS B_SOBAIFG, SSHN.C_BAIKAAM AS C_SOBAIFG, SSHN.A_RANKNO AS A_RANK, SSHN.B_RANKNO AS B_RANK, SSHN.C_RANKNO AS C_RANK, SSHN.POPCD AS POPCD, SSHN.POPSZ AS POPSIZE, SSHN.POPSU AS POPSU, SSHN.UPDKBN AS KOSINKB, SSHN.SENDFLG AS SOSINFLG, SSHN.OPERATOR AS OPERTO, CAST(DATE_FORMAT(SSHN.ADDDT, '%%Y%%m%%d') AS SIGNED) AS TOURKB, CAST(DATE_FORMAT(SSHN.UPDDT, '%%Y%%m%%d') AS SIGNED) AS KOSINB, CASE WHEN TEN2.TENCD IS NOT NULL AND SSHN.MOYSRBAN <= 9 AND SUBSTR(SSHN.TENATSUK_ARR, TEN.TENCD, 1) = ' ' THEN 'A' ELSE SUBSTR(SSHN.TENATSUK_ARR, TEN.TENCD, 1) END AS MSF, CAST(CAST(CASE WHEN MB.BMNKBN IN (1, 0) AND KASAN.SYORDT < MOYO.NNSTDT THEN MOYO.NNSTDT WHEN MB.BMNKBN IN (1, 0) AND KASAN.SYORDT >= MOYO.NNSTDT THEN CAST(KASAN.SYORDT AS SIGNED) WHEN MB.BMNKBN = 2 AND KASAN.SYORDT < MOYO.NNSTDT_TGF THEN MOYO.NNSTDT_TGF WHEN MB.BMNKBN = 2 AND KASAN.SYORDT >= MOYO.NNSTDT_TGF THEN CAST(KASAN.SYORDT AS SIGNED) END AS CHAR) AS DATETIME) AS KAISIBI, CAST(CAST(CASE WHEN MB.BMNKBN IN (1, 0) AND KASAN.SYORDT < MOYO.NNSTDT THEN MOYO.NNEDDT WHEN MB.BMNKBN IN (1, 0) AND KASAN.SYORDT >= MOYO.NNSTDT AND KASAN.SYORDT2 >= MOYO.NNEDDT THEN MOYO.NNEDDT WHEN MB.BMNKBN IN (1, 0) AND KASAN.SYORDT >= MOYO.NNSTDT AND KASAN.SYORDT2 < MOYO.NNEDDT THEN CAST(KASAN.SYORDT2 AS SIGNED) WHEN MB.BMNKBN = 2 AND KASAN.SYORDT < MOYO.NNSTDT_TGF THEN MOYO.NNEDDT_TGF WHEN MB.BMNKBN = 2 AND KASAN.SYORDT >= MOYO.NNSTDT_TGF AND KASAN.SYORDT2 >= MOYO.NNEDDT_TGF THEN MOYO.NNEDDT_TGF WHEN MB.BMNKBN = 2 AND KASAN.SYORDT >= MOYO.NNSTDT_TGF AND KASAN.SYORDT2 < MOYO.NNEDDT_TGF THEN CAST(KASAN.SYORDT2 AS SIGNED) END AS CHAR) AS DATETIME) AS SYURYBI FROM INATK2.TOKSO_SHN SSHN INNER JOIN INAWK.D2WK24_ZZQ112_KASAN KASAN ON 1 = 1 INNER JOIN INAPRE.TOKMOYCD MOYO ON SSHN.MOYSKBN = MOYO.MOYSKBN AND SSHN.MOYSSTDT = MOYO.MOYSSTDT AND SSHN.MOYSRBAN = MOYO.MOYSRBAN AND (MOYO.NNEDDT >= KASAN.SYORDT OR MOYO.NNEDDT_TGF >= KASAN.SYORDT) AND MOYO.UPDKBN <> 1 INNER JOIN (SELECT SEQ AS TENCD FROM INAPARM.MSTNUMS WHERE SEQ BETWEEN 1 AND 400) TEN ON 1 = 1 AND SSHN.UPDKBN <> 1 LEFT OUTER JOIN (SELECT TENCD FROM INAMS2K.MSTTEN TEN2 WHERE UPDKBN <> 1 AND TENCD >= 4) TEN2 ON TEN.TENCD = TEN2.TENCD LEFT OUTER JOIN INAPRE.MSTSHN_PD MS ON SSHN.SHNCD = MS.SHNCD AND MS.UPDKBN <> 1 LEFT OUTER JOIN INAMS2K.MSTBMN MB ON SSHN.BMNCD = MB.BMNCD AND MB.UPDKBN <> 1 LEFT OUTER JOIN INAMS2K.MSTZEIRT MZS1 ON MZS1.ZEIRTKBN = MS.ZEIRTKBN AND MZS1.UPDKBN <> 1 LEFT OUTER JOIN INAMS2K.MSTZEIRT MZS2 ON MZS2.ZEIRTKBN = MS.ZEIRTKBN_OLD AND MZS2.UPDKBN <> 1 LEFT OUTER JOIN INAMS2K.MSTZEIRT MZB1 ON MZB1.ZEIRTKBN = MB.ZEIRTKBN AND MZB1.UPDKBN <> 1 LEFT OUTER JOIN INAMS2K.MSTZEIRT MZB2 ON MZB2.ZEIRTKBN = MB.ZEIRTKBN_OLD AND MZB2.UPDKBN <> 1 WHERE SUBSTR(SSHN.TENATSUK_ARR, TEN.TENCD, 1) <> ' ' OR (TEN2.TENCD IS NOT NULL AND SSHN.MOYSRBAN <= 9); COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.D2WK24_ZZQ112_SSHNT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
