REM [182][D2WK24_ZZQ112_KASAN2]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAPARM.PRAM_ADDNISU_TENTEIRYOTKFILE → INAWK.D2WK24_ZZQ112_KASAN2 ロード処理（生活応援_商品1KASAN2）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.D2WK24_ZZQ112_KASAN2; INSERT IGNORE INTO INAWK.D2WK24_ZZQ112_KASAN2 SELECT CAST(DATE_FORMAT(DATE_SUB(SBD.DT, INTERVAL PAT.GENNISU DAY), '%%Y%%m%%d') AS SIGNED) AS SYORDT, CAST(DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL (PAT.ADDNISU - PAT.GENNISU) DAY), '%%Y%%m%%d') AS SIGNED) AS SYORDT2, PAT.ADDNISU - 1 AS NISU FROM INAPARM.PRAM_ADDNISU_TENTEIRYOTKFILE PAT INNER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.SMODE = 'DAILY' WHERE PAT.ADDNISUSMODE = 'SEIKATU13_UNMATCH'; COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.D2WK24_ZZQ112_KASAN2;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
