REM [199][mstBMN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0199
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=A11MTN03

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(棚卸管理_部門マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT BMNCD, BMNKBN, TRIM(BMNAN), TRIM(TRAILING '　' FROM BMNKN), ZEIKBN, ZEIRTHENKODT, ZEIRTKBN_OLD, ZEIRTKBN, ODBOOKKBN, HYOKAKBN, CASE WHEN GENKART = 0 THEN NULL ELSE GENKART END AS GENKART, CASE WHEN CORPBMNCD = 0 THEN NULL ELSE CORPBMNCD END AS CORPBMNCD, CASE WHEN URIBMNCD = 0 THEN NULL ELSE URIBMNCD END AS URIBMNCD, CASE WHEN HOGANBMNCD = 0 THEN NULL ELSE HOGANBMNCD END AS HOGANBMNCD, CASE WHEN JYOGENAM = 0 THEN NULL ELSE JYOGENAM END AS JYOGENAM, CASE WHEN JYOGENSU = 0 THEN NULL ELSE JYOGENSU END AS JYOGENSU, CASE WHEN TANAOROTIMKB = '0' THEN '' ELSE TANAOROTIMKB END AS TANAOROTIMKB, POSBAIHENKBN, KEIHIKBN, TANPINKBN, CASE WHEN DELKIJYUNSU = 0 THEN NULL ELSE DELKIJYUNSU END AS DELKIJYUNSU, WARIGAIFLG, ITEMBETSUCD, URISEIGENFLG, CASE WHEN URIKETAKBN = 0 THEN NULL ELSE URIKETAKBN END AS URIKETAKBN, UPDKBN, SENDFLG, TRIM(OPERATOR), DATE_FORMAT(ADDDT, '%%Y/%%m/%%d %%T'), DATE_FORMAT(UPDDT, '%%Y/%%m/%%d %%T') FROM INAMS.MSTBMN ORDER BY BMNCD" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
