REM [200][mstDAIBRUI]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0200
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=A11MTN04

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(棚卸管理_大分類マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT BMNCD, DAICD, RTRIM(DAIBRUIAN) AS DAIBRUIAN, TRIM(TRAILING '　' FROM DAIBRUIKN) AS DAIBRUIKN, CASE WHEN ATR1 = 0 THEN NULL ELSE ATR1 END AS ATR1, CASE WHEN ATR2 = 0 THEN NULL ELSE ATR2 END AS ATR2, CASE WHEN ATR3 = 0 THEN NULL ELSE ATR3 END AS ATR3, CASE WHEN ATR4 = 0 THEN NULL ELSE ATR4 END AS ATR4, CASE WHEN ATR5 = 0 THEN NULL ELSE ATR5 END AS ATR5, CASE WHEN ATR6 = 0 THEN NULL ELSE ATR6 END AS ATR6, UPDKBN, SENDFLG, TRIM(OPERATOR), DATE_FORMAT(ADDDT, '%%Y/%%m/%%d %%T'), DATE_FORMAT(UPDDT, '%%Y/%%m/%%d %%T') FROM INAMS.MSTDAIBRUI ORDER BY BMNCD, DAICD" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
