REM [202][mstTEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0202
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=A11MTN06

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(棚卸管理_店舗基本マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT TENCD, SEIKAAREAKBN, SENGYOKBN, SEINIKUKBN, CASE WHEN TENATR5 = 0 THEN NULL ELSE TENATR5 END AS TENATR5, CASE WHEN TENATR6 = 0 THEN NULL ELSE TENATR6 END AS TENATR6, TENOPENDT, CASE WHEN TENCLOSEDT = 0 THEN NULL ELSE TENCLOSEDT END AS TENCLOSEDT, CASE WHEN KAISODT1 = 0 THEN NULL ELSE KAISODT1 END AS KAISODT1, CASE WHEN KAISODT2 = 0 THEN NULL ELSE KAISODT2 END AS KAISODT2, CASE WHEN KAISODT3 = 0 THEN NULL ELSE KAISODT3 END AS KAISODT3, SC_SFLG, KOSEI_SFLG, BUNRUI_SFLG, BMN_SFLG, YOBI1_SFLG, YOBI2_SFLG, DTORIKOMIDT, HANBAIBUCD, CHIKUCD, CASE WHEN URIAERACD = 0 THEN NULL ELSE URIAERACD END AS URIAERACD, CASE WHEN CHIIKICD = 0 THEN NULL ELSE CHIIKICD END AS CHIIKICD, YOSANKBN_T, TRIM(TRAILING '　' FROM TENKN) AS TENKN, TRIM(TENAN) AS TENAN, YUBINNO_U, YUBINNO_S, TRIM(TRAILING '　' FROM ADDRKN_T) AS ADDRKN_T, TRIM(TRAILING '　' FROM ADDRKN_S) AS ADDRKN_S, TRIM(TRAILING '　' FROM ADDRKN_M) AS ADDRKN_M, TRIM(TRAILING '　' FROM ADDRKN_B) AS ADDRKN_B, TRIM(ADDRAN_T) AS ADDRAN_T, TRIM(ADDRAN_S) AS ADDRAN_S, TRIM(ADDRAN_M) AS ADDRAN_M, TRIM(ADDRAN_B) AS ADDRAN_B, TRIM(TRAILING '　' FROM MOYORIEKIKN) AS MOYORIEKIKN, TRIM(TRAILING '　' FROM BUSSTOPKN) AS BUSSTOPKN, TRIM(TRAILING '　' FROM OWNT_NMKN) AS OWNT_NMKN, TRIM(TRAILING '　' FROM OWNT_ADDRKN_T) AS OWNT_ADDRKN_T, TRIM(TRAILING '　' FROM OWNT_ADDRKN_S) AS OWNT_ADDRKN_S, TRIM(TRAILING '　' FROM OWNT_ADDRKN_M) AS OWNT_ADDRKN_M, TRIM(TRAILING '　' FROM OWNT_ADDRKN_B) AS OWNT_ADDRKN_B, TRIM(TRAILING '　' FROM OWNP_NMKN) AS OWNP_NMKN, TRIM(TRAILING '　' FROM OWNP_ADDRKN_T) AS OWNP_ADDRKN_T, TRIM(TRAILING '　' FROM OWNP_ADDRKN_S) AS OWNP_ADDRKN_S, TRIM(TRAILING '　' FROM OWNP_ADDRKN_M) AS OWNP_ADDRKN_M, TRIM(TRAILING '　' FROM OWNP_ADDRKN_B) AS OWNP_ADDRKN_B, TRIM(TRAILING '　' FROM OWNO_NMKN) AS OWNO_NMKN, TRIM(TRAILING '　' FROM OWNO_ADDRKN_T) AS OWNO_ADDRKN_T, TRIM(TRAILING '　' FROM OWNO_ADDRKN_S) AS OWNO_ADDRKN_S, TRIM(TRAILING '　' FROM OWNO_ADDRKN_M) AS OWNO_ADDRKN_M, TRIM(TRAILING '　' FROM OWNO_ADDRKN_B) AS OWNO_ADDRKN_B, TRIM(TEL1) AS TEL1, TRIM(TEL2) AS TEL2, TRIM(TEL3) AS TEL3, TRIM(TEL4) AS TEL4, TRIM(TEL5) AS TEL5, TRIM(FAX1) AS FAX1, TRIM(FAX2) AS FAX2, CASE WHEN EGYOTM1_STMD = 0 THEN NULL ELSE EGYOTM1_STMD END AS EGYOTM1_STMD, CASE WHEN EGYOTM1_EDMD = 0 THEN NULL ELSE EGYOTM1_EDMD END AS EGYOTM1_EDMD, CASE WHEN EGYOTM1_STHM = 0 THEN NULL ELSE EGYOTM1_STHM END AS EGYOTM1_STHM, CASE WHEN EGYOTM1_EDHM = 0 THEN NULL ELSE EGYOTM1_EDHM END AS EGYOTM1_EDHM, CASE WHEN EGYOTM2_STMD = 0 THEN NULL ELSE EGYOTM2_STMD END AS EGYOTM2_STMD, CASE WHEN EGYOTM2_EDMD = 0 THEN NULL ELSE EGYOTM2_EDMD END AS EGYOTM2_EDMD, CASE WHEN EGYOTM2_STHM = 0 THEN NULL ELSE EGYOTM2_STHM END AS EGYOTM2_STHM, CASE WHEN EGYOTM2_EDHM = 0 THEN NULL ELSE EGYOTM2_EDHM END AS EGYOTM2_EDHM, CASE WHEN EGYOTM3_STMD = 0 THEN NULL ELSE EGYOTM3_STMD END AS EGYOTM3_STMD, CASE WHEN EGYOTM3_EDMD = 0 THEN NULL ELSE EGYOTM3_EDMD END AS EGYOTM3_EDMD, CASE WHEN EGYOTM3_STHM = 0 THEN NULL ELSE EGYOTM3_STHM END AS EGYOTM3_STHM, CASE WHEN EGYOTM3_EDHM = 0 THEN NULL ELSE EGYOTM3_EDHM END AS EGYOTM3_EDHM, CASE WHEN AREA_BA = 0 THEN NULL ELSE AREA_BA END AS AREA_BA, CASE WHEN AERA_B1YUKA = 0 THEN NULL ELSE AERA_B1YUKA END AS AERA_B1YUKA, CASE WHEN AREA_B1URIBA = 0 THEN NULL ELSE AREA_B1URIBA END AS AREA_B1URIBA, CASE WHEN AREA_1FYUKA = 0 THEN NULL ELSE AREA_1FYUKA END AS AREA_1FYUKA, CASE WHEN AREA_FURIBA = 0 THEN NULL ELSE AREA_FURIBA END AS AREA_FURIBA, CASE WHEN AREA_2FYUKA = 0 THEN NULL ELSE AREA_2FYUKA END AS AREA_2FYUKA, CASE WHEN AREA_2FURIBA = 0 THEN NULL ELSE AREA_2FURIBA END AS AREA_2FURIBA, CASE WHEN AREA_3FYUKA = 0 THEN NULL ELSE AREA_3FYUKA END AS AREA_3FYUKA, CASE WHEN AREA_3FURIBA = 0 THEN NULL ELSE AREA_3FURIBA END AS AREA_3FURIBA, CASE WHEN AREA_4FYUKA = 0 THEN NULL ELSE AREA_4FYUKA END AS AREA_4FYUKA, CASE WHEN AREA_4FURIBA = 0 THEN NULL ELSE AREA_4FURIBA END AS AREA_4FURIBA, CASE WHEN PARK_NM_BA = 0 THEN NULL ELSE PARK_NM_BA END AS PARK_NM_BA, CASE WHEN PARK_NM_YANE = 0 THEN NULL ELSE PARK_NM_YANE END AS PARK_NM_YANE, CASE WHEN PARK_NM_TOBI = 0 THEN NULL ELSE PARK_NM_TOBI END AS PARK_NM_TOBI, CASE WHEN PARK_LT_BA = 0 THEN NULL ELSE PARK_LT_BA END AS PARK_LT_BA, CASE WHEN PARK_LT_YANE = 0 THEN NULL ELSE PARK_LT_YANE END AS PARK_LT_YANE, CASE WHEN PARK_LT_TOBI = 0 THEN NULL ELSE PARK_LT_TOBI END AS PARK_LT_TOBI, CASE WHEN PARK_HC_BA = 0 THEN NULL ELSE PARK_HC_BA END AS PARK_HC_BA, CASE WHEN PARK_HC_YANE = 0 THEN NULL ELSE PARK_HC_YANE END AS PARK_HC_YANE, CASE WHEN PARK_HC_TOBI = 0 THEN NULL ELSE PARK_HC_TOBI END AS PARK_HC_TOBI, PARK_BIKE, ELEVTRFLG, ESCALTRFLG, CASE WHEN ATSUK_CD = 0 THEN NULL ELSE ATSUK_CD END AS ATSUK_CD, CASE WHEN ATSUK_CREDIT = 0 THEN NULL ELSE ATSUK_CREDIT END AS ATSUK_CREDIT, CASE WHEN ATSUK_COLESS = 0 THEN NULL ELSE ATSUK_COLESS END AS ATSUK_COLESS, CASE WHEN ATSUK_POINT = 0 THEN NULL ELSE ATSUK_POINT END AS ATSUK_POINT, SEIKACD, CAST(STAFFSU * 10 AS CHAR) AS STAFFSU, MISEUNYOKBN, UPDKBN, SENDFLG, TRIM(OPERATOR), DATE_FORMAT(ADDDT, '%%Y/%%m/%%d %%T'), DATE_FORMAT(UPDDT, '%%Y/%%m/%%d %%T') FROM INAMS.MSTTEN ORDER BY TENCD" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
