REM [203][mstSHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0203
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=A11MTN07

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(棚卸管理_商品マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT SHNCD, YOYAKUDT, TENBAIKADT, CASE WHEN YOT_BMNCD = 0 THEN NULL ELSE YOT_BMNCD END AS YOT_BMNCD, CASE WHEN YOT_DAICD = 0 THEN NULL ELSE YOT_DAICD END AS YOT_DAICD, CASE WHEN YOT_CHUCD = 0 THEN NULL ELSE YOT_CHUCD END AS YOT_CHUCD, CASE WHEN YOT_SHOCD = 0 THEN NULL ELSE YOT_SHOCD END AS YOT_SHOCD, CASE WHEN URI_BMNCD = 0 THEN NULL ELSE URI_BMNCD END AS URI_BMNCD, CASE WHEN URI_DAICD = 0 THEN NULL ELSE URI_DAICD END AS URI_DAICD, CASE WHEN URI_CHUCD = 0 THEN NULL ELSE URI_CHUCD END AS URI_CHUCD, CASE WHEN URI_SHOCD = 0 THEN NULL ELSE URI_SHOCD END AS URI_SHOCD, BMNCD, DAICD, CHUCD, SHOCD, CASE WHEN SSHOCD = 0 THEN NULL ELSE SSHOCD END AS SSHOCD, CASE WHEN ATSUK_STDT = 0 THEN NULL ELSE ATSUK_STDT END AS ATSUK_STDT, CASE WHEN ATSUK_EDDT = 0 THEN NULL ELSE ATSUK_EDDT END AS ATSUK_EDDT, TEISHIKBN, SHNAN, TRIM(TRAILING '　' FROM SHNKN) AS SHNKN, TRIM(TRAILING '　' FROM PCARDKN) AS PCARDKN, TRIM(TRAILING '　' FROM POPKN) AS POPKN, TRIM(RECEIPTAN) AS RECEIPTAN, TRIM(TRAILING '　' FROM RECEIPTKN) AS RECEIPTKN, PCKBN, KAKOKBN, ICHIBAKBN, SHNKBN, TRIM(TRAILING '　' FROM SANCHIKN) AS SANCHIKN, SSIRCD, HSPTN, RG_ATSUKFLG, CAST(RG_GENKAAM AS CHAR) AS RG_GENKAAM, RG_BAIKAAM, RG_IRISU, RG_IDENFLG, RG_WAPNFLG, HS_ATSUKFLG, CAST(HS_GENKAAM AS CHAR) AS HS_GENKAAM, HS_BAIKAAM, HS_IRISU, HS_WAPNFLG, CASE WHEN HS_SPOTMINSU = 0 THEN NULL ELSE HS_SPOTMINSU END AS HS_SPOTMINSU, HP_SWAPNFLG, TRIM(TRAILING '　' FROM KIKKN) AS KIKKN, UP_YORYOSU, UP_TYORYOSU, UP_TANIKBN, SHNYOKOSZ, SHNTATESZ, SHNOKUSZ, CASE WHEN SHNJRYOSZ = 0 THEN NULL ELSE CAST(SHNJRYOSZ AS CHAR) END AS SHNJRYOSZ, PBKBN, KOMONOKBM, TANAOROKBN, TEIKEIKBN, ODS_HARUSU, ODS_NATSUSU, ODS_AKISU, ODS_FUYUSU, ODS_NYUKASU, ODS_NEBIKISU, PCARD_SHUKBN, PCARD_IROKBN, ZEIKBN, CASE WHEN ZEIRTKBN = 0 THEN NULL ELSE ZEIRTKBN END AS ZEIRTKBN, CASE WHEN ZEIRTKBN_OLD = 0 THEN NULL ELSE ZEIRTKBN_OLD END AS ZEIRTKBN_OLD, CASE WHEN ZEIRTHENKODT = 0 THEN NULL ELSE ZEIRTHENKODT END AS ZEIRTHENKODT, CASE WHEN SEIZOGENNISU = 0 THEN NULL ELSE SEIZOGENNISU END AS SEIZOGENNISU, TEIKANKBN, MAKERCD, IMPORTKBN, CASE WHEN SIWAKEKBN = 0 THEN NULL ELSE SIWAKEKBN END AS SIWAKEKBN, HENPIN_KBN, CASE WHEN TAISHONENSU = 0 THEN NULL ELSE TAISHONENSU END AS TAISHONENSU, CASE WHEN CALORIESU = 0 THEN NULL ELSE CALORIESU END AS CALORIESU, ELPFLG, BELLMARKFLG, RECYCLEFLG, ECOFLG, CASE WHEN HZI_YOTO = 0 THEN NULL ELSE HZI_YOTO END AS HZI_YOTO, CASE WHEN HZI_ZAISHITU = 0 THEN NULL ELSE HZI_ZAISHITU END AS HZI_ZAISHITU, HZI_RECYCLE, KIKANKBN, CASE WHEN SHUKYUKBN = 0 THEN NULL ELSE SHUKYUKBN END AS SHUKYUKBN, CASE WHEN DOSU = 0 THEN NULL ELSE DOSU END AS DOSU, CHINRETUCD, DANTUMICD, KASANARICD, CASE WHEN KASANARISZ = 0 THEN NULL ELSE KASANARISZ END AS KASANARISZ, CASE WHEN ASSHUKURT = 0 THEN NULL ELSE ASSHUKURT END AS ASSHUKURT, SHUBETUCD, URICD, TRIM(TRAILING '　' FROM SALESCOMKN) AS SALESCOMKN, URABARIKBN, PCARD_OPFLG, PARENTCD, BINKBN, HAT_MONKBN, HAT_TUEKBN, HAT_WEDKBN, HAT_THUKBN, HAT_FRIKBN, HAT_SATKBN, HAT_SUNKBN, READTMPTN, SIMEKAISU, IRYOREFLG, TOROKUMOTO, UPDKBN, SENDFLG, TRIM(OPERATOR), DATE_FORMAT(ADDDT, '%%Y/%%m/%%d %%T'), DATE_FORMAT(UPDDT, '%%Y/%%m/%%d %%T') FROM INAMS.MSTSHN ORDER BY SHNCD" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
