REM [205][tokMOYCD]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0205
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=A11MTN09

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(棚卸管理_催しコード)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, SHUNO, TRIM(TRAILING '　' FROM MOYKN) AS MOYKN, TRIM(MOYAN) AS MOYAN, NENMATKBN, HBSTDT, HBEDDT, NNSTDT, NNEDDT, NNSTDT_TGF, NNEDDT_TGF, CASE WHEN PLUSDDT = 0 THEN NULL ELSE PLUSDDT END AS PLUSDDT, PLUSFLG, UPDKBN, SENDFLG, TRIM(OPERATOR), DATE_FORMAT(ADDDT, '%%Y/%%m/%%d %%T'), DATE_FORMAT(UPDDT, '%%Y/%%m/%%d %%T') FROM INATK.TOKMOYCD ORDER BY MOYSKBN, MOYSSTDT, MOYSRBAN" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
