REM [206][tokSO_SHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0206
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=A11MTN10

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(棚卸管理_生活応援_商品)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, SHNCD, TRIM(TRAILING '　' FROM MAKERKN) AS MAKERKN, TRIM(TRAILING '　' FROM SHNKN) AS SHNKN, TRIM(TRAILING '　' FROM KIKKN) AS KIKKN, IRISU, MINSU, CAST(GENKAAM AS CHAR) AS GENKAAM, CASE WHEN A_BAIKAAM = 0 THEN NULL ELSE A_BAIKAAM END AS A_BAIKAAM, CASE WHEN B_BAIKAAM = 0 THEN NULL ELSE B_BAIKAAM END AS B_BAIKAAM, CASE WHEN C_BAIKAAM = 0 THEN NULL ELSE C_BAIKAAM END AS C_BAIKAAM, CASE WHEN A_RANKNO = 0 THEN NULL ELSE A_RANKNO END AS A_RANKNO, CASE WHEN B_RANKNO = 0 THEN NULL ELSE B_RANKNO END AS B_RANKNO, CASE WHEN C_RANKNO = 0 THEN NULL ELSE C_RANKNO END AS C_RANKNO, CASE WHEN POPCD = 0 THEN NULL ELSE POPCD END AS POPCD, TRIM(POPSZ) AS POPSZ, POPSU, TENATSUK_ARR, UPDKBN, SENDFLG, TRIM(OPERATOR), DATE_FORMAT(ADDDT, '%%Y/%%m/%%d %%T'), DATE_FORMAT(UPDDT, '%%Y/%%m/%%d %%T') FROM INATK.TOKSO_SHN ORDER BY MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1

