REM [015][UPDATE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET INFILENAME=
REM ===== 催し週
SET MSG=%DATE% %TIME% 催し週 INATK.TOKMOYSYU DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKMOYSYU WHERE SENDFLG=1 AND UPDKBN=1;commit" >>%OUTFILE% 2>&1

REM ===== ちらしのみ部門（催しコード）
SET MSG=%DATE% %TIME%  INATK.TOKCHIRASBMN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKCHIRASBMN T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKMOYCD T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN);commit" >>%OUTFILE% 2>&1

REM ===== 催しコード
SET MSG=%DATE% %TIME%  INATK.TOKMOYCD DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKMOYCD WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1


REM ===== ランクマスタ
SET MSG=%DATE% %TIME%  INATK.TOKRANK DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKRANK WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 臨時ランクマスタ
SET MSG=%DATE% %TIME%  INATK.TOKRANKEX DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKRANKEX WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 数量ランク（数量パターン）
SET MSG=%DATE% %TIME%  INATK.TOKSRYRANK DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSRYRANK T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKSRPTN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.BMNCD=T2.BMNCD AND T1.SRYPTNNO=T2.SRYPTNNO);commit" >>%OUTFILE% 2>&1

REM ===== 数量パターン
SET MSG=%DATE% %TIME%  INATK.TOKSRPTN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSRPTN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 臨時数量ランク（数量パターン）
SET MSG=%DATE% %TIME%  INATK.TOKSRYRANKEX DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSRYRANKEX T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKSRPTNEX T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.BMNCD=T2.BMNCD AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN AND T1.SRYPTNNO=T2.SRYPTNNO);commit" >>%OUTFILE% 2>&1

REM ===== 臨時数量パターン
SET MSG=%DATE% %TIME%  INATK.TOKSRPTNEX DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSRPTNEX WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 通常率パターン
SET MSG=%DATE% %TIME%  INATK.TOKRTPTN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKRTPTN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== BM催し送信_対象除外店（BM催し送信）
SET MSG=%DATE% %TIME%  INATK.TOKBM_TJTEN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKBM_TJTEN T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKBM T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN AND T1.BMNNO=T2.BMNNO);commit" >>%OUTFILE% 2>&1

REM ===== BM催し送信_商品（BM催し送信）
SET MSG=%DATE% %TIME%  INATK.TOKBM_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKBM_SHN T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKBM T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN AND T1.BMNNO=T2.BMNNO);commit" >>%OUTFILE% 2>&1

REM ===== BM催し送信
SET MSG=%DATE% %TIME%  INATK.TOKBM DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKBM WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 生活応援_部門
SET MSG=%DATE% %TIME%  INATK.TOKSO_BMN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSO_BMN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 生活応援_商品
SET MSG=%DATE% %TIME%  INATK.TOKSO_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSO_SHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 冷凍食品_企画
SET MSG=%DATE% %TIME%  INATK.TOKRS_KKK DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKRS_KKK WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 冷凍食品_商品
SET MSG=%DATE% %TIME%  INATK.TOKRS_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKRS_SHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 事前打出し商品
SET MSG=%DATE% %TIME%  INATK.TOKJU_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKJU_SHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 店舗アンケート付き送付け_催し
SET MSG=%DATE% %TIME%  INATK.TOKQJU_MOY DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKQJU_MOY WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 店舗アンケート付き送付け_商品
SET MSG=%DATE% %TIME%  INATK.TOKQJU_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKQJU_SHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート有)_店グループ
SET MSG=%DATE% %TIME%  INATK.TOKTG_TENGP DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_TENGP WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート有)_店舗（全店特売（アンケート有）_基本）
SET MSG=%DATE% %TIME%  INATK.TOKTG_TEN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_TEN T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKTG_KHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN);commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート有)_部門
SET MSG=%DATE% %TIME%  INATK.TOKTG_BMN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_BMN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート有)_商品
SET MSG=%DATE% %TIME%  INATK.TOKTG_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_SHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート有)_対象除外店（全店特売（アンケート有）_基本）
SET MSG=%DATE% %TIME%  INATK.TOKTG_TJTEN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_TJTEN T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKTG_KHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN);commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート有)_納入日（全店特売（アンケート有）_基本）
SET MSG=%DATE% %TIME%  INATK.TOKTG_NNDT DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_NNDT T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKTG_KHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN);commit" >>%OUTFILE% 2>&1

REM ===== アンケート結果_店グループ（全店特売（アンケート有）_基本）
SET MSG=%DATE% %TIME%  INATK.TOKTG_QAGP DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_QAGP T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKTG_KHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN);commit" >>%OUTFILE% 2>&1

REM ===== アンケート結果_店舗（全店特売（アンケート有）_基本）
SET MSG=%DATE% %TIME%  INATK.TOKTG_QATEN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_QATEN T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKTG_KHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN);commit" >>%OUTFILE% 2>&1

REM ===== アンケート結果_商品（全店特売（アンケート有）_基本）
SET MSG=%DATE% %TIME%  INATK.TOKTG_QASHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_QASHN T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKTG_KHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN);commit" >>%OUTFILE% 2>&1

REM ===== 全店特売（アンケート有）_基本
SET MSG=%DATE% %TIME%  INATK.TOKTG_KHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTG_KHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート無)_部門
SET MSG=%DATE% %TIME%  INATK.TOKSP_BMN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSP_BMN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート無)_対象除外店（全店特売(アンケート無)_商品）
SET MSG=%DATE% %TIME%  INATK.TOKSP_TJTEN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSP_TJTEN T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKSP_SHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN AND T1.BMNCD=T2.BMNCD AND T1.KANRINO=T2.KANRINO AND T1.KANRIENO=T2.KANRIENO);commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート無)_販売（全店特売(アンケート無)_商品）
SET MSG=%DATE% %TIME%  INATK.TOKSP_HB DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSP_HB T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKSP_SHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN AND T1.BMNCD=T2.BMNCD AND T1.KANRINO=T2.KANRINO AND T1.KANRIENO=T2.KANRIENO);commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート無)_納入日（全店特売(アンケート無)_商品）
SET MSG=%DATE% %TIME%  INATK.TOKSP_NNDT DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSP_NNDT T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKSP_SHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN AND T1.BMNCD=T2.BMNCD AND T1.KANRINO=T2.KANRINO AND T1.KANRIENO=T2.KANRIENO);commit" >>%OUTFILE% 2>&1
SET MSG=%DATE% %TIME%  INATK2.TOKSP_NNDT DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK2.TOKSP_NNDT T1 WHERE EXISTS (SELECT 1 FROM INATK.TOKSP_SHN T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.MOYSKBN=T2.MOYSKBN AND T1.MOYSSTDT=T2.MOYSSTDT AND T1.MOYSRBAN=T2.MOYSRBAN AND T1.BMNCD=T2.BMNCD AND T1.KANRINO=T2.KANRINO AND T1.KANRIENO=T2.KANRIENO);commit" >>%OUTFILE% 2>&1

REM ===== 全店特売(アンケート無)_商品
SET MSG=%DATE% %TIME%  INATK.TOKSP_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKSP_SHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 正規定量_商品
SET MSG=%DATE% %TIME%  INATK.HATSTR_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATSTR_SHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 正規定量_店別数量
SET MSG=%DATE% %TIME%  INATK.HATSTR_TEN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATSTR_TEN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 予約発注_納入日（予約発注_企画）
SET MSG=%DATE% %TIME%  INATK.HATYH_NNDT DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATYH_NNDT T1 WHERE EXISTS (SELECT 1 FROM INATK.HATYH_KKK T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.KKKCD=T2.KKKCD);commit" >>%OUTFILE% 2>&1

REM ===== 予約発注_店舗（予約発注_企画）
SET MSG=%DATE% %TIME%  INATK.HATYH_TEN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATYH_TEN T1 WHERE EXISTS (SELECT 1 FROM INATK.HATYH_KKK T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.KKKCD=T2.KKKCD);commit" >>%OUTFILE% 2>&1

REM ===== 予約発注_企画
SET MSG=%DATE% %TIME%  INATK.HATYH_KKK DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATYH_KKK WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 予約発注_商品
SET MSG=%DATE% %TIME%  INATK.HATYH_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATYH_SHN WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1

REM ===== 新店改装店発注_商品
SET MSG=%DATE% %TIME%  INATK.HATSK_SHN DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATSK_SHN T1 WHERE EXISTS (SELECT 1 FROM INATK.HATSK T2 WHERE T2.SENDFLG = 1 AND T2.UPDKBN = 1 AND T1.INPUTNO=T2.INPUTNO);commit" >>%OUTFILE% 2>&1

REM ===== 新店改装店発注
SET MSG=%DATE% %TIME%  INATK.HATSK DELETE処理（更新区分=1＆送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATSK WHERE SENDFLG = 1 AND UPDKBN = 1;commit" >>%OUTFILE% 2>&1




REM IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
