REM [000][AN_NOUNYU_BFR_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_NOUNYU_BFR_TEN ロード処理（中間納入日(ア有反映前)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_NOUNYU_BFR_TEN;commit;" >> %OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.AN_NOUNYU_BFR_TEN WITH WK AS (SELECT TGND.MOYSKBN, TGND.MOYSSTDT, TGND.MOYSRBAN, TGND.BMNCD, TGND.KANRINO, TGND.KANRIENO, NUMS.TENCD, TGND.NNDT, CASE WHEN TRIM(SUBSTR(TGND.TENHTSU_ARR, ((NUMS.TENCD - 1) * 5) + 1, 5)) = '' THEN NULL ELSE CAST(TRIM(SUBSTR(TGND.TENHTSU_ARR, ((NUMS.TENCD - 1) * 5) + 1, 5)) AS SIGNED) END AS HSUU, CASE WHEN SUBSTR(TGND.TENCHGFLG_ARR, NUMS.TENCD, 1) = ' ' THEN NULL ELSE CAST(SUBSTR(TGND.TENCHGFLG_ARR, NUMS.TENCD, 1) AS SIGNED) END AS TENHENKO, TGND.HTASU, TGND.PTNNO, TGND.TSEIKBN, TGND.ZJSKFLG, TGND.WEEKHTDT, CASE WHEN TGND.TENCHGFLG_ARR = REPEAT('1', 400) THEN 1 ELSE 0 END AS ALL1FLG FROM INATK2.TOKTG_NNDT TGND INNER JOIN INATK2.TOKTG_SHN TGS on TGND.MOYSKBN = TGS.MOYSKBN AND TGND.MOYSSTDT = TGS.MOYSSTDT AND TGND.MOYSRBAN = TGS.MOYSRBAN AND TGND.BMNCD = TGS.BMNCD AND TGND.KANRINO = TGS.KANRINO AND TGND.KANRIENO = TGS.KANRIENO AND TGS.UPDKBN <> 1 LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 WHERE TGND.SENDFLG <> 1) SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, TENCD, NNDT, HSUU, TENHENKO, HTASU, PTNNO, TSEIKBN, ZJSKFLG, WEEKHTDT FROM WK SHN;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_NOUNYU_BFR_TEN;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
