REM [000][AN_NOUNYU_BFR_NEW]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_BFR ロード処理（全店特売アンケート有 納入データ(反映前)）※OUTDD3:変更無回答用納入ﾃﾞｰﾀ
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e " INSERT ignore INTO INAIF.AN_NOUNYU_BFR WITH TGTG AS (SELECT * FROM INATK2.TOKTG_TENGP TGTG WHERE TGTG.UPDKBN <> 1), TGTEN AS (SELECT TGTEN.MOYSKBN, TGTEN.MOYSSTDT, TGTEN.MOYSRBAN, TGTEN.TENCD, TGTEN.TENGPCD, TGTG.QASYUKBN, TGTEN.KYOSEIFLG, TGTEN.LDTENKBN FROM INATK2.TOKTG_TEN TGTEN LEFT OUTER JOIN TGTG ON TGTG.MOYSKBN = TGTEN.MOYSKBN AND TGTG.MOYSSTDT = TGTEN.MOYSSTDT AND TGTG.MOYSRBAN = TGTEN.MOYSRBAN AND TGTG.TENGPCD = TGTEN.TENGPCD) SELECT WK05_PRE.MOYSCD, WK05_PRE.MOYSKBN, WK05_PRE.MOYSSTDT, WK05_PRE.MOYSRBAN, WK05_PRE.BMNCD, WK05_PRE.KANRINO, WK05_PRE.KANRIENO, WK05_PRE.TENCD, WK05_PRE.NNDT, MC.SHUNO, MS.TSHUFLG, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNSTDT_TGF ELSE MC.NNSTDT END AS MYOSNNSTDT, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNEDDT_TGF ELSE MC.NNEDDT END AS MYOSNNEDDT, MC.NENMATKBN, WK05_PRE.JLSTCREFLG, WK05_PRE.JLSTCREDT, WK05_PRE.JHTSUINDT, WK05_PRE.WEEKHTDT, TGKHN.QADEVSTDT, WK05_PRE.QADEVEDFLG, TGTEN.TENGPCD, TGTEN.KYOSEIFLG, WK05_PRE.SHNCD, WK05_PRE.REIDMYKBN, WK05_PRE.NNSTDT, WK05_PRE.NNEDDT, WK05_PRE.JUFLG, WK05_PRE.JUHTDT, WK05_PRE.BINKBN, WK05_PRE.NNSLIDE, WK05_PRE.CUTTENFLG, WK05_PRE.SHUDENFLG, WK05_PRE.HSUU, WK05_PRE.HTASU, WK05_PRE.PTNNO, WK05_PRE.TSEIKBN, WK05_PRE.ZJSKFLG, WK05_PRE.NNWEEKHTDT, TGTEN.QASYUKBN, WK05_PRE.LDSYFLG, CASE WHEN TGTEN.LDTENKBN = 0 THEN 1 WHEN TGTEN.LDTENKBN = 1 THEN 2 END AS MBSYFLG, WK05_PRE.ITMSELKBN, WK05_PRE.GTSIMECHGKBN, WK05_PRE.GTSIMEOKFLG, WK05_PRE.SENDFLG, 0 AS UPDKBN FROM INAPRE.AN_NOUNYU_BFR WK05_PRE INNER JOIN INATK2.TOKTG_KHN TGKHN ON WK05_PRE.MOYSKBN = TGKHN.MOYSKBN AND WK05_PRE.MOYSSTDT = TGKHN.MOYSSTDT AND WK05_PRE.MOYSRBAN = TGKHN.MOYSRBAN INNER JOIN INATK2.TOKMOYCD MC ON WK05_PRE.MOYSKBN = MC.MOYSKBN AND WK05_PRE.MOYSSTDT = MC.MOYSSTDT AND WK05_PRE.MOYSRBAN = MC.MOYSRBAN INNER JOIN (SELECT * FROM INATK2.TOKMOYSYU MS LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL - 1 YEAR), '%%y') <= SUBSTR(MS.SHUNO, 1, 2) AND SUBSTR(MS.SHUNO, 1, 2) <= DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL + 1 YEAR), '%%y')) MS ON MS.SHUNO = MC.SHUNO LEFT OUTER JOIN TGTEN ON WK05_PRE.MOYSKBN = TGTEN.MOYSKBN AND WK05_PRE.MOYSSTDT = TGTEN.MOYSSTDT AND WK05_PRE.MOYSRBAN = TGTEN.MOYSRBAN AND WK05_PRE.TENCD = TGTEN.TENCD LEFT OUTER JOIN INAPARM.PRAM_FRSDRYJUD FDJ ON FDJ.BMNCD = WK05_PRE.BMNCD AND FDJ.JUDFLG = 'S' WHERE NOT EXISTS (SELECT 1 FROM INATK2.TOKTG_SHN TGSHN WHERE WK05_PRE.MOYSKBN = TGSHN.MOYSKBN AND WK05_PRE.MOYSSTDT = TGSHN.MOYSSTDT AND WK05_PRE.MOYSRBAN = TGSHN.MOYSRBAN AND WK05_PRE.BMNCD = TGSHN.BMNCD AND WK05_PRE.KANRINO = TGSHN.KANRINO AND WK05_PRE.KANRIENO = TGSHN.KANRIENO AND TGSHN.SENDFLG <> 1);commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_BFR;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
