REM [000][JH_HSUU_KEY_NEQ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.JH_HSUU_KEY_NEQ ロード処理（事前発注_発注数量取込中間キー(ア無)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAWK.JH_HSUU_KEY_NEQ ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.JH_HSUU_KEY_NEQ SELECT ANN.MOYSCD, ANN.MOYSKBN, ANN.MOYSSTDT, ANN.MOYSRBAN, ANN.BMNCD, ANN.KANRINO, ANN.KANRIENO, ANN.TENCD FROM INAIF.AN_NOUNYU_NEQ ANN INNER JOIN INAIF.JH_SHIME_DATE JSD ON ANN.BMNCD = JSD.BMNCD AND ANN.NENMATKBN = JSD.NENMATKBN WHERE ANN.NNSTDT <> 0 AND ANN.UPDKBN <> 1 AND (((ANN.NENMATKBN = 1 OR ANN.TSHUFLG = 1) AND (ANN.NNSTDT BETWEEN JSD.TOKSTDT AND JSD.TOKEDDT OR ANN.NNEDDT BETWEEN JSD.TOKSTDT AND JSD.TOKEDDT)) OR (JSD.TYUSTDT <= ANN.NNSTDT AND ANN.NNSTDT <= JSD.TYUEDDT)) GROUP BY ANN.MOYSCD, ANN.MOYSKBN, ANN.MOYSSTDT, ANN.MOYSRBAN, ANN.BMNCD, ANN.KANRINO, ANN.KANRIENO, ANN.TENCD; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.JH_HSUU_KEY_NEQ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
