REM [000][AN_NOUNYU_BFR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_BFR マージ処理（全特アンケート有 納入データ(反映前)）- 事前発注数量取込日
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAIF.AN_NOUNYU_BFR ANB, (SELECT ANB.MOYSCD, ANB.MOYSKBN, ANB.MOYSSTDT, ANB.MOYSRBAN, ANB.BMNCD, ANB.KANRINO, ANB.KANRIENO, ANB.TENCD, MAX(JSD.SNDSIMEDT) AS SNDSIMEDT FROM INAIF.AN_NOUNYU_BFR ANB INNER JOIN INAWK.JH_HSUU_KEY_BFR JHK ON ANB.MOYSCD = JHK.MOYSCD AND ANB.BMNCD = JHK.BMNCD AND ANB.KANRINO = JHK.KANRINO AND ANB.KANRIENO = JHK.KANRIENO AND ANB.TENCD = JHK.TENCD INNER JOIN INAIF.JH_SHIME_DATE JSD ON ANB.BMNCD = JSD.BMNCD AND ANB.NENMATKBN = JSD.NENMATKBN AND (((ANB.NENMATKBN = 1 OR ANB.TSHUFLG = 1) AND (ANB.NNSTDT BETWEEN JSD.TOKSTDT AND JSD.TOKEDDT OR ANB.NNEDDT BETWEEN JSD.TOKSTDT AND JSD.TOKEDDT)) OR (JSD.TYUSTDT <= ANB.NNSTDT AND ANB.NNSTDT <= JSD.TYUEDDT)) GROUP BY ANB.MOYSCD, ANB.MOYSKBN, ANB.MOYSSTDT, ANB.MOYSRBAN, ANB.BMNCD, ANB.KANRINO, ANB.KANRIENO, ANB.TENCD) ANB_UPD SET JHTSUINDT = ANB_UPD.SNDSIMEDT WHERE ANB.MOYSCD = ANB_UPD.MOYSCD AND ANB.MOYSKBN = ANB_UPD.MOYSKBN AND ANB.MOYSSTDT = ANB_UPD.MOYSSTDT AND ANB.MOYSRBAN = ANB_UPD.MOYSRBAN AND ANB.BMNCD = ANB_UPD.BMNCD AND ANB.KANRINO = ANB_UPD.KANRINO AND ANB.KANRIENO = ANB_UPD.KANRIENO AND ANB.TENCD = ANB_UPD.TENCD; commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_BFR;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
