REM [000][AN_ZW_NOUNYU_BFR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_ZW_NOUNYU_BFR ロード処理（全特アンケート有 納入データ 全品割引(反映前)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_ZW_NOUNYU_BFR;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIF.AN_ZW_NOUNYU_BFR WITH TGTG AS (SELECT * FROM INATK2.TOKTG_TENGP TGTG WHERE TGTG.UPDKBN <> 1), TGTEN AS (SELECT TGTEN.MOYSKBN, TGTEN.MOYSSTDT, TGTEN.MOYSRBAN, TGTEN.TENCD, TGTEN.TENGPCD, TGTG.QASYUKBN, TGTEN.KYOSEIFLG, TGTEN.LDTENKBN FROM INATK2.TOKTG_TEN TGTEN LEFT OUTER JOIN TGTG ON TGTG.MOYSKBN = TGTEN.MOYSKBN AND TGTG.MOYSSTDT = TGTEN.MOYSSTDT AND TGTG.MOYSRBAN = TGTEN.MOYSRBAN AND TGTG.TENGPCD = TGTEN.TENGPCD) SELECT DISTINCT LPAD(TGSHN.MOYSKBN, 1, 0) || LPAD(TGSHN.MOYSSTDT, 6, 0) || LPAD(TGSHN.MOYSRBAN, 3, 0) AS MOYSCD, TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, TGSHN.BMNCD, TGSHN.KANRINO, TGSHN.KANRIENO, TC16.TENCD, TC16.NNDT, MC.SHUNO, MS.TSHUFLG, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNSTDT_TGF ELSE MC.NNSTDT END AS MYOSHBSTDT, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNEDDT_TGF ELSE MC.NNEDDT END AS MYOSNNEDDT, MC.NENMATKBN, TGKHN.JLSTCREFLG, TGSHN.JLSTCREDT, TGSHN.JHTSUINDT, TGSHN.WEEKHTDT, TGKHN.QADEVSTDT, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS QADEVEDFLG, TGTEN.TENGPCD, TGTEN.KYOSEIFLG, TGSHN.SHNCD, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, TGSHN.NNSTDT, TGSHN.NNEDDT, TGSHN.JUFLG, TGSHN.JUHTDT, TGSHN.BINKBN, 1 AS NNSLIDE, TGSHN.CUTTENFLG, TGSHN.SHUDENFLG, TC16.HSUU, TC16.HTASU, TC16.PTNNO, TC16.TSEIKBN, TC16.ZJSKFLG, TC16.WEEKHTDT AS NNWEEKHTDT, TGTEN.QASYUKBN, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS LDSYFLG, CASE WHEN TGTEN.LDTENKBN = 0 THEN 1 WHEN TGTEN.LDTENKBN = 1 THEN 2 END AS MBSYFLG, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS ITMSELKBN, TGSHN.GTSIMECHGKBN, TGSHN.GTSIMEOKFLG, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS SENDFLG, 0 AS UPDKBN FROM INATK2.TOKTG_SHN TGSHN INNER JOIN INAWK.AN_ZW_NOUNYU_BFR_TEN TC16 ON TGSHN.MOYSKBN = TC16.MOYSKBN AND TGSHN.MOYSSTDT = TC16.MOYSSTDT AND TGSHN.MOYSRBAN = TC16.MOYSRBAN AND TGSHN.BMNCD = TC16.BMNCD AND TGSHN.KANRINO = TC16.KANRINO AND TGSHN.KANRIENO = TC16.KANRIENO LEFT OUTER JOIN TGTEN ON TGSHN.MOYSKBN = TGTEN.MOYSKBN AND TGSHN.MOYSSTDT = TGTEN.MOYSSTDT AND TGSHN.MOYSRBAN = TGTEN.MOYSRBAN AND TC16.TENCD = TGTEN.TENCD INNER JOIN INATK2.TOKTG_KHN TGKHN ON TGSHN.MOYSKBN = TGKHN.MOYSKBN AND TGSHN.MOYSSTDT = TGKHN.MOYSSTDT AND TGSHN.MOYSRBAN = TGKHN.MOYSRBAN INNER JOIN (SELECT MC.* FROM INATK2.TOKMOYCD MC WHERE MC.UPDKBN <> 1) MC ON TGSHN.MOYSKBN = MC.MOYSKBN AND TGSHN.MOYSSTDT = MC.MOYSSTDT AND TGSHN.MOYSRBAN = MC.MOYSRBAN INNER JOIN (SELECT * FROM INATK2.TOKMOYSYU MS LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL - 1 YEAR), '%%y') <= SUBSTR(MS.SHUNO, 1, 2) AND SUBSTR(MS.SHUNO, 1, 2) <= DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL + 1 YEAR), '%%y')) MS ON MS.SHUNO = MC.SHUNO LEFT OUTER JOIN INAPARM.PRAM_FRSDRYJUD FDJ ON FDJ.BMNCD = TGSHN.BMNCD AND FDJ.JUDFLG = 'S' WHERE TGSHN.ADDSHUKBN = 1 AND TGSHN.UPDKBN <> 1 AND TGSHN.NNSTDT <> 0;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_ZW_NOUNYU_BFR;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
