REM [140][BFB01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0140
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFAUO001

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(定量特売ファイル（全店特売）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT RPAD(SHOHNC, 8, ' ') || RPAD(FILLER01, 6, ' ') || LPAD(COALESCE(CAST(SYOKBN AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(BINK AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(NOKAIS AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(NOSYUR AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(HAKAIS AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(HASYUR AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(NNYNOB AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(NONYB AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(HACHBI AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(HACYB AS CHAR), ''), 1, '0') || LPAD(COALESCE(replace (CAST(JZNGENKA AS CHAR), '.', ''), ''), 8, '0') || LPAD(COALESCE(replace (CAST(TUIGENKA AS CHAR), '.', ''), ''), 8, '0') || LPAD(COALESCE(replace (CAST(GENFU AS CHAR), '.', ''), ''), 8, '0') || LPAD(COALESCE(replace (CAST(GENFUK AS CHAR), '.', ''), ''), 8, '0') || LPAD(COALESCE(CAST(A_SOBAIFG AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(B_SOBAIFG AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(C_SOBAIFG AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(A_SOBAIFP AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(B_SOBAIFP AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(C_SOBAIFP AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(A_SOBAIFK AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(B_SOBAIFK AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(C_SOBAIFK AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(A_BAIKA_SOTO AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(B_BAIKA_SOTO AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(C_BAIKA_SOTO AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(HEKINP AS CHAR), ''), 5, '0') || LPAD(COALESCE(CAST(MISIR AS CHAR), ''), 3, '0') || LPAD(COALESCE(CAST(BD1SU AS CHAR), ''), 3, '0') || LPAD(COALESCE(CAST(BD2SU AS CHAR), ''), 3, '0') || LPAD(COALESCE(CAST(A_BDBAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(A_BD1BAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(A_BD2BAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(B_BDBAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(B_BD1BAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(B_BD2BAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(C_BDBAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(C_BD1BAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(C_BD2BAIKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(SIIRCD AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(NENMAT AS CHAR), ''), 1, '0') || RPAD(TEISEK, 1, ' ') || LPAD(COALESCE(CAST(TRTEISEK AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(TTKBN AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(KZKBN AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(TEFTEI AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(BETUDEN AS CHAR), ''), 1, '0') || RPAD(WAPENK, 1, ' ') || RPAD(IKKATK, 1, ' ') || LPAD(COALESCE(CAST(JIZNUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(SIDENF AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(TEICUTK AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(HOUZAI AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(DSEIK AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(PCKBN AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(HIGAWAK AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(HGEBATFL AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(REDMYFL AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(DATAK AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(SEISUR AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(HENSUR AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(SEITK AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(NONSJ AS CHAR), ''), 2, '0') || LPAD(COALESCE(CAST(ATARA AS CHAR), ''), 1, '0') || RPAD(RDHMHYO, 1, ' ') || RPAD(RDHMMON, 1, ' ') || RPAD(RDHMTUE, 1, ' ') || RPAD(RDHMWED, 1, ' ') || RPAD(RDHMTHU, 1, ' ') || RPAD(RDHMFRI, 1, ' ') || RPAD(RDHMSAT, 1, ' ') || RPAD(RDHMSUN, 1, ' ') || LPAD(COALESCE(CAST(NONSU AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(BUNBMC1 AS CHAR), ''), 3, '0') || LPAD(COALESCE(CAST(BUNDIC AS CHAR), ''), 2, '0') || LPAD(COALESCE(CAST(BUNCHC AS CHAR), ''), 2, '0') || LPAD(COALESCE(CAST(BUNSHC AS CHAR), ''), 2, '0') || LPAD(COALESCE(CAST(BUNSSC AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(MSSIRE AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(MSIR AS CHAR), ''), 3, '0') || RPAD(MSIKK, 1, ' ') || RPAD(MSWAP, 1, ' ') || LPAD(COALESCE(CAST(MSBIN AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(MOYOK AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(MOYOKA AS CHAR), ''), 6, '0') || LPAD(COALESCE(CAST(MOYORE AS CHAR), ''), 3, '0') || LPAD(COALESCE(CAST(BUNBMC2 AS CHAR), ''), 3, '0') || LPAD(COALESCE(CAST(KANBAN AS CHAR), ''), 4, '0') || LPAD(COALESCE(CAST(EDABAN AS CHAR), ''), 2, '0') || LPAD(COALESCE(CAST(SHUNO AS CHAR), ''), 4, '0') || LPAD(COALESCE(CAST(SMISECD AS CHAR), ''), 3, '0') || LPAD(COALESCE(CAST(KZCUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(KOUCUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(TEICUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(TOKCUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(KYUCUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(HACCUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(NONCUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(HSSCUT AS CHAR), ''), 1, '0') || LPAD(COALESCE(CAST(ZERO AS CHAR), ''), 1, '0') || RPAD(FILLER02, 1, ' ') || LPAD(COALESCE(CAST(SYORIK AS CHAR), ''), 2, '0') || RPAD(COALESCE(TOKCOME, ''), 30, '　') || RPAD(COALESCE(KIKMKJ, ''), 23, '　') || RPAD(COALESCE(SANTIMKJ, ''), 20, '　') || LPAD(COALESCE(CAST(JIZNB AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(JZHCB AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(JZHCSUB AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(SIHCSYB AS CHAR), ''), 8, '0') || LPAD(COALESCE(CAST(TTENRANK AS CHAR), ''), 3, '0') || LPAD(COALESCE(CAST(MSF_TBL AS CHAR), ''), 2800, '0') || RPAD(KZKUBETU, 1, ' ') || RPAD(SYUFLG, 1, ' ') || RPAD(HYSYUFLG, 1, ' ') || RPAD(JZNLSKSKB, 1, ' ') || RPAD(ANKUMUKB, 1, ' ') || RPAD(FILLER03, 1, ' ') || LPAD(COALESCE(CAST(SAKSEIB AS CHAR), ''), 8, '0') FROM INAWK.BFB01_Z A ORDER BY MOYOK, MOYOKA, MOYORE, BUNBMC2, KANBAN, EDABAN, NNYNOB, HAKAIS, HASYUR, SHOHNC">%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
