REM [148][JH_RTN_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME%  → INAWK.JH_RTN_TEN ロード処理（事前発注_店舗(戻り用)作成）※仮締用
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.JH_RTN_TEN; INSERT IGNORE INTO INAWK.JH_RTN_TEN SELECT TEN.LSTNO, TEN.BMNCD, TEN.HYOSEQNO, TEN.TENCD, SHN.SHNCD, SHN.BINKBN, TEN.IRISU_RG, TEN.IRISU_TB, TEN.SBAIKAAM_TB, TEN.BAIKAAM_TB, TEN.SBAIKAAM_RG, TEN.BAIKAAM_RG, TEN.GENKAAM_MAE, TEN.GENKAAM_ATO, TEN.GENKAAM_RG, TEN.GENKAAM_PACK, TEN.BAIKAAM_PACK, TEN.JTDT_01, TEN.JTDT_02, TEN.JTDT_03, TEN.JTDT_04, TEN.JTDT_05, TEN.JTDT_06, TEN.JTDT_07, TEN.JTDT_08, TEN.JTDT_09, TEN.JTDT_10, TEN.TSEIKBN_01, TEN.TSEIKBN_02, TEN.TSEIKBN_03, TEN.TSEIKBN_04, TEN.TSEIKBN_05, TEN.TSEIKBN_06, TEN.TSEIKBN_07, TEN.TSEIKBN_08, TEN.TSEIKBN_09, TEN.TSEIKBN_10, TEN.SHNKBN_01, TEN.SHNKBN_02, TEN.SHNKBN_03, TEN.SHNKBN_04, TEN.SHNKBN_05, TEN.SHNKBN_06, TEN.SHNKBN_07, TEN.SHNKBN_08, TEN.SHNKBN_09, TEN.SHNKBN_10, TEN.HTSU_01, TEN.HTSU_02, TEN.HTSU_03, TEN.HTSU_04, TEN.HTSU_05, TEN.HTSU_06, TEN.HTSU_07, TEN.HTSU_08, TEN.HTSU_09, TEN.HTSU_10, TEN.PAGENO, TEN.SENDFLG, TEN.OPERATOR, TEN.ADDDT, TEN.UPDDT FROM INATK2.TOKTJ_TEN TEN INNER JOIN INAIF.JH_SHIME_DATE T502 ON T502.LSTNO = TEN.LSTNO AND T502.BMNCD = TEN.BMNCD LEFT OUTER JOIN INATK2.TOKTJ_SHN SHN ON SHN.LSTNO = TEN.LSTNO AND SHN.BMNCD = TEN.BMNCD AND SHN.HYOSEQNO = TEN.HYOSEQNO WHERE TEN.SENDFLG IN (0, 9);commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.JH_RTN_TEN;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
