REM [196][INAAD_HATKEKKA]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAAD.HATKEKKA(発注結果) ロード処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAAD.HATKEKKA SELECT ORDERSTORECD, SALESORDERCOMPANYCD, SLIPNO, ORDERNO, CAST(ORDERDATE AS SIGNED) AS ORDERDATE, ORDERTIME, CAST(DELIVERYDATE AS SIGNED) AS DELIVERYDATE, DISTRIBUTIONDIV AS DISTRIBUTIONDIV, SUPPLYDIV AS SUPPLYDIV, SALESDIV AS SALESDIV, TEMPERATUREZONEDIV AS TEMPERATUREZONEDIV, PLANSALESCD, CONTROLNUMBER, ORDERUSERCD, DETAILNOOFLINES AS DETAILNOOFLINES, CATEGORY1CD AS CATEGORY1CD, CATEGORY2CD AS CATEGORY2CD, CATEGORY3CD AS CATEGORY3CD, CATEGORY4CD AS CATEGORY4CD, CAST(PRODUCTSCD AS CHAR (14)) AS PRODUCTSCD, PRODUCTSKANJI, CAST(SUBSTR(STD, 1, LENGTH(STD) - 2) || '.' || SUBSTR(STD, LENGTH(STD) - 1, 2) AS DECIMAL (10, 2)) AS STD, STDSUNITCD, CAST(SUBSTR(QTYPERUNIT, 1, LENGTH(QTYPERUNIT) - 2) || '.' || SUBSTR(QTYPERUNIT, LENGTH(QTYPERUNIT) - 1, 2) AS DECIMAL (10, 2)) AS QTYPERUNIT, CAST(SUBSTR(ORDERUNITQTY, 1, LENGTH(ORDERUNITQTY) - 2) || '.' || SUBSTR(ORDERUNITQTY, LENGTH(ORDERUNITQTY) - 1, 2) AS DECIMAL (10, 2)) AS ORDERUNITQTY, CAST(SUBSTR(ORDERTOTALQTY, 1, LENGTH(ORDERTOTALQTY) - 2) || '.' || SUBSTR(ORDERTOTALQTY, LENGTH(ORDERTOTALQTY) - 1, 2) AS DECIMAL (10, 2)) AS ORDERTOTALQTY, CAST(SUBSTR(ORIGINUNITPRICE, 1, LENGTH(ORIGINUNITPRICE) - 2) || '.' || SUBSTR(ORIGINUNITPRICE, LENGTH(ORIGINUNITPRICE) - 1, 2) AS DECIMAL (10, 2)) AS ORIGINUNITPRICE, CAST(SALEUNITPRICE AS SIGNED) AS SALEUNITPRICE, CAST(SUBSTR(COSTAMT, 1, LENGTH(COSTAMT) - 2) || '.' || SUBSTR(COSTAMT, LENGTH(COSTAMT) - 1, 2) AS DECIMAL (15, 2)) AS COSTAMT, CAST(SUBSTR(SELLPRICE, 1, LENGTH(SELLPRICE) - 2) || '.' || SUBSTR(SELLPRICE, LENGTH(SELLPRICE) - 1, 2) AS DECIMAL (15, 2)) AS SELLPRICE, ERRORDIV, ERRORMESSAGE, CENTERCD AS CENTERCD, CAST(SUPPLIERCD AS SIGNED) AS SUPPLIERCD, PRODUCTDIV AS PRODUCTDIV FROM INAIN.HATKEKKA;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAAD.HATKEKKA;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
