REM [196][INAIN_HATKEKKA]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET INFILENAME=C:\job\106\data\【朝特】SV10003_1119_2018030200078_2018030200068_001_01.txt
SET MSG=%DATE% %TIME%  →  LOAD処理(発注結果)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --local_infile=1 --show-warnings -vv -e "TRUNCATE TABLE INAIN.HATKEKKA; load data local infile '%INFILENAME%' IGNORE into table INAIN.HATKEKKA character set cp932 fields terminated by ',' ESCAPED BY '' lines terminated by '\r\n' (@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35) SET ORDERSTORECD = NULLIF(@1, ''), SALESORDERCOMPANYCD = NULLIF(@2, ''), SLIPNO = NULLIF(@3, ''), ORDERNO = NULLIF(@4, ''), ORDERDATE = NULLIF(@5, ''), ORDERTIME = NULLIF(@6, ''), DELIVERYDATE = NULLIF(@7, ''), DISTRIBUTIONDIV = NULLIF(@8, ''), SUPPLYDIV = NULLIF(@9, ''), SALESDIV = NULLIF(@10, ''), TEMPERATUREZONEDIV = NULLIF(@11, ''), PLANSALESCD = NULLIF(@12, ''), CONTROLNUMBER = NULLIF(@13, ''), ORDERUSERCD = NULLIF(@14, ''), DETAILNOOFLINES = NULLIF(@15, ''), CATEGORY1CD = NULLIF(@16, ''), CATEGORY2CD = NULLIF(@17, ''), CATEGORY3CD = NULLIF(@18, ''), CATEGORY4CD = NULLIF(@19, ''), PRODUCTSCD = NULLIF(@20, ''), PRODUCTSKANJI = NULLIF(@21, ''), STD = NULLIF(@22, ''), STDSUNITCD = NULLIF(@23, ''), QTYPERUNIT = NULLIF(@24, ''), ORDERUNITQTY = NULLIF(@25, ''), ORDERTOTALQTY = NULLIF(@26, ''), ORIGINUNITPRICE = NULLIF(@27, ''), SALEUNITPRICE = NULLIF(@28, ''), COSTAMT = NULLIF(@29, ''), SELLPRICE = NULLIF(@30, ''), ERRORDIV = NULLIF(@31, ''), ERRORMESSAGE = NULLIF(@32, ''), CENTERCD = NULLIF(@33, ''), SUPPLIERCD = NULLIF(@34, ''), PRODUCTDIV = NULLIF(@35, ''), ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIN.HATKEKKA;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
