REM [001][AEA81]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0001
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO001

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品基本マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SYOHIN AS (SELECT SHN.* FROM INAMS2.MSTSHN SHN WHERE SHN.SENDFLG IN (0, 9)), PRE AS (SELECT SHNCD FROM INAPRE.MSTSHN_PD WHERE UPDKBN <> 1 GROUP BY SHNCD) SELECT CASE WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END || 0 || SUBSTR(RPAD(SYOHIN.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(SYOHIN.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(SYOHIN.SHNCD, 14, ' '), 9, 6) || LPAD(SYOHIN.YOYAKUDT, 8, 0) || LPAD(SYOHIN.TENBAIKADT, 8, 0) || LPAD(SYOHIN.YOT_BMNCD, 3, 0) || LPAD(SYOHIN.YOT_DAICD, 2, 0) || LPAD(SYOHIN.YOT_CHUCD, 2, 0) || LPAD(SYOHIN.YOT_SHOCD, 2, 0) || LPAD(SYOHIN.URI_BMNCD, 3, 0) || LPAD(SYOHIN.URI_DAICD, 2, 0) || LPAD(SYOHIN.URI_CHUCD, 2, 0) || LPAD(SYOHIN.URI_SHOCD, 2, 0) || LPAD(SYOHIN.BMNCD, 3, 0) || LPAD(SYOHIN.DAICD, 2, 0) || LPAD(SYOHIN.CHUCD, 2, 0) || LPAD(SYOHIN.SHOCD, 2, 0) || LPAD(SYOHIN.SSHOCD, 1, 0) || LPAD(SYOHIN.ATSUK_STDT, 8, 0) || LPAD(SYOHIN.ATSUK_EDDT, 8, 0) || LPAD(SYOHIN.TEISHIKBN, 1, 0) || RPAD(SYOHIN.SHNAN, 20, ' ') || RPAD(SYOHIN.SHNKN, 20, '　') || RPAD(SYOHIN.PCARDKN, 20, '　') || RPAD(SYOHIN.POPKN, 20, '　') || RPAD(SYOHIN.RECEIPTAN, 20, ' ') || RPAD(SYOHIN.RECEIPTKN, 20, '　') || LPAD(SYOHIN.PCKBN, 1, 0) || LPAD(SYOHIN.KAKOKBN, 1, 0) || LPAD(SYOHIN.ICHIBAKBN, 1, 0) || LPAD(SYOHIN.SHNKBN, 1, 0) || RPAD(SYOHIN.SANCHIKN, 20, '　') || LPAD(SYOHIN.SSIRCD, 6, 0) || LPAD(SYOHIN.HSPTN, 3, 0) || LPAD(SYOHIN.RG_ATSUKFLG, 1, 0) || LPAD(CAST(SYOHIN.RG_GENKAAM * 100 AS SIGNED), 8, 0) || LPAD(SYOHIN.RG_BAIKAAM, 6, 0) || LPAD(SYOHIN.RG_IRISU, 3, 0) || LPAD(RPAD(SYOHIN.RG_IDENFLG, 1, ' '), 1, 0) || LPAD(RPAD(SYOHIN.RG_WAPNFLG, 1, ' '), 1, 0) || LPAD(SYOHIN.HS_ATSUKFLG, 1, 0) || LPAD(CAST(SYOHIN.HS_GENKAAM * 100 AS SIGNED), 8, 0) || LPAD(SYOHIN.HS_BAIKAAM, 6, 0) || LPAD(SYOHIN.HS_IRISU, 3, 0) || LPAD(RPAD(SYOHIN.HS_WAPNFLG, 1, ' '), 1, 0) || LPAD(SYOHIN.HS_SPOTMINSU, 2, 0) || LPAD(RPAD(SYOHIN.HP_SWAPNFLG, 1, ' '), 1, 0) || RPAD(SYOHIN.KIKKN, 23, '　') || LPAD(SYOHIN.UP_YORYOSU, 5, 0) || LPAD(SYOHIN.UP_TYORYOSU, 3, 0) || LPAD(SYOHIN.UP_TANIKBN, 2, 0) || LPAD(SYOHIN.SHNYOKOSZ, 4, 0) || LPAD(SYOHIN.SHNTATESZ, 4, 0) || LPAD(SYOHIN.SHNOKUSZ, 4, 0) || LPAD(CAST(SYOHIN.SHNJRYOSZ * 10 AS SIGNED), 6, 0) || LPAD(SYOHIN.PBKBN, 1, 0) || LPAD(SYOHIN.KOMONOKBM, 2, 0) || LPAD(SYOHIN.TANAOROKBN, 2, 0) || LPAD(SYOHIN.TEIKEIKBN, 1, 0) || LPAD(SYOHIN.ODS_HARUSU, 4, 0) || LPAD(SYOHIN.ODS_NATSUSU, 4, 0) || LPAD(SYOHIN.ODS_AKISU, 4, 0) || LPAD(SYOHIN.ODS_FUYUSU, 4, 0) || LPAD(SYOHIN.ODS_NYUKASU, 4, 0) || LPAD(SYOHIN.ODS_NEBIKISU, 4, 0) || LPAD(SYOHIN.PCARD_SHUKBN, 1, 0) || LPAD(SYOHIN.PCARD_IROKBN, 1, 0) || LPAD(SYOHIN.ZEIKBN, 1, 0) || LPAD(SYOHIN.ZEIRTKBN, 3, 0) || LPAD(SYOHIN.ZEIRTKBN_OLD, 3, 0) || LPAD(SYOHIN.ZEIRTHENKODT, 8, 0) || LPAD(SYOHIN.SEIZOGENNISU, 3, 0) || LPAD(SYOHIN.TEIKANKBN, 1, 0) || LPAD(SYOHIN.MAKERCD, 9, 0) || LPAD(SYOHIN.IMPORTKBN, 2, 0) || LPAD(SYOHIN.SIWAKEKBN, 2, 0) || LPAD(SYOHIN.HENPIN_KBN, 1, 0) || LPAD(SYOHIN.TAISHONENSU, 2, 0) || LPAD(SYOHIN.CALORIESU, 5, 0) || LPAD(SYOHIN.ELPFLG, 1, 0) || LPAD(SYOHIN.BELLMARKFLG, 1, 0) || LPAD(SYOHIN.RECYCLEFLG, 1, 0) || LPAD(SYOHIN.ECOFLG, 1, 0) || LPAD(SYOHIN.HZI_YOTO, 1, 0) || LPAD(SYOHIN.HZI_ZAISHITU, 1, 0) || LPAD(SYOHIN.HZI_RECYCLE, 1, 0) || LPAD(RPAD(SYOHIN.KIKANKBN, 1, ' '), 1, 0) || LPAD(SYOHIN.SHUKYUKBN, 2, 0) || LPAD(SYOHIN.DOSU, 3, 0) || LPAD(RPAD(SYOHIN.CHINRETUCD, 1, ' '), 1, 0) || LPAD(RPAD(SYOHIN.DANTUMICD, 2, ' '), 2, 0) || LPAD(RPAD(SYOHIN.KASANARICD, 1, ' '), 1, 0) || LPAD(SYOHIN.KASANARISZ, 3, 0) || LPAD(SYOHIN.ASSHUKURT, 2, 0) || LPAD(RPAD(SYOHIN.SHUBETUCD, 2, ' '), 2, 0) || LPAD(SYOHIN.URICD, 6, 0) || RPAD(SYOHIN.SALESCOMKN, 30, '　') || LPAD(SYOHIN.URABARIKBN, 1, 0) || LPAD(SYOHIN.PCARD_OPFLG, 1, 0) || LPAD(SUBSTR(RPAD(SYOHIN.PARENTCD, 14, ' '), 1, 8), 8, 0) || LPAD(SUBSTR(RPAD(SYOHIN.PARENTCD, 14, ' '), 9, 6), 6, 0) || LPAD(SYOHIN.BINKBN, 1, 0) || LPAD(SYOHIN.HAT_MONKBN, 1, 0) || LPAD(SYOHIN.HAT_TUEKBN, 1, 0) || LPAD(SYOHIN.HAT_WEDKBN, 1, 0) || LPAD(SYOHIN.HAT_THUKBN, 1, 0) || LPAD(SYOHIN.HAT_FRIKBN, 1, 0) || LPAD(SYOHIN.HAT_SATKBN, 1, 0) || LPAD(SYOHIN.HAT_SUNKBN, 1, 0) || LPAD(SYOHIN.READTMPTN, 3, 0) || LPAD(SYOHIN.SIMEKAISU, 1, 0) || LPAD(SYOHIN.IRYOREFLG, 1, 0) || LPAD(SYOHIN.TOROKUMOTO, 1, 0) || '      ' || LPAD(SYOHIN.UPDKBN, 1, 0) || LPAD(SYOHIN.SENDFLG, 1, 0) || RPAD(SYOHIN.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(SYOHIN.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(SYOHIN.UPDDT, '%%Y%%m%%d'), 8, 0) FROM SYOHIN LEFT OUTER JOIN PRE ON SYOHIN.SHNCD = PRE.SHNCD WHERE (PRE.SHNCD IS NOT NULL AND SYOHIN.UPDKBN = 1) OR SYOHIN.UPDKBN <> 1 ORDER BY SYOHIN.SHNCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
