REM [003][AEA83]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0003
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO011

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(売価コントロール)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SHN AS (SELECT SHN.SHNCD, SHN.UPDKBN FROM INAMS2.MSTSHN SHN WHERE SHN.SENDFLG IN (0, 9)), BC AS (SELECT BC.* FROM INAMS2.MSTBAIKACTL BC WHERE EXISTS (SELECT 1 FROM SHN WHERE SHN.UPDKBN <> 1 AND BC.SHNCD = SHN.SHNCD)), PRE AS (SELECT SHNCD FROM INAPRE.MSTBAIKACTL_PD T1 WHERE EXISTS (SELECT * FROM INAPRE.MSTSHN_PD T2 WHERE UPDKBN <> 1 AND T1.SHNCD = T2.SHNCD) GROUP BY SHNCD) SELECT CASE WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END || 0 || SUBSTR(B_BC.SHNCD, 1, 2) || SUBSTR(B_BC.SHNCD, 3, 6) || SUBSTR(RPAD(B_BC.SHNCD, 14, ' '), 9, 6) || LPAD(B_BC.TENGPCD, 4, 0) || LPAD(B_BC.YOYAKUDT, 8, 0) || LPAD(B_BC.AREAKBN, 1, 0) || LPAD(SUBSTR(B_BC.GENKAAM, 1, LOCATE('.', B_BC.GENKAAM) - 1), 6, 0) || SUBSTR(B_BC.GENKAAM, LOCATE('.', B_BC.GENKAAM) + 1) || LPAD(B_BC.BAIKAAM, 6, 0) || LPAD(B_BC.IRISU, 3, 0) || '         ' || RPAD(B_BC.OPERATOR, 20, ' ') || LPAD(B_BC.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(B_BC.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_BC.UPDDT, '%%Y%%m%%d'), 8, 0) FROM (SELECT * FROM BC) B_BC LEFT OUTER JOIN PRE ON B_BC.SHNCD = PRE.SHNCD ORDER BY B_BC.SHNCD, B_BC.TENGPCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
