REM [004][AEA84]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0004
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO017

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(ソースコード管理)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SHN AS (SELECT SHN.SHNCD, SHN.UPDKBN FROM INAMS2.MSTSHN SHN WHERE SHN.SENDFLG IN (0, 9)), SC AS (SELECT SC.* FROM INAMS2.MSTSRCCD SC WHERE SC.SEQNO IN (1, 2) AND EXISTS (SELECT 1 FROM SHN WHERE SHN.UPDKBN <> 1 AND SC.SHNCD = SHN.SHNCD)), PRE AS (SELECT SHNCD FROM INAPRE.MSTSRCCD_PD T1 WHERE T1.SEQNO IN (1, 2) AND EXISTS (SELECT 1 FROM INAPRE.MSTSHN_PD T2 WHERE UPDKBN <> 1 AND T1.SHNCD = T2.SHNCD) GROUP BY SHNCD) SELECT CASE WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END || SUBSTR(RPAD(B_SC.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_SC.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_SC.SHNCD, 14, ' '), 9, 6) || RPAD(B_SC.SRCCD, 14, ' ') || LPAD(B_SC.YOYAKUDT, 8, 0) || LPAD(B_SC.SEQNO, 1, 0) || LPAD(B_SC.SOURCEKBN, 1, 0) || '     ' || RPAD(B_SC.OPERATOR, 20, ' ') || LPAD(B_SC.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(B_SC.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_SC.UPDDT, '%%Y%%m%%d'), 8, 0) FROM (SELECT * FROM SC) B_SC LEFT OUTER JOIN PRE ON B_SC.SHNCD = PRE.SHNCD ORDER BY B_SC.SHNCD, B_SC.SRCCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
