REM [008][AEA81]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0008
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO003

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品基本マスタ(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SY AS (SELECT SY.* FROM INAMS2.MSTSHN_Y SY WHERE SY.SENDFLG IN (0, 9)), PRE AS (SELECT SHNCD, YOYAKUDT FROM INAPRE.MSTSHN_Y_PD WHERE UPDKBN <> 1) SELECT CASE WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END || 0 || SUBSTR(RPAD(SY.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(SY.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(SY.SHNCD, 14, ' '), 9, 6) || LPAD(SY.YOYAKUDT, 8, 0) || LPAD(SY.TENBAIKADT, 8, 0) || LPAD(SY.YOT_BMNCD, 3, 0) || LPAD(SY.YOT_DAICD, 2, 0) || LPAD(SY.YOT_CHUCD, 2, 0) || LPAD(SY.YOT_SHOCD, 2, 0) || LPAD(SY.URI_BMNCD, 3, 0) || LPAD(SY.URI_DAICD, 2, 0) || LPAD(SY.URI_CHUCD, 2, 0) || LPAD(SY.URI_SHOCD, 2, 0) || LPAD(SY.BMNCD, 3, 0) || LPAD(SY.DAICD, 2, 0) || LPAD(SY.CHUCD, 2, 0) || LPAD(SY.SHOCD, 2, 0) || LPAD(SY.SSHOCD, 1, 0) || LPAD(SY.ATSUK_STDT, 8, 0) || LPAD(SY.ATSUK_EDDT, 8, 0) || LPAD(SY.TEISHIKBN, 1, 0) || RPAD(SY.SHNAN, 20, ' ') || RPAD(SY.SHNKN, 20, '　') || RPAD(SY.PCARDKN, 20, '　') || RPAD(SY.POPKN, 20, '　') || RPAD(SY.RECEIPTAN, 20, ' ') || RPAD(SY.RECEIPTKN, 20, '　') || LPAD(SY.PCKBN, 1, 0) || LPAD(SY.KAKOKBN, 1, 0) || LPAD(SY.ICHIBAKBN, 1, 0) || LPAD(SY.SHNKBN, 1, 0) || RPAD(SY.SANCHIKN, 20, '　') || LPAD(SY.SSIRCD, 6, 0) || LPAD(SY.HSPTN, 3, 0) || LPAD(SY.RG_ATSUKFLG, 1, 0) || LPAD(CAST(SY.RG_GENKAAM * 100 AS SIGNED), 8, 0) || LPAD(SY.RG_BAIKAAM, 6, 0) || LPAD(SY.RG_IRISU, 3, 0) || LPAD(RPAD(SY.RG_IDENFLG, 1, ' '), 1, 0) || LPAD(RPAD(SY.RG_WAPNFLG, 1, ' '), 1, 0) || LPAD(SY.HS_ATSUKFLG, 1, 0) || LPAD(CAST(SY.HS_GENKAAM * 100 AS SIGNED), 8, 0) || LPAD(SY.HS_BAIKAAM, 6, 0) || LPAD(SY.HS_IRISU, 3, 0) || LPAD(RPAD(SY.HS_WAPNFLG, 1, ' '), 1, 0) || LPAD(SY.HS_SPOTMINSU, 2, 0) || LPAD(RPAD(SY.HP_SWAPNFLG, 1, ' '), 1, 0) || RPAD(SY.KIKKN, 23, '　') || LPAD(SY.UP_YORYOSU, 5, 0) || LPAD(SY.UP_TYORYOSU, 3, 0) || LPAD(SY.UP_TANIKBN, 2, 0) || LPAD(SY.SHNYOKOSZ, 4, 0) || LPAD(SY.SHNTATESZ, 4, 0) || LPAD(SY.SHNOKUSZ, 4, 0) || LPAD(CAST(SY.SHNJRYOSZ * 10 AS SIGNED), 6, 0) || LPAD(SY.PBKBN, 1, 0) || LPAD(SY.KOMONOKBM, 2, 0) || LPAD(SY.TANAOROKBN, 2, 0) || LPAD(SY.TEIKEIKBN, 1, 0) || LPAD(SY.ODS_HARUSU, 4, 0) || LPAD(SY.ODS_NATSUSU, 4, 0) || LPAD(SY.ODS_AKISU, 4, 0) || LPAD(SY.ODS_FUYUSU, 4, 0) || LPAD(SY.ODS_NYUKASU, 4, 0) || LPAD(SY.ODS_NEBIKISU, 4, 0) || LPAD(SY.PCARD_SHUKBN, 1, 0) || LPAD(SY.PCARD_IROKBN, 1, 0) || LPAD(SY.ZEIKBN, 1, 0) || LPAD(SY.ZEIRTKBN, 3, 0) || LPAD(SY.ZEIRTKBN_OLD, 3, 0) || LPAD(SY.ZEIRTHENKODT, 8, 0) || LPAD(SY.SEIZOGENNISU, 3, 0) || LPAD(SY.TEIKANKBN, 1, 0) || LPAD(SY.MAKERCD, 9, 0) || LPAD(SY.IMPORTKBN, 2, 0) || LPAD(SY.SIWAKEKBN, 2, 0) || LPAD(SY.HENPIN_KBN, 1, 0) || LPAD(SY.TAISHONENSU, 2, 0) || LPAD(SY.CALORIESU, 5, 0) || LPAD(SY.ELPFLG, 1, 0) || LPAD(SY.BELLMARKFLG, 1, 0) || LPAD(SY.RECYCLEFLG, 1, 0) || LPAD(SY.ECOFLG, 1, 0) || LPAD(SY.HZI_YOTO, 1, 0) || LPAD(SY.HZI_ZAISHITU, 1, 0) || LPAD(SY.HZI_RECYCLE, 1, 0) || LPAD(RPAD(SY.KIKANKBN, 1, ' '), 1, 0) || LPAD(SY.SHUKYUKBN, 2, 0) || LPAD(SY.DOSU, 3, 0) || LPAD(RPAD(SY.CHINRETUCD, 1, ' '), 1, 0) || LPAD(RPAD(SY.DANTUMICD, 2, ' '), 2, 0) || LPAD(RPAD(SY.KASANARICD, 1, ' '), 1, 0) || LPAD(SY.KASANARISZ, 3, 0) || LPAD(SY.ASSHUKURT, 2, 0) || LPAD(RPAD(SY.SHUBETUCD, 2, ' '), 2, 0) || LPAD(SY.URICD, 6, 0) || RPAD(SY.SALESCOMKN, 30, '　') || LPAD(SY.URABARIKBN, 1, 0) || LPAD(SY.PCARD_OPFLG, 1, 0) || LPAD(SUBSTR(RPAD(SY.PARENTCD, 14, ' '), 1, 8), 8, 0) || LPAD(SUBSTR(RPAD(SY.PARENTCD, 14, ' '), 9, 6), 6, 0) || LPAD(SY.BINKBN, 1, 0) || LPAD(SY.HAT_MONKBN, 1, 0) || LPAD(SY.HAT_TUEKBN, 1, 0) || LPAD(SY.HAT_WEDKBN, 1, 0) || LPAD(SY.HAT_THUKBN, 1, 0) || LPAD(SY.HAT_FRIKBN, 1, 0) || LPAD(SY.HAT_SATKBN, 1, 0) || LPAD(SY.HAT_SUNKBN, 1, 0) || LPAD(SY.READTMPTN, 3, 0) || LPAD(SY.SIMEKAISU, 1, 0) || LPAD(SY.IRYOREFLG, 1, 0) || LPAD(SY.TOROKUMOTO, 1, 0) || '      ' || LPAD(SY.UPDKBN, 1, 0) || LPAD(SY.SENDFLG, 1, 0) || RPAD(SY.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(SY.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(SY.UPDDT, '%%Y%%m%%d'), 8, 0) FROM SY LEFT OUTER JOIN PRE ON SY.SHNCD = PRE.SHNCD AND SY.YOYAKUDT = PRE.YOYAKUDT WHERE (PRE.SHNCD IS NOT NULL AND SY.UPDKBN = 1) OR SY.UPDKBN <> 1 ORDER BY SY.SHNCD, SY.YOYAKUDT" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
