REM [028][AFA01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0028
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEBUO001

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(店舗基本マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(TEN.TENCD, 3, 0) || LPAD(TEN.SEIKAAREAKBN, 1, 0) || LPAD(TEN.SENGYOKBN, 1, 0) || LPAD(TEN.SEINIKUKBN, 1, 0) || LPAD(TEN.TENATR5, 1, 0) || LPAD(TEN.TENATR6, 1, 0) || LPAD(TEN.TENOPENDT, 8, 0) || LPAD(TEN.TENCLOSEDT, 8, 0) || LPAD(TEN.KAISODT1, 8, 0) || LPAD(TEN.KAISODT2, 8, 0) || LPAD(TEN.KAISODT3, 8, 0) || LPAD(TEN.SC_SFLG, 1, 0) || LPAD(TEN.KOSEI_SFLG, 1, 0) || LPAD(TEN.BUNRUI_SFLG, 1, 0) || LPAD(TEN.BMN_SFLG, 1, 0) || LPAD(TEN.YOBI1_SFLG, 1, 0) || LPAD(TEN.YOBI2_SFLG, 1, 0) || LPAD(TEN.DTORIKOMIDT, 8, 0) || LPAD(TEN.HANBAIBUCD, 2, 0) || LPAD(TEN.CHIKUCD, 2, 0) || LPAD(TEN.URIAERACD, 2, 0) || LPAD(TEN.CHIIKICD, 1, 0) || LPAD(TEN.YOSANKBN_T, 1, 0) || RPAD(TEN.TENKN, 20, '　') || RPAD(TEN.TENAN, 20, ' ') || LPAD(TEN.YUBINNO_U, 3, 0) || LPAD(TEN.YUBINNO_S, 4, 0) || RPAD(TEN.ADDRKN_T, 5, '　') || RPAD(TEN.ADDRKN_S, 10, '　') || RPAD(TEN.ADDRKN_M, 5, '　') || RPAD(TEN.ADDRKN_B, 30, '　') || RPAD(TEN.ADDRAN_T, 10, ' ') || RPAD(TEN.ADDRAN_S, 10, ' ') || RPAD(TEN.ADDRAN_M, 10, ' ') || RPAD(TEN.ADDRAN_B, 20, ' ') || RPAD(TEN.MOYORIEKIKN, 15, '　') || RPAD(TEN.BUSSTOPKN, 15, '　') || RPAD(TEN.OWNT_NMKN, 15, '　') || RPAD(TEN.OWNT_ADDRKN_T, 5, '　') || RPAD(TEN.OWNT_ADDRKN_S, 10, '　') || RPAD(TEN.OWNT_ADDRKN_M, 5, '　') || RPAD(TEN.OWNT_ADDRKN_B, 30, '　') || RPAD(TEN.OWNP_NMKN, 15, '　') || RPAD(TEN.OWNP_ADDRKN_T, 5, '　') || RPAD(TEN.OWNP_ADDRKN_S, 10, '　') || RPAD(TEN.OWNP_ADDRKN_M, 5, '　') || RPAD(TEN.OWNP_ADDRKN_B, 30, '　') || RPAD(TEN.OWNO_NMKN, 15, '　') || RPAD(TEN.OWNO_ADDRKN_T, 5, '　') || RPAD(TEN.OWNO_ADDRKN_S, 10, '　') || RPAD(TEN.OWNO_ADDRKN_M, 5, '　') || RPAD(TEN.OWNO_ADDRKN_B, 30, '　') || RPAD(TEN.TEL1, 14, ' ') || RPAD(TEN.TEL2, 14, ' ') || RPAD(TEN.TEL3, 14, ' ') || RPAD(TEN.TEL4, 14, ' ') || RPAD(TEN.TEL5, 14, ' ') || RPAD(TEN.FAX1, 14, ' ') || RPAD(TEN.FAX2, 14, ' ') || LPAD(TEN.EGYOTM1_STMD, 4, 0) || LPAD(TEN.EGYOTM1_EDMD, 4, 0) || LPAD(TEN.EGYOTM1_STHM, 4, 0) || LPAD(TEN.EGYOTM1_EDHM, 4, 0) || LPAD(TEN.EGYOTM2_STMD, 4, 0) || LPAD(TEN.EGYOTM2_EDMD, 4, 0) || LPAD(TEN.EGYOTM2_STHM, 4, 0) || LPAD(TEN.EGYOTM2_EDHM, 4, 0) || LPAD(TEN.EGYOTM3_STMD, 4, 0) || LPAD(TEN.EGYOTM3_EDMD, 4, 0) || LPAD(TEN.EGYOTM3_STHM, 4, 0) || LPAD(TEN.EGYOTM3_EDHM, 4, 0) || LPAD(TEN.AREA_BA, 7, 0) || LPAD(TEN.AERA_B1YUKA, 7, 0) || LPAD(TEN.AREA_B1URIBA, 7, 0) || LPAD(TEN.AREA_1FYUKA, 7, 0) || LPAD(TEN.AREA_FURIBA, 7, 0) || LPAD(TEN.AREA_2FYUKA, 7, 0) || LPAD(TEN.AREA_2FURIBA, 7, 0) || LPAD(TEN.AREA_3FYUKA, 7, 0) || LPAD(TEN.AREA_3FURIBA, 7, 0) || LPAD(TEN.AREA_4FYUKA, 7, 0) || LPAD(TEN.AREA_4FURIBA, 7, 0) || LPAD(TEN.PARK_NM_BA, 5, 0) || LPAD(TEN.PARK_NM_YANE, 5, 0) || LPAD(TEN.PARK_NM_TOBI, 5, 0) || LPAD(TEN.PARK_LT_BA, 5, 0) || LPAD(TEN.PARK_LT_YANE, 5, 0) || LPAD(TEN.PARK_LT_TOBI, 5, 0) || LPAD(TEN.PARK_HC_BA, 5, 0) || LPAD(TEN.PARK_HC_YANE, 5, 0) || LPAD(TEN.PARK_HC_TOBI, 5, 0) || LPAD(TEN.PARK_BIKE, 5, 0) || LPAD(TEN.ELEVTRFLG, 1, 0) || LPAD(TEN.ESCALTRFLG, 1, 0) || LPAD(TEN.ATSUK_CD, 2, 0) || LPAD(TEN.ATSUK_CREDIT, 2, 0) || LPAD(TEN.ATSUK_COLESS, 2, 0) || LPAD(TEN.ATSUK_POINT, 2, 0) || LPAD(TEN.SEIKACD, 2, 0) || LPAD(SUBSTR(TEN.STAFFSU, 1, LOCATE('.', TEN.STAFFSU) - 1), 6, 0) || SUBSTR(TEN.STAFFSU, LOCATE('.', TEN.STAFFSU) + 1) || LPAD(TEN.MISEUNYOKBN, 1, 0) || '  ' || LPAD(TEN.UPDKBN, 1, 0) || LPAD(TEN.SENDFLG, 1, 0) || RPAD(TEN.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(TEN.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(TEN.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2K.MSTTEN TEN WHERE TEN.UPDKBN <> 1 ORDER BY TEN.TENCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
