REM [034][AFB01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0034
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VECUO001

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(仕入先マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(COALESCE(SIR.SIRCD, 0), 6, 0) || RPAD(COALESCE(SIR.SIRAN, ''), 20, ' ') || RPAD(COALESCE(SIR.SIRKN, ''), 20, '　') || RPAD(COALESCE(SIR.ADDRKN_T, ''), 5, '　') || RPAD(COALESCE(SIR.ADDRKN_S, ''), 10, '　') || RPAD(COALESCE(SIR.ADDRKN_M, ''), 5, '　') || RPAD(COALESCE(SIR.ADDR_B, ''), 20, '　') || RPAD(COALESCE(SIR.BUSHOKN, ''), 20, '　') || LPAD(COALESCE(SIR.YUBINNO_U, ''), 3, 0) || LPAD(COALESCE(SIR.YUBINNO_S, ''), 4, 0) || RPAD(COALESCE(SIR.TEL, ''), 20, ' ') || RPAD(COALESCE(SIR.NAISEN, ''), 4, ' ') || RPAD(COALESCE(SIR.FAX, ''), 20, ' ') || LPAD(COALESCE(SIR.DSIRCD, 0), 6, 0) || LPAD(COALESCE(SIR.DOYASIRCD, 0), 6, 0) || LPAD(COALESCE(SIR.STARTDT, 0), 8, 0) || LPAD(COALESCE(SIR.EDI_RKBN, 0), 1, 0) || LPAD(COALESCE(SIR.EDI_SKBN, 0), 1, 0) || LPAD(COALESCE(SIR.SIRYOTOKBN, 0), 1, 0) || LPAD(COALESCE(SIR.INAZAIKOKBN, 0), 1, 0) || LPAD(COALESCE(SIR.KAKGAKEKBN, 0), 1, 0) || RPAD(COALESCE(SIR.NOZEISHANO, ''), 12, ' ') || LPAD(COALESCE(SIR.SYORTANKAAM, 0), 6, 0) || LPAD(COALESCE(SIR.KHNRYOKINAM, 0), 6, 0) || LPAD(COALESCE(SIR.STOPFLG, 0), 1, 0) || RPAD(COALESCE(SIR.DOHOCD, ''), 6, ' ') || LPAD(COALESCE(SIR.DDENPKBN, 0), 1, 0) || LPAD(COALESCE(SIR.DSHUHKBN, 0), 1, 0) || LPAD(COALESCE(SIR.DWAPNKBN, 0), 1, 0) || RPAD(COALESCE(SIR.DF_IDENKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_TENDENFLG, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_VANKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_UNYOKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_DENPKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_SHUHKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_PICKDKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_PICKLKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_WAPNKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_IDENPKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_KAKOSJKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_RYUTSUKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_ZDENPKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_ZSHUHKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_ZPICKDKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_ZPICKLKBN, ''), 1, ' ') || LPAD(COALESCE(TRIM(SIR.DF_RSIRCD), ''), 6, 0) || RPAD(COALESCE(SIR.DF_YKNSHKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_YDENPKBN, ''), 1, ' ') || RPAD(COALESCE(SIR.DF_YSHUHKBN, ''), 1, ' ') || ' ' || LPAD(SIR.UPDKBN, 1, 0) || LPAD(SIR.SENDFLG, 1, 0) || RPAD(SIR.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(SIR.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(SIR.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2K.MSTSIR SIR WHERE SIR.UPDKBN <> 1 ORDER BY SIR.SIRCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
