REM [035][AIC52]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0035
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VECUO002

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(配送パターン仕入先)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(HPS.SIRCD, 6, 0) || LPAD(HPS.HSPTN, 3, 0) || RPAD(HPS.TENDENFLG, 1, ' ') || RPAD(HPS.VANKBN, 1, ' ') || RPAD(HPS.UNYOKBN, 1, ' ') || RPAD(HPS.DENPKBN, 1, ' ') || RPAD(HPS.SHUHKBN, 1, ' ') || RPAD(HPS.PICKDKBN, 1, ' ') || RPAD(HPS.PICKLKBN, 1, ' ') || RPAD(HPS.WAPNKBN, 1, ' ') || RPAD(HPS.IDENPKBN, 1, ' ') || RPAD(HPS.KAKOSJKBN, 1, ' ') || RPAD(HPS.RYUTSUKBN, 1, ' ') || RPAD(HPS.ZDENPKBN, 1, ' ') || RPAD(HPS.ZSHUHKBN, 1, ' ') || RPAD(HPS.ZPICKDKBN, 1, ' ') || RPAD(HPS.ZPICKLKBN, 1, ' ') || RPAD(HPS.RSIRCD, 6, ' ') || RPAD(HPS.YKNSHKBN, 1, ' ') || RPAD(HPS.YDENPKBN, 1, ' ') || RPAD(HPS.DSHUHKBN, 1, ' ') || LPAD(HPS.SENDFLG, 1, 0) || RPAD(HPS.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(HPS.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(HPS.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2K.MSTHSPTNSIR HPS WHERE EXISTS (SELECT 1 FROM INAMS2K.MSTSIR SIR WHERE HPS.SIRCD = SIR.SIRCD AND SIR.UPDKBN <> 1) ORDER BY HPS.SIRCD, HPS.HSPTN">%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
