REM [037][AEA81]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0606
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO002

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品基本マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH HP AS (SELECT HP.* FROM INAMS2K.MSTHSPTN HP WHERE HP.UPDKBN <> 1 AND HP.SENDFLG IN (0, 9)), SHN AS (SELECT SHN.* FROM INAMS2.MSTSHN SHN WHERE EXISTS (SELECT 1 FROM HP WHERE SHN.HSPTN = HP.HSPTN)) SELECT CONCAT('6', ' ', SUBSTR(RPAD(SHN.SHNCD, 14, ' '), 1, 2), SUBSTR(RPAD(SHN.SHNCD, 14, ' '), 3, 6), SUBSTR(RPAD(SHN.SHNCD, 14, ' '), 9, 6), LPAD(SHN.YOYAKUDT, 8, 0), LPAD(SHN.TENBAIKADT, 8, 0), LPAD(SHN.YOT_BMNCD, 3, 0), LPAD(SHN.YOT_DAICD, 2, 0), LPAD(SHN.YOT_CHUCD, 2, 0), LPAD(SHN.YOT_SHOCD, 2, 0), LPAD(SHN.URI_BMNCD, 3, 0), LPAD(SHN.URI_DAICD, 2, 0), LPAD(SHN.URI_CHUCD, 2, 0), LPAD(SHN.URI_SHOCD, 2, 0), LPAD(SHN.BMNCD, 3, 0), LPAD(SHN.DAICD, 2, 0), LPAD(SHN.CHUCD, 2, 0), LPAD(SHN.SHOCD, 2, 0), LPAD(SHN.SSHOCD, 1, 0), LPAD(SHN.ATSUK_STDT, 8, 0), LPAD(SHN.ATSUK_EDDT, 8, 0), LPAD(SHN.TEISHIKBN, 1, 0), RPAD(SHN.SHNAN, 20, ' '), RPAD(SHN.SHNKN, 20, '　'), RPAD(SHN.PCARDKN, 20, '　'), RPAD(SHN.POPKN, 20, '　'), RPAD(SHN.RECEIPTAN, 20, ' '), RPAD(SHN.RECEIPTKN, 20, '　'), LPAD(SHN.PCKBN, 1, 0), LPAD(SHN.KAKOKBN, 1, 0), LPAD(SHN.ICHIBAKBN, 1, 0), LPAD(SHN.SHNKBN, 1, 0), RPAD(SHN.SANCHIKN, 20, '　'), LPAD(SHN.SSIRCD, 6, 0), LPAD(SHN.HSPTN, 3, 0), LPAD(SHN.RG_ATSUKFLG, 1, 0), LPAD(CAST(SHN.RG_GENKAAM * 100 AS SIGNED), 8, 0), LPAD(SHN.RG_BAIKAAM, 6, 0), LPAD(SHN.RG_IRISU, 3, 0), LPAD(RPAD(SHN.RG_IDENFLG, 1, ' '), 1, 0), LPAD(RPAD(SHN.RG_WAPNFLG, 1, ' '), 1, 0), LPAD(SHN.HS_ATSUKFLG, 1, 0), LPAD(CAST(SHN.HS_GENKAAM * 100 AS SIGNED), 8, 0), LPAD(SHN.HS_BAIKAAM, 6, 0), LPAD(SHN.HS_IRISU, 3, 0), LPAD(RPAD(SHN.HS_WAPNFLG, 1, ' '), 1, 0), LPAD(SHN.HS_SPOTMINSU, 2, 0), LPAD(RPAD(SHN.HP_SWAPNFLG, 1, ' '), 1, 0), RPAD(SHN.KIKKN, 23, '　'), LPAD(SHN.UP_YORYOSU, 5, 0), LPAD(SHN.UP_TYORYOSU, 3, 0), LPAD(SHN.UP_TANIKBN, 2, 0), LPAD(SHN.SHNYOKOSZ, 4, 0), LPAD(SHN.SHNTATESZ, 4, 0), LPAD(SHN.SHNOKUSZ, 4, 0), LPAD(CAST(SHN.SHNJRYOSZ * 10 AS SIGNED), 6, 0), LPAD(SHN.PBKBN, 1, 0), LPAD(SHN.KOMONOKBM, 2, 0), LPAD(SHN.TANAOROKBN, 2, 0), LPAD(SHN.TEIKEIKBN, 1, 0), LPAD(SHN.ODS_HARUSU, 4, 0), LPAD(SHN.ODS_NATSUSU, 4, 0), LPAD(SHN.ODS_AKISU, 4, 0), LPAD(SHN.ODS_FUYUSU, 4, 0), LPAD(SHN.ODS_NYUKASU, 4, 0), LPAD(SHN.ODS_NEBIKISU, 4, 0), LPAD(SHN.PCARD_SHUKBN, 1, 0), LPAD(SHN.PCARD_IROKBN, 1, 0), LPAD(SHN.ZEIKBN, 1, 0), LPAD(SHN.ZEIRTKBN, 3, 0), LPAD(SHN.ZEIRTKBN_OLD, 3, 0), LPAD(SHN.ZEIRTHENKODT, 8, 0), LPAD(SHN.SEIZOGENNISU, 3, 0), LPAD(SHN.TEIKANKBN, 1, 0), LPAD(SHN.MAKERCD, 9, 0), LPAD(SHN.IMPORTKBN, 2, 0), LPAD(SHN.SIWAKEKBN, 2, 0), LPAD(SHN.HENPIN_KBN, 1, 0), LPAD(SHN.TAISHONENSU, 2, 0), LPAD(SHN.CALORIESU, 5, 0), LPAD(SHN.ELPFLG, 1, 0), LPAD(SHN.BELLMARKFLG, 1, 0), LPAD(SHN.RECYCLEFLG, 1, 0), LPAD(SHN.ECOFLG, 1, 0), LPAD(SHN.HZI_YOTO, 1, 0), LPAD(SHN.HZI_ZAISHITU, 1, 0), LPAD(SHN.HZI_RECYCLE, 1, 0), LPAD(RPAD(SHN.KIKANKBN, 1, ' '), 1, 0), LPAD(SHN.SHUKYUKBN, 2, 0), LPAD(SHN.DOSU, 3, 0), LPAD(RPAD(SHN.CHINRETUCD, 1, ' '), 1, 0), LPAD(RPAD(SHN.DANTUMICD, 2, ' '), 2, 0), LPAD(RPAD(SHN.KASANARICD, 1, ' '), 1, 0), LPAD(SHN.KASANARISZ, 3, 0), LPAD(SHN.ASSHUKURT, 2, 0), LPAD(RPAD(SHN.SHUBETUCD, 2, ' '), 2, 0), LPAD(SHN.URICD, 6, 0), RPAD(SHN.SALESCOMKN, 30, '　'), LPAD(SHN.URABARIKBN, 1, 0), LPAD(SHN.PCARD_OPFLG, 1, 0), LPAD(SUBSTR(RPAD(SHN.PARENTCD, 14, ' '), 1, 8), 8, 0), LPAD(SUBSTR(RPAD(SHN.PARENTCD, 14, ' '), 9, 6), 6, 0), LPAD(SHN.BINKBN, 1, 0), LPAD(SHN.HAT_MONKBN, 1, 0), LPAD(SHN.HAT_TUEKBN, 1, 0), LPAD(SHN.HAT_WEDKBN, 1, 0), LPAD(SHN.HAT_THUKBN, 1, 0), LPAD(SHN.HAT_FRIKBN, 1, 0), LPAD(SHN.HAT_SATKBN, 1, 0), LPAD(SHN.HAT_SUNKBN, 1, 0), LPAD(SHN.READTMPTN, 3, 0), LPAD(SHN.SIMEKAISU, 1, 0), LPAD(SHN.IRYOREFLG, 1, 0), LPAD(SHN.TOROKUMOTO, 1, 0), '      ', LPAD(SHN.UPDKBN, 1, 0), LPAD(SHN.SENDFLG, 1, 0), RPAD(SHN.OPERATOR, 20, ' '), LPAD(DATE_FORMAT(SHN.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(SHN.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM SHN ORDER BY SHN.SHNCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
