REM [037][AEA81_Y]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0607
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO004

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品基本マスタ(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH HP AS (SELECT HP.* FROM INAMS2K.MSTHSPTN HP WHERE HP.UPDKBN <> 1 AND HP.SENDFLG IN (0, 9)), SHNY AS (SELECT SHNY.* FROM INAMS2.MSTSHN_Y SHNY WHERE EXISTS (SELECT 1 FROM HP WHERE SHNY.HSPTN = HP.HSPTN)) SELECT CONCAT('6', ' ', SUBSTR(RPAD(SHNY.SHNCD, 14, ' '), 1, 2), SUBSTR(RPAD(SHNY.SHNCD, 14, ' '), 3, 6), SUBSTR(RPAD(SHNY.SHNCD, 14, ' '), 9, 6), LPAD(SHNY.YOYAKUDT, 8, 0), LPAD(SHNY.TENBAIKADT, 8, 0), LPAD(SHNY.YOT_BMNCD, 3, 0), LPAD(SHNY.YOT_DAICD, 2, 0), LPAD(SHNY.YOT_CHUCD, 2, 0), LPAD(SHNY.YOT_SHOCD, 2, 0), LPAD(SHNY.URI_BMNCD, 3, 0), LPAD(SHNY.URI_DAICD, 2, 0), LPAD(SHNY.URI_CHUCD, 2, 0), LPAD(SHNY.URI_SHOCD, 2, 0), LPAD(SHNY.BMNCD, 3, 0), LPAD(SHNY.DAICD, 2, 0), LPAD(SHNY.CHUCD, 2, 0), LPAD(SHNY.SHOCD, 2, 0), LPAD(SHNY.SSHOCD, 1, 0), LPAD(SHNY.ATSUK_STDT, 8, 0), LPAD(SHNY.ATSUK_EDDT, 8, 0), LPAD(SHNY.TEISHIKBN, 1, 0), RPAD(SHNY.SHNAN, 20, ' '), RPAD(SHNY.SHNKN, 20, '　'), RPAD(SHNY.PCARDKN, 20, '　'), RPAD(SHNY.POPKN, 20, '　'), RPAD(SHNY.RECEIPTAN, 20, ' '), RPAD(SHNY.RECEIPTKN, 20, '　'), LPAD(SHNY.PCKBN, 1, 0), LPAD(SHNY.KAKOKBN, 1, 0), LPAD(SHNY.ICHIBAKBN, 1, 0), LPAD(SHNY.SHNKBN, 1, 0), RPAD(SHNY.SANCHIKN, 20, '　'), LPAD(SHNY.SSIRCD, 6, 0), LPAD(SHNY.HSPTN, 3, 0), LPAD(SHNY.RG_ATSUKFLG, 1, 0), LPAD(CAST(SHNY.RG_GENKAAM * 100 AS SIGNED), 8, 0), LPAD(SHNY.RG_BAIKAAM, 6, 0), LPAD(SHNY.RG_IRISU, 3, 0), LPAD(RPAD(SHNY.RG_IDENFLG, 1, ' '), 1, 0), LPAD(RPAD(SHNY.RG_WAPNFLG, 1, ' '), 1, 0), LPAD(SHNY.HS_ATSUKFLG, 1, 0), LPAD(CAST(SHNY.HS_GENKAAM * 100 AS SIGNED), 8, 0), LPAD(SHNY.HS_BAIKAAM, 6, 0), LPAD(SHNY.HS_IRISU, 3, 0), LPAD(RPAD(SHNY.HS_WAPNFLG, 1, ' '), 1, 0), LPAD(SHNY.HS_SPOTMINSU, 2, 0), LPAD(RPAD(SHNY.HP_SWAPNFLG, 1, ' '), 1, 0), RPAD(SHNY.KIKKN, 23, '　'), LPAD(SHNY.UP_YORYOSU, 5, 0), LPAD(SHNY.UP_TYORYOSU, 3, 0), LPAD(SHNY.UP_TANIKBN, 2, 0), LPAD(SHNY.SHNYOKOSZ, 4, 0), LPAD(SHNY.SHNTATESZ, 4, 0), LPAD(SHNY.SHNOKUSZ, 4, 0), LPAD(CAST(SHNY.SHNJRYOSZ * 10 AS SIGNED), 6, 0), LPAD(SHNY.PBKBN, 1, 0), LPAD(SHNY.KOMONOKBM, 2, 0), LPAD(SHNY.TANAOROKBN, 2, 0), LPAD(SHNY.TEIKEIKBN, 1, 0), LPAD(SHNY.ODS_HARUSU, 4, 0), LPAD(SHNY.ODS_NATSUSU, 4, 0), LPAD(SHNY.ODS_AKISU, 4, 0), LPAD(SHNY.ODS_FUYUSU, 4, 0), LPAD(SHNY.ODS_NYUKASU, 4, 0), LPAD(SHNY.ODS_NEBIKISU, 4, 0), LPAD(SHNY.PCARD_SHUKBN, 1, 0), LPAD(SHNY.PCARD_IROKBN, 1, 0), LPAD(SHNY.ZEIKBN, 1, 0), LPAD(SHNY.ZEIRTKBN, 3, 0), LPAD(SHNY.ZEIRTKBN_OLD, 3, 0), LPAD(SHNY.ZEIRTHENKODT, 8, 0), LPAD(SHNY.SEIZOGENNISU, 3, 0), LPAD(SHNY.TEIKANKBN, 1, 0), LPAD(SHNY.MAKERCD, 9, 0), LPAD(SHNY.IMPORTKBN, 2, 0), LPAD(SHNY.SIWAKEKBN, 2, 0), LPAD(SHNY.HENPIN_KBN, 1, 0), LPAD(SHNY.TAISHONENSU, 2, 0), LPAD(SHNY.CALORIESU, 5, 0), LPAD(SHNY.ELPFLG, 1, 0), LPAD(SHNY.BELLMARKFLG, 1, 0), LPAD(SHNY.RECYCLEFLG, 1, 0), LPAD(SHNY.ECOFLG, 1, 0), LPAD(SHNY.HZI_YOTO, 1, 0), LPAD(SHNY.HZI_ZAISHITU, 1, 0), LPAD(SHNY.HZI_RECYCLE, 1, 0), LPAD(RPAD(SHNY.KIKANKBN, 1, ' '), 1, 0), LPAD(SHNY.SHUKYUKBN, 2, 0), LPAD(SHNY.DOSU, 3, 0), LPAD(RPAD(SHNY.CHINRETUCD, 1, ' '), 1, 0), LPAD(RPAD(SHNY.DANTUMICD, 2, ' '), 2, 0), LPAD(RPAD(SHNY.KASANARICD, 1, ' '), 1, 0), LPAD(SHNY.KASANARISZ, 3, 0), LPAD(SHNY.ASSHUKURT, 2, 0), LPAD(RPAD(SHNY.SHUBETUCD, 2, ' '), 2, 0), LPAD(SHNY.URICD, 6, 0), RPAD(SHNY.SALESCOMKN, 30, '　'), LPAD(SHNY.URABARIKBN, 1, 0), LPAD(SHNY.PCARD_OPFLG, 1, 0), LPAD(SUBSTR(RPAD(SHNY.PARENTCD, 14, ' '), 1, 8), 8, 0), LPAD(SUBSTR(RPAD(SHNY.PARENTCD, 14, ' '), 9, 6), 6, 0), LPAD(SHNY.BINKBN, 1, 0), LPAD(SHNY.HAT_MONKBN, 1, 0), LPAD(SHNY.HAT_TUEKBN, 1, 0), LPAD(SHNY.HAT_WEDKBN, 1, 0), LPAD(SHNY.HAT_THUKBN, 1, 0), LPAD(SHNY.HAT_FRIKBN, 1, 0), LPAD(SHNY.HAT_SATKBN, 1, 0), LPAD(SHNY.HAT_SUNKBN, 1, 0), LPAD(SHNY.READTMPTN, 3, 0), LPAD(SHNY.SIMEKAISU, 1, 0), LPAD(SHNY.IRYOREFLG, 1, 0), LPAD(SHNY.TOROKUMOTO, 1, 0), '      ', LPAD(SHNY.UPDKBN, 1, 0), LPAD(SHNY.SENDFLG, 1, 0), RPAD(SHNY.OPERATOR, 20, ' '), LPAD(DATE_FORMAT(SHNY.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(SHNY.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM SHNY ORDER BY SHNY.SHNCD, SHNY.YOYAKUDT" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
