REM [037][AEA82_Y]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0611
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO010

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(仕入グループ商品(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH HP AS (SELECT HP.* FROM INAMS2K.MSTHSPTN HP WHERE HP.UPDKBN <> 1 AND HP.SENDFLG IN (0, 9)), SGSY AS (SELECT SGSY.* FROM INAMS2.MSTSIRGPSHN_Y SGSY WHERE EXISTS (SELECT 1 FROM HP WHERE SGSY.HSPTN = HP.HSPTN)) SELECT '6' || SUBSTR(RPAD(SGSY.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(SGSY.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(SGSY.SHNCD, 14, ' '), 9, 6) || LPAD(SGSY.TENGPCD, 4, 0) || LPAD(SGSY.YOYAKUDT, 8, 0) || LPAD(SGSY.AREAKBN, 1, 0) || LPAD(SGSY.SIRCD, 6, 0) || LPAD(SGSY.HSPTN, 3, 0) || '       ' || RPAD(SGSY.OPERATOR, 20, ' ') || LPAD(SGSY.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(SGSY.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(SGSY.UPDDT, '%%Y%%m%%d'), 8, 0) FROM SGSY ORDER BY SGSY.SHNCD, SGSY.TENGPCD, SGSY.YOYAKUDT" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
