REM [045][ARD02]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0045
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEDUO002

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(大分類マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.BMNCD, 3, 0) || LPAD(T1.DAICD, 2, 0) || '     ' || RPAD(T1.DAIBRUIAN, 20, ' ') || RPAD(T1.DAIBRUIKN, 15, '　') || LPAD(T1.ATR1, 1, 0) || LPAD(T1.ATR2, 1, 0) || LPAD(T1.ATR3, 1, 0) || LPAD(T1.ATR4, 1, 0) || LPAD(T1.ATR5, 1, 0) || LPAD(T1.ATR6, 1, 0) || '      ' || LPAD(T1.UPDKBN, 1, 0) || LPAD(T1.SENDFLG, 1, 0) || RPAD(T1.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2K.MSTDAIBRUI T1 WHERE T1.UPDKBN <> 1 ORDER BY T1.BMNCD, T1.DAICD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
