REM [083][A11TBMH]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0083
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEGUO005

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(発注用店舗部門マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT CONCAT(LPAD(TENCD, 3, 0), LPAD(BUMN, 3, 0), LPAD(AREA, 2, 0), LPAD(LTPTN, 3, 0), RPAD(BUMNTNMKJ, 10, '　'), LPAD(GROUPNO, 4, 0), RPAD(BUMNRCTNMKN, 20, ' '), RPAD(BUMNRCTNMKJ, 20, '　'), LPAD(MIOKBN, 1, 0), LPAD(SHUKEICD, 4, 0), LPAD(WARIBIKIKBN, 1, 0), LPAD(REPLACE (CAST(BUMNGENKA AS CHAR), '.', ''), 5, 0), LPAD(JISHATENANTO, 1, 0), LPAD(LOSSBUNSEKI, 1, 0), LPAD(YOSANKBN2, 1, 0), LPAD(TANAKBN, 1, 0), LPAD(PCSHURUI, 1, 0), LPAD(PCIRO, 1, 0), LPAD(TENANTOCD, 5, 0), LPAD(BUMNATR1, 1, 0), LPAD(BUMNATR2, 1, 0), LPAD(BUMNATR3, 1, 0), LPAD(BUMNATR4, 1, 0), LPAD(BUMNATR5, 1, 0), LPAD(URI_FLG, 1, 0), LPAD(LTIME_MON, 2, 0), LPAD(LTIME_TUE, 2, 0), LPAD(LTIME_WED, 2, 0), LPAD(LTIME_THU, 2, 0), LPAD(LTIME_FRI, 2, 0), LPAD(LTIME_SAT, 2, 0), LPAD(LTIME_SAN, 2, 0), LPAD(UPDKBN, 1, 0)) AS '1' FROM INAIF.HA_A11TBMH ORDER BY TENCD, BUMN" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
