REM [084][HA_A11HSR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAIF.HA_A11HSR(発注用配送パターン仕入先) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAIF.HA_A11HSR IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAIF.HA_A11HSR ロード処理（発注用配送パターン仕入先）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.HA_A11HSR;INSERT IGNORE INTO INAIF.HA_A11HSR SELECT CASE WHEN HPS.HSPTN IS NULL THEN HP.HSPTN ELSE HPS.HSPTN END AS '1', CASE WHEN HPS.HSPTN IS NULL THEN 0 ELSE HPS.SIRCD END AS '2', CASE WHEN HP.HSPTN IS NOT NULL AND HPS.HSPTN IS NOT NULL THEN 0 WHEN HP.HSPTN IS NOT NULL THEN 1 ELSE 2 END AS '3', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.TENDENFLG END AS '4', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.VANKBN END AS '5', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.UNYOKBN END AS '6', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.DENPKBN END AS '7', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.SHUHKBN END AS '8', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.PICKDKBN END AS '9', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.PICKLKBN END AS '10', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.WAPNKBN END AS '11', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.IDENPKBN END AS '12', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.KAKOSJKBN END AS '13', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.RYUTSUKBN END AS '14', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.ZDENPKBN END AS '15', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.ZSHUHKBN END AS '16', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.ZPICKDKBN END AS '17', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.ZPICKLKBN END AS '18', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.RSIRCD END AS '19', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.YKNSHKBN END AS '20', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.YDENPKBN END AS '21', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.DSHUHKBN END AS '22', CASE WHEN HP.HSPTN IS NULL THEN 0 ELSE HP.CENTERCD END AS '23', CASE WHEN HP.HSPTN IS NULL THEN 0 ELSE HP.YCENTERCD END AS '24', ' ' AS '25' FROM INAMS2.MSTHSPTNSIR HPS LEFT OUTER JOIN (SELECT * FROM INAMS2.MSTHSPTN T WHERE T.UPDKBN <> 1) HP ON HPS.HSPTN = HP.HSPTN UNION ALL SELECT CASE WHEN HPS.HSPTN IS NULL THEN HP.HSPTN ELSE HPS.HSPTN END AS '1', CASE WHEN HPS.HSPTN IS NULL THEN 0 ELSE HPS.SIRCD END AS '2', CASE WHEN HP.HSPTN IS NOT NULL AND HPS.HSPTN IS NOT NULL THEN 0 WHEN HP.HSPTN IS NOT NULL THEN 1 ELSE 2 END AS '3', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.TENDENFLG END AS '4', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.VANKBN END AS '5', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.UNYOKBN END AS '6', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.DENPKBN END AS '7', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.SHUHKBN END AS '8', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.PICKDKBN END AS '9', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.PICKLKBN END AS '10', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.WAPNKBN END AS '11', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.IDENPKBN END AS '12', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.KAKOSJKBN END AS '13', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.RYUTSUKBN END AS '14', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.ZDENPKBN END AS '15', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.ZSHUHKBN END AS '16', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.ZPICKDKBN END AS '17', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.ZPICKLKBN END AS '18', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.RSIRCD END AS '19', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.YKNSHKBN END AS '20', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.YDENPKBN END AS '21', CASE WHEN HPS.HSPTN IS NULL THEN ' ' ELSE HPS.DSHUHKBN END AS '22', CASE WHEN HP.HSPTN IS NULL THEN 0 ELSE HP.CENTERCD END AS '23', CASE WHEN HP.HSPTN IS NULL THEN 0 ELSE HP.YCENTERCD END AS '24', ' ' AS '25' FROM INAMS2.MSTHSPTNSIR HPS RIGHT OUTER JOIN (SELECT * FROM INAMS2.MSTHSPTN T WHERE T.UPDKBN <> 1) HP ON HPS.HSPTN = HP.HSPTN WHERE HPS.HSPTN IS NULL UNION ALL SELECT HP.HSPTN, 0, 1, ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', CASE WHEN HP.HSPTN IS NULL THEN 0 ELSE HP.CENTERCD END, CASE WHEN HP.HSPTN IS NULL THEN 0 ELSE HP.YCENTERCD END, ' ' FROM (SELECT * FROM INAMS2.MSTHSPTN T WHERE T.UPDKBN <> 1) HP INNER JOIN (SELECT HSPTN FROM INAMS2.MSTHSPTNSIR GROUP BY HSPTN) HPS ON HPS.HSPTN = HP.HSPTN;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.HA_A11HSR;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
