REM [087][A11MSIR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0087
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEGUO009

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(発注用複数仕入先)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH MSIR AS (SELECT FSR.SIRCD AS SHIRECD, FST.TENCD, FSR.RSIRCD AS SHIRECD_J, FSR.SEQNO AS INPUTNO, '' AS FILLER, FSR.UPDKBN, FSR.SENDFLG AS SEND_FLG, FSR.OPERATOR, CAST(DATE_FORMAT(FSR.ADDDT, '%%Y%%m%%d') AS SIGNED) AS ADD_YMD, CAST(DATE_FORMAT(FSR.UPDDT, '%%Y%%m%%d') AS SIGNED) AS UPD_YMD FROM INAMS2K.MSTFUKUSUSIR_R FSR INNER JOIN INAMS2K.MSTFUKUSUSIR_T FST ON FSR.SIRCD = FST.SIRCD AND FSR.SEQNO = FST.SEQNO AND FSR.UPDKBN <> 1 AND FST.UPDKBN <> 1) SELECT LPAD(SHIRECD, 6, 0) || LPAD(TENCD, 3, 0) || LPAD(SHIRECD_J, 6, 0) || LPAD(INPUTNO, 2, 0) || RPAD(FILLER, 5, ' ') || LPAD(UPDKBN, 1, 0) || LPAD(SEND_FLG, 1, 0) || RPAD(OPERATOR, 20, ' ') || LPAD(ADD_YMD, 8, 0) || LPAD(UPD_YMD, 8, 0) FROM MSIR ORDER BY SHIRECD, TENCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
