REM [114][SYSSHUNO]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET INFILENAME=
SET MSG=%DATE% %TIME% INAAD.SYSSHUNO INSERT処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "INSERT INTO INAAD.SYSSHUNO SELECT SHUNO, STARTDT, ENDDT, OPERATOR, ADDDT, UPDDT FROM (SELECT (T2.YY * 100) + ROW_NUMBER() OVER (PARTITION BY T2.YYYY ORDER BY T2.STDT) AS SHUNO, T2.STDT AS STARTDT, T2.EDDT AS ENDDT, 'BATCH' AS OPERATOR, CURRENT_TIMESTAMP AS ADDDT, CURRENT_TIMESTAMP AS UPDDT FROM (SELECT T1.DT AS STDT, DATE_FORMAT(DATE_ADD(T1.DTDATE, INTERVAL + 6 DAY), '%%Y%%m%%d') AS EDDT, WEEKDAY(T1.DTDATE) + 1 AS STDTYB, DATE_FORMAT(T1.DTDATE, '%%Y') AS YYYY, DATE_FORMAT(T1.DTDATE, '%%y') AS YY FROM (SELECT DT, DATE_FORMAT(CAST(DT AS CHAR), '%%Y%%m%%d') AS DTDATE FROM INAPARM.MSTDAYS INNER JOIN (SELECT YEAR (SBD.DT) * 10000 + 101 AS SDT, YEAR (DATE_ADD(SBD.DT, INTERVAL + 1 YEAR)) * 10000 + 1231 AS EDT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY') SBD on 1 = 1 WHERE DT BETWEEN SBD.SDT AND SBD.EDT) T1) T2 WHERE T2.STDTYB = 1) T3 WHERE NOT EXISTS (SELECT * FROM INAAD.SYSSHUNO SN WHERE SN.SHUNO = T3.SHUNO);commit;">>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
