REM [075][MSTSHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAMS.MSTSHN(商品マスタ) マージ処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e   "UPDATE INAMS.MSTSHN SHN, (SELECT * FROM (SELECT SHN.SHNCD, CASE WHEN P_MNT.YOT = 1 THEN (SUBSTR(MNT.YBUNNEW, 1, 3)) ELSE SHN.YOT_BMNCD END AS YOT_BMNCD, CASE WHEN P_MNT.YOT = 1 THEN (SUBSTR(MNT.YBUNNEW, 4, 2)) ELSE SHN.YOT_DAICD END AS YOT_DAICD, CASE WHEN P_MNT.YOT = 1 THEN (SUBSTR(MNT.YBUNNEW, 6, 2)) ELSE SHN.YOT_CHUCD END AS YOT_CHUCD, CASE WHEN P_MNT.YOT = 1 THEN (SUBSTR(MNT.YBUNNEW, 8, 2)) ELSE SHN.YOT_SHOCD END AS YOT_SHOCD, CASE WHEN P_MNT.URI = 1 THEN (SUBSTR(MNT.URBUNNEW, 1, 3)) ELSE SHN.URI_BMNCD END AS URI_BMNCD, CASE WHEN P_MNT.URI = 1 THEN (SUBSTR(MNT.URBUNNEW, 4, 2)) ELSE SHN.URI_DAICD END AS URI_DAICD, CASE WHEN P_MNT.URI = 1 THEN (SUBSTR(MNT.URBUNNEW, 6, 2)) ELSE SHN.URI_CHUCD END AS URI_CHUCD, CASE WHEN P_MNT.URI = 1 THEN (SUBSTR(MNT.URBUNNEW, 8, 2)) ELSE SHN.URI_SHOCD END AS URI_SHOCD, CASE WHEN P_MNT.HYOU = 1 THEN (SUBSTR(MNT.HBUNNDCS, 1, 3)) ELSE SHN.BMNCD END AS BMNCD, CASE WHEN P_MNT.HYOU = 1 THEN (SUBSTR(MNT.HBUNNDCS, 4, 2)) ELSE SHN.DAICD END AS DAICD, CASE WHEN P_MNT.HYOU = 1 THEN (SUBSTR(MNT.HBUNNDCS, 6, 2)) ELSE SHN.CHUCD END AS CHUCD, CASE WHEN P_MNT.HYOU = 1 THEN (SUBSTR(MNT.HBUNNDCS, 8, 2)) ELSE SHN.SHOCD END AS SHOCD, CASE WHEN P_MNT.HYOU = 1 AND TRIM(MNT.HBUNNSS) <> '' THEN (MNT.HBUNNSS) ELSE SHN.SSHOCD END AS SSHOCD, CASE WHEN P_MNT.SIRCD = 1 THEN (MNT.SIIRENEW) ELSE SHN.SSIRCD END AS SSIRCD, CASE WHEN P_MNT.HSPTN = 1 THEN (MNT.HAINEW) ELSE SHN.HSPTN END AS HSPTN FROM INAIN.A10MNT MNT LEFT OUTER JOIN INAPARM.PRAM_MNT P_MNT ON 1 = 1 INNER JOIN INAMS.MSTSHN SHN ON MNT.SHCD = SHN.SHNCD WHERE EXISTS (SELECT 1 FROM INAMS.MSTSIR SIR LEFT OUTER JOIN INAPARM.PRAM_MNT P_MNT ON 1 = 1 WHERE MNT.SIIRENEW = SIR.SIRCD OR P_MNT.SIRCD <> 1) AND EXISTS (SELECT 1 FROM INAMS.MSTHSPTN HSPTN LEFT OUTER JOIN INAPARM.PRAM_MNT P_MNT ON 1 = 1 WHERE MNT.HAINEW = HSPTN.HSPTN OR P_MNT.HSPTN <> 1) AND EXISTS (SELECT 1 FROM INAMS.MSTSHOBRUI SHO LEFT OUTER JOIN INAPARM.PRAM_MNT P_MNT ON 1 = 1 WHERE MNT.HBUNNDCS = LPAD(SHO.BMNCD, 3, 0) || LPAD(SHO.DAICD, 2, 0) || LPAD(SHO.CHUCD, 2, 0) || LPAD(SHO.SHOCD, 2, 0) OR P_MNT.HYOU <> 1) AND EXISTS (SELECT 1 FROM INAMS.MSTSSHOBRUI SHO LEFT OUTER JOIN INAPARM.PRAM_MNT P_MNT ON 1 = 1 WHERE (P_MNT.HYOU = 1 AND MNT.HBUNNDCS = LPAD(SHO.BMNCD, 3, 0) || LPAD(SHO.DAICD, 2, 0) || LPAD(SHO.CHUCD, 2, 0) || LPAD(SHO.SHOCD, 2, 0) AND MNT.HBUNNSS = LPAD(SHO.SSHOCD, 1, 0)) OR (P_MNT.HYOU = 1 AND MNT.HBUNNSS = ' ') OR P_MNT.HYOU <> 1) AND EXISTS (SELECT 1 FROM INAMS.MSTSHOBRUI SHO LEFT OUTER JOIN INAPARM.PRAM_MNT P_MNT ON 1 = 1 WHERE MNT.YBUNNEW = LPAD(SHO.BMNCD, 3, 0) || LPAD(SHO.DAICD, 2, 0) || LPAD(SHO.CHUCD, 2, 0) || LPAD(SHO.SHOCD, 2, 0) OR P_MNT.YOT <> 1) AND EXISTS (SELECT 1 FROM INAMS.MSTSHOBRUI SHO LEFT OUTER JOIN INAPARM.PRAM_MNT P_MNT ON 1 = 1 WHERE MNT.URBUNNEW = LPAD(SHO.BMNCD, 3, 0) || LPAD(SHO.DAICD, 2, 0) || LPAD(SHO.CHUCD, 2, 0) || LPAD(SHO.SHOCD, 2, 0) OR P_MNT.URI <> 1) AND SHN.IRYOREFLG <> 1) AS T1) MNT SET SHN.YOT_BMNCD = MNT.YOT_BMNCD, SHN.YOT_DAICD = MNT.YOT_DAICD, SHN.YOT_CHUCD = MNT.YOT_CHUCD, SHN.YOT_SHOCD = MNT.YOT_SHOCD, SHN.URI_BMNCD = MNT.URI_BMNCD, SHN.URI_DAICD = MNT.URI_DAICD, SHN.URI_CHUCD = MNT.URI_CHUCD, SHN.URI_SHOCD = MNT.URI_SHOCD, SHN.BMNCD = MNT.BMNCD, SHN.DAICD = MNT.DAICD, SHN.CHUCD = MNT.CHUCD, SHN.SHOCD = MNT.SHOCD, SHN.SSHOCD = MNT.SSHOCD, SHN.SSIRCD = MNT.SSIRCD, SHN.HSPTN = MNT.HSPTN WHERE SHN.SHNCD = MNT.SHNCD;commit;">>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
