REM [075][ERR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET OUTFILENAME=075.ERR.csv
SET EXPFILE=%~DP0../exp/%OUTFILENAME%

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品マスタ変換テーブル(エラー))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT ERR.SHCD || ERR.SIIREOLD || ERR.SIIRENEW || ERR.YBUNOLD || ERR.YBUNNEW || ERR.URBUNOLD || ERR.URBUNNEW || ERR.HBUNODCS || ERR.HBUNOSS || ERR.HBUNNDCS || ERR.HBUNNSS || ERR.HAIOLD || ERR.HAINEW || ERR.ERSHCD || ERR.ERSIRCD || ERR.ERYBUN || ERR.ERURBUN || ERR.ERHBUN || ERR.ERHAP || ERR.SAKUSEI || ERR.FILLER FROM (SELECT MNT.SHCD, MNT.SIIREOLD, MNT.SIIRENEW, MNT.YBUNOLD, MNT.YBUNNEW, MNT.URBUNOLD, MNT.URBUNNEW, MNT.HBUNODCS, MNT.HBUNOSS, MNT.HBUNNDCS, MNT.HBUNNSS, MNT.HAIOLD, MNT.HAINEW, CASE WHEN SHN.SHNCD IS NULL THEN '1' ELSE MNT.ERSHCD END AS ERSHCD, CASE WHEN P_MNT.SIRCD = 1 AND SIR.SIRCD IS NULL THEN '1' ELSE MNT.ERSIRCD END AS ERSIRCD, CASE WHEN P_MNT.YOT = 1 AND YOT_SHO.BMNCD IS NULL THEN '1' ELSE MNT.ERYBUN END AS ERYBUN, CASE WHEN P_MNT.URI = 1 AND YOT_URI.BMNCD IS NULL THEN '1' ELSE MNT.ERURBUN END AS ERURBUN, CASE WHEN P_MNT.HYOU = 1 AND HYOU_SHO.BMNCD IS NULL THEN '1' WHEN P_MNT.HYOU = 1 AND TRIM(MNT.HBUNNSS) <> '' AND HYOU_SSHO.BMNCD IS NULL THEN '1' ELSE MNT.ERHBUN END AS ERHBUN, CASE WHEN P_MNT.HSPTN = 1 AND HSPTN.HSPTN IS NULL THEN '1' ELSE MNT.ERHAP END AS ERHAP, MNT.SAKUSEI, MNT.FILLER FROM INAIN.A10MNT MNT LEFT OUTER JOIN INAPARM.PRAM_MNT P_MNT ON 1 = 1 LEFT OUTER JOIN INAMS.MSTSHN SHN ON MNT.SHCD = SHN.SHNCD LEFT OUTER JOIN INAMS.MSTSIR SIR ON (MNT.SIIRENEW) = SIR.SIRCD LEFT OUTER JOIN INAMS.MSTSHOBRUI YOT_SHO ON MNT.YBUNNEW = LPAD(YOT_SHO.BMNCD, 3, 0) || LPAD(YOT_SHO.DAICD, 2, 0) || LPAD(YOT_SHO.CHUCD, 2, 0) || LPAD(YOT_SHO.SHOCD, 2, 0) LEFT OUTER JOIN INAMS.MSTSHOBRUI HYOU_SHO ON MNT.HBUNNDCS = LPAD(HYOU_SHO.BMNCD, 3, 0) || LPAD(HYOU_SHO.DAICD, 2, 0) || LPAD(HYOU_SHO.CHUCD, 2, 0) || LPAD(HYOU_SHO.SHOCD, 2, 0) LEFT OUTER JOIN INAMS.MSTSSHOBRUI HYOU_SSHO ON MNT.HBUNNDCS = LPAD(HYOU_SSHO.BMNCD, 3, 0) || LPAD(HYOU_SSHO.DAICD, 2, 0) || LPAD(HYOU_SSHO.CHUCD, 2, 0) || LPAD(HYOU_SSHO.SHOCD, 2, 0) AND MNT.HBUNNSS = LPAD(HYOU_SSHO.SSHOCD, 1, 0) LEFT OUTER JOIN INAMS.MSTSHOBRUI YOT_URI ON MNT.URBUNNEW = LPAD(YOT_SHO.BMNCD, 3, 0) || LPAD(YOT_SHO.DAICD, 2, 0) || LPAD(YOT_SHO.CHUCD, 2, 0) || LPAD(YOT_SHO.SHOCD, 2, 0) LEFT OUTER JOIN INAMS.MSTHSPTN HSPTN ON (MNT.HAINEW) = HSPTN.HSPTN) ERR WHERE ERR.ERSHCD = '1' OR ERR.ERSIRCD = '1' OR ERR.ERYBUN = '1' OR ERR.ERURBUN = '1' OR ERR.ERHBUN = '1' OR ERR.ERHAP = '1'">%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
