REM [000][ANWK_A11TC44]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.ANWK_A11TC44 ロード処理（全店特売(ｱﾝｹｰﾄ有)_商品対象店舗：TAISYO_TEN作成）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.ANWK_A11TC44;INSERT IGNORE INTO INAWK.ANWK_A11TC44 SELECT ASHN.MOYSKBN, ASHN.MOYSSTDT, ASHN.MOYSRBAN, ASHN.BMNCD, ASHN.KANRINO, ASHN.KANRIENO, NUM.SEQ FROM INATK2.TOKTG_SHN ASHN INNER JOIN INAPARM.MSTNUMS NUM ON 1 = 1 AND NUM.SEQ BETWEEN 1 AND 400 AND ASHN.UPDKBN <> 1 LEFT OUTER JOIN INATK2.TOKTG_TJTEN JTEN2 ON ASHN.MOYSKBN = JTEN2.MOYSKBN AND ASHN.MOYSSTDT = JTEN2.MOYSSTDT AND ASHN.MOYSRBAN = JTEN2.MOYSRBAN AND ASHN.BMNCD = JTEN2.BMNCD AND ASHN.KANRINO = JTEN2.KANRINO AND ASHN.KANRIENO = JTEN2.KANRIENO AND NUM.SEQ = JTEN2.TENCD WHERE CASE WHEN JTEN2.TJFLG = 1 THEN 'A' WHEN JTEN2.TJFLG = 2 THEN ' ' ELSE SUBSTR(ASHN.TENRANK_ARR, NUM.SEQ, 1) END <> ' ';COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.ANWK_A11TC44;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
