REM [000][SO_HANBAI]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.SO_HANBAI_WK ロード処理（生活応援 販売データ_WK）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.SO_HANBAI_WK;INSERT IGNORE INTO INAWK.SO_HANBAI_WK SELECT SOSHN.MOYSKBN, SOSHN.MOYSSTDT, SOSHN.MOYSRBAN, SOSHN.BMNCD, SOSHN.KANRINO, SOSHN.SHNCD, SOSHN.GENKAAM, SOSHN.A_BAIKAAM, SOSHN.B_BAIKAAM, SOSHN.C_BAIKAAM, SOSHN.A_RANKNO, SOSHN.B_RANKNO, SOSHN.C_RANKNO, MC.HBSTDT, MC.HBEDDT, SOSHN.TENATSUK_ARR, MC.HBSTDT, MC.HBEDDT, SHNY.TEIKEIKBN, SHNY.URICD, SHN.SHNCD, SHN.TEIKEIKBN, SHN.URICD, SCY1.SHNCD, SCY1.SRCCD, SCY1.SOURCEKBN, SCY2.SHNCD, SCY2.SRCCD, SCY2.SOURCEKBN, SC1.SRCCD, SC1.SOURCEKBN, SC2.SRCCD, SC2.SOURCEKBN from INATK2.TOKSO_SHN SOSHN INNER JOIN INATK2.TOKMOYCD MC ON SOSHN.MOYSKBN = MC.MOYSKBN AND SOSHN.MOYSSTDT = MC.MOYSSTDT AND SOSHN.MOYSRBAN = MC.MOYSRBAN LEFT OUTER JOIN INAMS2.MSTSHN_Y SHNY ON SHNY.SHNCD = SOSHN.SHNCD AND SHNY.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON SHN.SHNCD = SOSHN.SHNCD LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY1 ON SCY1.SHNCD = SOSHN.SHNCD AND SCY1.SEQNO = 1 AND SCY1.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY2 ON SCY2.SHNCD = SOSHN.SHNCD AND SCY2.SEQNO = 2 AND SCY2.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD SC1 ON SC1.SHNCD = SOSHN.SHNCD AND SC1.SEQNO = 1 LEFT OUTER JOIN INAMS2.MSTSRCCD SC2 ON SC2.SHNCD = SOSHN.SHNCD AND SC2.SEQNO = 2;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.SO_HANBAI_WK;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
