REM [000][JH_HSUU_KEY_BFR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.JH_HSUU_KEY_BFR ロード処理（事前発注_発注数量取込中間キー(ア有)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAWK.JH_HSUU_KEY_BFR IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.JH_HSUU_KEY_BFR;INSERT IGNORE INTO INAWK.JH_HSUU_KEY_BFR WITH BASE AS (SELECT ANB.MOYSCD, ANB.MOYSKBN, ANB.MOYSSTDT, ANB.MOYSRBAN, ANB.BMNCD, ANB.KANRINO, ANB.KANRIENO, ANB.TENCD, ANB.GTSIMECHGKBN, ANB.GTSIMEOKFLG FROM INAIF.AN_NOUNYU_BFR ANB INNER JOIN INAIF.JH_SHIME_DATE JSD ON ANB.BMNCD = JSD.BMNCD AND ANB.NENMATKBN = JSD.NENMATKBN WHERE ANB.NNSTDT <> 0 AND ANB.UPDKBN <> 1 AND (((ANB.NENMATKBN = 1 OR ANB.TSHUFLG = 1) AND (ANB.NNSTDT BETWEEN JSD.TOKSTDT AND JSD.TOKEDDT OR ANB.NNEDDT BETWEEN JSD.TOKSTDT AND JSD.TOKEDDT)) OR (JSD.TYUSTDT <= ANB.NNSTDT AND ANB.NNSTDT <= JSD.TYUEDDT)) AND NOT (ANB.GTSIMECHGKBN IN (3) AND ANB.GTSIMEOKFLG = 1)), ENOBEF AS (SELECT ANB.MOYSCD, ANB.KANRINO, ANB.KANRIENO, COALESCE(LAG(ANB.KANRIENO) OVER (PARTITION BY ANB.MOYSCD, ANB.KANRINO ORDER BY ANB.KANRIENO), - 1) AS KANRIENO2 FROM (SELECT ANB.MOYSCD, ANB.KANRINO, ANB.KANRIENO FROM BASE ANB GROUP BY ANB.MOYSCD, ANB.KANRINO, ANB.KANRIENO) ANB), SUB AS (SELECT ANB.MOYSCD, ANB.MOYSKBN, ANB.MOYSSTDT, ANB.MOYSRBAN, ANB.BMNCD, ANB.KANRINO, CASE WHEN ANB.GTSIMECHGKBN IN (2, 4) AND ANB.GTSIMEOKFLG <> 1 THEN ENOBEF.KANRIENO2 ELSE ANB.KANRIENO END AS KANRIENO, ANB.TENCD FROM BASE ANB INNER JOIN ENOBEF ON ENOBEF.MOYSCD = ANB.MOYSCD AND ENOBEF.KANRINO = ANB.KANRINO AND ENOBEF.KANRIENO = ANB.KANRIENO) SELECT MT.MOYSCD, MT.MOYSKBN, MT.MOYSSTDT, MT.MOYSRBAN, MT.BMNCD, MT.KANRINO, MT.KANRIENO, MT.TENCD FROM INAIF.AN_NOUNYU_BFR MT WHERE EXISTS (SELECT 1 FROM SUB WHERE MT.MOYSCD = SUB.MOYSCD AND MT.MOYSCD = SUB.MOYSCD AND MT.MOYSKBN = SUB.MOYSKBN AND MT.MOYSSTDT = SUB.MOYSSTDT AND MT.MOYSRBAN = SUB.MOYSRBAN AND MT.BMNCD = SUB.BMNCD AND MT.KANRINO = SUB.KANRINO AND MT.KANRIENO >= SUB.KANRIENO AND MT.TENCD = SUB.TENCD) GROUP BY MT.MOYSCD, MT.MOYSKBN, MT.MOYSSTDT, MT.MOYSRBAN, MT.BMNCD, MT.KANRINO, MT.KANRIENO, MT.TENCD;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.JH_HSUU_KEY_BFR;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
