REM [000][TOKTG_TENGP]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_TENGP マージ処理（全店特売(アンケート有)_店グループ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INATK2.TOKTG_TENGP TGTENGP, (SELECT TGTENGP.MOYSKBN, TGTENGP.MOYSSTDT, TGTENGP.MOYSRBAN, TGTENGP.TENGPCD, SBD.DT_INT FROM INATK2.TOKTG_TENGP TGTENGP LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE TGTENGP.KYOSEIFLG = 1 AND TGTENGP.QACREDT_K = SBD.DT_INT AND TGTENGP.QARCREDT_K = 0) UPD SET QACREDT_K = UPD.DT_INT, QARCREDT_K = 0 WHERE TGTENGP.MOYSKBN = UPD.MOYSKBN AND TGTENGP.MOYSSTDT = UPD.MOYSSTDT AND TGTENGP.MOYSRBAN = UPD.MOYSRBAN AND TGTENGP.TENGPCD = UPD.TENGPCD;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
