REM [000][AN_HANBAI_NEQ_WK1]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_HANBAI_NEQ_WK1 ロード処理（全特アンケート無 販売データWK1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_HANBAI_NEQ_WK1; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.AN_HANBAI_NEQ_WK1 SELECT ANWK.MOYSKBN, ANWK.MOYSSTDT, ANWK.MOYSRBAN, ANWK.BMNCD, ANWK.KANRINO, ANWK.KANRIENO, ANWK.TENCD, ANWK.MOYSCD, ANWK.HBDT, ANWK.BMNO, ANWK.MOHBSTDT, ANWK.MOHBEDDT, ANWK.HBOKUREFLG, ANWK.JLSTCREDT, ANWK.QADEVSTDT, ANWK.QADEVENDFLG, ANWK.TENGPCD, ANWK.KYOSEIFLG, ANWK.SHNCD, ANWK.ADDSHUKBN, ANWK.HBSTDT, ANWK.HBEDDT, ANWK.REIDMYKBN, ANWK.HBSLIDEFLG, ANWK.GENKAAM, ANWK.GENKARITU, ANWK.A_BAIKAAM, ANWK.B_BAIKAAM, ANWK.C_BAIKAAM, ANWK.A_GENKAAM_1KG, ANWK.B_GENKAAM_1KG, ANWK.C_GENKAAM_1KG, ANWK.A_WRITUKBN, ANWK.B_WRITUKBN, ANWK.C_WRITUKBN, ANWK.TKANPLUKBN, ANWK.KO_A_BAIKAAN, ANWK.BD1_A_BAIKAAN, ANWK.BD2_A_BAIKAAN, ANWK.KO_B_BAIKAAN, ANWK.BD1_B_BAIKAAN, ANWK.BD2_B_BAIKAAN, ANWK.KO_C_BAIKAAN, ANWK.BD1_C_BAIKAAN, ANWK.BD2_C_BAIKAAN, ANWK.PLUSNDFLG, ANWK.TEIKEIKBN, ANWK.SOURCEKBN1, ANWK.SRCCD1, ANWK.SOURCEKBN2, ANWK.SRCCD2, ANWK.URICD, ANWK.QASYUKBN, ANWK.LTENSAIFLG, ANWK.HANKAISIFLG, ANWK.TENSAIFLG, ANWK.URIASELKBN, ANWK.ITMSELKBN, ANWK.CBAIKA, ANWK.SBAIBL1, ANWK.SBAIBL2, ANWK.CBAIKAKG, ANWK.DATAKBN, ANWK.GTSIMECHGKBN, ANWK.GTSIMEOKFLG, ANWK.SENDFLG, ANWK.UPDKBN FROM INAIF.AN_HANBAI_NEQ ANWK WHERE EXISTS (SELECT * FROM INAWK.ANWK12_HAN_N WK12 WHERE ANWK.MOYSKBN = WK12.MOYSKBN AND ANWK.MOYSSTDT = WK12.MOYSSTDT AND ANWK.MOYSRBAN = WK12.MOYSRBAN AND ANWK.KANRINO = WK12.KANRINO AND ANWK.BMNCD = WK12.BMNCD AND ANWK.KANRIENO <= WK12.KANRIENO); commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_HANBAI_NEQ_WK1;;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
