REM [000][JH_TEN_SYUSEI]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.JH_TEN_SYUSEI ロード処理（店舗修正データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAIF.JH_TEN_SYUSEI IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.JH_TEN_SYUSEI;INSERT IGNORE INTO INAIF.JH_TEN_SYUSEI SELECT BMNCD, TENCD, SHNCD, NNDT, BINKBN, HTSU, 0 AS ERRKBN, 0 AS ADDDT FROM (SELECT BMNCD, TENCD, SHNCD, NNDT, BINKBN, HTSU, ROW_NUMBER() OVER (PARTITION BY BMNCD, TENCD, SHNCD, NNDT, BINKBN ORDER BY HTSU DESC) AS RNO FROM (SELECT ADDSHN.BMNCD, ADDSHN.TENCD, ADDSHN.SHNCD, ADDSHN.BINKBN, CASE WHEN NUMS.SEQ = 1 THEN ADDSHN.JTDT_01 WHEN NUMS.SEQ = 2 THEN ADDSHN.JTDT_02 WHEN NUMS.SEQ = 3 THEN ADDSHN.JTDT_03 WHEN NUMS.SEQ = 4 THEN ADDSHN.JTDT_04 WHEN NUMS.SEQ = 5 THEN ADDSHN.JTDT_05 WHEN NUMS.SEQ = 6 THEN ADDSHN.JTDT_06 WHEN NUMS.SEQ = 7 THEN ADDSHN.JTDT_07 WHEN NUMS.SEQ = 8 THEN ADDSHN.JTDT_08 WHEN NUMS.SEQ = 9 THEN ADDSHN.JTDT_09 WHEN NUMS.SEQ = 10 THEN ADDSHN.JTDT_10 END AS NNDT, CASE WHEN NUMS.SEQ = 1 THEN ADDSHN.HTSU_01 WHEN NUMS.SEQ = 2 THEN ADDSHN.HTSU_02 WHEN NUMS.SEQ = 3 THEN ADDSHN.HTSU_03 WHEN NUMS.SEQ = 4 THEN ADDSHN.HTSU_04 WHEN NUMS.SEQ = 5 THEN ADDSHN.HTSU_05 WHEN NUMS.SEQ = 6 THEN ADDSHN.HTSU_06 WHEN NUMS.SEQ = 7 THEN ADDSHN.HTSU_07 WHEN NUMS.SEQ = 8 THEN ADDSHN.HTSU_08 WHEN NUMS.SEQ = 9 THEN ADDSHN.HTSU_09 WHEN NUMS.SEQ = 10 THEN ADDSHN.HTSU_10 END AS HTSU FROM INAWK.JH_RTN_ADDSHN ADDSHN LEFT OUTER JOIN INAPARM.MSTNUMS NUMS ON NUMS.SEQ BETWEEN 1 AND 10 UNION ALL SELECT TEN.BMNCD, TEN.TENCD, TEN.SHNCD, TEN.BINKBN, CASE WHEN NUMS.SEQ = 1 THEN TEN.JTDT_01 WHEN NUMS.SEQ = 2 THEN TEN.JTDT_02 WHEN NUMS.SEQ = 3 THEN TEN.JTDT_03 WHEN NUMS.SEQ = 4 THEN TEN.JTDT_04 WHEN NUMS.SEQ = 5 THEN TEN.JTDT_05 WHEN NUMS.SEQ = 6 THEN TEN.JTDT_06 WHEN NUMS.SEQ = 7 THEN TEN.JTDT_07 WHEN NUMS.SEQ = 8 THEN TEN.JTDT_08 WHEN NUMS.SEQ = 9 THEN TEN.JTDT_09 WHEN NUMS.SEQ = 10 THEN TEN.JTDT_10 END AS NNDT, CASE WHEN NUMS.SEQ = 1 THEN TEN.HTSU_01 WHEN NUMS.SEQ = 2 THEN TEN.HTSU_02 WHEN NUMS.SEQ = 3 THEN TEN.HTSU_03 WHEN NUMS.SEQ = 4 THEN TEN.HTSU_04 WHEN NUMS.SEQ = 5 THEN TEN.HTSU_05 WHEN NUMS.SEQ = 6 THEN TEN.HTSU_06 WHEN NUMS.SEQ = 7 THEN TEN.HTSU_07 WHEN NUMS.SEQ = 8 THEN TEN.HTSU_08 WHEN NUMS.SEQ = 9 THEN TEN.HTSU_09 WHEN NUMS.SEQ = 10 THEN TEN.HTSU_10 END AS HTSU FROM INAWK.JH_RTN_TEN TEN LEFT OUTER JOIN INAPARM.MSTNUMS NUMS ON NUMS.SEQ BETWEEN 1 AND 10 WHERE TRIM(TEN.OPERATOR) <> 'BATCH') T1 WHERE HTSU <> 99999) WK WHERE RNO = 1;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.JH_TEN_SYUSEI;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
