REM [000][MS_HANBAI_EVS]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.MS_HANBAI_EVS ロード処理（催し送信回答用 販売データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAIF.MS_HANBAI_EVS IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.MS_HANBAI_EVS;INSERT IGNORE INTO INAIF.MS_HANBAI_EVS SELECT LPAD(CPSHN.MOYSKBN, 1, 0) || LPAD(CPSHN.MOYSSTDT, 6, 0) || LPAD(CPSHN.MOYSRBAN, 3, 0) AS MOYSCD, CPSHN.MOYSKBN, CPSHN.MOYSSTDT, CPSHN.MOYSRBAN, CPBMN.BMNCD, CPSHN.KANRINO, 0 AS KANRIENO, NUMS.TENCD AS TENCD, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT, 0 AS BMNO, CPSHN.HBSTDT AS MOHBSTDT, CPSHN.HBENDT AS MOHBEDDT, 0 AS HBOKUREFLG, 0 AS JLSTCREDT, 0 AS QADEVSTDT, 0 AS QADEVENDFLG, CPBMN.RANKNO_ADD AS TENGPCD, 0 AS KYOSEIFLG, CPSHN.SHNCD, 0 AS ADDSHUKBN, CPSHN.HBSTDT AS HBSTDT, CPSHN.HBENDT AS HBEDDT, 0 AS REIDMYKBN, 0 AS HBSLIDEFLG, CPSHN.GENKAAM AS GENKAAM, CPSHN.GENKART AS GENKARITU, CPSHN.BAIKAAM AS A_BAIKAAM, 0 AS B_BAIKAAM, 0 AS C_BAIKAAM, 0 AS A_GENKAAM_1KG, 0 AS B_GENKAAM_1KG, 0 AS C_GENKAAM_1KG, 0 AS A_WRITUKBN, 0 AS B_WRITUKBN, 0 AS C_WRITUKBN, 0 AS TKANPLUKBN, 0 AS KO_A_BAIKAAN, 0 AS BD1_A_BAIKAAN, 0 AS BD2_A_BAIKAAN, 0 AS KO_B_BAIKAAN, 0 AS BD1_B_BAIKAAN, 0 AS BD2_B_BAIKAAN, 0 AS KO_C_BAIKAAN, 0 AS BD1_C_BAIKAAN, 0 AS BD2_C_BAIKAAN, 0 AS PLUSNDFLG, CASE WHEN SHNY.TEIKEIKBN IS NOT NULL THEN SHNY.TEIKEIKBN ELSE SHN.TEIKEIKBN END AS TEIKEIKBN, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SOURCEKBN ELSE SC1.SOURCEKBN END AS SOURCEKBN1, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SRCCD ELSE SC1.SRCCD END AS SRCCD1, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SOURCEKBN ELSE SC2.SOURCEKBN END AS SOURCEKBN2, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SRCCD ELSE SC2.SRCCD END AS SRCCD2, CASE WHEN SHNY.URICD IS NOT NULL THEN SHNY.URICD ELSE SHN.URICD END AS URICD, 0 AS QASYUKBN, 1 AS LTENSAIFLG, 0 AS HANKAISIFLG, 1 AS TENSAIFLG, 1 AS URIASELKBN, 1 AS ITMSELKBN, CPSHN.BAIKAAM AS CBAIKA, 0 AS SBAIBL1, 0 AS SBAIBL2, 0 AS CBAIKAKG, 3 AS DATAKBN, 0 AS GTSIMECHGKBN, 0 AS GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM INATK2.TOKCP_SHN CPSHN INNER JOIN INATK2.TOKCP_BMN CPBMN ON CPSHN.MOYSKBN = CPBMN.MOYSKBN AND CPSHN.MOYSSTDT = CPBMN.MOYSSTDT AND CPSHN.MOYSRBAN = CPBMN.MOYSRBAN LEFT OUTER JOIN INAMS2.MSTSHN_Y SHNY ON SHNY.SHNCD = CPSHN.SHNCD AND SHNY.YOYAKUDT <= CPSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON SHN.SHNCD = CPSHN.SHNCD LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY1 ON SCY1.SHNCD = CPSHN.SHNCD AND SCY1.SEQNO = 1 AND SCY1.YOYAKUDT <= CPSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY2 ON SCY2.SHNCD = CPSHN.SHNCD AND SCY2.SEQNO = 2 AND SCY2.YOYAKUDT <= CPSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD SC1 ON SC1.SHNCD = CPSHN.SHNCD AND SC1.SEQNO = 1 LEFT OUTER JOIN INAMS2.MSTSRCCD SC2 ON SC2.SHNCD = CPSHN.SHNCD AND SC2.SEQNO = 2 LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 WHERE TRIM(SUBSTR(CPBMN.TENATSUK_ARR, NUMS.TENCD, 1)) <> '';COMMIT; " >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.MS_HANBAI_EVS;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
