REM [000][JH_HSUU_KEY_NEQ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.JH_HSUU_KEY_WK ロード処理（事前発注_発注数量取込中間キー）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE  INAWK.JH_HSUU_KEY_WK;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.JH_HSUU_KEY_WK SELECT AN.MOYSCD, AN.MOYSKBN, AN.MOYSSTDT, AN.MOYSRBAN, AN.BMNCD, AN.KANRINO, AN.KANRIENO, AN.TENCD, AN.NNDT, AN.SHNCD, AN.BINKBN, AN.TSEIKBN, AN.JHTSUINDT, AN.TSHUFLG, 3 AS EVENT_PRINO FROM INAIF.AN_NOUNYU_BFR AN INNER JOIN INAWK.JH_HSUU_KEY_BFR JHK ON AN.MOYSCD = JHK.MOYSCD AND AN.BMNCD = JHK.BMNCD AND AN.KANRINO = JHK.KANRINO AND AN.KANRIENO = JHK.KANRIENO AND AN.TENCD = JHK.TENCD UNION ALL SELECT AN.MOYSCD, AN.MOYSKBN, AN.MOYSSTDT, AN.MOYSRBAN, AN.BMNCD, AN.KANRINO, AN.KANRIENO, AN.TENCD, AN.NNDT, AN.SHNCD, AN.BINKBN, AN.TSEIKBN, AN.JHTSUINDT, AN.TSHUFLG, CASE AN.MOYSKBN WHEN 3 THEN 1 WHEN 4 THEN 2 WHEN 1 THEN 4 WHEN 2 THEN 5 WHEN 0 THEN 6 END AS EVENT_PRINO FROM INAIF.AN_NOUNYU_NEQ AN INNER JOIN INAWK.JH_HSUU_KEY_NEQ JHK ON AN.MOYSCD = JHK.MOYSCD AND AN.BMNCD = JHK.BMNCD AND AN.KANRINO = JHK.KANRINO AND AN.KANRIENO = JHK.KANRIENO AND AN.TENCD = JHK.TENCD; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE  INAWK.JH_HSUU_KEY_WK;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAWK.JH_HSUU_KEY ロード処理（事前発注_発注数量取込中間キー）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.JH_HSUU_KEY;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.JH_HSUU_KEY SELECT MOYSCD, MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, TENCD, NNDT, SHNCD, BINKBN, TSEIKBN FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY SHNCD, NNDT, TENCD, BINKBN ORDER BY EVENT_PRINO, MOYSCD, KANRINO, KANRIENO DESC) AS RNO, MIN(EVENT_PRINO) OVER (PARTITION BY SHNCD, NNDT, TENCD, BINKBN) AS EVENT_PRINO_MIN FROM INAWK.JH_HSUU_KEY_WK WK) WK WHERE (RNO = 1 OR EVENT_PRINO_MIN >= 4) AND NOT (TSHUFLG = 0 AND JHTSUINDT > 0) AND TSEIKBN IS NOT NULL AND TSEIKBN NOT IN (3, 4); commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.JH_HSUU_KEY;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
