REM [000][SO_HANBAI]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.SO_HANBAI ロード処理（生活応援 販売データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
rem SET EXPFILENAME=%~DP0..\exp\999_bf
rem "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(SOSHN.MOYSKBN, 1, 0) || LPAD(SOSHN.MOYSSTDT, 6, 0) || LPAD(SOSHN.MOYSRBAN, 3, 0) AS MOYSCD, SOSHN.MOYSKBN, SOSHN.MOYSSTDT, SOSHN.MOYSRBAN, SOSHN.BMNCD, SOSHN.KANRINO, 0 AS KANRIENO, NUMS.TENCD AS TENCD, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT, 0 AS BMNO, MC.HBSTDT AS MOHBSTDT, MC.HBEDDT AS MOHBEDDT, 0 AS HBOKUREFLG, 0 AS JLSTCREDT, 0 AS QADEVSTDT, 0 AS QADEVENDFLG, CASE WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'A' THEN A_RANKNO WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'B' THEN B_RANKNO WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'C' THEN C_RANKNO END AS TENGPCD, 0 AS KYOSEIFLG, SOSHN.SHNCD, 0 AS ADDSHUKBN, MC.HBSTDT AS HBSTDT, MC.HBEDDT AS HBEDDT, 0 AS REIDMYKBN, 0 AS HBSLIDEFLG, SOSHN.GENKAAM, 0 AS GENKARITU, SOSHN.A_BAIKAAM, SOSHN.B_BAIKAAM, SOSHN.C_BAIKAAM, 0 AS A_GENKAAM_1KG, 0 AS B_GENKAAM_1KG, 0 AS C_GENKAAM_1KG, 0 AS A_WRITUKBN, 0 AS B_WRITUKBN, 0 AS C_WRITUKBN, 0 AS TKANPLUKBN, 0 AS KO_A_BAIKAAN, 0 AS BD1_A_BAIKAAN, 0 AS BD2_A_BAIKAAN, 0 AS KO_B_BAIKAAN, 0 AS BD1_B_BAIKAAN, 0 AS BD2_B_BAIKAAN, 0 AS KO_C_BAIKAAN, 0 AS BD1_C_BAIKAAN, 0 AS BD2_C_BAIKAAN, 0 AS PLUSNDFLG, CASE WHEN SHNY.TEIKEIKBN IS NOT NULL THEN SHNY.TEIKEIKBN ELSE SHN.TEIKEIKBN END AS TEIKEIKBN, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SOURCEKBN ELSE SC1.SOURCEKBN END AS SOURCEKBN1, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SRCCD ELSE SC1.SRCCD END AS SRCCD1, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SOURCEKBN ELSE SC2.SOURCEKBN END AS SOURCEKBN2, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SRCCD ELSE SC2.SRCCD END AS SRCCD2, CASE WHEN SHNY.URICD IS NOT NULL THEN SHNY.URICD ELSE SHN.URICD END AS URICD, 0 AS QASYUKBN, 1 AS LTENSAIFLG, 0 AS HANKAISIFLG, 1 AS TENSAIFLG, CASE WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'A' THEN 1 WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'B' THEN 2 WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'C' THEN 3 END AS URIASELKBN, 1 AS ITMSELKBN, CASE WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'A' THEN SOSHN.A_BAIKAAM WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'B' THEN SOSHN.B_BAIKAAM WHEN SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1) = 'C' THEN SOSHN.C_BAIKAAM END AS CBAIKA, 0 AS SBAIBL1, 0 AS SBAIBL2, 0 AS CBAIKAKG, 5 AS DATAKBN, 0 AS GTSIMECHGKBN, 0 AS GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM INATK2.TOKSO_SHN SOSHN INNER JOIN INATK2.TOKMOYCD MC ON SOSHN.MOYSKBN = MC.MOYSKBN AND SOSHN.MOYSSTDT = MC.MOYSSTDT AND SOSHN.MOYSRBAN = MC.MOYSRBAN LEFT OUTER JOIN INAMS2.MSTSHN_Y SHNY ON SHNY.SHNCD = SOSHN.SHNCD AND SHNY.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON SHN.SHNCD = SOSHN.SHNCD LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY1 ON SCY1.SHNCD = SOSHN.SHNCD AND SCY1.SEQNO = 1 AND SCY1.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY2 ON SCY2.SHNCD = SOSHN.SHNCD AND SCY2.SEQNO = 2 AND SCY2.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD SC1 ON SC1.SHNCD = SOSHN.SHNCD AND SC1.SEQNO = 1 LEFT OUTER JOIN INAMS2.MSTSRCCD SC2 ON SC2.SHNCD = SOSHN.SHNCD AND SC2.SEQNO = 2 LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 WHERE TRIM(SUBSTR(SOSHN.TENATSUK_ARR, NUMS.TENCD, 1)) <> ''" >%EXPFILENAME% 2>>%OUTFILE%
rem IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIF.SO_HANBAI ロード処理（生活応援 販売データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TEST;INSERT INTO INAWK.TEST SELECT SOSHN.MOYSKBN, SOSHN.MOYSSTDT, SOSHN.MOYSRBAN, SOSHN.BMNCD, SOSHN.KANRINO, SOSHN.SHNCD, SOSHN.GENKAAM, SOSHN.A_BAIKAAM, SOSHN.B_BAIKAAM, SOSHN.C_BAIKAAM, SOSHN.A_RANKNO, SOSHN.B_RANKNO, SOSHN.C_RANKNO, MC.HBSTDT, MC.HBEDDT, SOSHN.TENATSUK_ARR, MC.HBSTDT, MC.HBEDDT, SHNY.TEIKEIKBN, SHNY.URICD, SHN.SHNCD, SHN.TEIKEIKBN, SHN.URICD, SCY1.SHNCD, SCY1.SRCCD, SCY1.SOURCEKBN, SCY2.SHNCD, SCY2.SRCCD, SCY2.SOURCEKBN, SC1.SRCCD, SC1.SOURCEKBN, SC2.SRCCD, SC2.SOURCEKBN from INATK2.TOKSO_SHN SOSHN INNER JOIN INATK2.TOKMOYCD MC ON SOSHN.MOYSKBN = MC.MOYSKBN AND SOSHN.MOYSSTDT = MC.MOYSSTDT AND SOSHN.MOYSRBAN = MC.MOYSRBAN LEFT OUTER JOIN INAMS2.MSTSHN_Y SHNY ON SHNY.SHNCD = SOSHN.SHNCD AND SHNY.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON SHN.SHNCD = SOSHN.SHNCD LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY1 ON SCY1.SHNCD = SOSHN.SHNCD AND SCY1.SEQNO = 1 AND SCY1.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY2 ON SCY2.SHNCD = SOSHN.SHNCD AND SCY2.SEQNO = 2 AND SCY2.YOYAKUDT <= MC.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD SC1 ON SC1.SHNCD = SOSHN.SHNCD AND SC1.SEQNO = 1 LEFT OUTER JOIN INAMS2.MSTSRCCD SC2 ON SC2.SHNCD = SOSHN.SHNCD AND SC2.SEQNO = 2; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIF.SO_HANBAI ロード処理（生活応援 販売データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
SET EXPFILENAME=%~DP0..\exp\999_af
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(WK.MOYSKBN, 1, 0) || LPAD(WK.MOYSSTDT, 6, 0) || LPAD(WK.MOYSRBAN, 3, 0) AS MOYSCD, WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, WK.BMNCD, WK.KANRINO, 0 AS KANRIENO, NUMS.TENCD AS TENCD, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT, 0 AS BMNO, WK.MOHBSTDT, WK.MOHBEDDT, 0 AS HBOKUREFLG, 0 AS JLSTCREDT, 0 AS QADEVSTDT, 0 AS QADEVENDFLG, CASE WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'A' THEN WK.A_RANKNO WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'B' THEN WK.B_RANKNO WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'C' THEN WK.C_RANKNO END AS TENGPCD, 0 AS KYOSEIFLG, WK.SOSHN_SHNCD, 0 AS ADDSHUKBN, WK.HBSTDT, WK.HBEDDT, 0 AS REIDMYKBN, 0 AS HBSLIDEFLG, WK.GENKAAM, 0 AS GENKARITU, WK.A_BAIKAAM, WK.B_BAIKAAM, WK.C_BAIKAAM, 0 AS A_GENKAAM_1KG, 0 AS B_GENKAAM_1KG, 0 AS C_GENKAAM_1KG, 0 AS A_WRITUKBN, 0 AS B_WRITUKBN, 0 AS C_WRITUKBN, 0 AS TKANPLUKBN, 0 AS KO_A_BAIKAAN, 0 AS BD1_A_BAIKAAN, 0 AS BD2_A_BAIKAAN, 0 AS KO_B_BAIKAAN, 0 AS BD1_B_BAIKAAN, 0 AS BD2_B_BAIKAAN, 0 AS KO_C_BAIKAAN, 0 AS BD1_C_BAIKAAN, 0 AS BD2_C_BAIKAAN, 0 AS PLUSNDFLG, CASE WHEN WK.SHNY_TEIKEIKBN IS NOT NULL THEN WK.SHNY_TEIKEIKBN ELSE WK.SHN_TEIKEIKBN END AS TEIKEIKBN, CASE WHEN WK.SCY1_SHNCD IS NOT NULL THEN WK.SCY1_SOURCEKBN ELSE WK.SC1_SOURCEKBN END AS SOURCEKBN1, CASE WHEN WK.SCY1_SHNCD IS NOT NULL THEN WK.SCY1_SRCCD ELSE WK.SC1_SRCCD END AS SRCCD1, CASE WHEN WK.SCY2_SHNCD IS NOT NULL THEN WK.SCY2_SOURCEKBN ELSE WK.SC2_SOURCEKBN END AS SOURCEKBN2, CASE WHEN WK.SCY2_SHNCD IS NOT NULL THEN WK.SCY2_SRCCD ELSE WK.SC2_SRCCD END AS SRCCD2, CASE WHEN WK.SHNY_URICD IS NOT NULL THEN WK.SHNY_URICD ELSE WK.SHN_URICD END AS URICD, 0 AS QASYUKBN, 1 AS LTENSAIFLG, 0 AS HANKAISIFLG, 1 AS TENSAIFLG, CASE WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'A' THEN 1 WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'B' THEN 2 WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'C' THEN 3 END AS URIASELKBN, 1 AS ITMSELKBN, CASE WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'A' THEN WK.A_BAIKAAM WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'B' THEN WK.B_BAIKAAM WHEN SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1) = 'C' THEN WK.C_BAIKAAM END AS CBAIKA, 0 AS SBAIBL1, 0 AS SBAIBL2, 0 AS CBAIKAKG, 5 AS DATAKBN, 0 AS GTSIMECHGKBN, 0 AS GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM INAWK.TEST WK LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 WHERE TRIM(SUBSTR(WK.TENATSUK_ARR, NUMS.TENCD, 1)) <> ''" >%EXPFILENAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
