REM [000][AN_NOUNYU_AFT_TEN.LOAD]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_NOUNYU_AFT_TEN ロード処理（中間納入日(ア有反映後)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_NOUNYU_AFT_TEN ;INSERT IGNORE INTO INAWK.AN_NOUNYU_AFT_TEN SELECT TGND.MOYSKBN, TGND.MOYSSTDT, TGND.MOYSRBAN, TGND.BMNCD, TGND.KANRINO, TGND.KANRIENO, TGND.TENCD, TGND.NNDT, TGND.HSUU, TGND.TENHENKO, TGND.HTASU, TGND.PTNNO, TGND.TSEIKBN, TGND.ZJSKFLG, TGND.WEEKHTDT FROM INAWK.AN_NOUNYU_BFR_TEN TGND UNION ALL SELECT WK09_PRE.MOYSKBN, WK09_PRE.MOYSSTDT, WK09_PRE.MOYSRBAN, WK09_PRE.BMNCD, WK09_PRE.KANRINO, WK09_PRE.KANRIENO, WK09_PRE.TENCD, WK09_PRE.NNDT, WK09_PRE.HSUU, 1 AS TENHENKO, WK09_PRE.HTASU, WK09_PRE.PTNNO, WK09_PRE.TSEIKBN, WK09_PRE.ZJSKFLG, WK09_PRE.WEEKHTDT FROM INAPRE.AN_NOUNYU_AFT WK09_PRE WHERE NOT EXISTS (SELECT * FROM INAWK.AN_NOUNYU_BFR_TEN TGND WHERE TGND.MOYSKBN = WK09_PRE.MOYSKBN AND TGND.MOYSSTDT = WK09_PRE.MOYSSTDT AND TGND.MOYSRBAN = WK09_PRE.MOYSRBAN AND TGND.BMNCD = WK09_PRE.BMNCD AND TGND.KANRINO = WK09_PRE.KANRINO AND TGND.KANRIENO = WK09_PRE.KANRIENO AND TGND.TENCD = WK09_PRE.TENCD);COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_NOUNYU_AFT_TEN;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
