REM [000][AN_NOUNYU_AFT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_AFT ロード処理（全特アンケート有 納入データ(反映後)）:反映対象外データ１
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT ignore INTO INAIF.AN_NOUNYU_AFT SELECT WK09.MOYSCD, WK09.MOYSKBN, WK09.MOYSSTDT, WK09.MOYSRBAN, WK09.BMNCD, WK09.KANRINO, WK09.KANRIENO, WK09.TENCD, WK09.NNDT, WK09.SHUNO, WK09.TSHUFLG, WK09.MYOSNNSTDT, WK09.MYOSNNEDDT, WK09.NENMATKBN, WK09.JLSTCREFLG, WK09.JLSTCREDT, WK09.JHTSUINDT, WK09.WEEKHTDT, WK09.QADEVSTDT, WK09.QADEVEDFLG, WK09.TENGPCD, WK09.KYOSEIFLG, WK09.SHNCD, WK09.REIDMYKBN, WK09.NNSTDT, WK09.NNEDDT, WK09.JUFLG, WK09.JUHTDT, WK09.BINKBN, WK09.NNSLIDE, WK09.CUTTENFLG, WK09.SHUDENFLG, CASE WHEN WK09.CUTTENFLG = 1 THEN CASE WHEN COALESCE(WK09.TENGPCD, 0) = 0 OR WK09.QASYUKBN = 5 OR WK09.LDSYFLG = 2 OR WK09.MBSYFLG IN (0, 3) OR WK09.ITMSELKBN = 2 THEN NULL ELSE WK09.HSUU END ELSE WK09.HSUU END AS HSUU, WK09.HTASU, WK09.PTNNO, WK09.TSEIKBN, WK09.ZJSKFLG, WK09.NNWEEKHTDT, WK09.QASYUKBN, WK09.LDSYFLG, WK09.MBSYFLG, WK09.ITMSELKBN, WK09.GTSIMECHGKBN, WK09.GTSIMEOKFLG, WK09.SENDFLG, WK09.UPDKBN FROM (SELECT WK05.MOYSCD, WK05.MOYSKBN, WK05.MOYSSTDT, WK05.MOYSRBAN, WK05.SHUNO, WK05.TSHUFLG, WK05.MYOSNNSTDT, WK05.MYOSNNEDDT, WK05.NENMATKBN, WK05.JLSTCREFLG, WK05.JLSTCREDT, WK05.JHTSUINDT, WK05.WEEKHTDT, WK05.QADEVSTDT, WK05.QADEVEDFLG, WK05.TENGPCD, WK05.KYOSEIFLG, WK05.KANRINO, WK05.KANRIENO, WK05.BMNCD, WK05.SHNCD, WK05.REIDMYKBN, WK05.NNSTDT, WK05.NNEDDT, WK05.JUFLG, WK05.JUHTDT, WK05.BINKBN, WK05.NNSLIDE, WK05.CUTTENFLG, WK05.SHUDENFLG, WK05.TENCD, WK05.NNDT, WK05.HSUU, WK05.HTASU, WK05.PTNNO, WK05.TSEIKBN, WK05.ZJSKFLG, WK05.NNWEEKHTDT, WK05.QASYUKBN, WK05.LDSYFLG, WK05.MBSYFLG, WK05.ITMSELKBN, WK05.GTSIMECHGKBN, WK05.GTSIMEOKFLG, WK05.SENDFLG, WK05.UPDKBN FROM INAIF.AN_NOUNYU_BFR WK05 LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE WK05.JLSTCREFLG = 0 AND WK05.JHTSUINDT = 0 AND WK05.QADEVSTDT > SBD.DT_INT) WK09; COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_AFT;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
