REM [000][TOKTG_QASHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_QASHN マージ処理（アンケート結果_商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT INTO INATK2.TOKTG_QASHN(MOYSKBN, MOYSSTDT, MOYSRBAN, TENGPCD, BMNCD, KANRINO, KANRIENO, URISELKBN, ITMSELKBN, URICHGAM1, URICHGAM2, URICHGAM3, CSVSEQNO, UPDKBN, SENDFLG, OPERATOR, ADDDT, UPDDT) SELECT * FROM (SELECT QASHN_DIFF.MOYSKBN AS MOYSKBN, QASHN_DIFF.MOYSSTDT AS MOYSSTDT, QASHN_DIFF.MOYSRBAN AS MOYSRBAN, QASHN_DIFF.TENGPCD AS TENGPCD, QASHN_DIFF.BMNCD AS BMNCD, QASHN_DIFF.KANRINO AS KANRINO, QASHN_DIFF.KANRIENO AS KANRIENO, QASHN_DIFF.URISELKBN AS URISELKBN, QASHN_DIFF.ITMSELKBN AS ITMSELKBN, QASHN_DIFF.URICHGAM1 AS URICHGAM1, QASHN_DIFF.URICHGAM2 AS URICHGAM2, QASHN_DIFF.URICHGAM3 AS URICHGAM3, QASHN_DIFF.CSVSEQNO AS CSVSEQNO, QASHN_DIFF.UPDKBN AS UPDKBN, QASHN_DIFF.SENDFLG AS SENDFLG, QASHN_DIFF.OPERATOR AS OPERATOR, QASHN_DIFF.ADDDT AS ADDDT, QASHN_DIFF.UPDDT AS UPDDT FROM INAWK.AN_QASHN_DIFF QASHN_DIFF, INATK2.TOKTG_QASHN QASHN WHERE QASHN.MOYSKBN = QASHN_DIFF.MOYSKBN AND QASHN.MOYSSTDT = QASHN_DIFF.MOYSSTDT AND QASHN.MOYSRBAN = QASHN_DIFF.MOYSRBAN AND QASHN.TENGPCD = QASHN_DIFF.TENGPCD AND QASHN.BMNCD = QASHN_DIFF.BMNCD AND QASHN.KANRINO = QASHN_DIFF.KANRINO AND QASHN.KANRIENO = QASHN_DIFF.KANRIENO) MT ON DUPLICATE KEY UPDATE URISELKBN = MT.URISELKBN, ITMSELKBN = MT.ITMSELKBN, URICHGAM1 = MT.URICHGAM1, URICHGAM2 = MT.URICHGAM2, URICHGAM3 = MT.URICHGAM3, CSVSEQNO = MT.CSVSEQNO, UPDKBN = MT.UPDKBN, SENDFLG = MT.SENDFLG, OPERATOR = MT.OPERATOR, ADDDT = MT.ADDDT, UPDDT = MT.UPDDT;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
