REM [000][AN_NOUNYU_BFR_NEW]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_BFR ロード処理（全店特売アンケート有 納入データ(反映前)）※OUTDD1:新規分回答用納入ﾃﾞｰﾀ
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAIF.AN_NOUNYU_BFR IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_NOUNYU_BFR;INSERT IGNORE INTO INAIF.AN_NOUNYU_BFR WITH TGTG AS (SELECT * FROM INATK2.TOKTG_TENGP TGTG WHERE TGTG.UPDKBN <> 1), TGTEN AS (SELECT TGTEN.MOYSKBN, TGTEN.MOYSSTDT, TGTEN.MOYSRBAN, TGTEN.TENCD, TGTEN.TENGPCD, TGTG.QASYUKBN, TGTEN.KYOSEIFLG, TGTEN.LDTENKBN FROM INATK2.TOKTG_TEN TGTEN LEFT OUTER JOIN TGTG ON TGTG.MOYSKBN = TGTEN.MOYSKBN AND TGTG.MOYSSTDT = TGTEN.MOYSSTDT AND TGTG.MOYSRBAN = TGTEN.MOYSRBAN AND TGTG.TENGPCD = TGTEN.TENGPCD) SELECT LPAD(TGSHN.MOYSKBN, 1, 0) || LPAD(TGSHN.MOYSSTDT, 6, 0) || LPAD(TGSHN.MOYSRBAN, 3, 0) AS MOYSCD, TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, TGSHN.BMNCD, TGSHN.KANRINO, TGSHN.KANRIENO, WK05TC16.TENCD, WK05TC16.NNDT, MC.SHUNO, MS.TSHUFLG, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNSTDT_TGF ELSE MC.NNSTDT END AS MYOSNNSTDT, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNEDDT_TGF ELSE MC.NNEDDT END AS MYOSNNEDDT, MC.NENMATKBN, TGKHN.JLSTCREFLG, TGSHN.JLSTCREDT, TGSHN.JHTSUINDT, TGSHN.WEEKHTDT, TGKHN.QADEVSTDT, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS QADEVEDFLG, TGTEN.TENGPCD, TGTEN.KYOSEIFLG, TGSHN.SHNCD, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, TGSHN.NNSTDT, TGSHN.NNEDDT, TGSHN.JUFLG, TGSHN.JUHTDT, TGSHN.BINKBN, 1 AS NNSLIDE, TGSHN.CUTTENFLG, TGSHN.SHUDENFLG, WK05TC16.HSUU, WK05TC16.HTASU, WK05TC16.PTNNO, WK05TC16.TSEIKBN, WK05TC16.ZJSKFLG, WK05TC16.WEEKHTDT AS NNWEEKHTDT, TGTEN.QASYUKBN, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS LDSYFLG, CASE WHEN TGTEN.LDTENKBN = 0 THEN 1 WHEN TGTEN.LDTENKBN = 1 THEN 2 END AS MBSYFLG, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS ITMSELKBN, TGSHN.GTSIMECHGKBN, TGSHN.GTSIMEOKFLG, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS SENDFLG, 8 AS UPDKBN FROM INATK2.TOKTG_SHN TGSHN INNER JOIN INATK2.TOKTG_KHN TGKHN ON TGSHN.MOYSKBN = TGKHN.MOYSKBN AND TGSHN.MOYSSTDT = TGKHN.MOYSSTDT AND TGSHN.MOYSRBAN = TGKHN.MOYSRBAN INNER JOIN INATK2.TOKMOYCD MC ON TGSHN.MOYSKBN = MC.MOYSKBN AND TGSHN.MOYSSTDT = MC.MOYSSTDT AND TGSHN.MOYSRBAN = MC.MOYSRBAN INNER JOIN (SELECT * FROM INATK2.TOKMOYSYU MS LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE CAST(DATE_FORMAT(SBD.DT - INTERVAL 1 YEAR, '%%y') AS SIGNED) <= SUBSTR(MS.SHUNO, 1, 2) AND SUBSTR(MS.SHUNO, 1, 2) <= CAST(DATE_FORMAT(SBD.DT + INTERVAL 1 YEAR, '%%y') AS SIGNED)) MS ON MS.SHUNO = MC.SHUNO INNER JOIN INAWK.AN_NOUNYU_BFR_TEN WK05TC16 ON TGSHN.MOYSKBN = WK05TC16.MOYSKBN AND TGSHN.MOYSSTDT = WK05TC16.MOYSSTDT AND TGSHN.MOYSRBAN = WK05TC16.MOYSRBAN AND TGSHN.BMNCD = WK05TC16.BMNCD AND TGSHN.KANRINO = WK05TC16.KANRINO AND TGSHN.KANRIENO = WK05TC16.KANRIENO LEFT OUTER JOIN TGTEN ON TGSHN.MOYSKBN = TGTEN.MOYSKBN AND TGSHN.MOYSSTDT = TGTEN.MOYSSTDT AND TGSHN.MOYSRBAN = TGTEN.MOYSRBAN AND WK05TC16.TENCD = TGTEN.TENCD LEFT OUTER JOIN INAPARM.PRAM_FRSDRYJUD FDJ ON FDJ.BMNCD = TGSHN.BMNCD AND FDJ.JUDFLG = 'S' WHERE TGSHN.UPDKBN <> 1 AND TGSHN.NNSTDT <> 0 AND TGSHN.SENDFLG <> 1 AND NOT EXISTS (SELECT 1 FROM INAPRE.AN_NOUNYU_BFR WK05_PRE WHERE WK05_PRE.MOYSKBN = TGSHN.MOYSKBN AND WK05_PRE.MOYSSTDT = TGSHN.MOYSSTDT AND WK05_PRE.MOYSRBAN = TGSHN.MOYSRBAN AND WK05_PRE.BMNCD = TGSHN.BMNCD AND WK05_PRE.KANRINO = TGSHN.KANRINO AND WK05_PRE.KANRIENO = TGSHN.KANRIENO) and EXISTS (SELECT * FROM (select WK.*, CASE WHEN TGND.TENCHGFLG_ARR = REPEAT('1', 400) THEN 1 ELSE 0 END AS ALL1FLG from INAWK.AN_NOUNYU_BFR_TEN WK inner join INATK2.TOKTG_NNDT TGND on WK.MOYSKBN = TGND.MOYSKBN AND WK.MOYSSTDT = TGND.MOYSSTDT AND WK.MOYSRBAN = TGND.MOYSRBAN AND WK.BMNCD = TGND.BMNCD AND WK.KANRINO = TGND.KANRINO AND WK.KANRIENO = TGND.KANRIENO AND WK.NNDT = TGND.NNDT AND TGND.SENDFLG <> 1) WK WHERE (WK.HSUU IS NOT NULL OR (WK.TENHENKO IS NOT NULL AND WK.ALL1FLG = 0)) AND WK05TC16.MOYSKBN = WK.MOYSKBN AND WK05TC16.MOYSSTDT = WK.MOYSSTDT AND WK05TC16.MOYSRBAN = WK.MOYSRBAN AND WK05TC16.BMNCD = WK.BMNCD AND WK05TC16.KANRINO = WK.KANRINO AND WK05TC16.KANRIENO = WK.KANRIENO AND WK05TC16.TENCD = WK.TENCD);COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_BFR;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
