REM [000][AN_NOUNYU_NEQ_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_NOUNYU_NEQ_TEN ロード処理（店舗単位 納入日(ア無)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_NOUNYU_NEQ_TEN;INSERT IGNORE INTO INAWK.AN_NOUNYU_NEQ_TEN SELECT SPND.MOYSKBN, SPND.MOYSSTDT, SPND.MOYSRBAN, SPND.BMNCD, SPND.KANRINO, SPND.KANRIENO, NUMS.TENCD, SPND.NNDT, CAST(TRIM(SUBSTR(SPND.TENHTSU_ARR, ((NUMS.TENCD - 1) * 5) + 1, 5)) AS SIGNED) AS HSUU, SPND.HTASU, SPND.PTNNO, SPND.TSEIKBN, SPND.ZJSKFLG, SPND.WEEKHTDT FROM INATK2.TOKSP_NNDT SPND LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 INNER JOIN INATK2.TOKSP_SHN SPSHN ON SPSHN.MOYSKBN = SPND.MOYSKBN AND SPSHN.MOYSSTDT = SPND.MOYSSTDT AND SPSHN.MOYSRBAN = SPND.MOYSRBAN AND SPSHN.BMNCD = SPND.BMNCD AND SPSHN.KANRINO = SPND.KANRINO AND SPSHN.KANRIENO = SPND.KANRIENO WHERE TRIM(SUBSTR(SPND.TENHTSU_ARR, ((NUMS.TENCD - 1) * 5) + 1, 5)) <> '';COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_NOUNYU_NEQ_TEN;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
