REM [000][TOKTG_QATEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_QATEN マージ処理（アンケート結果_店舗）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INATK2.TOKTG_QATEN(MOYSKBN, MOYSSTDT, MOYSRBAN, TENCD, KYOSEIFLG, TENGPCD, LDTENKBN, MBSYFLG, HBSTRTFLG, MBANSFLG, CSVSEQNO, SENDFLG, OPERATOR, ADDDT, UPDDT) SELECT * FROM (SELECT QATEN_DIFF.MOYSKBN AS MOYSKBN, QATEN_DIFF.MOYSSTDT AS MOYSSTDT, QATEN_DIFF.MOYSRBAN AS MOYSRBAN, QATEN_DIFF.TENCD AS TENCD, QATEN_DIFF.KYOSEIFLG AS KYOSEIFLG, QATEN_DIFF.TENGPCD AS TENGPCD, QATEN_DIFF.LDTENKBN AS LDTENKBN, QATEN_DIFF.MBSYFLG AS MBSYFLG, QATEN_DIFF.HBSTRTFLG AS HBSTRTFLG, QATEN_DIFF.MBANSFLG AS MBANSFLG, QATEN_DIFF.CSVSEQNO AS CSVSEQNO, QATEN_DIFF.SENDFLG AS SENDFLG, QATEN_DIFF.OPERATOR AS OPERATOR, QATEN_DIFF.ADDDT AS ADDDT, QATEN_DIFF.UPDDT AS UPDDT FROM INAWK.AN_QATEN_DIFF QATEN_DIFF, INATK2.TOKTG_QATEN QATEN WHERE QATEN.MOYSKBN = QATEN_DIFF.MOYSKBN AND QATEN.MOYSSTDT = QATEN_DIFF.MOYSSTDT AND QATEN.MOYSRBAN = QATEN_DIFF.MOYSRBAN AND QATEN.TENCD = QATEN_DIFF.TENCD AND QATEN.KYOSEIFLG = QATEN_DIFF.KYOSEIFLG) MT ON DUPLICATE KEY UPDATE TENGPCD = MT.TENGPCD, LDTENKBN = MT.LDTENKBN, MBSYFLG = MT.MBSYFLG, HBSTRTFLG = MT.HBSTRTFLG, MBANSFLG = MT.MBANSFLG, CSVSEQNO = MT.CSVSEQNO, SENDFLG = MT.SENDFLG, OPERATOR = MT.OPERATOR, ADDDT = MT.ADDDT, UPDDT = MT.UPDDT;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
