REM [000][AN_HANBAI_NEQ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_HANBAI_NEQ ロード処理（全特アンケート無 販売データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_HANBAI_NEQ;INSERT IGNORE INTO INAIF.AN_HANBAI_NEQ SELECT LPAD(SPSHN.MOYSKBN, 1, 0) || LPAD(SPSHN.MOYSSTDT, 6, 0) || LPAD(SPSHN.MOYSRBAN, 3, 0) AS MOYSCD, SPSHN.MOYSKBN, SPSHN.MOYSSTDT, SPSHN.MOYSRBAN, SPSHN.BMNCD, SPSHN.KANRINO, SPSHN.KANRIENO, SPSHN.TENCD, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT, 0 AS BMNO, SPSHN.MOHBSTDT, SPSHN.MOHBEDDT, 0 AS HBOKUREFLG, SPSHN.JLSTCREDT, 0 AS QADEVSTDT, CASE WHEN 1 = 1 THEN NULL ELSE 1 END AS QADEVENDFLG, CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.RANKNO_ADD_A WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.RANKNO_ADD_B WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.RANKNO_ADD_C ELSE 0 END AS TENGPCD, 0 AS KYOSEIFLG, SPSHN.SHNCD, SPSHN.ADDSHUKBN, SPSHN.HBSTDT, SPSHN.HBEDDT, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, 0 AS HANBAISLIDE, CASE WHEN SPSHN.ADDSHUKBN = 2 THEN SPSHN.GENKAAM_MAE WHEN SPSHN.ADDSHUKBN = 4 THEN CASE WHEN SPSHN.TKANPLUKBN = 1 THEN SPSHN.GENKAAM_MAE WHEN SPSHN.TKANPLUKBN = 2 THEN SPSHN.GENKAAM_1KG END WHEN SPSHN.ADDSHUKBN = 5 THEN CASE WHEN SPSHN.TKANPLUKBN = 1 THEN SPSHN.GENKAAM_MAE WHEN SPSHN.TKANPLUKBN = 2 THEN SPSHN.GENKAAM_1KG END END AS GENKAAM, 0 AS GENKARITU, SPSHN.A_BAIKAAM, SPSHN.B_BAIKAAM, SPSHN.C_BAIKAAM, SPSHN.A_GENKAAM_1KG, SPSHN.B_GENKAAM_1KG, SPSHN.C_GENKAAM_1KG, SPSHN.A_WRITUKBN, SPSHN.B_WRITUKBN, SPSHN.C_WRITUKBN, SPSHN.TKANPLUKBN, SPSHN.KO_A_BAIKAAN, SPSHN.BD1_A_BAIKAAN, SPSHN.BD2_A_BAIKAAN, SPSHN.KO_B_BAIKAAN, SPSHN.BD1_B_BAIKAAN, SPSHN.BD2_B_BAIKAAN, SPSHN.KO_C_BAIKAAN, SPSHN.BD1_C_BAIKAAN, SPSHN.BD2_C_BAIKAAN, SPSHN.PLUSNDFLG, CASE WHEN SHNY.TEIKEIKBN IS NOT NULL THEN SHNY.TEIKEIKBN ELSE SHN.TEIKEIKBN END AS TEIKEIKBN, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SOURCEKBN ELSE SC1.SOURCEKBN END AS SOURCEKBN1, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SRCCD ELSE SC1.SRCCD END AS SRCCD1, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SOURCEKBN ELSE SC2.SOURCEKBN END AS SOURCEKBN2, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SRCCD ELSE SC2.SRCCD END AS SRCCD2, CASE WHEN SHNY.URICD IS NOT NULL THEN SHNY.URICD ELSE SHN.URICD END AS URICD, 0 AS QASYUKBN, 1 AS LTENSAIFLG, CASE WHEN 1 = 1 THEN NULL ELSE 1 END AS HANKAISIFLG, 1 AS TENSAIFLG, CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN 1 WHEN SPSHN.TENATSUKKBN = 'B' THEN 2 WHEN SPSHN.TENATSUKKBN = 'C' THEN 3 END AS BAIKASELKBN, 1 AS SHOHINSEL, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.A_WRITUKBN WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.B_WRITUKBN WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.C_WRITUKBN END ELSE CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN CASE WHEN SPSHN.KO_A_BAIKAAN = 0 THEN SPSHN.A_BAIKAAM ELSE SPSHN.KO_A_BAIKAAN END WHEN SPSHN.TENATSUKKBN = 'B' THEN CASE WHEN SPSHN.KO_B_BAIKAAN = 0 THEN SPSHN.B_BAIKAAM ELSE SPSHN.KO_B_BAIKAAN END WHEN SPSHN.TENATSUKKBN = 'C' THEN CASE WHEN SPSHN.KO_C_BAIKAAN = 0 THEN SPSHN.C_BAIKAAM ELSE SPSHN.KO_C_BAIKAAN END END END AS CBAIKA, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 0 ELSE CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.BD1_A_BAIKAAN WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.BD1_B_BAIKAAN WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.BD1_C_BAIKAAN END END AS SBAIBL1, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 0 ELSE CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.BD2_A_BAIKAAN WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.BD2_B_BAIKAAN WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.BD2_C_BAIKAAN END END AS SBAIBL2, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 0 ELSE CASE WHEN SPSHN.TKANPLUKBN = 2 THEN CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.A_GENKAAM_1KG WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.B_GENKAAM_1KG WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.C_GENKAAM_1KG END END END AS CBAIKAKG, 2 AS DATAKBN, 0 AS GTSIMECHGKBN, 0 AS GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM (SELECT SPSHN.*, TMC.HBSTDT AS MOHBSTDT, TMC.HBEDDT AS MOHBEDDT, NUMS.TENCD, SUBSTR(SPHB.TENATSUK_ARR, NUMS.TENCD, 1) AS TENATSUKKBN FROM INATK2.TOKSP_SHN SPSHN INNER JOIN INATK2.TOKSP_HB SPHB ON SPSHN.MOYSKBN = SPHB.MOYSKBN AND SPSHN.MOYSSTDT = SPHB.MOYSSTDT AND SPSHN.MOYSRBAN = SPHB.MOYSRBAN AND SPSHN.BMNCD = SPHB.BMNCD AND SPSHN.KANRINO = SPHB.KANRINO AND SPSHN.KANRIENO = SPHB.KANRIENO INNER JOIN (SELECT * FROM INATK2.TOKMOYCD TMC WHERE TMC.UPDKBN <> 1) TMC ON SPSHN.MOYSKBN = TMC.MOYSKBN AND SPSHN.MOYSSTDT = TMC.MOYSSTDT AND SPSHN.MOYSRBAN = TMC.MOYSRBAN LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 WHERE SPSHN.UPDKBN <> 1 AND SPSHN.HBSTDT <> 0 AND TRIM(SUBSTR(SPHB.TENATSUK_ARR, NUMS.TENCD, 1)) <> '') SPSHN LEFT OUTER JOIN INAMS2.MSTSHN_Y SHNY ON SHNY.SHNCD = SPSHN.SHNCD AND SHNY.YOYAKUDT <= SPSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON SHN.SHNCD = SPSHN.SHNCD LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY1 ON SCY1.SHNCD = SPSHN.SHNCD AND SCY1.SEQNO = 1 AND SCY1.YOYAKUDT <= SPSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY2 ON SCY2.SHNCD = SPSHN.SHNCD AND SCY2.SEQNO = 2 AND SCY2.YOYAKUDT <= SPSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD SC1 ON SC1.SHNCD = SPSHN.SHNCD AND SC1.SEQNO = 1 LEFT OUTER JOIN INAMS2.MSTSRCCD SC2 ON SC2.SHNCD = SPSHN.SHNCD AND SC2.SEQNO = 2;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_HANBAI_NEQ;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
