REM [000][AN_CRE_KEY]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_CRE_KEY ロード処理（アンケート結果作成キー）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_CRE_KEY;INSERT IGNORE INTO INAWK.AN_CRE_KEY SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, QACREDT FROM INATK2.TOKTG_KHN TGKHN LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE TGKHN.UPDKBN <> 1 AND TGKHN.QARCREDT = 0 AND SBD.DT_INT = TGKHN.QACREDT UNION SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, QACREDT FROM INATK2.TOKTG_KHN TGKHN LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE TGKHN.UPDKBN <> 1 AND TGKHN.QARCREDT <> 0 AND SBD.DT_INT = TGKHN.QARCREDT;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_CRE_KEY;;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
