REM [000][TOKTG_QAGP]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_QAGP マージ処理（アンケート結果_店グループ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INATK2.TOKTG_QAGP(MOYSKBN, MOYSSTDT, MOYSRBAN, TENGPCD, KYOSEIFLG, QASYUKBN, LDSYFLG, URIASELKBN, SCHANSFLG, ITMANSFLG, CSVSEQNO, SENDFLG, OPERATOR, ADDDT, UPDDT) SELECT * FROM (SELECT QAGP_DIFF.MOYSKBN AS MOYSKBN, QAGP_DIFF.MOYSSTDT AS MOYSSTDT, QAGP_DIFF.MOYSRBAN AS MOYSRBAN, QAGP_DIFF.TENGPCD AS TENGPCD, QAGP_DIFF.KYOSEIFLG AS KYOSEIFLG, QAGP_DIFF.QASYUKBN AS QASYUKBN, QAGP_DIFF.LDSYFLG AS LDSYFLG, QAGP_DIFF.URIASELKBN AS URIASELKBN, QAGP_DIFF.SCHANSFLG AS SCHANSFLG, QAGP_DIFF.ITMANSFLG AS ITMANSFLG, QAGP_DIFF.CSVSEQNO AS CSVSEQNO, QAGP_DIFF.SENDFLG AS SENDFLG, QAGP_DIFF.OPERATOR AS OPERATOR, QAGP_DIFF.ADDDT AS ADDDT, QAGP_DIFF.UPDDT AS UPDDT FROM INAWK.AN_QATENGP_DIFF QAGP_DIFF, INATK2.TOKTG_QAGP QAGP WHERE QAGP_DIFF.MOYSKBN = QAGP.MOYSKBN AND QAGP_DIFF.MOYSSTDT = QAGP.MOYSSTDT AND QAGP_DIFF.MOYSRBAN = QAGP.MOYSRBAN AND QAGP_DIFF.TENGPCD = QAGP.TENGPCD) MT ON DUPLICATE KEY UPDATE KYOSEIFLG = MT.KYOSEIFLG, QASYUKBN = MT.QASYUKBN, LDSYFLG = MT.LDSYFLG, URIASELKBN = MT.URIASELKBN, SCHANSFLG = MT.SCHANSFLG, ITMANSFLG = MT.ITMANSFLG, CSVSEQNO = MT.CSVSEQNO, SENDFLG = MT.SENDFLG, OPERATOR = MT.OPERATOR, ADDDT = MT.ADDDT, UPDDT = MT.UPDDT;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
