REM [000][MS_HANBAI_BMS]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.MS_HANBAI_BMS ロード処理（B/M 催し送信回答用 販売データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAIF.MS_HANBAI_BMS IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.MS_HANBAI_BMS;INSERT IGNORE INTO INAIF.MS_HANBAI_BMS SELECT LPAD(BMSHN.MOYSKBN, 1, 0) || LPAD(BMSHN.MOYSSTDT, 6, 0) || LPAD(BMSHN.MOYSRBAN, 3, 0) AS MOYSCD, BMSHN.MOYSKBN, BMSHN.MOYSSTDT, BMSHN.MOYSRBAN, BMSHN.BMNNO AS BMNCD, BMSHN.KANRINO, 0 AS KANRIENO, NUMS.TENCD AS TENCD, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT, CAST('0' || SUBSTR(BMSHN.SHNCD, 1, 2) AS SIGNED) AS BMNO, BM.HBSTDT AS MOHBSTDT, BM.HBEDDT AS MOHBEDDT, 0 AS HBOKUREFLG, 0 AS JLSTCREDT, 0 AS QADEVSTDT, 0 AS QADEVENDFLG, BM.RANKNO_ADD AS TENGPCD, 0 AS KYOSEIFLG, BMSHN.SHNCD, 0 AS ADDSHUKBN, BM.HBSTDT AS HBSTDT, BM.HBEDDT AS HBEDDT, 0 AS REIDMYKBN, 0 AS HBSLIDEFLG, BMSHN.GENKAAM AS GENKAAM, 0 AS GENKARITU, 0 AS A_BAIKAAM, 0 AS B_BAIKAAM, 0 AS C_BAIKAAM, 0 AS A_GENKAAM_1KG, 0 AS B_GENKAAM_1KG, 0 AS C_GENKAAM_1KG, 0 AS A_WRITUKBN, 0 AS B_WRITUKBN, 0 AS C_WRITUKBN, 0 AS TKANPLUKBN, BM.BAIKAAM AS KO_A_BAIKAAN, 0 AS BD1_A_BAIKAAN, 0 AS BD2_A_BAIKAAN, 0 AS KO_B_BAIKAAN, 0 AS BD1_B_BAIKAAN, 0 AS BD2_B_BAIKAAN, 0 AS KO_C_BAIKAAN, 0 AS BD1_C_BAIKAAN, 0 AS BD2_C_BAIKAAN, 0 AS PLUSNDFLG, CASE WHEN SHNY.TEIKEIKBN IS NOT NULL THEN SHNY.TEIKEIKBN ELSE SHN.TEIKEIKBN END AS TEIKEIKBN, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SOURCEKBN ELSE SC1.SOURCEKBN END AS SOURCEKBN1, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SRCCD ELSE SC1.SRCCD END AS SRCCD1, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SOURCEKBN ELSE SC2.SOURCEKBN END AS SOURCEKBN2, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SRCCD ELSE SC2.SRCCD END AS SRCCD2, CASE WHEN SHNY.URICD IS NOT NULL THEN SHNY.URICD ELSE SHN.URICD END AS URICD, 0 AS QASYUKBN, 1 AS LTENSAIFLG, 0 AS HANKAISIFLG, 1 AS TENSAIFLG, 1 AS URIASELKBN, 1 AS ITMSELKBN, BM.BAIKAAM AS CBAIKA, BM.BD_BAIKAAN1 AS SBAIBL1, BM.BD_BAIKAAN2 AS SBAIBL2, 0 AS CBAIKAKG, 4 AS DATAKBN, 0 AS GTSIMECHGKBN, 0 AS GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM INATK2.TOKBM_SHN BMSHN INNER JOIN INATK2.TOKBM BM ON BMSHN.MOYSKBN = BM.MOYSKBN AND BMSHN.MOYSSTDT = BM.MOYSSTDT AND BMSHN.MOYSRBAN = BM.MOYSRBAN AND BMSHN.BMNNO = BM.BMNNO AND BMSHN.MOYSRBAN = BM.MOYSRBAN LEFT OUTER JOIN INAMS2.MSTSHN_Y SHNY ON SHNY.SHNCD = BMSHN.SHNCD AND SHNY.YOYAKUDT <= BM.HBSTDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON SHN.SHNCD = BMSHN.SHNCD LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY1 ON SCY1.SHNCD = BMSHN.SHNCD AND SCY1.SEQNO = 1 AND SCY1.YOYAKUDT <= BM.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY2 ON SCY2.SHNCD = BMSHN.SHNCD AND SCY2.SEQNO = 2 AND SCY2.YOYAKUDT <= BM.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD SC1 ON SC1.SHNCD = BMSHN.SHNCD AND SC1.SEQNO = 1 LEFT OUTER JOIN INAMS2.MSTSRCCD SC2 ON SC2.SHNCD = BMSHN.SHNCD AND SC2.SEQNO = 2 LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 WHERE TRIM(SUBSTR(BM.TENATSUK_ARR, NUMS.TENCD, 1)) <> '';COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.MS_HANBAI_BMS;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
