REM [000][AN_NOUNYU_AFT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_AFT ロード処理（全特アンケート有 納入データ(反映後)）:反映対象データ
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_NOUNYU_AFT;INSERT IGNORE INTO INAIF.AN_NOUNYU_AFT SELECT WK09.MOYSCD, WK09.MOYSKBN, WK09.MOYSSTDT, WK09.MOYSRBAN, WK09.BMNCD, WK09.KANRINO, WK09.KANRIENO, WK09.TENCD, WK09.NNDT, WK09.SHUNO, WK09.TSHUFLG, WK09.MYOSNNSTDT, WK09.MYOSNNEDDT, WK09.NENMATKBN, WK09.JLSTCREFLG, WK09.JLSTCREDT, WK09.JHTSUINDT, WK09.WEEKHTDT, WK09.QADEVSTDT, WK09.QADEVEDFLG, WK09.TENGPCD, WK09.KYOSEIFLG, WK09.SHNCD, WK09.REIDMYKBN, WK09.NNSTDT, WK09.NNEDDT, WK09.JUFLG, WK09.JUHTDT, WK09.BINKBN, WK09.NNSLIDE, WK09.CUTTENFLG, WK09.SHUDENFLG, CASE WHEN WK09.CUTTENFLG = 1 THEN CASE WHEN COALESCE(WK09.TENGPCD, 0) = 0 OR WK09.QASYUKBN = 5 OR WK09.LDSYFLG = 2 OR WK09.MBSYFLG IN (0, 3) OR WK09.ITMSELKBN = 2 THEN NULL ELSE WK09.HSUU END ELSE WK09.HSUU END AS HSUU, WK09.HTASU, WK09.PTNNO, WK09.TSEIKBN, WK09.ZJSKFLG, WK09.NNWEEKHTDT, WK09.QASYUKBN, WK09.LDSYFLG, WK09.MBSYFLG, WK09.ITMSELKBN, WK09.GTSIMECHGKBN, WK09.GTSIMEOKFLG, WK09.SENDFLG, WK09.UPDKBN FROM (SELECT WK05.MOYSCD, WK05.MOYSKBN, WK05.MOYSSTDT, WK05.MOYSRBAN, WK05.SHUNO, WK05.TSHUFLG, WK05.MYOSNNSTDT, WK05.MYOSNNEDDT, WK05.NENMATKBN, WK05.JLSTCREFLG, WK05.JLSTCREDT, WK05.JHTSUINDT, WK05.WEEKHTDT, WK05.QADEVSTDT, WK05.QADEVEDFLG, WK05.TENGPCD, WK05.KYOSEIFLG, WK05.KANRINO, WK05.KANRIENO, WK05.BMNCD, WK05.SHNCD, WK05.REIDMYKBN, WK05.NNSTDT, WK05.NNEDDT, WK05.JUFLG, WK05.JUHTDT, WK05.BINKBN, WK05.NNSLIDE, WK05.CUTTENFLG, WK05.SHUDENFLG, WK05.TENCD, WK05.NNDT, WK05.HSUU, WK05.HTASU, WK05.PTNNO, WK05.TSEIKBN, WK05.ZJSKFLG, WK05.NNWEEKHTDT, WK05.QASYUKBN, CASE WHEN QAGP.MOYSKBN IS NOT NULL THEN QAGP.LDSYFLG ELSE WK05.LDSYFLG END AS LDSYFLG, CASE WHEN QATEN.MOYSKBN IS NOT NULL THEN CASE WHEN QATEN.LDTENKBN = 0 THEN CASE WHEN QATEN.MBSYFLG = 1 THEN 1 WHEN QATEN.MBSYFLG = 2 THEN 0 END WHEN QATEN.LDTENKBN = 1 THEN CASE WHEN QATEN.MBSYFLG = 1 THEN 2 WHEN QATEN.MBSYFLG = 2 THEN 3 END END ELSE WK05.MBSYFLG END AS MBSYFLG, CASE WHEN WK05.QASYUKBN = 4 THEN CASE WHEN QASHN.ITMSELKBN = 0 THEN 2 ELSE 1 END ELSE WK05.ITMSELKBN END AS ITMSELKBN, WK05.GTSIMECHGKBN, WK05.GTSIMEOKFLG, WK05.SENDFLG, WK05.UPDKBN FROM INAIF.AN_NOUNYU_BFR WK05 LEFT OUTER JOIN INATK2.TOKTG_QATEN QATEN ON WK05.MOYSKBN = QATEN.MOYSKBN AND WK05.MOYSSTDT = QATEN.MOYSSTDT AND WK05.MOYSRBAN = QATEN.MOYSRBAN AND WK05.TENGPCD = QATEN.TENGPCD AND WK05.TENCD = QATEN.TENCD LEFT OUTER JOIN INATK2.TOKTG_QAGP QAGP ON WK05.MOYSKBN = QAGP.MOYSKBN AND WK05.MOYSSTDT = QAGP.MOYSSTDT AND WK05.MOYSRBAN = QAGP.MOYSRBAN AND WK05.TENGPCD = QAGP.TENGPCD LEFT OUTER JOIN INATK2.TOKTG_QASHN QASHN ON WK05.MOYSKBN = QASHN.MOYSKBN AND WK05.MOYSSTDT = QASHN.MOYSSTDT AND WK05.MOYSRBAN = QASHN.MOYSRBAN AND WK05.TENGPCD = QASHN.TENGPCD AND WK05.BMNCD = QASHN.BMNCD AND WK05.KANRINO = QASHN.KANRINO LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE WK05.JLSTCREFLG = 0 AND WK05.JHTSUINDT = 0 AND WK05.QADEVSTDT <= SBD.DT_INT) WK09;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_AFT;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
