REM [100][BFC01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0100
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFBUO013

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(催しコード)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.MOYSKBN, 1, 0) || LPAD(T1.MOYSSTDT, 6, 0) || LPAD(T1.MOYSRBAN, 3, 0) || LPAD(COALESCE(T1.SHUNO, 0), 4, 0) || RPAD(COALESCE(T1.MOYKN, ''), 20, '　') || RPAD(COALESCE(T1.MOYAN, ''), 20, ' ') || LPAD(COALESCE(T1.NENMATKBN, 0), 1, 0) || LPAD(COALESCE(T1.HBSTDT, '0'), 8, '0') || LPAD(COALESCE(T1.HBEDDT, '0'), 8, '0') || LPAD(COALESCE(T1.NNSTDT, '0'), 8, '0') || LPAD(COALESCE(T1.NNEDDT, '0'), 8, '0') || LPAD(COALESCE(T1.NNSTDT_TGF, 0), 8, '0') || LPAD(COALESCE(T1.NNEDDT_TGF, 0), 8, '0') || LPAD(COALESCE(T1.PLUSDDT, '0'), 8, '0') || '0' || LPAD(T1.UPDKBN, 1, 0) || LPAD(T1.SENDFLG, 1, 0) || RPAD(T1.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM INATK2.TOKMOYCD T1 WHERE T1.UPDKBN <> 1 ORDER BY T1.MOYSKBN, T1.MOYSSTDT, T1.MOYSRBAN" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
