REM [103][BFC07]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0103
SET EXPFILE=%~DP0..\exp\%OUTFILENAME%
SET HULFTID=VFBUO016

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(数量ランクマスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.BMNCD, 3, 0) || LPAD(T1.SRYPTNNO, 3, 0) || RPAD(T1.TENRANK, 1, ' ') || LPAD(COALESCE(T1.SURYO, 0), 5, 0) || LPAD(T1.SENDFLG, 1, 0) || RPAD(T1.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 8, 0) AS '1' FROM INATK2.TOKSRYRANK T1 WHERE EXISTS (SELECT * FROM INATK2.TOKSRPTN T2 WHERE T1.BMNCD = T2.BMNCD AND T1.SRYPTNNO = T2.SRYPTNNO AND T2.UPDKBN <> 1) ORDER BY T1.BMNCD, T1.SRYPTNNO, T1.TENRANK" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
