REM [107][BFC02]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET EXPFILENAME=%~DP0..\exp\0107
SET OUTFILENAME=0107
SET HULFTID=VFBUO021

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(全特アンケート有基本)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.MOYSKBN, 1, 0) || LPAD(T1.MOYSSTDT, 6, 0) || LPAD(T1.MOYSRBAN, 3, 0) || LPAD(COALESCE(T1.HBOKUREFLG, 0), 1, 0) || LPAD(COALESCE(T1.GTSIMEDT, 0), 8, 0) || LPAD(COALESCE(T1.GTSIMEFLG, 0), 1, 0) || LPAD(COALESCE(T1.LSIMEDT, 0), 8, 0) || LPAD(COALESCE(T1.QAYYYYMM, 0), 6, 0) || LPAD(COALESCE(T1.QAENO, 0), 2, 0) || LPAD(COALESCE(T1.QACREDT, 0), 8, 0) || LPAD(COALESCE(T1.QARCREDT, 0), 8, 0) || LPAD(COALESCE(T1.JLSTCREFLG, 0), 1, 0) || LPAD(COALESCE(T1.HNCTLFLG, 0), 1, 0) || LPAD(COALESCE(T1.TPNG1FLG, 0), 1, 0) || LPAD(COALESCE(T1.TPNG2FLG, 0), 1, 0) || LPAD(COALESCE(T1.TPNG3FLG, 0), 1, 0) || LPAD(COALESCE(T1.SIMEFLG1_LD, 0), 1, 0) || LPAD(COALESCE(T1.SIMEFLG2_LD, 0), 1, 0) || LPAD(COALESCE(T1.SIMEFLG_MB, 0), 1, 0) || LPAD(COALESCE(T1.QADEVSTDT, 0), 8, 0) || LPAD(T1.UPDKBN, 1, 0) || LPAD(T1.SENDFLG, 1, 0) || RPAD(T1.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INATK2.TOKTG_KHN T1 WHERE T1.UPDKBN <> 1 ORDER BY T1.MOYSKBN, T1.MOYSSTDT, T1.MOYSRBAN" >%EXPFILENAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
