REM [121][BFC24]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0121
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFBUO035

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(分類割引＿企画)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.KKKNO, 4, 0) || RPAD(COALESCE(T1.BTKN, ''), 20, '　') || LPAD(COALESCE(T1.HBSTDT, 0), 8, 0) || LPAD(COALESCE(T1.HBEDDT, 0), 8, 0) || LPAD(COALESCE(T1.MOYSKBN, 0), 1, 0) || LPAD(COALESCE(T1.MOYSSTDT, 0), 6, 0) || LPAD(COALESCE(T1.MOYSRBAN, 0), 3, 0) || LPAD(COALESCE(T1.BMNCD, 0), 3, 0) || LPAD(COALESCE(T1.DAICD, 0), 2, 0) || LPAD(COALESCE(T1.CHUCD, 0), 2, 0) || LPAD(COALESCE(T1.SHOCD, 0), 2, 0) || LPAD(COALESCE(T1.WARIRT, 0), 2, 0) || LPAD(COALESCE(T1.WARIGK, 0), 6, 0) || LPAD(COALESCE(T1.ICHIRTGK, 0), 6, 0) || LPAD(COALESCE(T1.RANKNO_ADD, 0), 3, 0) || LPAD(COALESCE(T1.RANKNO_DEL, 0), 3, 0) || RPAD(COALESCE(T1.TENATSUK_ARR, ''), 400, ' ') || LPAD(COALESCE(T1.UPDKBN, 0), 1, 0) || LPAD(COALESCE(T1.SENDFLG, 0), 1, 0) || RPAD(COALESCE(T1.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 0), 8, 0) || LPAD(COALESCE(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 0), 8, 0) AS '1' FROM INATK2.TOKBT_KKK T1 WHERE T1.UPDKBN <> 1 ORDER BY T1.KKKNO" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
