REM [124][BFC33]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET EXPFILENAME=%~DP0..\exp\0124
SET OUTFILENAME=0124
SET HULFTID=VFBUO038

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(新店改装店発注＿発注)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.INPUTNO, 5, 0) || LPAD(COALESCE(T1.TENNO, 0), 3, 0) || LPAD(COALESCE(T1.HTDT, 0), 8, 0) || LPAD(COALESCE(T1.NNDT, 0), 8, 0) || LPAD(COALESCE(T1.SHNKBN, 0), 1, 0) || LPAD(COALESCE(T1.KSPAGE, 0), 8, 0) || LPAD(COALESCE(T1.BDENKBN, 0), 1, 0) || LPAD(COALESCE(T1.UPDKBN, 0), 1, 0) || LPAD(COALESCE(T1.SENDFLG, 0), 1, 0) || RPAD(COALESCE(T1.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 0), 8, 0) || LPAD(COALESCE(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 0), 8, 0) AS '1' FROM INATK2.HATSK T1 WHERE T1.UPDKBN <> 1 ORDER BY T1.INPUTNO" >%EXPFILENAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
