REM [125][BFC34]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET EXPFILENAME=%~DP0..\exp\0125
SET OUTFILENAME=0125
SET HULFTID=VFBUO039

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(新店改装店発注＿商品)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.INPUTNO, 5, 0) || LPAD(T1.KANRINO, 5, 0) || RPAD(COALESCE(T1.SHNCD, ''), 14, ' ') || LPAD(COALESCE(T1.SURYO, 0), 5, 0) || LPAD(COALESCE(T1.SENDFLG, 0), 1, 0) || RPAD(COALESCE(T1.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 0), 8, 0) || LPAD(COALESCE(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 0), 8, 0) AS '1' FROM INATK2.HATSK_SHN T1 INNER JOIN INATK2.HATSK T2 ON T1.INPUTNO = T2.INPUTNO AND T2.UPDKBN <> 1 ORDER BY T1.INPUTNO, T1.KANRINO" >%EXPFILENAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
