REM [140][BFB01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_NEQ union INAIF.AN_ZW_NOUNYU_NEQ → INAWK.ANWK12_NOU_N ロード処理（対象納入データ(ア無)ワーク）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.ANWK12_NOU_N;INSERT IGNORE INTO INAWK.ANWK12_NOU_N SELECT ANWK.MOYSKBN, ANWK.MOYSSTDT, ANWK.MOYSRBAN, ANWK.BMNCD, ANWK.KANRINO, MAX(ANWK.KANRIENO) AS KANRIENO FROM (SELECT * FROM INAIF.AN_NOUNYU_NEQ UNION ALL SELECT * FROM INAIF.AN_ZW_NOUNYU_NEQ) ANWK WHERE ANWK.NNDT > 0 AND ANWK.UPDKBN <> 1 AND ((ANWK.GTSIMECHGKBN = 1 AND ANWK.GTSIMEOKFLG = 1) OR (ANWK.GTSIMECHGKBN IN (2, 4) AND ANWK.GTSIMEOKFLG = 1) OR (ANWK.GTSIMECHGKBN = 3 AND ANWK.GTSIMEOKFLG = 0) OR (ANWK.GTSIMECHGKBN = 0 AND ANWK.GTSIMEOKFLG = 0)) GROUP BY MOYSKBN, MOYSSTDT, MOYSRBAN, KANRINO, BMNCD;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.ANWK12_NOU_N;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
