REM [][TMWK_A11TC34]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INATK2.TOKRS_SHN + INATK2.TOKRS_KKK → INAWK.TMWK_A11TC34 ロード処理（展開用冷凍食品ワーク）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TMWK_A11TC34;INSERT IGNORE INTO INAWK.TMWK_A11TC34  WITH RSHN AS (SELECT * FROM (SELECT ROW_NUMBER() OVER (PARTITION BY HBSTDT, BMNCD, WRITUKBN, DUMMYCD, SHNCD ORDER BY BAIKAAM) AS RNO, T1.* FROM INATK2.TOKRS_SHN T1 WHERE UPDKBN = 0) TS WHERE RNO = 1) SELECT DISTINCT RSHN.BMNCD, RSHN.WRITUKBN, RSHN.DUMMYCD, RSHN.SHNCD, RSHN.HBSTDT, KKK.HBENDT, RSHN.SEICUTKBN, RSHN.KANRINO, RSHN.MAKERKN, RSHN.SHNKN, RSHN.KIKKN, RSHN.IRISU, RSHN.BAIKAAM, RSHN.GENKAAM FROM RSHN INNER JOIN (SELECT KKK1.HBSTDT, KKK1.BMNCD, CASE WHEN MIN(KKK2.HBSTDT) IS NOT NULL THEN CAST(DATE_FORMAT(CAST(CAST(MIN(KKK2.HBSTDT) AS CHAR) AS DATETIME) - INTERVAL 1 DAY, '%%Y%%m%%d') AS SIGNED) ELSE 99999999 END AS HBENDT FROM INATK2.TOKRS_KKK KKK1 LEFT OUTER JOIN INATK2.TOKRS_KKK KKK2 ON KKK1.BMNCD = KKK2.BMNCD AND KKK1.HBSTDT < KKK2.HBSTDT GROUP BY KKK1.HBSTDT, KKK1.BMNCD) KKK ON RSHN.HBSTDT = KKK.HBSTDT AND RSHN.BMNCD = KKK.BMNCD;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.TMWK_A11TC34;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
