REM [][TMWK44_A11TC05]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAWK.TMWK44_A11TC05(生活応援 回答用販売データ_催し付加) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAWK.TMWK44_A11TC05 IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAWK.TMWK44_A11TC05 ロード処理（生活応援 回答用販売データ_催し付加）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TMWK44_A11TC05;INSERT IGNORE INTO INAWK.TMWK44_A11TC05 SELECT SSHN.MOYSKBN, SSHN.MOYSSTDT, SSHN.MOYSRBAN, 0, TC01.HBSTDT, TC01.HBEDDT, 0, 0, 0, 0, CASE WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'A' THEN SSHN.A_RANKNO WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'B' THEN SSHN.B_RANKNO WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'C' THEN SSHN.C_RANKNO END, 0, SSHN.KANRINO, 0, SSHN.BMNCD, SSHN.SHNCD, 0, MOYO.HBSTDT, MOYO.HBEDDT, 0, 0, SSHN.GENKAAM, 0, SSHN.A_BAIKAAM, SSHN.B_BAIKAAM, SSHN.C_BAIKAAM, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, CASE WHEN SHN_Y.SHNCD IS NOT NULL THEN SHN_Y.TEIKEIKBN WHEN SHN.SHNCD IS NOT NULL THEN SHN.TEIKEIKBN ELSE 0 END, CASE WHEN SRC_Y.SHNCD IS NOT NULL THEN SRC_Y.SOURCEKBN1 WHEN SRC.SHNCD IS NOT NULL THEN SRC.SOURCEKBN1 ELSE 0 END, CASE WHEN SRC_Y.SHNCD IS NOT NULL THEN SRC_Y.SRCCD1 WHEN SRC.SHNCD IS NOT NULL THEN SRC.SRCCD1 ELSE '0' END, CASE WHEN SRC_Y.SHNCD IS NOT NULL THEN SRC_Y.SOURCEKBN2 WHEN SRC.SHNCD IS NOT NULL THEN SRC.SOURCEKBN2 ELSE 0 END, CASE WHEN SRC_Y.SHNCD IS NOT NULL THEN SRC_Y.SRCCD2 WHEN SRC.SHNCD IS NOT NULL THEN SRC.SRCCD2 ELSE '0' END, CASE WHEN SHN_Y.SHNCD IS NOT NULL THEN SHN_Y.URICD WHEN SHN.SHNCD IS NOT NULL THEN SHN.URICD ELSE 0 END, NUM.SEQ, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, CASE WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'A' THEN '1' WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'B' THEN '2' WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'C' THEN '3' END, 1, CASE WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'A' THEN SSHN.A_BAIKAAM WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'B' THEN SSHN.B_BAIKAAM WHEN SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) = 'C' THEN SSHN.C_BAIKAAM END, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, TC01.MOYKN, TC01.MOYAN, TC01.PLUSDDT FROM INATK2.TOKSO_SHN SSHN INNER JOIN INATK2.TOKMOYCD MOYO ON SSHN.MOYSKBN = MOYO.MOYSKBN AND SSHN.MOYSSTDT = MOYO.MOYSSTDT AND SSHN.MOYSRBAN = MOYO.MOYSRBAN AND MOYO.UPDKBN <> 1 AND SSHN.UPDKBN <> 1 AND SSHN.TENATSUK_ARR <> '' INNER JOIN INAPARM.MSTNUMS NUM ON 1 = 1 AND NUM.SEQ BETWEEN 1 AND 400 INNER JOIN INAWK.TMWK_A11TC01_S TC01 ON SSHN.MOYSKBN = TC01.MOYSKBN AND SSHN.MOYSSTDT = TC01.MOYSSTDT AND SSHN.MOYSRBAN = TC01.MOYSRBAN LEFT OUTER JOIN INAWK.TMWK_MSTSHN_Y SHN_Y ON SSHN.SHNCD = SHN_Y.SHNCD AND MOYO.HBSTDT BETWEEN SHN_Y.YOYAKUDT AND SHN_Y.ENDDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON SSHN.SHNCD = SHN.SHNCD LEFT OUTER JOIN INAWK.TMWK_MSTSRCCD_Y SRC_Y ON SSHN.SHNCD = SRC_Y.SHNCD AND MOYO.HBSTDT BETWEEN SRC_Y.YOYAKUDT AND SRC_Y.ENDDT LEFT OUTER JOIN INAWK.TMWK_MSTSRCCD SRC ON SSHN.SHNCD = SRC.SHNCD WHERE SUBSTR(SSHN.TENATSUK_ARR, 1 + (NUM.SEQ - 1), 1) <> ' ';COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.TMWK44_A11TC05;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
