REM [][TMWK_A11TC01_S]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAWK.TMWK_A11TC01_S(変更分生活応援催しコード) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAWK.TMWK_A11TC01_S IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAWK.TMWK_A11TC01_S ロード処理（変更分生活応援催しコード）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TMWK_A11TC01_S;INSERT IGNORE INTO INAWK.TMWK_A11TC01_S SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, MOYKN, MOYAN, HBSTDT, HBEDDT, PLUSDDT FROM INATK2.TOKMOYCD MOYO WHERE MOYO.UPDKBN <> 1 AND MOYO.MOYSKBN = 5 AND MOYO.HBEDDT >= (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY' AND ACTIVEFLG = 1);COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.TMWK_A11TC01_S;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
