REM [140][BFB01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.TMWK41_A11TC05_OUEN テーブルクリア
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TMWK41_A11TC05_OUEN;COMMIT" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAWK.TMWK41_A11TC05_OUEN ロード処理（回答用販売データ_OUEN）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.TMWK41_A11TC05_OUEN WITH SYORI AS (SELECT CAST(DATE_FORMAT(SBD.DT - INTERVAL 10 DAY, '%%Y%%m%%d') AS SIGNED) AS DT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY') SELECT WK41.*, OUEN41.CNT, CASE WHEN TKANPLUKBN = 2 THEN WK41.CBAIKAKG ELSE WK41.CBAIKA END AS BAIKA, WK41.KANRINO AS SORTKEY1, WK41.TENGPCD AS SORTKEY2, WK41.TENCD AS SORTKEY3 FROM INAWK.TMWK41_A11TC05 WK41 INNER JOIN INAWK.TMWK41_A11TC05_01 OUEN41 ON WK41.MOYSKBN = OUEN41.MOYSKBN AND WK41.MOYSSTDT = OUEN41.MOYSSTDT AND WK41.MOYSRBAN = OUEN41.MOYSRBAN AND WK41.SHNCD = OUEN41.SHNCD AND WK41.PLUSNDFLG = 0 AND WK41.HBSTDT <> 0 AND WK41.REIDMYKBN IN (0, 2) AND WK41.UPDKBN <> 1 AND WK41.MOHBEDDT >= (SELECT DT FROM SYORI) UNION ALL SELECT WK42.*, OUEN42.CNT, CASE WHEN TKANPLUKBN = 2 THEN WK42.CBAIKA WHEN WK42.QASYUKBN IN (1, 2, 4) THEN CASE WHEN WK42.BAIKASELKBN = 2 THEN CASE WHEN WK42.KO_B_BAIKAAN = 0 THEN WK42.CBAIKA ELSE WK42.KO_B_BAIKAAN END WHEN WK42.BAIKASELKBN = 3 THEN CASE WHEN WK42.KO_C_BAIKAAN = 0 THEN WK42.CBAIKA ELSE WK42.KO_C_BAIKAAN END ELSE CASE WHEN WK42.KO_A_BAIKAAN = 0 THEN WK42.CBAIKA ELSE WK42.KO_A_BAIKAAN END END WHEN WK42.QASYUKBN = 3 THEN WK42.CBAIKA ELSE 0 END AS BAIKA, WK42.TENGPCD AS SORTKEY1, WK42.TENCD AS SORTKEY2, WK42.KANRINO AS SORTKEY3 FROM INAWK.TMWK42_A11TC05 WK42 INNER JOIN INAWK.TMWK42_A11TC05_01 OUEN42 ON WK42.MOYSKBN = OUEN42.MOYSKBN AND WK42.MOYSSTDT = OUEN42.MOYSSTDT AND WK42.MOYSRBAN = OUEN42.MOYSRBAN AND WK42.SHNCD = OUEN42.SHNCD AND WK42.PLUSNDFLG = 0 AND WK42.HBSTDT <> 0 AND WK42.REIDMYKBN IN (0, 2) AND WK42.UPDKBN <> 1 AND WK42.MOHBEDDT >= (SELECT DT FROM SYORI) UNION ALL SELECT WK48.*, OUEN48.CNT, WK48.CBAIKA AS BAIKA, WK48.KANRINO AS SORTKEY1, WK48.TENGPCD AS SORTKEY2, WK48.TENCD AS SORTKEY3 FROM INAWK.TMWK48_A11TC05 WK48 INNER JOIN INAWK.TMWK48_A11TC05_01 OUEN48 ON WK48.MOYSKBN = OUEN48.MOYSKBN AND WK48.MOYSSTDT = OUEN48.MOYSSTDT AND WK48.MOYSRBAN = OUEN48.MOYSRBAN AND WK48.SHNCD = OUEN48.SHNCD AND WK48.UPDKBN <> 1 AND WK48.HBSTDT <> 0 AND WK48.MOHBEDDT >= (SELECT DT FROM SYORI);COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.TMWK41_A11TC05_OUEN;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
