REM [][TMWK42_A11TC05]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAWK.TMWK42_A11TC05(全特ア有 回答用販売データ_催し付加) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAWK.TMWK42_A11TC05 IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAWK.TMWK42_A11TC05 ロード処理（全特ア有 回答用販売データ_催し付加）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TMWK42_A11TC05;INSERT IGNORE INTO INAWK.TMWK42_A11TC05 SELECT ASHN.MOYSKBN, ASHN.MOYSSTDT, ASHN.MOYSRBAN, ASHN.BMNO, TC01.HBSTDT, TC01.HBEDDT, ASHN.HBOKUREFLG, ASHN.JLSTCREDT, ASHN.QADEVSTDT, ASHN.QADEVENDFLG, ASHN.TENGPCD, ASHN.KYOSEIFLG, ASHN.KANRINO, ASHN.KANRIENO, ASHN.BMNCD, ASHN.SHNCD, ASHN.ADDSHUKBN, ASHN.HBSTDT, ASHN.HBEDDT, ASHN.REIDMYKBN, ASHN.HBSLIDEFLG, ASHN.GENKAAM, ASHN.GENKARITU, ASHN.A_BAIKAAM, ASHN.B_BAIKAAM, ASHN.C_BAIKAAM, ASHN.A_GENKAAM_1KG, ASHN.B_GENKAAM_1KG, ASHN.C_GENKAAM_1KG, ASHN.A_WRITUKBN, ASHN.B_WRITUKBN, ASHN.C_WRITUKBN, ASHN.TKANPLUKBN, ASHN.KO_A_BAIKAAN, ASHN.BD1_A_BAIKAAN, ASHN.BD2_A_BAIKAAN, ASHN.KO_B_BAIKAAN, ASHN.BD1_B_BAIKAAN, ASHN.BD2_B_BAIKAAN, ASHN.KO_C_BAIKAAN, ASHN.BD1_C_BAIKAAN, ASHN.BD2_C_BAIKAAN, ASHN.PLUSNDFLG, ASHN.TEIKEIKBN, ASHN.SOURCEKBN1, ASHN.SRCCD1, ASHN.SOURCEKBN2, ASHN.SRCCD2, ASHN.URICD, ASHN.TENCD, CAST(DATE_FORMAT(ASHN.HBDT1, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT2, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT3, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT4, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT5, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT6, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT7, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT8, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT9, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(ASHN.HBDT10, '%%Y%%m%%d') AS SIGNED), ASHN.QASYUKBN, ASHN.LTENSAIFLG, ASHN.HANKAISIFLG, ASHN.TENSAIFLG, CAST(ASHN.BAIKASELKBN AS CHAR (1)), ASHN.SHOHINSEL, ASHN.CBAIKA, ASHN.SBAIBL1, ASHN.SBAIBL2, ASHN.CBAIKAKG, ASHN.DATAKBN, ASHN.GTSIMECHGKBN, ASHN.GTSIMEOKFLG, ASHN.SENDFLG, ASHN.UPDKBN, 0, 0, TC01.MOYKN, TC01.MOYAN, TC01.PLUSDDT FROM (SELECT * FROM INAWK.TMWK40_A11TC13_A UNION ALL SELECT A.MOYSKBN, A.MOYSSTDT, A.MOYSRBAN, BMNO, MOHBSTDT, MOHBEDDT, HBOKUREFLG, JLSTCREDT, QADEVSTDT, QADEVENDFLG, A.TENGPCD, KYOSEIFLG, A.KANRINO, A.KANRIENO, A.BMNCD, SHNCD, ADDSHUKBN, HBSTDT, HBEDDT, REIDMYKBN, HBSLIDEFLG, GENKAAM, GENKARITU, A_BAIKAAM, B_BAIKAAM, C_BAIKAAM, A_GENKAAM_1KG, B_GENKAAM_1KG, C_GENKAAM_1KG, A_WRITUKBN, B_WRITUKBN, C_WRITUKBN, TKANPLUKBN, KO_A_BAIKAAN, BD1_A_BAIKAAN, BD2_A_BAIKAAN, KO_B_BAIKAAN, BD1_B_BAIKAAN, BD2_B_BAIKAAN, KO_C_BAIKAAN, BD1_C_BAIKAAN, BD2_C_BAIKAAN, PLUSNDFLG, TEIKEIKBN, SOURCEKBN1, SRCCD1, SOURCEKBN2, SRCCD2, URICD, A.TENCD, CAST(NULL AS DATE) AS HBDT1, CAST(NULL AS DATE) AS HBDT2, CAST(NULL AS DATE) AS HBDT3, CAST(NULL AS DATE) AS HBDT4, CAST(NULL AS DATE) AS HBDT5, CAST(NULL AS DATE) AS HBDT6, CAST(NULL AS DATE) AS HBDT7, CAST(NULL AS DATE) AS HBDT8, CAST(NULL AS DATE) AS HBDT9, CAST(NULL AS DATE) AS HBDT10, QASYUKBN, LTENSAIFLG, HANKAISIFLG, TENSAIFLG, URIASELKBN AS BAIKASELKBN, ITMSELKBN AS SHOHINSEL, CBAIKA, SBAIBL1, SBAIBL2, CBAIKAKG, DATAKBN, GTSIMECHGKBN, GTSIMEOKFLG, SENDFLG, UPDKBN FROM INAIF.AN_HANBAI_AFT A INNER JOIN (SELECT A.MOYSKBN, A.MOYSSTDT, A.MOYSRBAN, A.TENGPCD, A.TENCD, A.BMNCD, A.KANRINO, MAX(A.KANRIENO) AS KANRIENO FROM INAIF.AN_HANBAI_AFT A WHERE NOT (A.GTSIMECHGKBN IN (1, 2, 4) AND A.GTSIMEOKFLG = 0) GROUP BY A.MOYSKBN, A.MOYSSTDT, A.MOYSRBAN, A.TENGPCD, A.TENCD, A.BMNCD, A.KANRINO) B ON A.MOYSKBN = B.MOYSKBN AND A.MOYSSTDT = B.MOYSSTDT AND A.MOYSRBAN = B.MOYSRBAN AND A.TENGPCD = B.TENGPCD AND A.TENCD = B.TENCD AND A.BMNCD = B.BMNCD AND A.KANRINO = B.KANRINO AND A.KANRIENO = B.KANRIENO WHERE NOT (A.GTSIMECHGKBN = 3 AND A.GTSIMEOKFLG = 1) AND A.REIDMYKBN <> 1) ASHN INNER JOIN INAWK.TMWK_A11TC01_A TC01 ON ASHN.MOYSKBN = TC01.MOYSKBN AND ASHN.MOYSSTDT = TC01.MOYSSTDT AND ASHN.MOYSRBAN = TC01.MOYSRBAN WHERE NOT EXISTS (SELECT CRS.* FROM INATK2.TOKCHIRASBMN CRS WHERE ASHN.MOYSKBN = CRS.MOYSKBN AND ASHN.MOYSSTDT = CRS.MOYSSTDT AND ASHN.MOYSRBAN = CRS.MOYSRBAN AND ASHN.BMNCD = CRS.BMNCD);COMMIT; " >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.TMWK42_A11TC05;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
