REM [][TMWK40_A11TC13_N]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAWK.TMWK40_A11TC13_N(回答用販売データ_冷食展開(ア無)) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAWK.TMWK40_A11TC13_N IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAWK.TMWK40_A11TC13_N ロード処理（回答用販売データ_冷食展開(ア無)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TMWK40_A11TC13_N;INSERT IGNORE INTO INAWK.TMWK40_A11TC13_N SELECT RTAN2.MOYSKBN, RTAN2.MOYSSTDT, RTAN2.MOYSRBAN, RTAN2.BMNO, RTAN2.MOHBSTDT, RTAN2.MOHBEDDT, RTAN2.HBOKUREFLG, RTAN2.JLSTCREDT, RTAN2.QADEVSTDT, RTAN2.QADEVENDFLG, RTAN2.TENGPCD, RTAN2.KYOSEIFLG, RTAN2.KANRINO, RTAN2.KANRIENO, RTAN2.BMNCD, RTAN2.SHNCD, RTAN2.ADDSHUKBN, RTAN2.HBSTDT, RTAN2.HBEDDT, RTAN2.REIDMYKBN, RTAN2.HBSLIDEFLG, RTAN2.GENKAAM, RTAN2.GENKARITU, RTAN2.A_BAIKAAM, RTAN2.B_BAIKAAM, RTAN2.C_BAIKAAM, RTAN2.A_GENKAAM_1KG, RTAN2.B_GENKAAM_1KG, RTAN2.C_GENKAAM_1KG, RTAN2.A_WRITUKBN, RTAN2.B_WRITUKBN, RTAN2.C_WRITUKBN, RTAN2.TKANPLUKBN, RTAN2.KO_A_BAIKAAN, RTAN2.BD1_A_BAIKAAN, RTAN2.BD2_A_BAIKAAN, RTAN2.KO_B_BAIKAAN, RTAN2.BD1_B_BAIKAAN, RTAN2.BD2_B_BAIKAAN, RTAN2.KO_C_BAIKAAN, RTAN2.BD1_C_BAIKAAN, RTAN2.BD2_C_BAIKAAN, RTAN2.PLUSNDFLG, CASE WHEN SHN_Y.SHNCD IS NOT NULL THEN SHN_Y.TEIKEIKBN WHEN SHN.SHNCD IS NOT NULL THEN SHN.TEIKEIKBN ELSE 0 END, CASE WHEN SRC_Y.SHNCD IS NOT NULL THEN SRC_Y.SOURCEKBN1 WHEN SRC.SHNCD IS NOT NULL THEN SRC.SOURCEKBN1 ELSE 0 END, CASE WHEN SRC_Y.SHNCD IS NOT NULL THEN SRC_Y.SRCCD1 WHEN SRC.SHNCD IS NOT NULL THEN SRC.SRCCD1 ELSE '0' END, CASE WHEN SRC_Y.SHNCD IS NOT NULL THEN SRC_Y.SOURCEKBN2 WHEN SRC.SHNCD IS NOT NULL THEN SRC.SOURCEKBN2 ELSE 0 END, CASE WHEN SRC_Y.SHNCD IS NOT NULL THEN SRC_Y.SRCCD2 WHEN SRC.SHNCD IS NOT NULL THEN SRC.SRCCD2 ELSE '0' END, CASE WHEN SHN_Y.SHNCD IS NOT NULL THEN SHN_Y.URICD WHEN SHN.SHNCD IS NOT NULL THEN SHN.URICD ELSE 0 END, RTAN2.TENCD, CAST(RTAN2.HBDT1 AS DATE), CAST(RTAN2.HBDT2 AS DATE), CAST(RTAN2.HBDT3 AS DATE), CAST(RTAN2.HBDT4 AS DATE), CAST(RTAN2.HBDT5 AS DATE), CAST(RTAN2.HBDT6 AS DATE), CAST(RTAN2.HBDT7 AS DATE), CAST(RTAN2.HBDT8 AS DATE), CAST(RTAN2.HBDT9 AS DATE), CAST(RTAN2.HBDT10 AS DATE), RTAN2.QASYUKBN, RTAN2.LTENSAIFLG, RTAN2.HANKAISIFLG, RTAN2.TENSAIFLG, RTAN2.BAIKASELKBN, CAST(RTAN2.SHOHINSEL AS SIGNED), RTAN2.CBAIKA, RTAN2.SBAIBL1, RTAN2.SBAIBL2, RTAN2.CBAIKAKG, RTAN2.DATAKBN, RTAN2.GTSIMECHGKBN, RTAN2.GTSIMEOKFLG, RTAN2.SENDFLG, RTAN2.UPDKBN FROM (SELECT ROW_NUMBER() OVER (PARTITION BY AN2.MOYSKBN, AN2.MOYSSTDT, AN2.MOYSRBAN, AN2.TENGPCD, AN2.TENCD, AN2.BMNCD, AN2.KANRINO, AN2.KANRIENO, AN2.TENCD, CASE WHEN RSHN.BMNCD IS NOT NULL THEN RSHN.SHNCD ELSE AN2.SHNCD END ORDER BY CASE WHEN RSHN.BMNCD IS NOT NULL THEN RSHN.HBSTDT ELSE AN2.HBSTDT END) AS RNO, AN2.MOYSKBN, AN2.MOYSSTDT, AN2.MOYSRBAN, AN2.BMNO, AN2.MOHBSTDT, AN2.MOHBEDDT, AN2.HBOKUREFLG, AN2.JLSTCREDT, AN2.QADEVSTDT, AN2.QADEVENDFLG, AN2.TENGPCD, AN2.KYOSEIFLG, AN2.KANRINO, AN2.KANRIENO, AN2.BMNCD, RSHN.SHNCD, AN2.ADDSHUKBN, AN2.HBSTDT, AN2.HBEDDT, 2 AS REIDMYKBN, AN2.HBSLIDEFLG, RSHN.GENKAAM, AN2.GENKARITU, AN2.A_BAIKAAM, AN2.B_BAIKAAM, AN2.C_BAIKAAM, AN2.A_GENKAAM_1KG, AN2.B_GENKAAM_1KG, AN2.C_GENKAAM_1KG, AN2.A_WRITUKBN, AN2.B_WRITUKBN, AN2.C_WRITUKBN, AN2.TKANPLUKBN, AN2.KO_A_BAIKAAN, AN2.BD1_A_BAIKAAN, AN2.BD2_A_BAIKAAN, AN2.KO_B_BAIKAAN, AN2.BD1_B_BAIKAAN, AN2.BD2_B_BAIKAAN, AN2.KO_C_BAIKAAN, AN2.BD1_C_BAIKAAN, AN2.BD2_C_BAIKAAN, AN2.PLUSNDFLG, AN2.TEIKEIKBN, AN2.SOURCEKBN1, AN2.SRCCD1, AN2.SOURCEKBN2, AN2.SRCCD2, AN2.URICD, AN2.TENCD, CAST(NULL AS DATE) AS HBDT1, CAST(NULL AS DATE) AS HBDT2, CAST(NULL AS DATE) AS HBDT3, CAST(NULL AS DATE) AS HBDT4, CAST(NULL AS DATE) AS HBDT5, CAST(NULL AS DATE) AS HBDT6, CAST(NULL AS DATE) AS HBDT7, CAST(NULL AS DATE) AS HBDT8, CAST(NULL AS DATE) AS HBDT9, CAST(NULL AS DATE) AS HBDT10, AN2.QASYUKBN, AN2.LTENSAIFLG, AN2.HANKAISIFLG, AN2.TENSAIFLG, AN2.URIASELKBN AS BAIKASELKBN, NULL AS SHOHINSEL, CASE WHEN RSHN.SHNCD IS NOT NULL THEN RSHN.BAIKAAM END AS CBAIKA, AN2.SBAIBL1, AN2.SBAIBL2, AN2.CBAIKAKG, AN2.DATAKBN, AN2.GTSIMECHGKBN, AN2.GTSIMEOKFLG, AN2.SENDFLG, AN2.UPDKBN FROM (SELECT * FROM INAIF.AN_HANBAI_NEQ WHERE DATAKBN = 2 AND REIDMYKBN = 1) AN2 INNER JOIN INAWK.TMWK_A11TC34 RSHN ON AN2.BMNCD = RSHN.BMNCD AND AN2.CBAIKA = RSHN.WRITUKBN AND AN2.SHNCD = RSHN.DUMMYCD AND (AN2.HBSTDT BETWEEN RSHN.HBSTDT AND RSHN.HBEDDT OR AN2.HBEDDT BETWEEN RSHN.HBSTDT AND RSHN.HBEDDT)) RTAN2 LEFT OUTER JOIN INAWK.TMWK_MSTSHN_Y SHN_Y ON RTAN2.SHNCD = SHN_Y.SHNCD AND RTAN2.HBSTDT BETWEEN SHN_Y.YOYAKUDT AND SHN_Y.ENDDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON RTAN2.SHNCD = SHN.SHNCD LEFT OUTER JOIN INAWK.TMWK_MSTSRCCD_Y SRC_Y ON RTAN2.SHNCD = SRC_Y.SHNCD AND RTAN2.HBSTDT BETWEEN SRC_Y.YOYAKUDT AND SRC_Y.ENDDT LEFT OUTER JOIN INAWK.TMWK_MSTSRCCD SRC ON RTAN2.SHNCD = SRC.SHNCD WHERE RNO = 1;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.TMWK40_A11TC13_N;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
