REM [][TMWK41_A11TC05]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAWK.TMWK41_A11TC05(全特ア無 回答用販売データ_催し付加) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAWK.TMWK41_A11TC05 IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAWK.TMWK41_A11TC05 ロード処理（全特ア無 回答用販売データ_催し付加）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TMWK41_A11TC05;INSERT IGNORE INTO INAWK.TMWK41_A11TC05 SELECT NSHN.MOYSKBN, NSHN.MOYSSTDT, NSHN.MOYSRBAN, NSHN.BMNO, TC01.HBSTDT, TC01.HBEDDT, NSHN.HBOKUREFLG, NSHN.JLSTCREDT, NSHN.QADEVSTDT, NSHN.QADEVENDFLG, NSHN.TENGPCD, NSHN.KYOSEIFLG, NSHN.KANRINO, NSHN.KANRIENO, NSHN.BMNCD, NSHN.SHNCD, NSHN.ADDSHUKBN, NSHN.HBSTDT, NSHN.HBEDDT, NSHN.REIDMYKBN, NSHN.HBSLIDEFLG, NSHN.GENKAAM, NSHN.GENKARITU, NSHN.A_BAIKAAM, NSHN.B_BAIKAAM, NSHN.C_BAIKAAM, NSHN.A_GENKAAM_1KG, NSHN.B_GENKAAM_1KG, NSHN.C_GENKAAM_1KG, NSHN.A_WRITUKBN, NSHN.B_WRITUKBN, NSHN.C_WRITUKBN, NSHN.TKANPLUKBN, NSHN.KO_A_BAIKAAN, NSHN.BD1_A_BAIKAAN, NSHN.BD2_A_BAIKAAN, NSHN.KO_B_BAIKAAN, NSHN.BD1_B_BAIKAAN, NSHN.BD2_B_BAIKAAN, NSHN.KO_C_BAIKAAN, NSHN.BD1_C_BAIKAAN, NSHN.BD2_C_BAIKAAN, NSHN.PLUSNDFLG, NSHN.TEIKEIKBN, NSHN.SOURCEKBN1, NSHN.SRCCD1, NSHN.SOURCEKBN2, NSHN.SRCCD2, NSHN.URICD, NSHN.TENCD, CAST(DATE_FORMAT(NSHN.HBDT1, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT2, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT3, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT4, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT5, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT6, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT7, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT8, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT9, '%%Y%%m%%d') AS SIGNED), CAST(DATE_FORMAT(NSHN.HBDT10, '%%Y%%m%%d') AS SIGNED), NSHN.QASYUKBN, NSHN.LTENSAIFLG, NSHN.HANKAISIFLG, NSHN.TENSAIFLG, CAST(NSHN.BAIKASELKBN AS CHAR (1)), NSHN.SHOHINSEL, NSHN.CBAIKA, NSHN.SBAIBL1, NSHN.SBAIBL2, NSHN.CBAIKAKG, NSHN.DATAKBN, NSHN.GTSIMECHGKBN, NSHN.GTSIMEOKFLG, NSHN.SENDFLG, NSHN.UPDKBN, 0, 0, TC01.MOYKN, TC01.MOYAN, TC01.PLUSDDT FROM (SELECT * FROM INAWK.TMWK40_A11TC13_N UNION ALL SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, BMNO, MOHBSTDT, MOHBEDDT, HBOKUREFLG, JLSTCREDT, QADEVSTDT, QADEVENDFLG, TENGPCD, KYOSEIFLG, KANRINO, KANRIENO, BMNCD, SHNCD, ADDSHUKBN, HBSTDT, HBEDDT, REIDMYKBN, HBSLIDEFLG, GENKAAM, GENKARITU, A_BAIKAAM, B_BAIKAAM, C_BAIKAAM, A_GENKAAM_1KG, B_GENKAAM_1KG, C_GENKAAM_1KG, A_WRITUKBN, B_WRITUKBN, C_WRITUKBN, TKANPLUKBN, KO_A_BAIKAAN, BD1_A_BAIKAAN, BD2_A_BAIKAAN, KO_B_BAIKAAN, BD1_B_BAIKAAN, BD2_B_BAIKAAN, KO_C_BAIKAAN, BD1_C_BAIKAAN, BD2_C_BAIKAAN, PLUSNDFLG, TEIKEIKBN, SOURCEKBN1, SRCCD1, SOURCEKBN2, SRCCD2, URICD, TENCD, CAST(NULL AS DATE) AS HBDT1, CAST(NULL AS DATE) AS HBDT2, CAST(NULL AS DATE) AS HBDT3, CAST(NULL AS DATE) AS HBDT4, CAST(NULL AS DATE) AS HBDT5, CAST(NULL AS DATE) AS HBDT6, CAST(NULL AS DATE) AS HBDT7, CAST(NULL AS DATE) AS HBDT8, CAST(NULL AS DATE) AS HBDT9, CAST(NULL AS DATE) AS HBDT10, QASYUKBN, LTENSAIFLG, HANKAISIFLG, TENSAIFLG, URIASELKBN AS BAIKASELKBN, ITMSELKBN AS SHOHINSEL, CBAIKA, SBAIBL1, SBAIBL2, CBAIKAKG, DATAKBN, GTSIMECHGKBN, GTSIMEOKFLG, SENDFLG, UPDKBN FROM INAIF.AN_HANBAI_NEQ WHERE DATAKBN = 2 AND UPDKBN <> 1 AND REIDMYKBN <> 1) NSHN INNER JOIN INAWK.TMWK_A11TC01_N TC01 ON NSHN.MOYSKBN = TC01.MOYSKBN AND NSHN.MOYSSTDT = TC01.MOYSSTDT AND NSHN.MOYSRBAN = TC01.MOYSRBAN;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.TMWK41_A11TC05;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
