REM [144][BFG01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0144
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFEUO001

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(催し送信　（ＰＬＵ）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(WK.TENCD, 3, 0) || LPAD(CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%%Y%%m%%d') AS SIGNED), 8, 0) || LPAD(CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%%H%%i') AS SIGNED), 4, 0) || ' ' || '1' || CASE WHEN WK.MOYSKBN = 1 THEN '01' WHEN WK.MOYSKBN = 2 THEN '02' WHEN WK.MOYSKBN IN (3, 4) THEN '04' WHEN WK.MOYSKBN = 5 AND WK.CNT <= 1500 THEN '05' WHEN WK.MOYSKBN = 5 AND WK.CNT > 1500 THEN '06' END || RIGHT (LPAD(WK.MOYSSTDT, 6, 0), 4) || RIGHT (LPAD(WK.MOYSRBAN, 3, 0), 2) || '   ' || RPAD(WK.MOYKN, 20, '　') || RPAD(WK.MOYAN, 20, ' ') || '                    ' || LPAD(WK.MOHBSTDT, 8, 0) || LPAD(WK.MOHBEDDT, 8, 0) || LPAD(0, 9, 0) || LPAD(0, 1, 0) || RPAD(WK.SHNCD, 13, ' ') || '             ' || LPAD(WK.HBSTDT, 8, 0) || LPAD(WK.HBEDDT, 8, 0) || LPAD(REPLACE (CAST(CAST((CASE WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) <= COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (WK.BAIKA, 0), 0) + COALESCE(TRUNCATE (CAST(WK.BAIKA * MZS1.ZEIRT AS DECIMAL) / 100, 1), 0)) WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) > COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (WK.BAIKA, 0), 0) + COALESCE(TRUNCATE (CAST(WK.BAIKA * MZS2.ZEIRT AS DECIMAL) / 100, 1), 0)) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) <= COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (WK.BAIKA, 0), 0) + COALESCE(TRUNCATE (CAST(WK.BAIKA * MZB1.ZEIRT AS DECIMAL) / 100, 1), 0)) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) > COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (WK.BAIKA, 0), 0) + COALESCE(TRUNCATE (CAST(WK.BAIKA * MZB2.ZEIRT AS DECIMAL) / 100, 1), 0)) ELSE WK.BAIKA END) AS SIGNED) AS CHAR), '.', ''), 6, 0) || LPAD(0, 6, 0) || LPAD(REPLACE (CAST(COALESCE(WK.GENKAAM, 0) AS CHAR), '.', ''), 8, 0) || LPAD(WK.TEIKEIKBN, 1, 0) || LPAD(0, 7, 0) || LPAD(0, 9, 0) || LPAD(0, 4, 0) || '   ' || RPAD('', 20, '　') || RPAD('', 20, ' ') || '                    ' || LPAD(0, 3, 0) || LPAD(0, 6, 0) || LPAD(0, 3, 0) || LPAD(0, 6, 0) || LPAD(WK.BMNCD, 3, 0) || LPAD(WK.MOYSKBN, 1, 0) || LPAD(WK.MOYSSTDT, 6, 0) || LPAD(WK.MOYSRBAN, 3, 0) || LPAD(WK.BMNO, 3, 0) || LPAD(0, 5, 0) || LPAD(WK.PLUSDDT, 8, 0) AS '1' FROM INAWK.TMWK41_A11TC05_OUEN WK LEFT OUTER JOIN INAMS2.MSTSHN MS ON LPAD(WK.SHNCD, 8, 0) = MS.SHNCD AND MS.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTBMN MB ON MS.BMNCD = MB.BMNCD AND MB.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZS1 ON MZS1.ZEIRTKBN = MS.ZEIRTKBN AND MZS1.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZS2 ON MZS2.ZEIRTKBN = MS.ZEIRTKBN_OLD AND MZS2.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZB1 ON MZB1.ZEIRTKBN = MB.ZEIRTKBN AND MZB1.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZB2 ON MZB2.ZEIRTKBN = MB.ZEIRTKBN_OLD AND MZB2.UPDKBN <> 1 ORDER BY CASE WHEN WK.MOYSKBN = 1 THEN '01' WHEN WK.MOYSKBN = 2 THEN '02' WHEN WK.MOYSKBN IN (3, 4) THEN '04' WHEN WK.MOYSKBN = 5 AND WK.CNT <= 1500 THEN '05' WHEN WK.MOYSKBN = 5 AND WK.CNT > 1500 THEN '06' END, RIGHT (LPAD(WK.MOYSSTDT, 6, 0), 4), WK.MOYSRBAN, WK.SHNCD, CASE WHEN WK.REIDMYKBN = 2 THEN WK.HBSTDT * - 1 ELSE WK.SORTKEY1 END, CASE WHEN WK.REIDMYKBN = 2 THEN WK.HBEDDT ELSE WK.SORTKEY2 END, CASE WHEN WK.REIDMYKBN = 2 THEN WK.SORTKEY1 ELSE WK.SORTKEY3 END, CASE WHEN WK.REIDMYKBN = 2 THEN WK.SORTKEY2 ELSE WK.HBSTDT END, CASE WHEN WK.REIDMYKBN = 2 THEN WK.SORTKEY3 ELSE WK.HBEDDT END" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
