REM [140][BFB01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.TMWK42_A11TC05_01 テーブルクリア
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.TMWK42_A11TC05_01;COMMIT" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAWK.TMWK42_A11TC05_01 ロード処理（全特ア有 回答用販売データ_10日分）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.TMWK42_A11TC05_01 WITH SYORI AS (SELECT CAST(DATE_FORMAT(SBD.DT - INTERVAL 10 DAY, '%%Y%%m%%d') AS SIGNED) AS DT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY') SELECT TC05.MOYSKBN, TC05.MOYSSTDT, TC05.MOYSRBAN, TC05.SHNCD, COUNT(*) AS CNT FROM INAWK.TMWK42_A11TC05 TC05 WHERE TC05.PLUSNDFLG = 0 AND TC05.HBSTDT <> 0 AND TC05.REIDMYKBN IN (0, 2) AND TC05.UPDKBN <> 1 AND TC05.MOHBEDDT >= (SELECT DT FROM SYORI) GROUP BY TC05.MOYSKBN, TC05.MOYSSTDT, TC05.MOYSRBAN, TC05.SHNCD;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.TMWK42_A11TC05_01;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
