REM [145][BFG01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0145
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFEUO002

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(催し送信　（Ｂ／Ｍ）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SYORI AS (SELECT CAST(DATE_FORMAT(SBD.DT - INTERVAL 10 DAY, '%%Y%%m%%d') AS SIGNED) AS DT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY'), OUEN AS (SELECT TC05.MOYSKBN, TC05.MOYSSTDT, TC05.MOYSRBAN, TC05.SHNCD, COUNT(*) AS CNT FROM INAWK.TMWK49_A11TC05 TC05 WHERE TC05.UPDKBN <> 1 AND TC05.HBSTDT <> 0 AND TC05.MOHBEDDT >= (SELECT DT FROM SYORI) GROUP BY TC05.MOYSKBN, TC05.MOYSSTDT, TC05.MOYSRBAN, TC05.SHNCD) SELECT LPAD(WK.TENCD, 3, 0) || LPAD(CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%%Y%%m%%d') AS SIGNED), 8, 0) || LPAD(CAST(DATE_FORMAT(CURRENT_TIMESTAMP, '%%H%%i') AS SIGNED), 4, 0) || ' ' || '1' || CASE WHEN WK.MOYSKBN = 1 THEN '01' WHEN WK.MOYSKBN = 2 THEN '02' WHEN WK.MOYSKBN IN (3, 4) THEN '04' WHEN WK.MOYSKBN = 5 AND OUEN.CNT <= 1500 THEN '05' WHEN WK.MOYSKBN = 5 AND OUEN.CNT > 1500 THEN '06' END || RIGHT (LPAD(WK.MOYSSTDT, 6, 0), 4) || RIGHT (LPAD(WK.MOYSRBAN, 3, 0), 2) || '   ' || RPAD(WK.MOYKN, 20, '　') || RPAD(WK.MOYAN, 20, ' ') || '                    ' || LPAD(WK.MOHBSTDT, 8, 0) || LPAD(WK.MOHBEDDT, 8, 0) || LPAD(0, 9, 0) || LPAD(0, 1, 0) || RPAD(WK.SHNCD, 13, ' ') || '             ' || LPAD(WK.HBSTDT, 8, 0) || LPAD(WK.HBEDDT, 8, 0) || LPAD(CAST(CASE WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) <= COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (WK.KO_A_BAIKAAN, 0), 0) + COALESCE(TRUNCATE (CAST(WK.KO_A_BAIKAAN * MZS1.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) > COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (WK.KO_A_BAIKAAN, 0), 0) + COALESCE(TRUNCATE (CAST(WK.KO_A_BAIKAAN * MZS2.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) <= COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (WK.KO_A_BAIKAAN, 0), 0) + COALESCE(TRUNCATE (CAST(WK.KO_A_BAIKAAN * MZB1.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) > COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (WK.KO_A_BAIKAAN, 0), 0) + COALESCE(TRUNCATE (CAST(WK.KO_A_BAIKAAN * MZB2.ZEIRT AS DECIMAL) / 100, 0), 0)) ELSE WK.KO_A_BAIKAAN END AS SIGNED), 6, 0) || LPAD(0, 6, 0) || LPAD(REPLACE (CAST(CAST(WK.GENKAAM AS DECIMAL (8, 2)) AS CHAR), '.', ''), 8, 0) || LPAD(WK.TEIKEIKBN, 1, 0) || LPAD(0, 7, 0) || LPAD(0, 9, 0) || LPAD(BM.BMNNO, 4, 0) || '   ' || RPAD(BM.BMNMKN, 20, '　') || RPAD(BM.BMNMAN, 20, ' ') || '                    ' || LPAD(BM.BD_KOSU1, 3, 0) || LPAD(CAST(CASE WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) <= COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (BM.BD_BAIKAAN1, 0), 0) + COALESCE(TRUNCATE (CAST(BM.BD_BAIKAAN1 * MZS1.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) > COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (BM.BD_BAIKAAN1, 0), 0) + COALESCE(TRUNCATE (CAST(BM.BD_BAIKAAN1 * MZS2.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) <= COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (BM.BD_BAIKAAN1, 0), 0) + COALESCE(TRUNCATE (CAST(BM.BD_BAIKAAN1 * MZB1.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) > COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (BM.BD_BAIKAAN1, 0), 0) + COALESCE(TRUNCATE (CAST(BM.BD_BAIKAAN1 * MZB2.ZEIRT AS DECIMAL) / 100, 0), 0)) ELSE COALESCE(BM.BD_BAIKAAN1, 0) END AS SIGNED), 6, 0) || LPAD(BM.BD_KOSU2, 3, 0) || LPAD(CAST(CASE WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) <= COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (BM.BD_BAIKAAN2, 0), 0) + COALESCE(TRUNCATE (CAST(BM.BD_BAIKAAN2 * MZS1.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) > COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (BM.BD_BAIKAAN2, 0), 0) + COALESCE(TRUNCATE (CAST(BM.BD_BAIKAAN2 * MZS2.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) <= COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (BM.BD_BAIKAAN2, 0), 0) + COALESCE(TRUNCATE (CAST(BM.BD_BAIKAAN2 * MZB1.ZEIRT AS DECIMAL) / 100, 0), 0)) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) > COALESCE(20000000 + WK.MOYSSTDT, 0) THEN FLOOR(COALESCE(TRUNCATE (BM.BD_BAIKAAN2, 0), 0) + COALESCE(TRUNCATE (CAST(BM.BD_BAIKAAN2 * MZB2.ZEIRT AS DECIMAL) / 100, 0), 0)) ELSE COALESCE(BM.BD_BAIKAAN2, 0) END AS SIGNED), 6, 0) || LPAD(WK.BMNCD, 3, 0) || LPAD(WK.MOYSKBN, 1, 0) || LPAD(WK.MOYSSTDT, 6, 0) || LPAD(WK.MOYSRBAN, 3, 0) || LPAD(WK.BMNO, 3, 0) || LPAD(0, 5, 0) || LPAD(WK.PLUSDDT, 8, 0) AS '1' FROM INAWK.TMWK49_A11TC05 WK INNER JOIN INATK2.TOKBM BM ON WK.MOYSKBN = BM.MOYSKBN AND WK.MOYSSTDT = BM.MOYSSTDT AND WK.MOYSRBAN = BM.MOYSRBAN AND WK.BMNO = BM.BMNNO AND WK.UPDKBN <> 1 AND WK.HBSTDT <> 0 AND WK.MOHBEDDT >= (SELECT DT FROM SYORI) LEFT OUTER JOIN OUEN ON WK.MOYSKBN = OUEN.MOYSKBN AND WK.MOYSSTDT = OUEN.MOYSSTDT AND WK.MOYSRBAN = OUEN.MOYSRBAN AND WK.SHNCD = OUEN.SHNCD LEFT OUTER JOIN INAMS2.MSTSHN MS ON LPAD(WK.SHNCD, 8, 0) = MS.SHNCD AND MS.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTBMN MB ON MS.BMNCD = MB.BMNCD AND MB.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZS1 ON MZS1.ZEIRTKBN = MS.ZEIRTKBN AND MZS1.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZS2 ON MZS2.ZEIRTKBN = MS.ZEIRTKBN_OLD AND MZS2.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZB1 ON MZB1.ZEIRTKBN = MB.ZEIRTKBN AND MZB1.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZB2 ON MZB2.ZEIRTKBN = MB.ZEIRTKBN_OLD AND MZB2.UPDKBN <> 1 ORDER BY CASE WHEN WK.MOYSKBN = 1 THEN '01' WHEN WK.MOYSKBN = 2 THEN '02' WHEN WK.MOYSKBN IN (3, 4) THEN '04' WHEN WK.MOYSKBN = 5 AND OUEN.CNT <= 1500 THEN '05' WHEN WK.MOYSKBN = 5 AND OUEN.CNT > 1500 THEN '06' END, RIGHT (LPAD(WK.MOYSSTDT, 6, 0), 4), WK.MOYSRBAN, WK.BMNO, WK.SHNCD, WK.TENGPCD, WK.TENCD, WK.KANRINO, WK.HBSTDT, WK.HBEDDT" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
