REM [146][A11TN11]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET OUTFILENAME=0146
SET EXPFILENAME=%~DP0..\exp\%OUTFILENAME%
SET HULFTID=VFEUO004
SET HULFTID2=MDMUR033

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(催し送信　（分類分割）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH RECURSIVE TEMP AS ((SELECT 1 AS NUM UNION ALL SELECT NUM + 1 FROM TEMP LIMIT 400)) SELECT CASE WHEN SUBSTR(RPAD(COALESCE(T1.TENATSUK_ARR, ''), 400, ' '), T3.NUM, 1) = '1' THEN LPAD(T3.NUM, 3, 0) END || LPAD(COALESCE(DATE_FORMAT(CURRENT_TIMESTAMP, '%%Y%%m%%d'), 0), 8, 0) || LPAD(COALESCE(DATE_FORMAT(CURRENT_TIMESTAMP, '%%h%%i'), 0), 4, 0) || ' ' || LPAD(T1.KKKNO, 4, 0) || RPAD(COALESCE(T1.BTKN, ''), 20, '　') || LPAD(COALESCE(T1.HBSTDT, 0), 8, 0) || LPAD(COALESCE(T1.HBEDDT, 0), 8, 0) || LPAD(COALESCE(T1.MOYSKBN, 0), 1, 0) || LPAD(COALESCE(T1.MOYSSTDT, 0), 6, 0) || LPAD(COALESCE(T1.MOYSRBAN, 0), 3, 0) || LPAD(COALESCE(T1.BMNCD, 0), 3, 0) || LPAD(COALESCE(T1.DAICD, 0), 2, 0) || LPAD(COALESCE(T1.CHUCD, 0), 2, 0) || LPAD(COALESCE(T1.SHOCD, 0), 2, 0) || LPAD(COALESCE(T1.WARIRT, 0), 2, 0) || LPAD(COALESCE(T1.WARIGK, 0), 6, 0) || LPAD(COALESCE(T1.ICHIRTGK, 0), 6, 0) || LPAD(COALESCE(T2.HBSTDT, 0), 8, 0) || LPAD(COALESCE(T2.HBEDDT, 0), 8, 0) || RPAD(COALESCE(T2.MOYKN, ''), 20, '　') || RPAD(COALESCE(T2.MOYAN, ''), 20, ' ') || LPAD(COALESCE(T2.PLUSDDT, 0), 8, 0) AS '1' FROM INATK2.TOKBT_KKK T1 INNER JOIN INATK2.TOKMOYCD T2 ON T1.MOYSKBN = T2.MOYSKBN AND T1.MOYSSTDT = T2.MOYSSTDT AND T1.MOYSRBAN = T2.MOYSRBAN, TEMP T3 WHERE SUBSTR(RPAD(COALESCE(T1.TENATSUK_ARR, ''), 400, ' '), T3.NUM, 1) = '1' AND T1.UPDKBN <> 1 ORDER BY T1.KKKNO, CASE WHEN SUBSTR(RPAD(COALESCE(T1.TENATSUK_ARR, ''), 400, ' '), T3.NUM, 1) = '1' THEN LPAD(T3.NUM, 3, 0) END" >%EXPFILENAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

REM ===== CCRへの送信追加 2025/06/17 =======
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID2% %OUTFILENAME%


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
