REM [149][JH_RTN_ADDSHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME%  → INAWK.JH_RTN_ADDSHN ロード処理（事前発注_追加商品(戻り用)作成）※仮締用
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.JH_RTN_ADDSHN;INSERT IGNORE INTO INAWK.JH_RTN_ADDSHN SELECT SHN.LSTNO, SHN.BMNCD, SHN.HYOSEQNO, SHN.TENCD, SHN.SHNCD, SHN.BINKBN, SHN.JTDT_01, SHN.JTDT_02, SHN.JTDT_03, SHN.JTDT_04, SHN.JTDT_05, SHN.JTDT_06, SHN.JTDT_07, SHN.JTDT_08, SHN.JTDT_09, SHN.JTDT_10, SHN.HTSU_01, SHN.HTSU_02, SHN.HTSU_03, SHN.HTSU_04, SHN.HTSU_05, SHN.HTSU_06, SHN.HTSU_07, SHN.HTSU_08, SHN.HTSU_09, SHN.HTSU_10, SHN.PAGENO, SHN.SENDFLG, SHN.OPERATOR, SHN.ADDDT, SHN.UPDDT FROM INATK2.TOKTJ_ADDSHN SHN INNER JOIN INAIF.JH_SHIME_DATE T502 ON T502.LSTNO = SHN.LSTNO AND T502.BMNCD = SHN.BMNCD WHERE SHN.SENDFLG IN (0, 9);COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.JH_RTN_ADDSHN;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
