REM [097][BFC38]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0097
SET EXPFILE=%~DP0..\exp\%OUTFILENAME%
SET HULFTID=VFBUO009

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(アンケート結果＿店グループ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.MOYSKBN, 1, 0) || LPAD(T1.MOYSSTDT, 6, 0) || LPAD(T1.MOYSRBAN, 3, 0) || LPAD(COALESCE(T1.TENGPCD, 0), 3, 0) || LPAD(COALESCE(T1.KYOSEIFLG, 0), 1, 0) || LPAD(COALESCE(T1.QASYUKBN, 0), 1, 0) || LPAD(COALESCE(T1.LTENSAIFLG, 0), 1, 0) || LPAD(COALESCE(T1.BAIKAIKATSU, 0), 1, 0) || LPAD(COALESCE(T1.SCHANSFLG, 0), 1, 0) || LPAD(COALESCE(T1.ITEMKFLG, 0), 1, 0) || LPAD(COALESCE(T1.CSV_SEQ, 0), 12, 0) || LPAD(COALESCE(T1.SENDFLG, 0), 1, 0) || RPAD(COALESCE(T1.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(T1.ADDDT, 0), 8, 0) || LPAD(COALESCE(T1.UPDDT, 0), 8, 0) FROM (SELECT WK03.MOYSKBN, WK03.MOYSSTDT, WK03.MOYSRBAN, WK03.TENGPCD, WK03.KYOSEIFLG, WK03.QASYUKBN, 1 AS LTENSAIFLG, 1 AS BAIKAIKATSU, 0 AS SCHANSFLG, 0 AS ITEMKFLG, 0 AS CSV_SEQ, 0 AS SENDFLG, '' AS OPERATOR, SBD.DT_INT AS ADDDT, NULL AS UPDDT FROM INAWK.ANWK03 WK03 INNER JOIN (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY') SBD ON 1 = 1 UNION ALL SELECT QGP.MOYSKBN, QGP.MOYSSTDT, QGP.MOYSRBAN, QGP.TENGPCD, QGP.KYOSEIFLG, QGP.QASYUKBN, QGP.LDSYFLG, QGP.URIASELKBN, QGP.SCHANSFLG, QGP.ITMANSFLG, QGP.CSVSEQNO, QGP.SENDFLG, QGP.OPERATOR, CAST(DATE_FORMAT(QGP.ADDDT, '%%Y%%m%%d') AS SIGNED) AS ADDDT, CAST(DATE_FORMAT(QGP.UPDDT, '%%Y%%m%%d') AS SIGNED) AS UPDDT FROM INATK2.TOKTG_QAGP QGP WHERE NOT EXISTS (SELECT * FROM INAWK.ANWK03 WK03 WHERE WK03.MOYSKBN = QGP.MOYSKBN AND WK03.MOYSSTDT = QGP.MOYSSTDT AND WK03.MOYSRBAN = QGP.MOYSRBAN AND WK03.TENGPCD = QGP.TENGPCD)) T1 ORDER BY T1.MOYSKBN, T1.MOYSSTDT, T1.MOYSRBAN, T1.TENGPCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
