REM [098][BFC40]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0098
SET EXPFILE=%~DP0..\exp\%OUTFILENAME%
SET HULFTID=VFBUO010

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(アンケート結果＿店舗)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.MOYSKBN, 1, 0) || LPAD(COALESCE(T1.MOYSSTDT, 0), 6, 0) || LPAD(COALESCE(T1.MOYSRBAN, 0), 3, 0) || LPAD(COALESCE(T1.TENCD, 0), 3, 0) || LPAD(COALESCE(T1.KYOSEIFLG, 0), 1, 0) || LPAD(COALESCE(T1.TENGPCD, 0), 3, 0) || LPAD(COALESCE(T1.LDTENKBN, 0), 1, 0) || LPAD(COALESCE(T1.MBSYFLG, 0), 1, 0) || LPAD(COALESCE(T1.HBSTRTFLG, 0), 1, 0) || LPAD(COALESCE(T1.MBANSFLG, 0), 1, 0) || LPAD(COALESCE(T1.CSVSEQNO, 0), 12, 0) || LPAD(COALESCE(T1.SENDFLG, 0), 1, 0) || LPAD(COALESCE(T1.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(T1.ADDDT, 0), 8, 0) || LPAD(COALESCE(T1.UPDDT, 0), 8, 0) FROM (SELECT TEN.MOYSKBN, TEN.MOYSSTDT, TEN.MOYSRBAN, TEN.TENCD, TEN.KYOSEIFLG, TEN.TENGPCD, TEN.LDTENKBN, 1 AS MBSYFLG, 0 AS HBSTRTFLG, 0 AS MBANSFLG, 0 AS CSVSEQNO, 0 AS SENDFLG, ' ' AS OPERATOR, SBD.DT_INT AS ADDDT, NULL AS UPDDT FROM INATK2.TOKTG_TEN TEN INNER JOIN (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY') SBD ON 1 = 1 INNER JOIN INAWK.ANWK03 WK03 ON TEN.MOYSKBN = WK03.MOYSKBN AND TEN.MOYSSTDT = WK03.MOYSSTDT AND TEN.MOYSRBAN = WK03.MOYSRBAN AND TEN.TENGPCD = WK03.TENGPCD LEFT OUTER JOIN (SELECT * FROM INATK2.TOKTG_TENGP WHERE UPDKBN <> 1) TGP ON TEN.MOYSKBN = TGP.MOYSKBN AND TEN.MOYSSTDT = TGP.MOYSSTDT AND TEN.MOYSRBAN = TGP.MOYSRBAN AND TEN.TENGPCD = TGP.TENGPCD UNION ALL SELECT QTEN.MOYSKBN, QTEN.MOYSSTDT, QTEN.MOYSRBAN, QTEN.TENCD, QTEN.KYOSEIFLG, QTEN.TENGPCD, QTEN.LDTENKBN, QTEN.MBSYFLG, QTEN.HBSTRTFLG, QTEN.MBANSFLG, QTEN.CSVSEQNO, QTEN.SENDFLG, QTEN.OPERATOR, CAST(DATE_FORMAT(QTEN.ADDDT, '%%Y%%m%%d') AS SIGNED) AS ADDDT, CAST(DATE_FORMAT(QTEN.UPDDT, '%%Y%%m%%d') AS SIGNED) AS UPDDT FROM INATK2.TOKTG_QATEN QTEN WHERE NOT EXISTS (SELECT * FROM INATK2.TOKTG_QAGP QGP INNER JOIN INAWK.ANWK03 WK03 ON QGP.MOYSKBN = WK03.MOYSKBN AND QGP.MOYSSTDT = WK03.MOYSSTDT AND QGP.MOYSRBAN = WK03.MOYSRBAN AND QGP.TENGPCD = WK03.TENGPCD WHERE QGP.MOYSKBN = QTEN.MOYSKBN AND QGP.MOYSSTDT = QTEN.MOYSSTDT AND QGP.MOYSRBAN = QTEN.MOYSRBAN AND QGP.TENGPCD = QTEN.TENGPCD)) T1 ORDER BY T1.MOYSKBN, T1.MOYSSTDT, T1.MOYSRBAN, T1.TENCD, T1.KYOSEIFLG" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
