REM [099][BFC39]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0099
SET EXPFILE=%~DP0..\exp\%OUTFILENAME%
SET HULFTID=VFBUO011

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(アンケート結果＿商品)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.MOYSKBN, 1, 0) || LPAD(T1.MOYSSTDT, 6, 0) || LPAD(T1.MOYSRBAN, 3, 0) || LPAD(COALESCE(T1.TENGPCD, 0), 3, 0) || LPAD(COALESCE(T1.BMNCD, 0), 3, 0) || LPAD(COALESCE(T1.KANRINO, 0), 4, 0) || LPAD(COALESCE(T1.KANRIENO, 0), 2, 0) || LPAD(COALESCE(T1.URISELKBN, 0), 1, 0) || LPAD(COALESCE(T1.ITMSELKBN, 0), 1, 0) || LPAD(COALESCE(T1.URICHGAM1, 0), 6, 0) || LPAD(COALESCE(T1.URICHGAM2, 0), 6, 0) || LPAD(COALESCE(T1.URICHGAM3, 0), 6, 0) || LPAD(COALESCE(T1.CSVSEQNO, 0), 12, 0) || LPAD(COALESCE(T1.SENDFLG, 0), 1, 0) || RPAD(COALESCE(T1.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(T1.ADDDT, 0), 8, 0) || LPAD(COALESCE(T1.UPDDT, 0), 8, 0) FROM (SELECT SHN.MOYSKBN, SHN.MOYSSTDT, SHN.MOYSRBAN, WK03.TENGPCD, SHN.BMNCD, SHN.KANRINO, SHN.KANRIENO, CASE WHEN WK03.QASYUKBN <> 3 THEN 0 ELSE 1 END AS URISELKBN, 1 AS ITMSELKBN, CASE WHEN WK03.QASYUKBN <> 3 THEN 0 WHEN WK03.QASYUKBN = 3 AND SHN.ADDSHUKBN = 01 THEN SHN.A_WRITUKBN WHEN WK03.QASYUKBN = 3 AND SHN.ADDSHUKBN IN (01, 02, 03, 04, 05) AND SHN.KO_A_BAIKAAN <> 0 THEN SHN.KO_A_BAIKAAN WHEN WK03.QASYUKBN = 3 AND SHN.ADDSHUKBN IN (01, 02, 03, 04, 05) AND SHN.KO_A_BAIKAAN = 0 THEN SHN.A_BAIKAAM END AS URICHGAM1, CASE WHEN WK03.QASYUKBN <> 3 THEN 0 WHEN WK03.QASYUKBN = 3 AND SHN.ADDSHUKBN = 01 THEN 0 WHEN WK03.QASYUKBN = 3 AND SHN.ADDSHUKBN IN (01, 02, 03, 04, 05) THEN SHN.BD1_A_BAIKAAN END AS URICHGAM2, CASE WHEN WK03.QASYUKBN <> 3 THEN 0 WHEN WK03.QASYUKBN = 3 AND SHN.ADDSHUKBN = 01 THEN 0 WHEN WK03.QASYUKBN = 3 AND SHN.ADDSHUKBN IN (01, 02, 03, 04, 05) THEN SHN.BD1_A_BAIKAAN END AS URICHGAM3, ROW_NUMBER() OVER (PARTITION BY SHN.MOYSKBN, SHN.MOYSSTDT, SHN.MOYSRBAN, WK03.TENGPCD ORDER BY SHN.HIGAWRFLG, SHN.BMNCD, SHN.HBSTDT, SHN.DAICD, SHN.CHUCD, SHN.SHNCD) AS CSVSEQNO, 0 AS SENDFLG, RPAD(SHN.SHNCD, 14, ' ') || CASE WHEN WK03.QASYUKBN <> 3 THEN 0 ELSE 1 END AS OPERATOR, SBD.DT_INT AS ADDDT, NULL AS UPDDT FROM INATK2.TOKTG_SHN SHN INNER JOIN (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY') SBD ON 1 = 1 INNER JOIN INAWK.ANWK03 WK03 ON SHN.MOYSKBN = WK03.MOYSKBN AND SHN.MOYSSTDT = WK03.MOYSSTDT AND SHN.MOYSRBAN = WK03.MOYSRBAN UNION ALL SELECT SHN.MOYSKBN, SHN.MOYSSTDT, SHN.MOYSRBAN, SHN.TENGPCD, SHN.BMNCD, SHN.KANRINO, SHN.KANRIENO, SHN.URISELKBN, SHN.ITMSELKBN, SHN.URICHGAM1, SHN.URICHGAM2, SHN.URICHGAM3, SHN.CSVSEQNO, SHN.SENDFLG, SHN.OPERATOR, CAST(DATE_FORMAT(SHN.ADDDT, '%%Y%%m%%d') AS SIGNED) AS ADDDT, CAST(DATE_FORMAT(SHN.UPDDT, '%%Y%%m%%d') AS SIGNED) AS UPDDT FROM INATK2.TOKTG_QASHN SHN WHERE NOT EXISTS (SELECT * FROM INATK2.TOKTG_QAGP QGP INNER JOIN INAWK.ANWK03 WK03 ON QGP.MOYSKBN = WK03.MOYSKBN AND QGP.MOYSSTDT = WK03.MOYSSTDT AND QGP.MOYSRBAN = WK03.MOYSRBAN WHERE QGP.MOYSKBN = SHN.MOYSKBN AND QGP.MOYSSTDT = SHN.MOYSSTDT AND QGP.MOYSRBAN = SHN.MOYSRBAN)) T1 ORDER BY T1.MOYSKBN, T1.MOYSSTDT, T1.MOYSRBAN, T1.TENGPCD, T1.BMNCD, T1.KANRINO, T1.KANRIENO" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
