REM [031][AIB03]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0031
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEBUO004

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(店舗部門実績)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(BJ.TENCD, 3, 0) || LPAD(BJ.BMNCD, 3, 0) || LPAD(BJ.TENITEMSU, 7, 0) || LPAD(BJ.TENPLUSU, 7, 0) || '   ' || LPAD(BJ.SENDFLG, 1, 0) || RPAD(BJ.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(BJ.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(BJ.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2.MSTBUMONJISSEKI BJ ORDER BY BJ.TENCD, BJ.BMNCD;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
