REM [044][AFC01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0044
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEDUO001

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(部門マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.BMNCD, 3, 0) || LPAD(T1.BMNKBN, 1, 0) || RPAD(T1.BMNAN, 20, ' ') || RPAD(T1.BMNKN, 20, '　') || LPAD(T1.ZEIKBN, 1, 0) || LPAD(T1.ZEIRTHENKODT, 8, 0) || LPAD(T1.ZEIRTKBN_OLD, 3, 0) || LPAD(T1.ZEIRTKBN, 3, 0) || LPAD(T1.ODBOOKKBN, 1, 0) || LPAD(T1.HYOKAKBN, 1, 0) || LPAD(CAST(T1.GENKART * 100 AS SIGNED), 4, 0) || LPAD(T1.CORPBMNCD, 3, 0) || LPAD(T1.URIBMNCD, 3, 0) || LPAD(T1.HOGANBMNCD, 3, 0) || LPAD(CAST(T1.JYOGENAM * 100 AS SIGNED), 11, 0) || LPAD(CAST(T1.JYOGENSU * 100 AS SIGNED), 11, 0) || LPAD(T1.TANAOROTIMKB, 1, ' ') || LPAD(T1.POSBAIHENKBN, 1, 0) || LPAD(T1.KEIHIKBN, 1, 0) || LPAD(T1.TANPINKBN, 1, 0) || LPAD(T1.DELKIJYUNSU, 3, 0) || LPAD(T1.WARIGAIFLG, 1, 0) || LPAD(T1.ITEMBETSUCD, 1, 0) || LPAD(T1.URISEIGENFLG, 1, 0) || LPAD(T1.URIKETAKBN, 1, 0) || '     ' || LPAD(T1.UPDKBN, 1, 0) || LPAD(T1.SENDFLG, 1, 0) || RPAD(T1.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2.MSTBMN T1 WHERE T1.UPDKBN <> 1 ORDER BY T1.BMNCD;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
