REM [061][A11NAME]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0061
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEEUO004

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(名称マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT RPAD(trim(T1.MEISHOKBN), 6, ' ') || RPAD(T1.MEISHOCD, 6, ' ') || RPAD(T1.MEISHOKBNKN, 40, '　') || RPAD(T1.NMKN, 14, '　') || RPAD(T1.TNMKN, 8, '　') || RPAD(T1.NMAN, 19, ' ') || LPAD(COALESCE(T1.SENDFLG, 0), 1, 0) || LPAD(CASE WHEN T1.ADDDT IS NULL THEN '' WHEN DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d') = '19000101' THEN '' ELSE DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d') END, 8, ' ') || LPAD(CASE WHEN T1.UPDDT IS NULL THEN '' WHEN DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d') = '19000101' THEN '' ELSE DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d') END, 8, ' ') FROM INAMS2.MSTMEISHO T1 ORDER BY T1.MEISHOKBN, T1.MEISHOCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
