REM [081][HA_A11SHOH]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.HA_A11SHOH(発注用商品マスタ) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.HA_A11SHOH ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAIF.HA_A11SHOH ロード処理（発注用商品マスタ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAIF.HA_A11SHOH SELECT SHN.SHNCD, SHN.YOYAKUDT, SHN.TENBAIKADT, SHN.BMNCD, SHN.DAICD, SHN.CHUCD, SHN.SHOCD, SHN.SSHOCD, SHN.ATSUK_STDT, SHN.ATSUK_EDDT, SHN.TEISHIKBN, SHN.SHNAN, SHN.SHNKN, SHN.PCARDKN, SHN.POPKN, SHN.RECEIPTAN, SHN.RECEIPTKN, SHN.PCKBN, SHN.KAKOKBN, SHN.ICHIBAKBN, SHN.SHNKBN, SHN.SSIRCD, SHN.HSPTN, SHN.RG_ATSUKFLG, SHN.RG_GENKAAM, SHN.RG_BAIKAAM, SHN.RG_IRISU, SHN.RG_IDENFLG, SHN.RG_WAPNFLG, SHN.HS_ATSUKFLG, SHN.HS_GENKAAM, SHN.HS_BAIKAAM, SHN.HS_IRISU, SHN.HS_WAPNFLG, SHN.HS_SPOTMINSU, SHN.HP_SWAPNFLG, SHN.KIKKN, SHN.UP_YORYOSU, SHN.UP_TYORYOSU, SHN.UP_TANIKBN, SHN.SHNYOKOSZ, SHN.SHNTATESZ, SHN.SHNOKUSZ, SHN.SHNJRYOSZ, SHN.PBKBN, SHN.KOMONOKBM, SHN.TANAOROKBN, SHN.TEIKEIKBN, SHN.ODS_HARUSU, SHN.ODS_NATSUSU, SHN.ODS_AKISU, SHN.ODS_FUYUSU, SHN.ODS_NYUKASU, SHN.ODS_NEBIKISU, SHN.PCARD_SHUKBN, SHN.PCARD_IROKBN, SHN.SEIZOGENNISU, SHN.TEIKANKBN, SHN.MAKERCD, SHN.IMPORTKBN, SHN.SIWAKEKBN, SHN.HENPIN_KBN, SHN.TAISHONENSU, SHN.CALORIESU, SHN.ELPFLG, SHN.BELLMARKFLG, SHN.RECYCLEFLG, SHN.ECOFLG, SHN.HZI_YOTO, SHN.HZI_ZAISHITU, SHN.HZI_RECYCLE, SHN.KIKANKBN, SHN.SHUKYUKBN, SHN.DOSU, SHN.CHINRETUCD, SHN.DANTUMICD, SHN.KASANARICD, SHN.KASANARISZ, SHN.ASSHUKURT, SHN.SHUBETUCD, SHN.URICD, SHN.URABARIKBN, SHN.PCARD_OPFLG, SHN.PARENTCD, SHN.BINKBN, CASE WHEN SHN.HAT_MONKBN = 0 THEN 1 ELSE 0 END, CASE WHEN SHN.HAT_TUEKBN = 0 THEN 1 ELSE 0 END, CASE WHEN SHN.HAT_WEDKBN = 0 THEN 1 ELSE 0 END, CASE WHEN SHN.HAT_THUKBN = 0 THEN 1 ELSE 0 END, CASE WHEN SHN.HAT_FRIKBN = 0 THEN 1 ELSE 0 END, CASE WHEN SHN.HAT_SATKBN = 0 THEN 1 ELSE 0 END, CASE WHEN SHN.HAT_SUNKBN = 0 THEN 1 ELSE 0 END, SHN.READTMPTN, SHN.SIMEKAISU, SHN.TOROKUMOTO, CASE WHEN SHN.READTMPTN <> 0 THEN RTM.READTM_MON ELSE 0 END, CASE WHEN SHN.READTMPTN <> 0 THEN RTM.READTM_TUE ELSE 0 END, CASE WHEN SHN.READTMPTN <> 0 THEN RTM.READTM_WED ELSE 0 END, CASE WHEN SHN.READTMPTN <> 0 THEN RTM.READTM_THU ELSE 0 END, CASE WHEN SHN.READTMPTN <> 0 THEN RTM.READTM_FRI ELSE 0 END, CASE WHEN SHN.READTMPTN <> 0 THEN RTM.READTM_SAT ELSE 0 END, CASE WHEN SHN.READTMPTN <> 0 THEN RTM.READTM_SUN ELSE 0 END, CASE WHEN SHN.ZEIKBN = 3 AND BMN.BMNCD IS NOT NULL THEN BMN.ZEIKBN WHEN SHN.ZEIKBN = 3 THEN SHN.ZEIKBN ELSE SHN.ZEIKBN END, SHN.UPDKBN FROM INAMS2.MSTSHN SHN LEFT OUTER JOIN (SELECT * FROM INAMS2.MSTREADTM WHERE UPDKBN <> 1) RTM ON SHN.READTMPTN = RTM.READTMPTN LEFT OUTER JOIN (SELECT * FROM INAMS2.MSTBMN WHERE UPDKBN <> 1) BMN ON '0' + LEFT (SHN.SHNCD, 2) = BMN.BMNCD WHERE SHN.UPDKBN <> 1 AND SHN.IRYOREFLG <> 1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"ANALYZE TABLE INAIF.HA_A11SHOH;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
