REM [082][HA_A11TSH]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.HA_A11TSH(発注用仕入売価店舗) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAIF.HA_A11TSH ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAIF.HA_A11TSH ロード処理（発注用仕入売価店舗）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIF.HA_A11TSH SELECT CASE WHEN SGT.SHNCD IS NULL THEN BCT.SHNCD ELSE SGT.SHNCD END AS '1', CASE WHEN SGT.TENCD IS NULL THEN BCT.TENCD ELSE SGT.TENCD END AS '2', CASE WHEN SGT.YOYAKUDT IS NULL THEN BCT.YOYAKUDT ELSE SGT.YOYAKUDT END AS '3', CASE WHEN BCT.GENKAAM IS NULL THEN 0 ELSE BCT.GENKAAM END AS '4', CASE WHEN BCT.BAIKAAM IS NULL THEN 0 ELSE BCT.BAIKAAM END AS '5', CASE WHEN BCT.IRISU IS NULL THEN 0 ELSE BCT.IRISU END AS '6', CASE WHEN SGT.SIRCD IS NULL THEN 0 ELSE SGT.SIRCD END AS '7', CASE WHEN SGT.HSPTN IS NULL THEN 0 ELSE SGT.HSPTN END AS '8', '         ' AS '9' FROM (SELECT T3.SHNCD, SMG1.TENCD, T3.YOYAKUDT, T3.AREAKBN, T3.SIRCD, T3.HSPTN, T3.OPERATOR, 0 AS KOUSINKUBUN, T3.ADDDT, T3.UPDDT FROM INAMS2.MSTSIRGPSHN T3 INNER JOIN (SELECT T1.GPKBN, T1.BMNCD, T1.TENGPCD, T2.TENCD, T1.AREAKBN FROM INAMS2.MSTSHNTENGP T1 INNER JOIN INAMS2.MSTSHNTENGPTEN T2 ON T1.BMNCD = T2.BMNCD AND T1.TENGPCD = T2.TENGPCD AND T1.UPDKBN <> 1 AND T1.AREAKBN = 1 AND T1.GPKBN = 1 AND T2.GPKBN = 1 UNION SELECT T1.GPKBN, T1.BMNCD, T1.TENGPCD, T2.TENCD, T1.AREAKBN FROM INAMS2.MSTSHNTENGP T1 INNER JOIN INAMS2.MSTTENBMN T2 ON T1.BMNCD = T2.BMNCD AND T1.TENGPCD = T2.AREACD AND T1.UPDKBN <> 1 AND T1.AREAKBN = 0 AND T1.GPKBN = 1 AND T2.UPDKBN <> 1) SMG1 ON '0' + LEFT (T3.SHNCD, 2) = SMG1.BMNCD AND T3.TENGPCD = SMG1.TENGPCD AND T3.AREAKBN = SMG1.AREAKBN) SGT LEFT OUTER JOIN (SELECT BCT1.SHNCD, BCT1.TENCD, BCT1.YOYAKUDT, BCT1.AREAKBN, BCT1.GENKAAM, BCT1.BAIKAAM, BCT1.IRISU, BCT1.OPERATOR, BCT1.KOUSINKUBUN, BCT1.ADDDT, BCT1.UPDDT FROM (SELECT T5.SHNCD, SMG2.TENCD, T5.YOYAKUDT, T5.AREAKBN, T5.GENKAAM, T5.BAIKAAM, T5.IRISU, T5.OPERATOR, 0 AS KOUSINKUBUN, T5.ADDDT, T5.UPDDT, ROW_NUMBER() OVER (PARTITION BY T5.SHNCD, SMG2.TENCD ORDER BY T5.SHNCD, SMG2.TENCD, T5.BAIKAAM, T5.GENKAAM, T5.IRISU, T5.YOYAKUDT) AS ODRNO FROM (SELECT BCTL.SHNCD, BCTL.TENGPCD, BCTL.YOYAKUDT, BCTL.AREAKBN, CASE WHEN COALESCE(BCTL.GENKAAM, 0) = 0 THEN SHN.RG_GENKAAM ELSE BCTL.GENKAAM END AS GENKAAM, CASE WHEN COALESCE(BCTL.BAIKAAM, 0) = 0 THEN SHN.RG_BAIKAAM ELSE BCTL.BAIKAAM END AS BAIKAAM, CASE WHEN COALESCE(BCTL.IRISU, 0) = 0 THEN SHN.RG_IRISU ELSE BCTL.IRISU END AS IRISU, BCTL.OPERATOR, BCTL.SENDFLG, BCTL.ADDDT, BCTL.UPDDT FROM INAMS2.MSTSHN SHN INNER JOIN INAMS2.MSTBAIKACTL BCTL ON SHN.SHNCD = BCTL.SHNCD AND SHN.UPDKBN <> 1) T5 INNER JOIN (SELECT T1.GPKBN, T1.BMNCD, T1.TENGPCD, T2.TENCD, T1.AREAKBN FROM INAMS2.MSTSHNTENGP T1 INNER JOIN INAMS2.MSTSHNTENGPTEN T2 ON T1.BMNCD = T2.BMNCD AND T1.TENGPCD = T2.TENGPCD AND T1.UPDKBN <> 1 AND T1.AREAKBN = 1 AND T1.GPKBN = 2 AND T2.GPKBN = 2 UNION SELECT T1.GPKBN, T1.BMNCD, T1.TENGPCD, T2.TENCD, T1.AREAKBN FROM INAMS2.MSTSHNTENGP T1 INNER JOIN INAMS2.MSTTENBMN T2 ON T1.BMNCD = T2.BMNCD AND T1.TENGPCD = T2.AREACD AND T1.UPDKBN <> 1 AND T1.AREAKBN = 0 AND T1.GPKBN = 2 AND T2.UPDKBN <> 1) SMG2 ON '0' + LEFT (T5.SHNCD, 2) = SMG2.BMNCD AND T5.TENGPCD = SMG2.TENGPCD AND T5.AREAKBN = SMG2.AREAKBN) BCT1 WHERE ODRNO = 1) BCT ON SGT.SHNCD = BCT.SHNCD AND SGT.TENCD = BCT.TENCD UNION ALL SELECT CASE WHEN SGT.SHNCD IS NULL THEN BCT.SHNCD ELSE SGT.SHNCD END AS '1', CASE WHEN SGT.TENCD IS NULL THEN BCT.TENCD ELSE SGT.TENCD END AS '2', CASE WHEN SGT.YOYAKUDT IS NULL THEN BCT.YOYAKUDT ELSE SGT.YOYAKUDT END AS '3', CASE WHEN BCT.GENKAAM IS NULL THEN 0 ELSE BCT.GENKAAM END AS '4', CASE WHEN BCT.BAIKAAM IS NULL THEN 0 ELSE BCT.BAIKAAM END AS '5', CASE WHEN BCT.IRISU IS NULL THEN 0 ELSE BCT.IRISU END AS '6', CASE WHEN SGT.SIRCD IS NULL THEN 0 ELSE SGT.SIRCD END AS '7', CASE WHEN SGT.HSPTN IS NULL THEN 0 ELSE SGT.HSPTN END AS '8', '         ' AS '9' FROM (SELECT T3.SHNCD, SMG1.TENCD, T3.YOYAKUDT, T3.AREAKBN, T3.SIRCD, T3.HSPTN, T3.OPERATOR, 0 AS KOUSINKUBUN, T3.ADDDT, T3.UPDDT FROM INAMS2.MSTSIRGPSHN T3 INNER JOIN (SELECT T1.GPKBN, T1.BMNCD, T1.TENGPCD, T2.TENCD, T1.AREAKBN FROM INAMS2.MSTSHNTENGP T1 INNER JOIN INAMS2.MSTSHNTENGPTEN T2 ON T1.BMNCD = T2.BMNCD AND T1.TENGPCD = T2.TENGPCD AND T1.UPDKBN <> 1 AND T1.AREAKBN = 1 AND T1.GPKBN = 1 AND T2.GPKBN = 1 UNION SELECT T1.GPKBN, T1.BMNCD, T1.TENGPCD, T2.TENCD, T1.AREAKBN FROM INAMS2.MSTSHNTENGP T1 INNER JOIN INAMS2.MSTTENBMN T2 ON T1.BMNCD = T2.BMNCD AND T1.TENGPCD = T2.AREACD AND T1.UPDKBN <> 1 AND T1.AREAKBN = 0 AND T1.GPKBN = 1 AND T2.UPDKBN <> 1) SMG1 ON '0' + LEFT (T3.SHNCD, 2) = SMG1.BMNCD AND T3.TENGPCD = SMG1.TENGPCD AND T3.AREAKBN = SMG1.AREAKBN) SGT RIGHT OUTER JOIN (SELECT BCT1.SHNCD, BCT1.TENCD, BCT1.YOYAKUDT, BCT1.AREAKBN, BCT1.GENKAAM, BCT1.BAIKAAM, BCT1.IRISU, BCT1.OPERATOR, BCT1.KOUSINKUBUN, BCT1.ADDDT, BCT1.UPDDT FROM (SELECT T5.SHNCD, SMG2.TENCD, T5.YOYAKUDT, T5.AREAKBN, T5.GENKAAM, T5.BAIKAAM, T5.IRISU, T5.OPERATOR, 0 AS KOUSINKUBUN, T5.ADDDT, T5.UPDDT, ROW_NUMBER() OVER (PARTITION BY T5.SHNCD, SMG2.TENCD ORDER BY T5.SHNCD, SMG2.TENCD, T5.BAIKAAM, T5.GENKAAM, T5.IRISU, T5.YOYAKUDT) AS ODRNO FROM (SELECT BCTL.SHNCD, BCTL.TENGPCD, BCTL.YOYAKUDT, BCTL.AREAKBN, CASE WHEN COALESCE(BCTL.GENKAAM, 0) = 0 THEN SHN.RG_GENKAAM ELSE BCTL.GENKAAM END AS GENKAAM, CASE WHEN COALESCE(BCTL.BAIKAAM, 0) = 0 THEN SHN.RG_BAIKAAM ELSE BCTL.BAIKAAM END AS BAIKAAM, CASE WHEN COALESCE(BCTL.IRISU, 0) = 0 THEN SHN.RG_IRISU ELSE BCTL.IRISU END AS IRISU, BCTL.OPERATOR, BCTL.SENDFLG, BCTL.ADDDT, BCTL.UPDDT FROM INAMS2.MSTSHN SHN INNER JOIN INAMS2.MSTBAIKACTL BCTL ON SHN.SHNCD = BCTL.SHNCD AND SHN.UPDKBN <> 1) T5 INNER JOIN (SELECT T1.GPKBN, T1.BMNCD, T1.TENGPCD, T2.TENCD, T1.AREAKBN FROM INAMS2.MSTSHNTENGP T1 INNER JOIN INAMS2.MSTSHNTENGPTEN T2 ON T1.BMNCD = T2.BMNCD AND T1.TENGPCD = T2.TENGPCD AND T1.UPDKBN <> 1 AND T1.AREAKBN = 1 AND T1.GPKBN = 2 AND T2.GPKBN = 2 UNION SELECT T1.GPKBN, T1.BMNCD, T1.TENGPCD, T2.TENCD, T1.AREAKBN FROM INAMS2.MSTSHNTENGP T1 INNER JOIN INAMS2.MSTTENBMN T2 ON T1.BMNCD = T2.BMNCD AND T1.TENGPCD = T2.AREACD AND T1.UPDKBN <> 1 AND T1.AREAKBN = 0 AND T1.GPKBN = 2 AND T2.UPDKBN <> 1) SMG2 ON '0' + LEFT (T5.SHNCD, 2) = SMG2.BMNCD AND T5.TENGPCD = SMG2.TENGPCD AND T5.AREAKBN = SMG2.AREAKBN) BCT1 WHERE ODRNO = 1) BCT ON SGT.SHNCD = BCT.SHNCD AND SGT.TENCD = BCT.TENCD WHERE SGT.SHNCD IS NULL AND SGT.TENCD IS NULL;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.HA_A11TSH;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
