REM [083][HA_A11TBMH]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.HA_A11TBMH(発注用店舗部門マスタ) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.HA_A11TBMH ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAIF.HA_A11TBMH ロード処理（発注用店舗部門マスタ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAIF.HA_A11TBMH SELECT TBM.TENCD, TBM.BMNCD, TBM.AREACD, TBM.READTMPTN, TBM.BMNKN, TBM.GROUPNO, TBM.BMNRECEIPTAN, TBM.BMNRECEIPTKN, TBM.MIOKBN, TBM.SHUKEICD, TBM.WARIBIKIKBN, TBM.BMNGENKART, TBM.TENANTKBN, TBM.LOSSTKBN, TBM.YOSANKBN_B, TBM.TANAOROTKBN, TBM.PCARD_SHUKBN, TBM.PCARD_IROKBN, TBM.TENANTCD, TBM.BMN_ATR1, TBM.BMN_ATR2, TBM.BMN_ATR3, TBM.BMN_ATR4, TBM.BMN_ATR5, TBM.URIFLG, CASE WHEN COALESCE(TBM.READTMPTN, 0) = 0 THEN 0 ELSE RTM.READTM_MON END, CASE WHEN COALESCE(TBM.READTMPTN, 0) = 0 THEN 0 ELSE RTM.READTM_TUE END, CASE WHEN COALESCE(TBM.READTMPTN, 0) = 0 THEN 0 ELSE RTM.READTM_WED END, CASE WHEN COALESCE(TBM.READTMPTN, 0) = 0 THEN 0 ELSE RTM.READTM_THU END, CASE WHEN COALESCE(TBM.READTMPTN, 0) = 0 THEN 0 ELSE RTM.READTM_FRI END, CASE WHEN COALESCE(TBM.READTMPTN, 0) = 0 THEN 0 ELSE RTM.READTM_SAT END, CASE WHEN COALESCE(TBM.READTMPTN, 0) = 0 THEN 0 ELSE RTM.READTM_SUN END, TBM.UPDKBN FROM INAMS2.MSTTENBMN TBM LEFT OUTER JOIN (SELECT * FROM INAMS2.MSTREADTM T WHERE T.UPDKBN <> 1) RTM ON TBM.READTMPTN = RTM.READTMPTN WHERE TBM.UPDKBN <> 1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.HA_A11TBMH;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
