REM [085][A11EHSR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0085
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEGUO007

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(発注用配送パターン仕入先店舗（エリア）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(HAISOUPTN, 3, 0) || LPAD(TENCD, 3, 0) || LPAD(BUMN, 3, 0) || LPAD(SHIRECD, 6, 0) || LPAD(PTN_FLG, 1, 0) || RPAD(MISEDEN_FLG, 1, ' ') || RPAD(KEISANCENTER, 1, ' ') || RPAD(UNYOKBN, 1, ' ') || RPAD(DENPKBN, 1, ' ') || RPAD(SHUKEIHYO, 1, ' ') || RPAD(PICKDATA, 1, ' ') || RPAD(PICKLIST, 1, ' ') || RPAD(WAPPEN, 1, ' ') || RPAD(IKTDENP, 1, ' ') || RPAD(KAKOUSHIJI, 1, ' ') || RPAD(RYUTUKBN, 1, ' ') || RPAD(ZAIKO_DENPKBN, 1, ' ') || RPAD(ZAIKO_SHUKEIHYO, 1, ' ') || RPAD(ZAIKO_PICKDATA, 1, ' ') || RPAD(ZAIKO_PICKLIST, 1, ' ') || RPAD(SHIRECD_J, 6, ' ') || RPAD(YKM_KENSHU, 1, ' ') || RPAD(YKM_DENPKBN, 1, ' ') || RPAD(YKM_SHUKEIHYO, 1, ' ') || LPAD(CENTERCD, 3, 0) || LPAD(YKM_CENTERCD, 3, 0) || RPAD(FILLER, 14, ' ') FROM INAIF.HA_A11EHSR_A ORDER BY HAISOUPTN, TENCD, BUMN, SHIRECD;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
