REM [085][HA_A11EHSR_A]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.HA_A11EHSR_A(発注用配送パターン仕入先店舗（エリア）) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAIF.HA_A11EHSR_A ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAIF.HA_A11EHSR_A ロード処理（発注用配送パターン仕入先店舗（エリア））
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAIF.HA_A11EHSR_A SELECT CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.HSPTN WHEN AHS.HSPTN IS NULL THEN AH.HSPTN ELSE AHS.HSPTN END AS '1', TBM.TENCD, TBM.BMNCD, CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.SIRCD WHEN AHS.HSPTN IS NULL THEN 0 ELSE AHS.SIRCD END AS '2', CASE WHEN AHS2.HSPTN IS NOT NULL THEN 0 WHEN AHS.HSPTN IS NULL THEN 1 ELSE 2 END AS '3', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.TENDENFLG WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.TENDENFLG END AS '4', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.VANKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.VANKBN END AS '5', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.UNYOKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.UNYOKBN END AS '6', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.DENPKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.DENPKBN END AS '7', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.SHUHKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.SHUHKBN END AS '8', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.PICKDKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.PICKDKBN END AS '9', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.PICKLKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.PICKLKBN END AS '10', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.WAPNKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.WAPNKBN END AS '11', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.IDENPKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.IDENPKBN END AS '12', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.KAKOSJKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.KAKOSJKBN END AS '13', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.RYUTSUKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.RYUTSUKBN END AS '14', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.ZDENPKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.ZDENPKBN END AS '15', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.ZSHUHKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.ZSHUHKBN END AS '16', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.ZPICKDKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.ZPICKDKBN END AS '17', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.ZPICKLKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.ZPICKLKBN END AS '18', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.RSIRCD WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.RSIRCD END AS '19', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.YKNSHKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.YKNSHKBN END AS '20', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.YDENPKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.YDENPKBN END AS '21', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AHS2.DSHUHKBN WHEN AHS.HSPTN IS NULL THEN ' ' ELSE AHS.DSHUHKBN END AS '22', CASE WHEN AHS2.HSPTN IS NOT NULL THEN AH.CENTERCD WHEN AH.HSPTN IS NULL THEN 0 ELSE AH.CENTERCD END AS '23', CAST(CASE WHEN AHS2.HSPTN IS NOT NULL THEN AH.YCENTERCD WHEN AH.HSPTN IS NULL THEN '0' ELSE AH.YCENTERCD END AS SIGNED) AS '24', ' ' AS '25' FROM INAMS2.MSTHSGP HSG INNER JOIN INAMS2.MSTHSTENGP HTG ON HSG.HSGPCD = HTG.HSGPCD AND HSG.AREAKBN = 0 AND HSG.UPDKBN <> 1 AND HTG.UPDKBN <> 1 INNER JOIN INAMS2.MSTTENBMN TBM ON HTG.TENGPCD = TBM.AREACD AND TBM.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTAREAHSPTNSIR AHS ON HTG.HSGPCD = 0 AND HTG.TENGPCD = AHS.TENGPCD LEFT OUTER JOIN INAMS2.MSTAREAHSPTN AH ON HTG.HSGPCD = AH.HSGPCD AND HTG.TENGPCD = AH.TENGPCD LEFT OUTER JOIN INAMS2.MSTAREAHSPTNSIR AHS2 ON AH.HSPTN = AHS2.HSPTN AND AH.TENGPCD = AHS2.TENGPCD UNION ALL SELECT AH.HSPTN, TBM.TENCD, TBM.BMNCD, 0, 1, ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', AH.CENTERCD, CAST(AH.YCENTERCD AS SIGNED), ' ' FROM INAMS2.MSTHSGP HSG INNER JOIN INAMS2.MSTHSTENGP HTG ON HSG.HSGPCD = HTG.HSGPCD AND HSG.AREAKBN = 0 AND HSG.UPDKBN <> 1 AND HTG.UPDKBN <> 1 INNER JOIN INAMS2.MSTTENBMN TBM ON HTG.TENGPCD = TBM.AREACD AND TBM.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTAREAHSPTNSIR AHS ON HTG.HSGPCD = 0 AND HTG.TENGPCD = AHS.TENGPCD LEFT OUTER JOIN INAMS2.MSTAREAHSPTN AH ON HTG.HSGPCD = AH.HSGPCD AND HTG.TENGPCD = AH.TENGPCD INNER JOIN (SELECT HSPTN, TENGPCD FROM INAMS2.MSTAREAHSPTNSIR GROUP BY HSPTN, TENGPCD) AHS2 ON AH.HSPTN = AHS2.HSPTN AND AH.TENGPCD = AHS2.TENGPCD;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.HA_A11EHSR_A;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
