REM [087][HA_A11MSIR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.HA_A11MSIR(発注用複数仕入先) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.HA_A11MSIR;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAIF.HA_A11MSIR ロード処理（発注用複数仕入先）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAIF.HA_A11MSIR (SELECT FSR.SIRCD, FST.TENCD, FSR.RSIRCD, FSR.SEQNO, '', FSR.UPDKBN, FSR.SENDFLG, FSR.OPERATOR, CAST(DATE_FORMAT(FSR.ADDDT, '%%Y%%m%%d') AS SIGNED),CAST(DATE_FORMAT(FSR.UPDDT, '%%Y%%m%%d') AS SIGNED) FROM INAMS2.MSTFUKUSUSIR_R FSR INNER JOIN INAMS2.MSTFUKUSUSIR_T FST ON FSR.SIRCD = FST.SIRCD AND FSR.SEQNO = FST.SEQNO AND FSR.UPDKBN <> 1 AND FST.UPDKBN <> 1); commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"ANALYZE TABLE INAIF.HA_A11MSIR;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
