REM [088][A11SHOH]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0088
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEGUO002

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(発注用商品マスタ（予約）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT RPAD(SHOHINCD, 14, ' ') || LPAD(MSTCHG_Y_YMD, 8, 0) || LPAD(MISE_BAIKABI, 8, 0) || LPAD(BUMN, 3, 0) || LPAD(DAIBUNCD, 2, 0) || LPAD(CHUBUNCD, 2, 0) || LPAD(SHOBUNCD, 2, 0) || LPAD(SHOSHOBUNCD, 1, 0) || LPAD(ATSUKAI_S, 8, 0) || LPAD(ATSUKAI_E, 8, 0) || LPAD(ATUKAITEISHI, 1, 0) || RPAD(SHOHINNMKN, 20, ' ') || RPAD(SHOHINNMKJ, 20, '　') || RPAD(PCNM, 20, '　') || RPAD(POPNM, 20, '　') || RPAD(RECEIPTNMKN, 20, ' ') || RPAD(RECEIPTNMKJ, 20, '　') || LPAD(PCKBN, 1, 0) || LPAD(KAKOUKBN, 1, 0) || LPAD(ICHIBAKBN, 1, 0) || LPAD(SHOHIN_SHURUI, 1, 0) || LPAD(SHIRECD_H, 6, 0) || LPAD(HAISOUPTN, 3, 0) || LPAD(ATUKAIFLG, 1, 0) || LPAD(REPLACE (CAST(GENKA AS CHAR), '.', ''), 8, 0) || LPAD(BAIKA1, 6, 0) || LPAD(MISEIRISU, 3, 0) || RPAD(IKKATUFLG, 1, ' ') || RPAD(WAPPEN, 1, ' ') || LPAD(HANSOKU_ATUKAI_FLG, 1, 0) || LPAD(REPLACE (CAST(HANSOKU_GENKA AS CHAR), '.', ''), 8, 0) || LPAD(HANSOKU_BAIKA, 6, 0) || LPAD(HANSOKU_MISEIRISU, 3, 0) || RPAD(HANSOKU_WAPPEN, 1, ' ') || LPAD(HANSOKU_SPOTSU, 2, 0) || RPAD(HANSOKU_TOKUWAPPEN, 1, ' ') || RPAD(KIKAKU, 23, '　') || LPAD(UNIT_CAPA, 5, 0) || LPAD(UNIT_TANICAPA, 3, 0) || LPAD(UNIT_TANI, 2, 0) || LPAD(SHOHIN_SIZE_W, 4, 0) || LPAD(SHOHIN_SIZE_H, 4, 0) || LPAD(SHOHIN_SIZE_D, 4, 0) || LPAD(REPLACE (CAST(SHOHIN_SIZE_WEIGHT AS CHAR), '.', ''), 6, 0) || LPAD(PBKBN, 1, 0) || LPAD(KOMONOKBN, 2, 0) || LPAD(TANAKBN, 2, 0) || LPAD(TEIKEIKBN, 1, 0) || LPAD(ODS_SHOMI_HARU, 4, 0) || LPAD(ODS_SHOMI_NATU, 4, 0) || LPAD(ODS_SHOMI_AKI, 4, 0) || LPAD(ODS_SHOMI_FUYU, 4, 0) || LPAD(ODS_NYUKA, 4, 0) || LPAD(ODS_NEBIKI, 4, 0) || LPAD(PCSHURUI, 1, 0) || LPAD(PCIRO, 1, 0) || LPAD(SEIZOUGENDO, 3, 0) || LPAD(FUTEIKBN, 1, 0) || LPAD(MARKER_CD, 9, 0) || LPAD(YUNYUKBN, 2, 0) || LPAD(SHIWAKEKBN, 2, 0) || LPAD(HENPINKBN, 1, 0) || LPAD(TAISHOAGE, 2, 0) || LPAD(CALORIE, 5, 0) || LPAD(ELP_FLG, 1, 0) || LPAD(BELLMARK_FLG, 1, 0) || LPAD(RECYCLE_FLG, 1, 0) || LPAD(ECOMARK_FLG, 1, 0) || LPAD(HOUZAI_YOUTO, 1, 0) || LPAD(HOUZAI_ZAISHITU, 1, 0) || LPAD(HOUZAI_RECYCLE, 1, 0) || RPAD(KIKAN_TANI, 1, ' ') || LPAD(SHUKYU, 2, 0) || LPAD(DOSU, 3, 0) || RPAD(CHINRETU_CD, 1, ' ') || RPAD(DANZUMI_CD, 2, ' ') || RPAD(KASANARI_CD, 1, ' ') || LPAD(KASANARI_SZ, 3, 0) || LPAD(ASSHUKU, 2, 0) || RPAD(SHUBETU_CD, 2, ' ') || LPAD(HANBAI_CD, 6, 0) || LPAD(URABARI, 1, 0) || LPAD(PC_OUTPUT, 1, 0) || RPAD(SHOHINCD_OYA, 14, ' ') || LPAD(BINKBN, 1, 0) || LPAD(HACHU_MON, 1, 0) || LPAD(HACHU_TUE, 1, 0) || LPAD(HACHU_WED, 1, 0) || LPAD(HACHU_THU, 1, 0) || LPAD(HACHU_FRI, 1, 0) || LPAD(HACHU_SAT, 1, 0) || LPAD(HACHU_SUN, 1, 0) || LPAD(LTPTN, 3, 0) || LPAD(SHIMESU, 1, 0) || LPAD(TOROKUMOTO, 1, 0) || LPAD(LTIME_MON, 2, 0) || LPAD(LTIME_TUE, 2, 0) || LPAD(LTIME_WED, 2, 0) || LPAD(LTIME_THU, 2, 0) || LPAD(LTIME_FRI, 2, 0) || LPAD(LTIME_SAT, 2, 0) || LPAD(LTIME_SUN, 2, 0) || LPAD(ZEIKBN, 1, 0) || LPAD(UPDKBN, 1, 0) FROM INAIF.HA_A11SHOH_Y ORDER BY SHOHINCD, MSTCHG_Y_YMD;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
