REM [015][UPDATE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET INFILENAME=
REM ===== 商品
SET MSG=%DATE% %TIME% 商品コード空き番 INAMS.SYSSHNCD_AKI UPDATE処理（更新区分=1＆登録日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAAD.SYSSHNCD_AKI T1 SET USEFLG = 0 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE DATE_FORMAT(ADDDT, '%%Y%%m%%d') IN (SELECT DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND UPDKBN = 1 AND T1.SHNCD = T2.SHNCD) ; COMMIT;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 販売コード空き番 INAMS.SYSURICD_AKI UPDATE処理（更新区分=1＆登録日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAAD.SYSURICD_AKI T1 SET USEFLG = 0 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE DATE_FORMAT(ADDDT, '%%Y%%m%%d') IN (SELECT DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND UPDKBN = 1 AND T1.URICD = T2.URICD); COMMIT;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 商品 INAMS.MSTSHN DELETE処理（更新区分=1＆登録日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS.MSTSHN WHERE DATE_FORMAT(ADDDT, '%%Y%%m%%d') IN (SELECT DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND UPDKBN = 1; COMMIT;" >>%OUTFILE% 2>&1



REM IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
