REM [036][UPDATE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET INFILENAME=
SET MSG=%DATE% %TIME% INAAD.SYSSHORIDT UPDATE処理(処理日付+1)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAAD.SYSSHORIDT T1, (SELECT 6 AS ID, SHORIDT FROM (SELECT CAST(DATE_FORMAT(DATE_FORMAT(AA.SHORIDT, '%%Y%%m%%d') + INTERVAl 1 DAY, '%%Y%%m%%d') AS SIGNED) AS SHORIDT FROM INAAD.SYSSHORIDT AA) A) T2 SET T1.SHORIDT = T2.SHORIDT, T1.OPERATOR = '035', T1.UPDDT = CURRENT_TIMESTAMP WHERE T1.ID = T2.ID; COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
