REM [000][SYSBATCHDT_TK]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAPARM.SYSBATCHDT_TK MERGE処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAPARM.SYSBATCHDT_TK T1, (SELECT 'DAILY' AS SMODE, DATE_FORMAT(A.SHORIDT, '%%Y%%m%%d') AS DT, A.SHORIDT AS DT_INT, CAST(DATE_FORMAT(A.SHORIDT, '%%Y%%m%%d') AS DATETIME) AS DTTIME, CAST(CAST(DATE_FORMAT(A.SHORIDT, '%%Y%%m%%d') AS DATETIME) AS SIGNED) AS DTTIME_INT, WEEKDAY(DATE_FORMAT(A.SHORIDT, '%%Y%%m%%d')) + 1 AS YOBI FROM (SELECT CAST(DATE_FORMAT(DATE_FORMAT(AA.SHORIDT, '%%Y%%m%%d'), '%%Y%%m%%d') AS SIGNED) AS SHORIDT FROM INAAD.SYSSHORIDT AA) A) T2 SET T1.DT = T2.DT, T1.DT_INT = T2.DT_INT, T1.DTTIME = T2.DTTIME, T1.DTTIME_INT = T2.DTTIME_INT, T1.YOBI = T2.YOBI WHERE T1.SMODE = T2.SMODE; COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
