REM [015][UPDATE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET INFILENAME=
REM ===== 商品_予約

REM 削除前データの保持
SET MSG=%DATE% %TIME% INAWK.MSTSHN LOAD処理(商品マスタ)
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e " TRUNCATE TABLE INAWK.MSTSHN;INSERT IGNORE INTO INAWK.MSTSHN SELECT SHNCD, YOYAKUDT, TENBAIKADT, YOT_BMNCD, YOT_DAICD, YOT_CHUCD, YOT_SHOCD, URI_BMNCD, URI_DAICD, URI_CHUCD, URI_SHOCD, BMNCD, DAICD, CHUCD, SHOCD, SSHOCD, ATSUK_STDT, ATSUK_EDDT, TEISHIKBN, SHNAN, SHNKN, PCARDKN, POPKN, RECEIPTAN, RECEIPTKN, PCKBN, KAKOKBN, ICHIBAKBN, SHNKBN, SANCHIKN, SSIRCD, HSPTN, RG_ATSUKFLG, RG_GENKAAM, RG_BAIKAAM, RG_IRISU, RG_IDENFLG, RG_WAPNFLG, HS_ATSUKFLG, HS_GENKAAM, HS_BAIKAAM, HS_IRISU, HS_WAPNFLG, HS_SPOTMINSU, HP_SWAPNFLG, KIKKN, UP_YORYOSU, UP_TYORYOSU, UP_TANIKBN, SHNYOKOSZ, SHNTATESZ, SHNOKUSZ, SHNJRYOSZ, PBKBN, KOMONOKBM, TANAOROKBN, TEIKEIKBN, ODS_HARUSU, ODS_NATSUSU, ODS_AKISU, ODS_FUYUSU, ODS_NYUKASU, ODS_NEBIKISU, PCARD_SHUKBN, PCARD_IROKBN, ZEIKBN, ZEIRTKBN, ZEIRTKBN_OLD, ZEIRTHENKODT, SEIZOGENNISU, TEIKANKBN, MAKERCD, IMPORTKBN, SIWAKEKBN, HENPIN_KBN, TAISHONENSU, CALORIESU, ELPFLG, BELLMARKFLG, RECYCLEFLG, ECOFLG, HZI_YOTO, HZI_ZAISHITU, HZI_RECYCLE, KIKANKBN, SHUKYUKBN, DOSU, CHINRETUCD, DANTUMICD, KASANARICD, KASANARISZ, ASSHUKURT, SHUBETUCD, URICD, SALESCOMKN, URABARIKBN, PCARD_OPFLG, PARENTCD, BINKBN, HAT_MONKBN, HAT_TUEKBN, HAT_WEDKBN, HAT_THUKBN, HAT_FRIKBN, HAT_SATKBN, HAT_SUNKBN, READTMPTN, SIMEKAISU, IRYOREFLG, TOROKUMOTO, UPDKBN, SENDFLG, OPERATOR, ADDDT, UPDDT, K_HONKB, K_WAPNFLG_R, K_WAPNFLG_H, K_TORIKB, ITFCD, CENTER_IRISU FROM INAMS.MSTSHN; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 商品 INAMS.MSTSHN DELETE処理（マスタ変更予定=処理日付＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSHN T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN=0) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1

REM 20180725 マスタ変更予定日、店売価実施日を0にしない、送信フラグ=1、更新日を変更しない
REM 20180417 商品マスタの登録日を維持、更新日はマスタ変更予定日にする、ITFコード、センター入数を追加
SET MSG=%DATE% %TIME% 商品 INAMS.MSTSHN LOAD処理（マスタ変更予定=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAMS.MSTSHN SELECT T1.SHNCD, T1.YOYAKUDT, T1.TENBAIKADT, T1.YOT_BMNCD, T1.YOT_DAICD, T1.YOT_CHUCD, T1.YOT_SHOCD, T1.URI_BMNCD, T1.URI_DAICD, T1.URI_CHUCD, T1.URI_SHOCD, T1.BMNCD, T1.DAICD, T1.CHUCD, T1.SHOCD, T1.SSHOCD, T1.ATSUK_STDT, T1.ATSUK_EDDT, T1.TEISHIKBN, T1.SHNAN, T1.SHNKN, T1.PCARDKN, T1.POPKN, T1.RECEIPTAN, T1.RECEIPTKN, T1.PCKBN, T1.KAKOKBN, T1.ICHIBAKBN, T1.SHNKBN, T1.SANCHIKN, T1.SSIRCD, T1.HSPTN, T1.RG_ATSUKFLG, T1.RG_GENKAAM, T1.RG_BAIKAAM, T1.RG_IRISU, T1.RG_IDENFLG, T1.RG_WAPNFLG, T1.HS_ATSUKFLG, T1.HS_GENKAAM, T1.HS_BAIKAAM, T1.HS_IRISU, T1.HS_WAPNFLG, T1.HS_SPOTMINSU, T1.HP_SWAPNFLG, T1.KIKKN, T1.UP_YORYOSU, T1.UP_TYORYOSU, T1.UP_TANIKBN, T1.SHNYOKOSZ, T1.SHNTATESZ, T1.SHNOKUSZ, T1.SHNJRYOSZ, T1.PBKBN, T1.KOMONOKBM, T1.TANAOROKBN, T1.TEIKEIKBN, T1.ODS_HARUSU, T1.ODS_NATSUSU, T1.ODS_AKISU, T1.ODS_FUYUSU, T1.ODS_NYUKASU, T1.ODS_NEBIKISU, T1.PCARD_SHUKBN, T1.PCARD_IROKBN, T1.ZEIKBN, T1.ZEIRTKBN, T1.ZEIRTKBN_OLD, T1.ZEIRTHENKODT, T1.SEIZOGENNISU, T1.TEIKANKBN, T1.MAKERCD, T1.IMPORTKBN, T1.SIWAKEKBN, T1.HENPIN_KBN, T1.TAISHONENSU, T1.CALORIESU, T1.ELPFLG, T1.BELLMARKFLG, T1.RECYCLEFLG, T1.ECOFLG, T1.HZI_YOTO, T1.HZI_ZAISHITU, T1.HZI_RECYCLE, T1.KIKANKBN, T1.SHUKYUKBN, T1.DOSU, T1.CHINRETUCD, T1.DANTUMICD, T1.KASANARICD, T1.KASANARISZ, T1.ASSHUKURT, T1.SHUBETUCD, T1.URICD, T1.SALESCOMKN, T1.URABARIKBN, T1.PCARD_OPFLG, T1.PARENTCD, T1.BINKBN, T1.HAT_MONKBN, T1.HAT_TUEKBN, T1.HAT_WEDKBN, T1.HAT_THUKBN, T1.HAT_FRIKBN, T1.HAT_SATKBN, T1.HAT_SUNKBN, T1.READTMPTN, T1.SIMEKAISU, T1.IRYOREFLG, T1.TOROKUMOTO, T1.UPDKBN, 1 AS SENDFLG, T1.OPERATOR, CASE WHEN T3.SHNCD IS NULL THEN T1.ADDDT WHEN T3.UPDKBN <> 1 THEN T3.ADDDT ELSE T1.ADDDT END AS ADDDT, DATE_FORMAT(T1.YOYAKUDT, '%%Y%%m%%d') AS UPDDT, T1.K_HONKB, T1.K_WAPNFLG_R, T1.K_WAPNFLG_H, T1.K_TORIKB, T1.ITFCD, T1.CENTER_IRISU FROM INAMS.MSTSHN_Y T1 LEFT OUTER JOIN INAWK.MSTSHN T3 ON T1.SHNCD = T3.SHNCD WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN = 0 ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



REM ===== 仕入グループ商品_予約
SET MSG=%DATE% %TIME% 仕入グループ商品 INAMS.MSTSIRGPSHN DELETE処理（マスタ変更予定=処理日付＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSIRGPSHN T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN=0) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1
REM 自データと一致情報を削除
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSIRGPSHN T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD FROM INAMS.MSTSIRGPSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT)) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 仕入グループ商品 INAMS.MSTSIRGPSHN LOAD処理（マスタ変更予定=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAMS.MSTSIRGPSHN SELECT SHNCD, TENGPCD, YOYAKUDT, AREAKBN, SIRCD, HSPTN, 1 AS SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAMS.MSTSIRGPSHN_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN = 0) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT) ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



REM ===== 売価コントロール_予約
SET MSG=%DATE% %TIME% 売価コントロール INAMS.MSTBAIKACTL DELETE処理（マスタ変更予定=処理日付＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS.MSTBAIKACTL T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN=0) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1
REM 自データと一致情報を削除
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS.MSTBAIKACTL T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD FROM INAMS.MSTBAIKACTL_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT)) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 売価コントロール INAMS.MSTBAIKACTL LOAD処理（マスタ変更予定=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAMS.MSTBAIKACTL SELECT SHNCD, TENGPCD, YOYAKUDT, AREAKBN, GENKAAM, BAIKAAM, IRISU, 1 AS SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAMS.MSTBAIKACTL_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN = 0) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT) ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR




REM ===== ソースコード管理_予約
SET MSG=%DATE% %TIME% ソースコード管理 INAMS.MSTSRCCD DELETE処理（マスタ変更予定=処理日付＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM >> %OUTFILE% DB2 -L %OUTTIME% "DELETE FROM INAMS.MSTSRCCD T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN=0) T3 WHERE T3.SHNCD = T0.SHNCD)"
REM 自データと一致情報を削除
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSRCCD T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD FROM INAMS.MSTSRCCD_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT)) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ソースコード管理 INAMS.MSTSRCCD LOAD処理（マスタ変更予定=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAMS.MSTSRCCD SELECT SHNCD, SRCCD, YOYAKUDT, SEQNO, SOURCEKBN, 1 AS SENDFLG, OPERATOR, ADDDT, UPDDT, YUKO_STDT, YUKO_EDDT FROM INAMS.MSTSRCCD_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN = 0) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT) ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR




REM ===== 自動発注管理_予約
SET MSG=%DATE% %TIME% 自動発注管理 INAMS.MSTAHS DELETE処理（マスタ変更予定=処理日付＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e% "DELETE FROM INAMS.MSTAHS T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN=0) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 自動発注管理 INAMS.MSTAHS LOAD処理（マスタ変更予定=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAMS.MSTAHS SELECT SHNCD, TENCD, YOYAKUDT, AHSKB, 1 AS SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAMS.MSTAHS_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN = 0) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT) ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR




REM ===== グループ分類管理_予約
SET MSG=%DATE% %TIME% グループ分類管理 INAMS.MSTGRP DELETE処理（マスタ変更予定=処理日付＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS.MSTGRP T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN=0) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% グループ分類管理 INAMS.MSTGRP LOAD処理（マスタ変更予定=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAMS.MSTGRP SELECT SHNCD, GRPID, YOYAKUDT, SEQNO, 1 AS SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAMS.MSTGRP_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN = 0) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT) ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR




REM ===== 店別異部門管理_予約
SET MSG=%DATE% %TIME% 店別異部門管理 INAMS.MSTSHNTENBMN DELETE処理（マスタ変更予定=処理日付＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSHNTENBMN T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN=0) T3 WHERE T3.SHNCD = T0.SHNCD) ; commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 店別異部門管理 INAMS.MSTSHNTENBMN LOAD処理（マスタ変更予定=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAMS.MSTSHNTENBMN SELECT SHNCD, TENSHNCD, TENGPCD, YOYAKUDT, AREAKBN, 1 AS SENDFLG, OPERATOR, ADDDT, UPDDT, SRCCD FROM INAMS.MSTSHNTENBMN_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE T2.SHORIDT = T1.YOYAKUDT) AND T1.UPDKBN = 0) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT) ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



REM IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
