REM [015][UPDATE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET INFILENAME=



REM ===== 仕入グループ商品_予約
SET MSG=%DATE% %TIME% 仕入グループ商品 INAMS.MSTSIRGPSHN DELETE処理（店売価実績日=処理日付＋1日＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSIRGPSHN_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE CAST(DATE_FORMAT(DATE_FORMAT(T2.SHORIDT, '%%Y%%m%%d') + INTERVAL 1 DAY, '%%Y%%m%%d') AS SIGNED) = T1.TENBAIKADT)) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT); COMMIT;" >>%OUTFILE% 2>&1

REM ===== 売価コントロール_予約
SET MSG=%DATE% %TIME% 売価コントロール INAMS.MSTBAIKACTL DELETE処理（店売価実績日=処理日付＋1日＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTBAIKACTL_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE CAST(DATE_FORMAT(DATE_FORMAT(T2.SHORIDT, '%%Y%%m%%d') + INTERVAL 1 DAY, '%%Y%%m%%d') AS SIGNED) = T1.TENBAIKADT)) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT) ; COMMIT;" >>%OUTFILE% 2>&1

REM ===== ソースコード管理_予約
SET MSG=%DATE% %TIME% ソースコード管理 INAMS.MSTSRCCD DELETE処理（店売価実績日=処理日付＋1日＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSRCCD_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE CAST(DATE_FORMAT(DATE_FORMAT(T2.SHORIDT, '%%Y%%m%%d') + INTERVAl 1 DAY, '%%Y%%m%%d') AS SIGNED) = T1.TENBAIKADT)) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT); COMMIT;" >>%OUTFILE% 2>&1

REM ===== 自動発注管理_予約
SET MSG=%DATE% %TIME% 自動発注管理 INAMS.MSTAHS DELETE処理（店売価実績日=処理日付＋1日＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTAHS_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE CAST(DATE_FORMAT(DATE_FORMAT(T2.SHORIDT, '%%Y%%m%%d') + INTERVAl 1 DAY, '%%Y%%m%%d') AS SIGNED) = T1.TENBAIKADT)) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT); COMMIT;" >>%OUTFILE% 2>&1

REM ===== グループ分類管理_予約
SET MSG=%DATE% %TIME% グループ分類管理 INAMS.MSTGRP DELETE処理（店売価実績日=処理日付＋1日＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTGRP_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE CAST(DATE_FORMAT(DATE_FORMAT(T2.SHORIDT, '%%Y%%m%%d') + INTERVAl 1 DAY, '%%Y%%m%%d') AS SIGNED) = T1.TENBAIKADT)) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT); COMMIT;" >>%OUTFILE% 2>&1

REM ===== 店別異部門管理_予約
SET MSG=%DATE% %TIME% 店別異部門管理 INAMS.MSTSHNTENBMN DELETE処理（店売価実績日=処理日付＋1日＆商品_予約.商品=〃.商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSHNTENBMN_Y T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SHNCD, T1.YOYAKUDT FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE CAST(DATE_FORMAT(DATE_FORMAT(T2.SHORIDT, '%%Y%%m%%d') + INTERVAl 1 DAY, '%%Y%%m%%d') AS SIGNED) = T1.TENBAIKADT)) T3 WHERE T3.SHNCD = T0.SHNCD AND T3.YOYAKUDT = T0.YOYAKUDT); COMMIT;" >>%OUTFILE% 2>&1


REM ===== 商品_予約
SET MSG=%DATE% %TIME% 商品 INAMS.MSTSHN DELETE処理（店売価実績日=処理日付＋1日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAAD.SYSSHORIDT T2 WHERE CAST(DATE_FORMAT(DATE_FORMAT(T2.SHORIDT, '%%Y%%m%%d') + INTERVAl 1 day, '%%Y%%m%%d') AS SIGNED) = T1.TENBAIKADT); COMMIT;" >>%OUTFILE% 2>&1


REM IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
