REM [079][A11TK15]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIN.BFG01_PLU → INAWK.A11TK15 ロード処理（店別催し送信状況_店舗ワーク）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.A11TK15 ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.A11TK15 SELECT T1.*, NULL AS UPDDT FROM (SELECT DISTINCT 1 AS DATAKBN, EVNTCD2 || EVNT_S_DATE || EVNTCD4 AS SMOYSCD, '' AS SHNCD, 0 AS TENPO, 0 AS HBSTDT, 0 AS HBEDDT, '' AS OPERATOR, NULL AS ADDDT FROM INAIN.BFG01_PLU BFG01 WHERE EXISTS (SELECT 1 FROM (SELECT BFG01.EVNTCD2, BFG01.EVNT_S_DATE1, BFG01.EVNTCD3, BFG01.EVNTCD4, MAX(BFG01.TENPO) AS TENPO FROM INAIN.BFG01_PLU BFG01 GROUP BY BFG01.EVNTCD2, BFG01.EVNT_S_DATE1, BFG01.EVNTCD3, BFG01.EVNTCD4) BFG01_EXS WHERE BFG01.EVNTCD2 = BFG01_EXS.EVNTCD2 AND BFG01.EVNT_S_DATE1 = BFG01_EXS.EVNT_S_DATE1 AND BFG01.EVNTCD3 = BFG01_EXS.EVNTCD3 AND BFG01.EVNTCD4 = BFG01_EXS.EVNTCD4 AND BFG01.TENPO = BFG01_EXS.TENPO) UNION ALL SELECT 2 AS DATAKBN, EVNTCD2 || EVNT_S_DATE || EVNTCD4 AS SMOYSCD, BFG01.SYOHINCD1 || BFG01.SYOHINCD2 AS SHNCD, BFG01.TENPO AS TENPO, BFG01.SALE_S_DATE1 || BFG01.SALE_S_DATE AS HBSTDT, BFG01.SALE_E_DATE1 || BFG01.SALE_E_DATE AS HBEDDT, '' AS OPERATOR, CAST(CURRENT_DATE AS DATETIME) AS ADDDT FROM INAIN.BFG01_PLU BFG01) T1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.A11TK15;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
