REM [080][A11TK10]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIN.BFG01_BM → INAWK.A11TK10 ロード処理（店別B/M送信状況_商品ワーク）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAWK.A11TK10 ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.A11TK10 SELECT T1.*, NULL AS UPDDT FROM (SELECT DISTINCT 1 AS DATAKBN, EVNTCD2 || EVNT_S_DATE || EVNTCD4 AS SMOYSCD, 0 AS SBMNO, '' AS SHNCD, 0 AS GENKAAM, '' AS OPERATOR, NULL AS ADDDT FROM INAIN.BFG01_BM BFG01 WHERE EXISTS (SELECT 1 FROM (SELECT BFG01.EVNTCD2, BFG01.EVNT_S_DATE1, BFG01.EVNTCD3, BFG01.EVNTCD4 FROM INAIN.BFG01_BM BFG01 GROUP BY BFG01.EVNTCD2, BFG01.EVNT_S_DATE1, BFG01.EVNTCD3, BFG01.EVNTCD4) BFG01_EXS WHERE BFG01.EVNTCD2 = BFG01_EXS.EVNTCD2 AND BFG01.EVNT_S_DATE1 = BFG01_EXS.EVNT_S_DATE1 AND BFG01.EVNTCD3 = BFG01_EXS.EVNTCD3 AND BFG01.EVNTCD4 = BFG01_EXS.EVNTCD4) UNION ALL SELECT DISTINCT 2 AS DATAKBN, EVNTCD2 || EVNT_S_DATE || EVNTCD4 AS SMOYSCD, BFG01.BANBANG AS SBMNO, BFG01.SYOHINCD1 || BFG01.SYOHINCD2 AS SHNCD, CAST(SUBSTR(BFG01.SALE_GENKA, 1, 6) || '.' || SUBSTR(BFG01.SALE_GENKA, 7, 2) AS DECIMAL (8, 2)) AS GENKAAM, '' AS OPERATOR, CAST(CURRENT_DATE AS DATETIME) AS ADDDT FROM INAIN.BFG01_BM BFG01 WHERE EXISTS (SELECT 1 FROM (SELECT BFG01.EVNTCD2, BFG01.EVNT_S_DATE1, BFG01.EVNTCD3, BFG01.EVNTCD4, BFG01.BANBANG, MAX(BFG01.SYOHINCD1) AS SYOHINCD1 FROM INAIN.BFG01_BM BFG01 GROUP BY BFG01.EVNTCD2, BFG01.EVNT_S_DATE1, BFG01.EVNTCD3, BFG01.EVNTCD4, BFG01.BANBANG) BFG01_EXS WHERE BFG01.EVNTCD2 = BFG01_EXS.EVNTCD2 AND BFG01.EVNT_S_DATE1 = BFG01_EXS.EVNT_S_DATE1 AND BFG01.EVNTCD3 = BFG01_EXS.EVNTCD3 AND BFG01.EVNTCD4 = BFG01_EXS.EVNTCD4 AND BFG01.BANBANG = BFG01_EXS.BANBANG AND BFG01.SYOHINCD1 = BFG01_EXS.SYOHINCD1)) T1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.A11TK10;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
