REM [079][BFG01_BM]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

rem INAIN.BFG01_BM テーブルクリア
SET MSG=%DATE% %TIME% TRUNCATE INAIN.BFG01_BM
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIN.BFG01_BM ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% TRUNCATE INAIN.BFG01_BM
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIN.BFG01_BM_01 ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

rem ファイルパスの設定
SET INFILENAME=0080
set filename=DATA\%INFILENAME%
set filename_tmp=%filename:\=\\%

SET MSG=%DATE% %TIME%  →  BFG01_BM_01 LOAD処理
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --local_infile=1 --show-warnings -vv -e "load data local infile '%filename_tmp%' IGNORE into table INAIN.BFG01_BM_01 character set cp932 fields terminated by ',' ESCAPED BY '' lines terminated by '\r\n' (@1) SET DATA = @1; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


rem BFG01_BMへU登録 =========================================================================

SET MSG=%DATE% %TIME%  →  LOAD処理(催し送信状況ファイル（ＰＬＵ）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIN.BFG01_BM SELECT MID(DATA, 1, 3) AS TENPO, MID(DATA, 4, 2) AS SAKU_DATE1, MID(DATA, 6, 6) AS SAKU_DATE, MID(DATA, 12, 4) AS SAKU_TIME, MID(DATA, 16, 1) AS SYORIKBN, MID(DATA, 17, 1) AS EVNTCD1, MID(DATA, 18, 2) AS EVNTCD2, MID(DATA, 20, 4) AS EVNTCD3, MID(DATA, 24, 2) AS EVNTCD4, MID(DATA, 26, 3) AS SHIFT_KI1, MID(DATA, 29, 20) AS EVNTNM, MID(DATA, 49, 20) AS EVNTKNM1, MID(DATA, 69, 20) AS EVNTKNM2, MID(DATA, 89, 2) AS EVNT_S_DATE1, MID(DATA, 91, 6) AS EVNT_S_DATE, MID(DATA, 97, 2) AS EVNT_E_DATE1, MID(DATA, 99, 6) AS EVNT_E_DATE, MID(DATA, 105, 9) AS EVNT_YOSAN, MID(DATA, 114, 1) AS HANBAI_KBN, MID(DATA, 115, 8) AS SYOHINCD1, MID(DATA, 123, 5) AS SYOHINCD2, MID(DATA, 128, 12) AS PLUCD1, MID(DATA, 140, 1) AS PLUCD2, MID(DATA, 141, 2) AS SALE_S_DATE1, MID(DATA, 143, 6) AS SALE_S_DATE, MID(DATA, 149, 2) AS SALE_E_DATE1, MID(DATA, 151, 6) AS SALE_E_DATE, MID(DATA, 157, 6) AS SALE_BAIKA, MID(DATA, 163, 6) AS SALE_SAGEHABA, MID(DATA, 169, 8) AS SALE_GENKA, MID(DATA, 177, 1) AS GENKA_FLG, MID(DATA, 178, 7) AS YOSAN_TENSU, MID(DATA, 185, 9) AS YOSAN_GAKU, MID(DATA, 194, 4) AS BAND_NO, MID(DATA, 198, 3) AS SHIFT_KI2, MID(DATA, 201, 20) AS BAND_NM, MID(DATA, 221, 20) AS BAND_KNM1, MID(DATA, 241, 20) AS BAND_KNM2, MID(DATA, 261, 3) AS BAND_KOSU1, MID(DATA, 264, 6) AS BAND_BAIKA1, MID(DATA, 270, 3) AS BAND_KOSU2, MID(DATA, 273, 6) AS BAND_BAIKA2, MID(DATA, 279, 3) AS BUNBMC, MID(DATA, 282, 1) AS MOYOK, MID(DATA, 283, 6) AS MOYOKA, MID(DATA, 289, 3) AS MOYORE, MID(DATA, 292, 3) AS BANBANG, MID(DATA, 295, 5) AS GERITU, MID(DATA, 300, 8) AS PLUHISB FROM INAIN.BFG01_BM_01;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIN.BFG01_BM;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
