REM [000][AN_NOUNYU_BFR_NEW]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_BFR_SHN_WK テーブルクリア
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_NOUNYU_BFR_SHN_WK;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_BFR_SHN_WK ロード処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.AN_NOUNYU_BFR_SHN_WK SELECT WK05_PRE.MOYSCD, WK05_PRE.MOYSKBN, WK05_PRE.MOYSSTDT, WK05_PRE.MOYSRBAN, WK05_PRE.BMNCD, WK05_PRE.KANRINO, WK05_PRE.KANRIENO, WK05_PRE.TENCD, WK05_PRE.NNDT, WK05_PRE.SHUNO, WK05_PRE.TSHUFLG, WK05_PRE.MYOSNNSTDT, WK05_PRE.MYOSNNEDDT, WK05_PRE.NENMATKBN, WK05_PRE.JLSTCREFLG, WK05_PRE.JLSTCREDT, WK05_PRE.JHTSUINDT, WK05_PRE.WEEKHTDT, WK05_PRE.QADEVSTDT, WK05_PRE.QADEVEDFLG, WK05_PRE.TENGPCD, WK05_PRE.KYOSEIFLG, TGSHN.SHNCD, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, WK05_PRE.NNSTDT, WK05_PRE.NNEDDT, TGSHN.JUFLG, TGSHN.JUHTDT, TGSHN.BINKBN, 0 AS NNSLIDE, TGSHN.CUTTENFLG, TGSHN.SHUDENFLG, WK05_PRE.HSUU, WK05_PRE.HTASU, WK05_PRE.PTNNO, WK05_PRE.TSEIKBN, WK05_PRE.ZJSKFLG, WK05_PRE.NNWEEKHTDT, WK05_PRE.QASYUKBN, WK05_PRE.LDSYFLG, WK05_PRE.MBSYFLG, WK05_PRE.ITMSELKBN, CASE WHEN TGSHN.GTSIMECHGKBN = 3 THEN WK05_PRE.GTSIMECHGKBN ELSE TGSHN.GTSIMECHGKBN END AS GTSIMECHGKBN, CASE WHEN TGSHN.GTSIMECHGKBN = 3 THEN WK05_PRE.GTSIMEOKFLG ELSE TGSHN.GTSIMEOKFLG END AS GTSIMEOKFLG, WK05_PRE.SENDFLG AS SENDFLG, 9 AS UPDKBN, MIN(WK05_PRE.TENCD) OVER (PARTITION BY WK05_PRE.MOYSCD, WK05_PRE.MOYSKBN, WK05_PRE.MOYSSTDT, WK05_PRE.MOYSRBAN, WK05_PRE.BMNCD, WK05_PRE.KANRINO, WK05_PRE.KANRIENO) AS BASE_TENCD, MIN(WK05_PRE.NNDT) OVER (PARTITION BY WK05_PRE.MOYSCD, WK05_PRE.MOYSKBN, WK05_PRE.MOYSSTDT, WK05_PRE.MOYSRBAN, WK05_PRE.BMNCD, WK05_PRE.KANRINO, WK05_PRE.KANRIENO, WK05_PRE.TENCD) AS BASE_NNDT FROM INAPRE.AN_NOUNYU_BFR WK05_PRE INNER JOIN INATK2.TOKTG_SHN TGSHN ON WK05_PRE.MOYSKBN = TGSHN.MOYSKBN AND WK05_PRE.MOYSSTDT = TGSHN.MOYSSTDT AND WK05_PRE.MOYSRBAN = TGSHN.MOYSRBAN AND WK05_PRE.BMNCD = TGSHN.BMNCD AND WK05_PRE.KANRINO = TGSHN.KANRINO AND WK05_PRE.KANRIENO = TGSHN.KANRIENO AND TGSHN.UPDKBN <> 1 AND TGSHN.NNSTDT <> 0 AND TGSHN.SENDFLG <> 1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_BFR_SHN_WK;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
