REM [000][AN_ZW_NOUNYU_NEQ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_ZW_NOUNYU_NEQ ロード処理（全特アンケート無 納入データ 全品割引）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_ZW_NOUNYU_NEQ ;commit;" >> %OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIF.AN_ZW_NOUNYU_NEQ SELECT DISTINCT LPAD(SPSHN.MOYSKBN, 1, 0) || LPAD(SPSHN.MOYSSTDT, 6, 0) || LPAD(SPSHN.MOYSRBAN, 3, 0) AS MOYSCD, SPSHN.MOYSKBN, SPSHN.MOYSSTDT, SPSHN.MOYSRBAN, SPSHN.BMNCD, SPSHN.KANRINO, SPSHN.KANRIENO, TC17.TENCD, TC17.NNDT, MC.SHUNO, MS.TSHUFLG, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNSTDT_TGF ELSE MC.NNSTDT END AS MYOSNNSTDT, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNEDDT_TGF ELSE MC.NNEDDT END AS MYOSNNEDDT, MC.NENMATKBN, 0 AS JLSTCREFLG, SPSHN.JLSTCREDT, SPSHN.JHTSUINDT, SPSHN.WEEKHTDT, 0 AS QADEVSTDT, 0 AS QADEVEDFLG, 0 AS TENGPCD, 0 AS KYOSEIFLG, SPSHN.SHNCD, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, SPSHN.NNSTDT, SPSHN.NNEDDT, SPSHN.JUFLG, SPSHN.JUHTDT, SPSHN.BINKBN, 0 AS NNSLIDE, SPSHN.CUTTENFLG AS CUTTENFLG, SPSHN.SHUDENFLG, TC17.HSUU, TC17.HTASU, TC17.PTNNO, TC17.TSEIKBN, TC17.ZJSKFLG, TC17.WEEKHTDT AS NNWEEKHTDT, 0 AS QASYUKBN, 1 AS LDSYFLG, 1 AS MBSYFLG, 1 AS ITMSELKBN, 0 AS GTSIMECHGKBN, 0 AS GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM INATK2.TOKSP_SHN SPSHN INNER JOIN INAWK.AN_ZW_NOUNYU_NEQ_TEN TC17 ON SPSHN.MOYSKBN = TC17.MOYSKBN AND SPSHN.MOYSSTDT = TC17.MOYSSTDT AND SPSHN.MOYSRBAN = TC17.MOYSRBAN AND SPSHN.BMNCD = TC17.BMNCD AND SPSHN.KANRINO = TC17.KANRINO AND SPSHN.KANRIENO = TC17.KANRIENO INNER JOIN (SELECT MC.* FROM INATK2.TOKMOYCD MC WHERE MC.UPDKBN <> 1) MC ON SPSHN.MOYSKBN = MC.MOYSKBN AND SPSHN.MOYSSTDT = MC.MOYSSTDT AND SPSHN.MOYSRBAN = MC.MOYSRBAN INNER JOIN (SELECT * FROM INATK2.TOKMOYSYU MS LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL - 1 YEAR), '%%y') <= SUBSTR(MS.SHUNO, 1, 2) AND SUBSTR(MS.SHUNO, 1, 2) <= DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL + 1 YEAR), '%%y')) MS ON MS.SHUNO = MC.SHUNO LEFT OUTER JOIN INAPARM.PRAM_FRSDRYJUD FDJ ON FDJ.BMNCD = SPSHN.BMNCD AND FDJ.JUDFLG = 'S' WHERE SPSHN.ADDSHUKBN = 1 AND SPSHN.UPDKBN <> 1 AND SPSHN.NNSTDT <> 0;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_ZW_NOUNYU_NEQ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
