REM [000][JH_TOK_ERR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.JH_TOK_ERR ロード処理（特売エラーファイル）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "INSERT IGNORE INTO INAIF.JH_TOK_ERR WITH JTE AS (SELECT COUNT(*) AS SEQ FROM INAIF.JH_TOK_ERR JTE), JH_TEN_SYUSEI AS (SELECT BMNCD, TENCD, SHNCD, NNDT, BINKBN, HTSU, 0 AS ERRKBN, 0 AS ADDDT FROM (SELECT BMNCD, TENCD, SHNCD, NNDT, BINKBN, HTSU, ROW_NUMBER() OVER (PARTITION BY BMNCD, TENCD, SHNCD, NNDT, BINKBN ORDER BY HTSU DESC) AS RNO FROM (SELECT ADDSHN.BMNCD, ADDSHN.TENCD, ADDSHN.SHNCD, ADDSHN.BINKBN, CASE WHEN NUMS.SEQ = 1 THEN ADDSHN.JTDT_01 WHEN NUMS.SEQ = 2 THEN ADDSHN.JTDT_02 WHEN NUMS.SEQ = 3 THEN ADDSHN.JTDT_03 WHEN NUMS.SEQ = 4 THEN ADDSHN.JTDT_04 WHEN NUMS.SEQ = 5 THEN ADDSHN.JTDT_05 WHEN NUMS.SEQ = 6 THEN ADDSHN.JTDT_06 WHEN NUMS.SEQ = 7 THEN ADDSHN.JTDT_07 WHEN NUMS.SEQ = 8 THEN ADDSHN.JTDT_08 WHEN NUMS.SEQ = 9 THEN ADDSHN.JTDT_09 WHEN NUMS.SEQ = 10 THEN ADDSHN.JTDT_10 END AS NNDT, CASE WHEN NUMS.SEQ = 1 THEN ADDSHN.HTSU_01 WHEN NUMS.SEQ = 2 THEN ADDSHN.HTSU_02 WHEN NUMS.SEQ = 3 THEN ADDSHN.HTSU_03 WHEN NUMS.SEQ = 4 THEN ADDSHN.HTSU_04 WHEN NUMS.SEQ = 5 THEN ADDSHN.HTSU_05 WHEN NUMS.SEQ = 6 THEN ADDSHN.HTSU_06 WHEN NUMS.SEQ = 7 THEN ADDSHN.HTSU_07 WHEN NUMS.SEQ = 8 THEN ADDSHN.HTSU_08 WHEN NUMS.SEQ = 9 THEN ADDSHN.HTSU_09 WHEN NUMS.SEQ = 10 THEN ADDSHN.HTSU_10 END AS HTSU FROM INAWK.JH_RTN_ADDSHN ADDSHN LEFT OUTER JOIN INAPARM.MSTNUMS NUMS ON NUMS.SEQ BETWEEN 1 AND 10 UNION ALL SELECT TEN.BMNCD, TEN.TENCD, TEN.SHNCD, TEN.BINKBN, CASE WHEN NUMS.SEQ = 1 THEN TEN.JTDT_01 WHEN NUMS.SEQ = 2 THEN TEN.JTDT_02 WHEN NUMS.SEQ = 3 THEN TEN.JTDT_03 WHEN NUMS.SEQ = 4 THEN TEN.JTDT_04 WHEN NUMS.SEQ = 5 THEN TEN.JTDT_05 WHEN NUMS.SEQ = 6 THEN TEN.JTDT_06 WHEN NUMS.SEQ = 7 THEN TEN.JTDT_07 WHEN NUMS.SEQ = 8 THEN TEN.JTDT_08 WHEN NUMS.SEQ = 9 THEN TEN.JTDT_09 WHEN NUMS.SEQ = 10 THEN TEN.JTDT_10 END AS NNDT, CASE WHEN NUMS.SEQ = 1 THEN TEN.HTSU_01 WHEN NUMS.SEQ = 2 THEN TEN.HTSU_02 WHEN NUMS.SEQ = 3 THEN TEN.HTSU_03 WHEN NUMS.SEQ = 4 THEN TEN.HTSU_04 WHEN NUMS.SEQ = 5 THEN TEN.HTSU_05 WHEN NUMS.SEQ = 6 THEN TEN.HTSU_06 WHEN NUMS.SEQ = 7 THEN TEN.HTSU_07 WHEN NUMS.SEQ = 8 THEN TEN.HTSU_08 WHEN NUMS.SEQ = 9 THEN TEN.HTSU_09 WHEN NUMS.SEQ = 10 THEN TEN.HTSU_10 END AS HTSU FROM INAWK.JH_RTN_TEN TEN LEFT OUTER JOIN INAPARM.MSTNUMS NUMS ON NUMS.SEQ BETWEEN 1 AND 10 WHERE TRIM(TEN.OPERATOR) <> 'BATCH') T1 WHERE HTSU <> 99999) WK WHERE RNO = 1) SELECT ROW_NUMBER() OVER (ORDER BY ANN.BMNCD, ANN.SHNCD, ANN.BINKBN, ANN.TENCD, ANN.NNDT) + JTE.SEQ AS SEQ, ANN.BMNCD, ANN.SHNCD, ANN.BINKBN, ANN.TENCD, ANN.NNDT, JTS.HTSU, ANN.HSUU, 0 AS TOKKBN, 0 AS INPUTKBN, 1 AS TTKBN, 0 AS JISEIKBN, 0 AS YOUBIKBN, 0 AS SHNKBN, JTS.ERRKBN, ANN.MOYSKBN, ANN.MOYSSTDT, ANN.MOYSRBAN, ANN.KANRINO, 0 AS SYUTENCD, '' AS SHNAN, 0 AS GENKAAM, 0 AS BAIKAAM, 0 AS IRISU, 0 AS DAICD, 0 AS CHUCD, CURRENT_TIMESTAMP AS ADDDT FROM INAIF.AN_NOUNYU_NEQ ANN INNER JOIN INAIF.JH_SHIME_DATE JSD ON ANN.BMNCD = JSD.BMNCD AND ANN.NENMATKBN = JSD.NENMATKBN INNER JOIN JH_TEN_SYUSEI JTS ON ANN.SHNCD = JTS.SHNCD AND ANN.NNDT = JTS.NNDT AND ANN.BINKBN = JTS.BINKBN AND ANN.TENCD = JTS.TENCD LEFT OUTER JOIN JTE ON 1 = 1 WHERE ANN.NNSTDT <> 0 AND ANN.UPDKBN <> 1 AND (ANN.NENMATKBN = 1 OR ANN.TSHUFLG = 1) AND JSD.TYUSTDT <= ANN.NNSTDT AND ANN.NNSTDT <= JSD.TYUEDDT AND ANN.TSEIKBN NOT IN (3, 4) AND ANN.HSUU IS NOT NULL;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.JH_TOK_ERR;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
