REM [000][AN_NOUNYU_AFT_TEN.LOAD]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAPRE.AN_NOUNYU_NEQ ロード処理（処理前のINAIF.AN_NOUNYU_NEQ を退避）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM INAPREをINAPRE2に移動(検証用)
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAPRE2.AN_NOUNYU_NEQ;commit; ">>%OUTFILE% 2>&1
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAPRE2.AN_NOUNYU_NEQ SELECT * FROM INAPRE.AN_NOUNYU_NEQ;commit;" >> %OUTFILE%

REM INAIFをINAPREに移動
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAPRE.AN_NOUNYU_NEQ;commit; ">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAPRE.AN_NOUNYU_NEQ SELECT * FROM INAIF.AN_NOUNYU_NEQ;commit;" >> %OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAPRE.AN_NOUNYU_NEQ;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
