REM [000][AN_NOUNYU_NEQ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM INDEXの情報
SET TBNAME=AN_NOUNYU_NEQ
SET SCNAME=INAIF
SET INDEX=%~dp0..\index\%TBNAME%


SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_NEQ テーブルクリア処理（全店特売アンケート無 納入データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_NOUNYU_NEQ;commit;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_NEQ INDEX詳細出力（全店特売アンケート無 納入データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e  "SELECT INDEX_NAME, GROUP_CONCAT(COLUMN_NAME SEPARATOR ',') AS COLUMN_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_NAME = '%TBNAME%' AND TABLE_SCHEMA = '%SCNAME%' AND INDEX_NAME <> 'PRIMARY' GROUP BY INDEX_NAME"  >%INDEX% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_NEQ INDEX削除（全店特売アンケート無 納入データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
FOR /F %%D IN (%INDEX%) DO ( "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DROP INDEX %%D ON %SCNAME%.%TBNAME%;COMMIT;" >>%OUTFILE% 2>&1 )


SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_NEQ ロード処理（全店特売アンケート無 納入データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIF.AN_NOUNYU_NEQ SELECT LPAD(SPSHN.MOYSKBN, 1, 0) || LPAD(SPSHN.MOYSSTDT, 6, 0) || LPAD(SPSHN.MOYSRBAN, 3, 0) AS MOYSCD, SPSHN.MOYSKBN, SPSHN.MOYSSTDT, SPSHN.MOYSRBAN, SPSHN.BMNCD, SPSHN.KANRINO, SPSHN.KANRIENO, TC17.TENCD, TC17.NNDT, MC.SHUNO, MS.TSHUFLG, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNSTDT_TGF ELSE MC.NNSTDT END AS MYOSNNSTDT, CASE WHEN FDJ.BMNCD IS NOT NULL THEN MC.NNEDDT_TGF ELSE MC.NNEDDT END AS MYOSNNEDDT, MC.NENMATKBN, CASE WHEN WK06_PRE.MOYSKBN IS NULL THEN 0 ELSE WK06_PRE.JLSTCREFLG END AS JLSTCREFLG, CASE WHEN WK06_PRE.MOYSKBN IS NULL THEN SPSHN.JLSTCREDT ELSE WK06_PRE.JLSTCREDT END AS JLSTCREDT, CASE WHEN WK06_PRE.MOYSKBN IS NULL THEN SPSHN.JHTSUINDT ELSE WK06_PRE.JHTSUINDT END AS JHTSUINDT, CASE WHEN WK06_PRE.MOYSKBN IS NULL THEN SPSHN.WEEKHTDT ELSE WK06_PRE.WEEKHTDT END AS WEEKHTDT, 0 AS QADEVSTDT, 0 AS QADEVEDFLG, 0 AS TENGPCD, 0 AS KYOSEIFLG, SPSHN.SHNCD, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, SPSHN.NNSTDT, SPSHN.NNEDDT, SPSHN.JUFLG, SPSHN.JUHTDT, SPSHN.BINKBN, 0 AS NNSLIDE, SPSHN.CUTTENFLG AS CUTTENFLG, SPSHN.SHUDENFLG, TC17.HSUU, TC17.HTASU, TC17.PTNNO, TC17.TSEIKBN, TC17.ZJSKFLG, CASE WHEN WK06_PRE.MOYSKBN IS NULL THEN TC17.WEEKHTDT ELSE WK06_PRE.NNWEEKHTDT END AS NNWEEKHTDT, 0 AS QASYUKBN, 1 AS LDSYFLG, 1 AS MBSYFLG, 1 AS ITMSELKBN, 0 AS GTSIMECHGKBN, 0 AS GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM INAWK.AN_NOUNYU_NEQ_TEN TC17 INNER JOIN INATK2.TOKSP_SHN SPSHN ON SPSHN.MOYSKBN = TC17.MOYSKBN AND SPSHN.MOYSSTDT = TC17.MOYSSTDT AND SPSHN.MOYSRBAN = TC17.MOYSRBAN AND SPSHN.BMNCD = TC17.BMNCD AND SPSHN.KANRINO = TC17.KANRINO AND SPSHN.KANRIENO = TC17.KANRIENO AND SPSHN.UPDKBN <> 1 INNER JOIN INATK2.TOKMOYCD MC ON SPSHN.MOYSKBN = MC.MOYSKBN AND SPSHN.MOYSSTDT = MC.MOYSSTDT AND SPSHN.MOYSRBAN = MC.MOYSRBAN INNER JOIN (SELECT * FROM INATK2.TOKMOYSYU MS LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL - 1 YEAR), '%%y') <= SUBSTR(MS.SHUNO, 1, 2) AND SUBSTR(MS.SHUNO, 1, 2) <= DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL + 1 YEAR), '%%y')) MS ON MS.SHUNO = MC.SHUNO LEFT OUTER JOIN INAPRE.AN_NOUNYU_NEQ WK06_PRE ON TC17.MOYSKBN = WK06_PRE.MOYSKBN AND TC17.MOYSSTDT = WK06_PRE.MOYSSTDT AND TC17.MOYSRBAN = WK06_PRE.MOYSRBAN AND TC17.BMNCD = WK06_PRE.BMNCD AND TC17.KANRINO = WK06_PRE.KANRINO AND TC17.KANRIENO = WK06_PRE.KANRIENO AND TC17.TENCD = WK06_PRE.TENCD AND TC17.NNDT = WK06_PRE.NNDT LEFT OUTER JOIN INAPARM.PRAM_FRSDRYJUD FDJ ON FDJ.BMNCD = SPSHN.BMNCD AND FDJ.JUDFLG = 'S';commit;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_NEQ INDEX再作成（全店特売アンケート無 納入データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
FOR /F "tokens=1,2 delims=	" %%D IN (%INDEX%) DO ( "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "CREATE INDEX %%D ON %SCNAME%.%TBNAME%(%%E);COMMIT;" >>%OUTFILE% 2>&1 )


"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_NEQ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
