REM [000][AN_HANBAI_BFR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_HANBAI_BFR ロード処理（全店特売アンケート有 販売データ(反映前)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_HANBAI_BFR ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIF.AN_HANBAI_BFR WITH TGTG AS (SELECT * FROM INATK2.TOKTG_TENGP TGTG WHERE TGTG.UPDKBN <> 1), TGTEN AS (SELECT TGTEN.MOYSKBN, TGTEN.MOYSSTDT, TGTEN.MOYSRBAN, TGTEN.TENCD, TGTEN.TENGPCD, TGTG.QASYUKBN, TGTEN.KYOSEIFLG, TGTEN.LDTENKBN FROM INATK2.TOKTG_TEN TGTEN LEFT OUTER JOIN TGTG ON TGTG.MOYSKBN = TGTEN.MOYSKBN AND TGTG.MOYSSTDT = TGTEN.MOYSSTDT AND TGTG.MOYSRBAN = TGTEN.MOYSRBAN AND TGTG.TENGPCD = TGTEN.TENGPCD), TGKHN AS (SELECT * FROM INATK2.TOKTG_KHN TGKHN WHERE TGKHN.UPDKBN <> 1), TGSHN AS (SELECT TGSHN.*, NUMS.TENCD FROM INATK2.TOKTG_SHN TGSHN INNER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 LEFT OUTER JOIN (SELECT TGTEN.MOYSKBN, TGTEN.MOYSSTDT, TGTEN.MOYSRBAN FROM TGTEN GROUP BY TGTEN.MOYSKBN, TGTEN.MOYSSTDT, TGTEN.MOYSRBAN) TGTEN0 ON TGSHN.MOYSKBN = TGTEN0.MOYSKBN AND TGSHN.MOYSSTDT = TGTEN0.MOYSSTDT AND TGSHN.MOYSRBAN = TGTEN0.MOYSRBAN WHERE TGSHN.UPDKBN <> 1 AND CASE WHEN TGTEN0.MOYSKBN IS NULL THEN TRIM(SUBSTR(TGSHN.TENRANK_ARR, NUMS.TENCD, 1)) ELSE 'X' END <> '') SELECT LPAD(TGSHN.MOYSKBN, 1, 0) || LPAD(TGSHN.MOYSSTDT, 6, 0) || LPAD(TGSHN.MOYSRBAN, 3, 0) AS MOYSCD, TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, TGSHN.BMNCD, TGSHN.KANRINO, TGSHN.KANRIENO, COALESCE(TGTEN.TENCD, TGSHN.TENCD) AS TENCD, 0 AS BMNO, TMC.HBSTDT AS MOHBSTDT, TMC.HBEDDT AS MOHBEDDT, TGKHN.HBOKUREFLG, TGSHN.JLSTCREDT, TGKHN.QADEVSTDT, 0 AS QADEVENDFLG, TGTEN.TENGPCD, TGTEN.KYOSEIFLG, TGSHN.SHNCD, TGSHN.ADDSHUKBN, TGSHN.HBSTDT, TGSHN.HBEDDT, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, TGSHN.HBSLIDEFLG, CASE WHEN TGSHN.ADDSHUKBN = 2 THEN TGSHN.GENKAAM_MAE WHEN TGSHN.ADDSHUKBN = 4 THEN CASE WHEN TGSHN.TKANPLUKBN = 1 THEN TGSHN.GENKAAM_MAE WHEN TGSHN.TKANPLUKBN = 2 THEN TGSHN.GENKAAM_1KG END WHEN TGSHN.ADDSHUKBN = 5 THEN CASE WHEN TGSHN.TKANPLUKBN = 1 THEN TGSHN.GENKAAM_MAE WHEN TGSHN.TKANPLUKBN = 2 THEN TGSHN.GENKAAM_1KG END END AS GENKAAM, 0 AS GENKARITU, TGSHN.A_BAIKAAM, TGSHN.B_BAIKAAM, TGSHN.C_BAIKAAM, TGSHN.A_GENKAAM_1KG, TGSHN.B_GENKAAM_1KG, TGSHN.C_GENKAAM_1KG, TGSHN.A_WRITUKBN, TGSHN.B_WRITUKBN, TGSHN.C_WRITUKBN, TGSHN.TKANPLUKBN, TGSHN.KO_A_BAIKAAN, TGSHN.BD1_A_BAIKAAN, TGSHN.BD2_A_BAIKAAN, TGSHN.KO_B_BAIKAAN, TGSHN.BD1_B_BAIKAAN, TGSHN.BD2_B_BAIKAAN, TGSHN.KO_C_BAIKAAN, TGSHN.BD1_C_BAIKAAN, TGSHN.BD2_C_BAIKAAN, TGSHN.PLUSNDFLG, CASE WHEN SHNY.TEIKEIKBN IS NOT NULL THEN SHNY.TEIKEIKBN ELSE SHN.TEIKEIKBN END AS TEIKEIKBN, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SOURCEKBN ELSE SC1.SOURCEKBN END AS SOURCEKBN1, CASE WHEN SCY1.SHNCD IS NOT NULL THEN SCY1.SRCCD ELSE SC1.SRCCD END AS SRCCD1, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SOURCEKBN ELSE SC2.SOURCEKBN END AS SOURCEKBN2, CASE WHEN SCY2.SHNCD IS NOT NULL THEN SCY2.SRCCD ELSE SC2.SRCCD END AS SRCCD2, CASE WHEN SHNY.URICD IS NOT NULL THEN SHNY.URICD ELSE SHN.URICD END AS URICD, TGTEN.QASYUKBN, 1 AS LTENSAIFLG, 0 AS HANKAISIFLG, CASE WHEN TGTEN.LDTENKBN = 0 THEN 1 WHEN TGTEN.LDTENKBN = 1 THEN 2 END AS TENSAIFLG, 1 AS BAIKASELKBN, 1 AS SHOHINSEL, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN TGSHN.A_WRITUKBN ELSE CASE WHEN COALESCE(TGSHN.KO_A_BAIKAAN, 0) = 0 THEN TGSHN.A_BAIKAAM ELSE TGSHN.KO_A_BAIKAAN END END AS CBAIKA, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 0 ELSE TGSHN.BD1_A_BAIKAAN END AS SBAIBL1, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 0 ELSE TGSHN.BD2_A_BAIKAAN END AS SBAIBL2, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 0 ELSE TGSHN.A_GENKAAM_1KG END AS CBAIKAKG, 1 AS DATAKBN, TGSHN.GTSIMECHGKBN, TGSHN.GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM TGSHN INNER JOIN TGKHN ON TGSHN.MOYSKBN = TGKHN.MOYSKBN AND TGSHN.MOYSSTDT = TGKHN.MOYSSTDT AND TGSHN.MOYSRBAN = TGKHN.MOYSRBAN LEFT OUTER JOIN TGTEN ON TGSHN.MOYSKBN = TGTEN.MOYSKBN AND TGSHN.MOYSSTDT = TGTEN.MOYSSTDT AND TGSHN.MOYSRBAN = TGTEN.MOYSRBAN AND TGSHN.TENCD = TGTEN.TENCD INNER JOIN INATK2.TOKMOYCD TMC ON TGSHN.MOYSKBN = TMC.MOYSKBN AND TGSHN.MOYSSTDT = TMC.MOYSSTDT AND TGSHN.MOYSRBAN = TMC.MOYSRBAN LEFT OUTER JOIN INAMS2.MSTSHN_Y SHNY ON SHNY.SHNCD = TGSHN.SHNCD AND SHNY.YOYAKUDT <= TGSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSHN SHN ON SHN.SHNCD = TGSHN.SHNCD LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY1 ON SCY1.SHNCD = TGSHN.SHNCD AND SCY1.SEQNO = 1 AND SCY1.YOYAKUDT <= TGSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD_Y SCY2 ON SCY2.SHNCD = TGSHN.SHNCD AND SCY2.SEQNO = 2 AND SCY2.YOYAKUDT <= TGSHN.HBSTDT LEFT OUTER JOIN INAMS2.MSTSRCCD SC1 ON SC1.SHNCD = TGSHN.SHNCD AND SC1.SEQNO = 1 LEFT OUTER JOIN INAMS2.MSTSRCCD SC2 ON SC2.SHNCD = TGSHN.SHNCD AND SC2.SEQNO = 2 WHERE TMC.UPDKBN <> 1; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_HANBAI_BFR; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
