REM [000][AN_ZW_NOUNYU_AFT_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_ZW_NOUNYU_AFT_TEN ロード処理（中間納入日(ア有全割反映後)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAWK.AN_ZW_NOUNYU_AFT_TEN ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.AN_ZW_NOUNYU_AFT_TEN SELECT TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, TGSHN.BMNCD, TGSHN.KANRINO, TGSHN.KANRIENO, TGTJTEN.TENCD, TGSHN.NNSTDT AS NNDT, CASE WHEN TGTJTEN.TENCD <> 0 THEN CASE WHEN TGTJTEN.TJFLG = 1 THEN 0 WHEN TGTJTEN.TJFLG = 2 THEN NULL END END HSUU, CASE WHEN 1 = 1 THEN NULL ELSE 0 END AS TENHENKO, 0 AS HTASU, 0 AS PTNNO, 0 AS TSEIKBN, 0 AS ZJSKFLG, 0 AS WEEKHTDT FROM INATK2.TOKTG_SHN TGSHN INNER JOIN INATK2.TOKTG_TJTEN TGTJTEN ON TGSHN.MOYSKBN = TGTJTEN.MOYSKBN AND TGSHN.MOYSSTDT = TGTJTEN.MOYSSTDT AND TGSHN.MOYSRBAN = TGTJTEN.MOYSRBAN AND TGSHN.BMNCD = TGTJTEN.BMNCD AND TGSHN.KANRINO = TGTJTEN.KANRINO AND TGSHN.KANRIENO = TGTJTEN.KANRIENO WHERE TGSHN.ADDSHUKBN = 1 AND TGSHN.UPDKBN <> 1 AND TGSHN.NNSTDT <> 0 UNION ALL SELECT TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, TGSHN.BMNCD, TGSHN.KANRINO, TGSHN.KANRIENO, NUMS.TENCD, TGSHN.NNSTDT AS NNDT, CASE WHEN TRIM(SUBSTR(TGSHN.TENRANK_ARR, NUMS.TENCD, 1)) = '' THEN 0 ELSE 0 END HSUU, NULL AS TENHENKO, 0 AS HTASU, 0 AS PTNNO, 0 AS TSEIKBN, 0 AS ZJSKFLG, 0 AS WEEKHTDT FROM INATK2.TOKTG_SHN TGSHN LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 WHERE TGSHN.ADDSHUKBN = 1 AND TGSHN.UPDKBN <> 1 AND TGSHN.NNSTDT <> 0 AND NOT EXISTS (SELECT 1 FROM INATK2.TOKTG_TJTEN TGTJTEN WHERE TGSHN.MOYSKBN = TGTJTEN.MOYSKBN AND TGSHN.MOYSSTDT = TGTJTEN.MOYSSTDT AND TGSHN.MOYSRBAN = TGTJTEN.MOYSRBAN AND TGSHN.BMNCD = TGTJTEN.BMNCD AND TGSHN.KANRINO = TGTJTEN.KANRINO AND TGSHN.KANRIENO = TGTJTEN.KANRIENO); commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_ZW_NOUNYU_AFT_TEN;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
