REM [000][AN_ZW_NOUNYU_AFT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_ZW_NOUNYU_AFT ロード処理（全特アンケート有 納入データ 全品割引(反映後)）:反映対象外データ1
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIF.AN_ZW_NOUNYU_AFT SELECT WK10.MOYSCD, WK10.MOYSKBN, WK10.MOYSSTDT, WK10.MOYSRBAN, WK10.BMNCD, WK10.KANRINO, WK10.KANRIENO, WK10.TENCD, WK10.NNDT, WK10.SHUNO, WK10.TSHUFLG, WK10.MYOSNNSTDT, WK10.MYOSNNEDDT, WK10.NENMATKBN, WK10.JLSTCREFLG, WK10.JLSTCREDT, WK10.JHTSUINDT, WK10.WEEKHTDT, WK10.QADEVSTDT, WK10.QADEVEDFLG, WK10.TENGPCD, WK10.KYOSEIFLG, WK10.SHNCD, WK10.REIDMYKBN, WK10.NNSTDT, WK10.NNEDDT, WK10.JUFLG, WK10.JUHTDT, WK10.BINKBN, WK10.NNSLIDE, WK10.CUTTENFLG, WK10.SHUDENFLG, CASE WHEN WK10.CUTTENFLG = 1 THEN CASE WHEN COALESCE(WK10.TENGPCD, 0) = 0 OR WK10.QASYUKBN = 5 OR WK10.LDSYFLG = 2 OR WK10.MBSYFLG IN (0, 3) OR WK10.ITMSELKBN = 2 THEN NULL ELSE WK10.HSUU END ELSE WK10.HSUU END AS HSUU, WK10.HTASU, WK10.PTNNO, WK10.TSEIKBN, WK10.ZJSKFLG, WK10.NNWEEKHTDT, WK10.QASYUKBN, WK10.LDSYFLG, WK10.MBSYFLG, WK10.ITMSELKBN, WK10.GTSIMECHGKBN, WK10.GTSIMEOKFLG, WK10.SENDFLG, WK10.UPDKBN FROM (SELECT WK10.MOYSCD, WK10.MOYSKBN, WK10.MOYSSTDT, WK10.MOYSRBAN, WK10.SHUNO, WK10.TSHUFLG, WK10.MYOSNNSTDT, WK10.MYOSNNEDDT, WK10.NENMATKBN, WK10.JLSTCREFLG, WK10.JLSTCREDT, WK10.JHTSUINDT, WK10.WEEKHTDT, WK10.QADEVSTDT, WK10.QADEVEDFLG, WK10.TENGPCD, WK10.KYOSEIFLG, WK10.KANRINO, WK10.KANRIENO, WK10.BMNCD, WK10.SHNCD, WK10.REIDMYKBN, WK10.NNSTDT, WK10.NNEDDT, WK10.JUFLG, WK10.JUHTDT, WK10.BINKBN, WK10.NNSLIDE, WK10.CUTTENFLG, WK10.SHUDENFLG, WK10.TENCD, WK10.NNDT, WK10.HSUU, WK10.HTASU, WK10.PTNNO, WK10.TSEIKBN, WK10.ZJSKFLG, WK10.NNWEEKHTDT, WK10.QASYUKBN, WK10.LDSYFLG, WK10.MBSYFLG, WK10.ITMSELKBN, WK10.GTSIMECHGKBN, WK10.GTSIMEOKFLG, WK10.SENDFLG, WK10.UPDKBN FROM INAIF.AN_ZW_NOUNYU_BFR WK10 LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE WK10.JLSTCREFLG = 0 AND WK10.JLSTCREDT = 0 AND WK10.QADEVSTDT > SBD.DT_INT) WK10; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_ZW_NOUNYU_AFT;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
