REM [][THWK01_A10TSKD]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% 各マスタ → INAWK.THWK01_A10TSKDロード処理（新店改装店発注）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.THWK01_A10TSKD;INSERT IGNORE INTO INAWK.THWK01_A10TSKD SELECT '' AS FILLER_01, HSK2.TENNO, HSK2.SHNCD, HSK2.SURYO, HSK2.HTDT, HSK2.NNDT, WEEKDAY(CAST(CAST(HSK2.NNDT AS CHAR) AS DATETIME)) + 1 AS '1', HSK2.SHNKBN, HSK2.BDENKBN, '' AS SEPKBN, CASE WHEN SKTBL.SHOHINCD IS NOT NULL THEN SKTBL.SHIMESU WHEN SHN.SHOHINCD IS NOT NULL THEN SHN.SHIMESU ELSE 0 END AS SICTFLG, CASE WHEN PRMJOB.BMNCD IS NOT NULL THEN CAST(PRMJOB.JOBFLG AS CHAR (1)) ELSE '' END AS JOBFLG, '' AS FILLER_02, CASE WHEN SHN.SHOHINCD IS NOT NULL THEN 1 ELSE 0 END AS SSFLG FROM (SELECT HSK.TENNO, HSK.HTDT, HSK.NNDT, HSK.SHNKBN, HSK.BDENKBN, HSHN.SHNCD, SUM(HSHN.SURYO) AS SURYO, 0 AS SHIMESU, 0 AS SHOHIN_MASTER_FLG FROM INATK2.HATSK HSK INNER JOIN (SELECT SBD.DT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY') SBD ON 1 = 1 INNER JOIN INATK2.HATSK_SHN HSHN ON HSK.INPUTNO = HSHN.INPUTNO AND HSK.UPDKBN <> 1 AND HSK.HTDT = CAST(DATE_FORMAT(SBD.DT + INTERVAL 1 DAY, '%%Y%%m%%d') AS SIGNED) GROUP BY HSK.TENNO, HSK.HTDT, HSK.NNDT, HSK.SHNKBN, HSK.BDENKBN, HSHN.SHNCD) HSK2 LEFT OUTER JOIN (SELECT SHN3.SHOHINCD, SHN3.MSTCHG_Y_YMD, SHN3.SHIMESU FROM (SELECT SHN2.SHOHINCD, SHN2.MSTCHG_Y_YMD, SHN2.SHIMESU, ROW_NUMBER() OVER (PARTITION BY SHN2.SHOHINCD ORDER BY SHN2.SORTNO, SHN2.MSTCHG_Y_YMD) AS ODRNO FROM (SELECT SHN_Y.SHOHINCD, SHN_Y.MSTCHG_Y_YMD, SHN_Y.SHIMESU, 1 AS SORTNO FROM INAIF.HA_A11SHOH_Y SHN_Y WHERE SHN_Y.UPDKBN <> 1 UNION ALL SELECT SHN_Y.SHOHINCD, 99999999 AS MSTCHG_Y_YMD, 999 AS SHIMESU, 2 AS SORTNO FROM INAIF.HA_A11SHOH_Y SHN_Y WHERE SHN_Y.UPDKBN <> 1) SHN2) SHN3 WHERE SHN3.ODRNO <= 2) SKTBL ON HSK2.SHNCD = SKTBL.SHOHINCD and HSK2.NNDT >= SKTBL.MSTCHG_Y_YMD LEFT OUTER JOIN INAIF.HA_A11SHOH SHN ON HSK2.SHNCD = SHN.SHOHINCD LEFT OUTER JOIN INAPARM.PRAM_JOBFLG PRMJOB ON LEFT (HSK2.SHNCD, 2) = PRMJOB.BMNCD AND CASE WHEN SKTBL.SHOHINCD IS NOT NULL THEN SKTBL.SHIMESU WHEN SHN.SHOHINCD IS NOT NULL THEN SHN.SHIMESU ELSE 0 END = PRMJOB.SIMEKAISU;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.THWK01_A10TSKD" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
