REM [445][新店改装店発注]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET OUTFILENAME=0445.csv
SET EXPFILE=%~DP0../exp/%OUTFILENAME%

SET MSG=%DATE% %TIME%  →  EXPORT処理(新店改装店発注)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(TSKD.TENCD, 3, 0) || LPAD(TSKD.HCUHZK, 8, 0) || LPAD(TSKD.NNYHZK, 8, 0) || LPAD(TSKD.SHOKBN, 1, 0) || LPAD(TSKD.BDENKBN, 1, 0) || RPAD(TSKD.SHOCD, 13, ' ') || RPAD(TSKD.JAN, 15, ' ') || LPAD(TSKD.HCUSU, 5, 0) || RPAD(TSKD.SICTFLG, 1, ' ') || LPAD(TSKD.SSFLG, 1, 0) FROM (SELECT TSKD.TENCD, TSKD.HCUHZK, TSKD.NNYHZK, TSKD.SHOKBN, TSKD.BDENKBN, TSKD.SHOCD, '' AS JAN, TSKD.HCUSU, TSKD.SICTFLG, 0 AS SSFLG, 1 AS ODRNO FROM INAWK.THWK01_A10TSKD TSKD WHERE TSKD.SSFLG = 1 UNION ALL SELECT 0 AS TENCD, 0 AS HCUHZK, 0 AS NNYHZK, 0 AS SHOKBN, 0 AS BDENKBN, '0000000000000' AS SHOCD, '000000000000000' AS JAN, 0 AS HCUSU, '0' AS SICTFLG, 0 AS SSFLG, 2 AS ODRNO FROM (SELECT 1 AS DUMMY) DUMMY) TSKD ORDER BY ODRNO, NNYHZK, SHOCD, TENCD, HCUHZK, SHOKBN, BDENKBN" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
