REM [][D2WK51_A10TTD_D
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM SET MSG=%DATE% %TIME% INAWK.D2WK51_A10TTD_D(予約発注データワーク(ドライ)) テーブルクリア処理
REM ECHO %MSG%
REM >> %OUTFILE% ECHO %MSG%
REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAWK.D2WK51_A10TTD_D IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% 各マスタ → INAWK.D2WK51_A10TTD_D ロード処理（予約発注データワーク(ドライ)作成）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.D2WK51_A10TTD_D;INSERT IGNORE INTO INAWK.D2WK51_A10TTD_D SELECT YH.SHNCD, '' AS FILLER_01, YH.TENCD, 0 AS SIRCD, 0 AS MISIR, 0 AS MBGGEN, 0 AS TBAIKA, YH.HTSU, 0 AS SHOKBN, 0 AS HCUSHKBN, 0 AS TSEKBN, '' AS SEPKBN, '' AS WPNKBN, 1 AS BINKBN, 1 AS HCMFLG, YH.HTDT, WEEKDAY(CAST(CAST(YH.HTDT AS CHAR) AS DATETIME)) + 1, YH.NNDT, WEEKDAY(CAST(CAST(YH.NNDT AS CHAR) AS DATETIME)) + 1, CASE WHEN SHN_Y.SHOHINCD IS NOT NULL AND YH.NNDT >= SHN_Y.MSTCHG_Y_YMD THEN SHN_Y.FUTEIKBN WHEN SHN.SHOHINCD IS NOT NULL THEN SHN.FUTEIKBN ELSE 0 END, 9 AS BETUDEN, 0 AS NIJYUB, 0 AS NJYKB1, '' AS NJYKB2, 0 AS MOYOK, 0 AS MOYOKA, 0 AS MOYORE, 0 AS KANBAN, 0 AS ATARA, 0 AS ENPTN, '09' AS JOBFLG, '' AS TOGKBN, '' AS FILLER02 FROM (SELECT YHTEN.SHNCD, YHTEN.TENCD, YHSHN.HTDT, YHTEN.NNDT, SUM(YHTEN.HTSU) AS HTSU FROM INATK2.HATYH_TEN YHTEN INNER JOIN (SELECT SBD.DT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY') SBD ON 1 = 1 INNER JOIN INATK2.HATYH_SHN YHSHN ON YHSHN.KKKCD = YHTEN.KKKCD AND YHSHN.SHNCD = YHTEN.SHNCD AND YHSHN.UPDKBN <> 1 AND YHSHN.HTDT = CAST(DATE_FORMAT(SBD.DT + INTERVAL 1 DAY, '%%Y%%m%%d') AS SIGNED) GROUP BY YHTEN.SHNCD, YHTEN.TENCD, YHSHN.HTDT, YHTEN.NNDT HAVING SUM(YHTEN.HTSU) <> 0) YH LEFT OUTER JOIN INAIF.HA_A11SHOH_Y SHN_Y ON YH.SHNCD = SHN_Y.SHOHINCD AND SHN_Y.UPDKBN <> 1 LEFT OUTER JOIN INAIF.HA_A11SHOH SHN ON YH.SHNCD = SHN.SHOHINCD AND SHN.UPDKBN <> 1 WHERE EXISTS (SELECT * FROM INAMS2.MSTBMN BMN WHERE BMN.BMNKBN <> 2 AND BMN.UPDKBN <> 1 AND LEFT (YH.SHNCD, 2) = BMN.BMNCD);COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.D2WK51_A10TTD_D" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
