REM [446][予約発注]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET OUTFILENAME=0446.csv
SET EXPFILE=%~DP0../exp/%OUTFILENAME%

SET MSG=%DATE% %TIME%  →  EXPORT処理(予約発注)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(TTD.TENCD, 3, 0) || LPAD(TTD.HCUBI, 8, 0) || LPAD(TTD.NNYBI, 8, 0) || LPAD(TTD.SHOKBN, 1, 0) || LPAD(TTD.BETUDEN, 1, 0) || RPAD(TTD.SHOCD, 13, ' ') || RPAD(TTD.JAN, 15, ' ') || LPAD(TTD.HCUSU, 5, 0) || LPAD(TTD.SHIMESU, 1, 0) || LPAD(TTD.SSFLG, 1, 0) FROM (SELECT WK50.TENCD, WK50.HCUBI, WK50.NNYBI, WK50.SHOKBN, WK50.BETUDEN, WK50.SHOCD, '' AS JAN, WK50.HCUSU, 0 AS SHIMESU, 0 AS SSFLG, 1 AS ODRNO FROM INAWK.D2WK50_A10TTD_S WK50 UNION ALL SELECT WK51.TENCD, WK51.HCUBI, WK51.NNYBI, WK51.SHOKBN, WK51.BETUDEN, WK51.SHOCD, '' AS JAN, WK51.HCUSU, 0 AS SHIMESU, 0 AS SSFLG, 1 AS ODRNO FROM INAWK.D2WK51_A10TTD_D WK51 UNION ALL SELECT 0 AS TENCD, 0 AS HCUBI, 0 AS NNYBI, 0 AS SHOKBN, 0 AS BETUDEN, '0000000000000' AS SHOCD, '000000000000000' AS JAN, 0 AS HCUSU, 0 AS SHIMESU, 0 AS SSFLG, 2 AS ODRNO FROM (SELECT 1 AS DUMMY) DUMMY) TTD ORDER BY ODRNO, SHOCD, TENCD, HCUBI, NNYBI" >%EXPFILE% 2>>%OUTFILE% 
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
