REM [015][UPDATE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET INFILENAME=
REM ===== 店舗基本
SET MSG=%DATE% %TIME% 店舗実績 INAMS.MSTTENJSKI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTTENJSKI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTTEN T2 WHERE UPDKBN = 1 AND SENDFLG = 1 AND T1.TENCD = T2.TENCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 店舗部門 INAMS.MSTTENBMN DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTTENBMN T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTTEN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.TENCD=T2.TENCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 部門実績 INAMS.MSTBUMONJISSEKI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTBUMONJISSEKI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTTEN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.TENCD=T2.TENCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 店舗曜日別発注部門 INAMS.MSTTENYOBIHTBMN DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTTENYOBIHTBMN T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTTEN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.TENCD=T2.TENCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 店舗休日 INAMS.MSTTENKYU DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTTENKYU T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTTEN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.TENCD=T2.TENCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 商品店グループ店舗 INAMS.MSTSHNTENGPTEN DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHNTENGPTEN T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTTEN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.TENCD=T2.TENCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 店舗基本 INAMS.MSTTEN DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTTEN WHERE UPDKBN=1 AND SENDFLG=1;commit;" >>%OUTFILE% 2>&1


REM ===== 商品店グループ
SET MSG=%DATE% %TIME% 商品店グループ店舗 INAMS.MSTSHNTENGPTEN DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHNTENGPTEN T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHNTENGP T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.GPKBN=T2.GPKBN AND T1.BMNCD=T2.BMNCD AND T1.TENGPCD=T2.TENGPCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 商品店グループ INAMS.MSTSHNTENGP DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHNTENGP WHERE UPDKBN=1 AND SENDFLG=1;commit;" >>%OUTFILE% 2>&1


REM ===== 仕入先
SET MSG=%DATE% %TIME% 複数仕入先＿実仕入先 INAMS.MSTFUKUSUSIR_R DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTFUKUSUSIR_R T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSIR T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.SIRCD=T2.SIRCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 複数仕入先＿店舗 INAMS.MSTFUKUSUSIR_T DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTFUKUSUSIR_T T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSIR T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.SIRCD=T2.SIRCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 配送パターン仕入先 INAMS.MSTHSPTNSIR DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTHSPTNSIR T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSIR T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.SIRCD=T2.SIRCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% エリア別配送パターン仕入先 INAMS.MSTAREAHSPTNSIR DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTAREAHSPTNSIR T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSIR T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.SIRCD=T2.SIRCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 仕入先 INAMS.MSTSIR DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSIR WHERE UPDKBN=1 AND SENDFLG=1;commit;" >>%OUTFILE% 2>&1


REM ===== 部門
SET MSG=%DATE% %TIME% 大分類 INAMS.MSTDAIBRUI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTDAIBRUI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 中分類 INAMS.MSTCHUBRUI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTCHUBRUI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 小分類 INAMS.MSTSHOBRUI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHOBRUI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 小小分類 INAMS.MSTSSHOBRUI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSSHOBRUI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 用途分類大分類 INAMS.MSTDAIBRUI_YOT DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTDAIBRUI_YOT T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 用途分類中分類 INAMS.MSTCHUBRUI_YOT DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTCHUBRUI_YOT T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 用途分類小分類 INAMS.MSTSHOBRUI_YOT DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHOBRUI_YOT T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 売場分類大分類 INAMS.MSTDAIBRUI_URI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTDAIBRUI_URI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 売場分類中分類 INAMS.MSTCHUBRUI_URI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTCHUBRUI_URI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 売場分類小分類 INAMS.MSTSHOBRUI_URI DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHOBRUI_URI T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 値付分類大分類 INAMS.MSTDAIBRUI_NEZ DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTDAIBRUI_NEZ T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 値付分類中分類 INAMS.MSTCHUBRUI_NEZ DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTCHUBRUI_NEZ T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 値付分類小分類 INAMS.MSTSHOBRUI_NEZ DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHOBRUI_NEZ T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTBMN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND T1.BMNCD=T2.BMNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 部門 INAMS.MSTBMN DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTBMN WHERE UPDKBN=1 AND SENDFLG=1;commit;" >>%OUTFILE% 2>&1


REM ===== メーカー
SET MSG=%DATE% %TIME% メーカー INAMS.MSTMAKER DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTMAKER WHERE UPDKBN=1 AND SENDFLG=1;commit;" >>%OUTFILE% 2>&1


REM ===== プライスカード発行トラン
SET MSG=%DATE% %TIME% プライスカード発行トラン INAMS.TRNPCARD DELETE処理（全件）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "TRUNCATE TABLE INAMS.TRNPCARD ;commit;" >>%OUTFILE% 2>&1


REM ===== プライスカード発行枚数トラン
SET MSG=%DATE% %TIME% プライスカード発行トラン INAMS.TRNPCARDSU DELETE処理（全件）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "TRUNCATE TABLE INAMS.TRNPCARDSU ;commit;" >>%OUTFILE% 2>&1


REM ===== 値入率入数チェック
SET MSG=%DATE% %TIME% 値入率入数チェック INAMS.MSTNEIRERIT DELETE処理（更新区分=1 ＆ 送信フラグ=1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTNEIRERIT WHERE UPDKBN=1 AND SENDFLG=1;commit;" >>%OUTFILE% 2>&1


REM ===== 商品
SET MSG=%DATE% %TIME% 平均パック単価 INAMS.MSTAVGPTANKA DELETE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTAVGPTANKA T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN = 1 AND SENDFLG = 1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d') = (CURRENT_DATE) AND T1.SHNCD = T2.SHNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 仕入グループ商品 INAMS.MSTSIRGPSHN DELETE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSIRGPSHN T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d')=(CURRENT_DATE) AND T1.SHNCD=T2.SHNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 売価コントロール INAMS.MSTBAIKACTL DELETE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTBAIKACTL T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d')=(CURRENT_DATE) AND T1.SHNCD=T2.SHNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ソースコード管理 INAMS.MSTSRCCD DELETE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSRCCD T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d')=(CURRENT_DATE) AND T1.SHNCD=T2.SHNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 自動発注管理 INAMS.MSTSHN DELETE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTAHS T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d')=(CURRENT_DATE) AND T1.SHNCD=T2.SHNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% グループ分類管理 INAMS.MSTGRP DELETE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTGRP T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d')=(CURRENT_DATE) AND T1.SHNCD=T2.SHNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 店別異部門管理 INAMS.MSTSHNTENBMN DELETE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHNTENBMN T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d')=(CURRENT_DATE) AND T1.SHNCD=T2.SHNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 商品コード空き番 INAMS.SYSSHNCD_AKI UPDATE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "UPDATE INAAD.SYSSHNCD_AKI T1 SET USEFLG = 0 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d')=(CURRENT_DATE) AND T1.SHNCD=T2.SHNCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 販売コード空き番 INAMS.SYSURICD_AKI UPDATE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "UPDATE INAAD.SYSURICD_AKI T1 SET USEFLG = 0 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE UPDKBN=1 AND SENDFLG=1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d')=(CURRENT_DATE) AND T1.URICD=T2.URICD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 商品 INAMS.MSTSHN DELETE処理（更新区分=1 ＆ 送信フラグ=1 ＆ 更新日=今日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHN WHERE UPDKBN = 1 AND SENDFLG = 1 AND DATE_FORMAT(UPDDT,'%%Y%%m%%d') = (CURRENT_DATE);commit;" >>%OUTFILE% 2>&1


REM ===== 商品＿予約
SET MSG=%DATE% %TIME% 仕入グループ商品＿予約 INAMS.MSTSIRGPSHN_Y DELETE処理（更新区分=1 ＆ 店売価実施日-1日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSIRGPSHN_Y T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN_Y T2 WHERE UPDKBN=1 AND (DATE_ADD(DATE_FORMAT(TENBAIKADT,'%%Y%%m%%d'),INTERVAL -1 day)) IN (SELECT DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND T1.SHNCD=T2.SHNCD AND T1.YOYAKUDT=T2.YOYAKUDT);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 売価コントロール＿予約 INAMS.MSTBAIKACTL_Y DELETE処理（更新区分=1 ＆ 店売価実施日-1日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTBAIKACTL_Y T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN_Y T2 WHERE UPDKBN=1 AND (DATE_ADD(DATE_FORMAT(TENBAIKADT,'%%Y%%m%%d'),INTERVAL-1 day)) IN (SELECT DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND T1.SHNCD=T2.SHNCD AND T1.YOYAKUDT=T2.YOYAKUDT);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ソースコード管理＿予約 INAMS.MSTSRCCD_Y DELETE処理（更新区分=1 ＆ 店売価実施日-1日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSRCCD_Y T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN_Y T2 WHERE UPDKBN=1 AND (DATE_ADD(DATE_FORMAT(TENBAIKADT,'%%Y%%m%%d'),INTERVAL-1 day)) IN (SELECT DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND T1.SHNCD=T2.SHNCD AND T1.YOYAKUDT=T2.YOYAKUDT);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 自動発注管理＿予約 INAMS.MSTAHS_Y DELETE処理（更新区分=1 ＆ 店売価実施日-1日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTAHS_Y T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN_Y T2 WHERE UPDKBN=1 AND (DATE_ADD(DATE_FORMAT(TENBAIKADT,'%%Y%%m%%d'),INTERVAL-1 day) )IN (SELECT DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND T1.SHNCD=T2.SHNCD AND T1.YOYAKUDT=T2.YOYAKUDT);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% グループ分類管理＿予約 INAMS.MSTGRP_Y DELETE処理（更新区分=1 ＆ 店売価実施日-1日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTGRP_Y T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN_Y T2 WHERE UPDKBN=1 AND (DATE_ADD(DATE_FORMAT(TENBAIKADT,'%%Y%%m%%d'),INTERVAL-1 day)) IN (SELECT DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND T1.SHNCD=T2.SHNCD AND T1.YOYAKUDT=T2.YOYAKUDT);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 店別異部門管理＿予約 INAMS.MSTSHNTENBMN_Y DELETE処理（更新区分=1 ＆ 店売価実施日-1日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHNTENBMN_Y T1 WHERE EXISTS (SELECT 1 FROM INAMS.MSTSHN_Y T2 WHERE UPDKBN=1 AND (DATE_ADD(DATE_FORMAT(TENBAIKADT,'%%Y%%m%%d'),INTERVAL-1 day)) IN (SELECT DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d') FROM INAAD.SYSSHORIDT) AND T1.SHNCD=T2.SHNCD AND T1.YOYAKUDT=T2.YOYAKUDT);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 商品＿予約 INAMS. DELETE処理（更新区分=1 ＆ 店売価実施日-1日=処理日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHN_Y WHERE UPDKBN = 1 AND (DATE_FORMAT(TENBAIKADT, '%%Y%%m%%d') - INTERVAL 1 DAY) IN (SELECT DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d') FROM INAAD.SYSSHORIDT);COMMIT" >>%OUTFILE% 2>&1


REM ===== CSV取込トラン
SET MSG=%DATE% %TIME% ＣＳＶ取込トラン＿仕入グループ商品 INAMS.CSVSIRSHN DELETE処理（更新区分=1 ＆ 取込日時=処理日付-7日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.CSVSIRSHN T1 WHERE EXISTS (SELECT 1 FROM (SELECT T3.SEQ, T3.INPUTNO FROM INAMS.CSVSHNHEAD T2 INNER JOIN INAMS.CSVSHN T3 ON T3.SEQ = T2.SEQ AND T3.UPDKBN = 1 AND T2.INPUT_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d'),INTERVAL - 7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T1.SEQ = X.SEQ AND T1.INPUTNO = X.INPUTNO);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ＣＳＶ取込トラン＿売価コントロール INAMS.CSVBAIKACTL DELETE処理（更新区分=1 ＆ 取込日時=処理日付-7日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.CSVBAIKACTL T1 WHERE EXISTS (SELECT 1 FROM (SELECT T3.SEQ,T3.INPUTNO FROM INAMS.CSVSHNHEAD T2 INNER JOIN INAMS.CSVSHN T3 ON T3.SEQ=T2.SEQ AND T3.UPDKBN=1 AND T2.INPUT_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d'),INTERVAL-7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T1.SEQ=X.SEQ AND T1.INPUTNO=X.INPUTNO);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ＣＳＶ取込トラン＿ソースコード管理 INAMS.CSVSRCCD DELETE処理（更新区分=1 ＆ 取込日時=処理日付-7日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.CSVSRCCD T1 WHERE EXISTS (SELECT 1 FROM (SELECT T3.SEQ,T3.INPUTNO FROM INAMS.CSVSHNHEAD T2 INNER JOIN INAMS.CSVSHN T3 ON T3.SEQ=T2.SEQ AND T3.UPDKBN=1 AND T2.INPUT_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d'),INTERVAL-7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T1.SEQ=X.SEQ AND T1.INPUTNO=X.INPUTNO);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ＣＳＶ取込トラン＿自動発注管理 INAMS.CSVMSTAHS DELETE処理（更新区分=1 ＆ 取込日時=処理日付-7日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.CSVMSTAHS T1 WHERE EXISTS (SELECT 1 FROM (SELECT T3.SEQ,T3.INPUTNO FROM INAMS.CSVSHNHEAD T2 INNER JOIN INAMS.CSVSHN T3 ON T3.SEQ=T2.SEQ AND T3.UPDKBN=1 AND T2.INPUT_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d'),INTERVAL-7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T1.SEQ=X.SEQ AND T1.INPUTNO=X.INPUTNO);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ＣＳＶ取込トラン＿グループ分類管理 INAMS.CSVMSTGRP DELETE処理（更新区分=1 ＆ 取込日時=処理日付-7日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.CSVMSTGRP T1 WHERE EXISTS (SELECT 1 FROM (SELECT T3.SEQ,T3.INPUTNO FROM INAMS.CSVSHNHEAD T2 INNER JOIN INAMS.CSVSHN T3 ON T3.SEQ=T2.SEQ AND T3.UPDKBN=1 AND T2.INPUT_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d'),INTERVAL-7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T1.SEQ=X.SEQ AND T1.INPUTNO=X.INPUTNO);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ＣＳＶ取込トラン＿店別異部門管理 INAMS.CSVMSTSHNTENBMN DELETE処理（更新区分=1 ＆ 取込日時=処理日付-7日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.CSVMSTSHNTENBMN T1 WHERE EXISTS (SELECT 1 FROM (SELECT T3.SEQ,T3.INPUTNO FROM INAMS.CSVSHNHEAD T2 INNER JOIN INAMS.CSVSHN T3 ON T3.SEQ=T2.SEQ AND T3.UPDKBN=1 AND T2.INPUT_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d'),INTERVAL-7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T1.SEQ=X.SEQ AND T1.INPUTNO=X.INPUTNO);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ＣＳＶ取込トラン＿商品 INAMS.CSVSHNHEAD DELETE処理（更新区分=1 ＆ 取込日時=処理日付-7日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.CSVSHNHEAD T1 WHERE EXISTS (SELECT 1 FROM INAMS.CSVSHN T2 WHERE T2.SEQ=T1.SEQ AND T2.UPDKBN=1 AND T1.INPUT_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT),'%%Y%%m%%d'),INTERVAL-7 DAY) FROM INAAD.SYSSHORIDT));commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ＣＳＶ取込トラン＿商品ヘッダ INAMS.CSVSHNHEAD DELETE処理（CSV取込トラン_商品=0 ＆ 取込日時=処理日付-7日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.CSVSHNHEAD T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SEQ FROM INAMS.CSVSHNHEAD T1 LEFT OUTER JOIN INAMS.CSVSHN T2 ON T2.SEQ = T1.SEQ AND T1.INPUT_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d'),INTERVAL - 7 DAY) FROM INAAD.SYSSHORIDT) GROUP BY T1.SEQ HAVING COUNT(T2.SEQ) = 0) X WHERE T0.SEQ=X.SEQ);commit;" >>%OUTFILE% 2>&1


REM ===== ジャーナル＿商品
SET MSG=%DATE% %TIME% ジャーナル＿仕入れグループ商品 INAAD.JNLSIRSHN DELETE処理（更新情報_更新日時<処理日付-7日 ＆ レコード>1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAAD.JNLSIRSHN T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SEQ, ROW_NUMBER() OVER (PARTITION BY T1.SHNCD ORDER BY T1.INF_DATE DESC) AS NUM FROM INAAD.JNLSHN T1 WHERE T1.INF_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d') ,INTERVAL- 7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T0.SEQ = X.SEQ AND X.NUM > 1);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ジャーナル＿売価コントロール INAAD.JNLBAIKACTL DELETE処理（更新情報_更新日時<処理日付-7日 ＆ レコード>1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAAD.JNLBAIKACTL T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SEQ, ROW_NUMBER() OVER (PARTITION BY T1.SHNCD ORDER BY T1.INF_DATE DESC) AS NUM FROM INAAD.JNLSHN T1 WHERE T1.INF_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d') ,INTERVAL- 7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T0.SEQ = X.SEQ AND X.NUM > 1);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ジャーナル＿ソースコード管理 INAAD.JNLSRCCD DELETE処理（更新情報_更新日時<処理日付-7日 ＆ レコード>1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAAD.JNLSRCCD T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SEQ, ROW_NUMBER() OVER (PARTITION BY T1.SHNCD ORDER BY T1.INF_DATE DESC) AS NUM FROM INAAD.JNLSHN T1 WHERE T1.INF_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d'),INTERVAL - 7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T0.SEQ = X.SEQ AND X.NUM > 1);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ジャーナル＿自動発注管理 INAAD.JNLAHS DELETE処理（更新情報_更新日時<処理日付-7日 ＆ レコード>1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAAD.JNLAHS T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SEQ, ROW_NUMBER() OVER (PARTITION BY T1.SHNCD ORDER BY T1.INF_DATE DESC) AS NUM FROM INAAD.JNLSHN T1 WHERE T1.INF_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d'),INTERVAL - 7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T0.SEQ = X.SEQ AND X.NUM > 1);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ジャーナル＿グループ分類管理 INAAD.JNLMSTGRP DELETE処理（更新情報_更新日時<処理日付-7日 ＆ レコード>1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAAD.JNLMSTGRP T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SEQ, ROW_NUMBER() OVER (PARTITION BY T1.SHNCD ORDER BY T1.INF_DATE DESC) AS NUM FROM INAAD.JNLSHN T1 WHERE T1.INF_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d') ,INTERVAL- 7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T0.SEQ = X.SEQ AND X.NUM > 1);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ジャーナル＿店別異部門管理 INAAD.JNLMSTSHNTENBMN DELETE処理（更新情報_更新日時<処理日付-7日 ＆ レコード>1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAAD.JNLMSTSHNTENBMN T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SEQ, ROW_NUMBER() OVER (PARTITION BY T1.SHNCD ORDER BY T1.INF_DATE DESC) AS NUM FROM INAAD.JNLSHN T1 WHERE T1.INF_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d'),INTERVAL - 7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T0.SEQ = X.SEQ AND X.NUM > 1);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% ジャーナル＿商品 INAAD.JNLSHN DELETE処理（更新情報_更新日時<処理日付-7日 ＆ レコード>1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAAD.JNLSHN T0 WHERE EXISTS (SELECT 1 FROM (SELECT T1.SEQ, ROW_NUMBER() OVER (PARTITION BY T1.SHNCD ORDER BY T1.INF_DATE DESC) AS NUM FROM INAAD.JNLSHN T1 WHERE T1.INF_DATE <= (SELECT DATE_ADD(DATE_FORMAT(MAX(SHORIDT), '%%Y%%m%%d'),INTERVAL - 7 DAY) FROM INAAD.SYSSHORIDT)) X WHERE T0.SEQ = X.SEQ AND X.NUM > 1);commit;" >>%OUTFILE% 2>&1


REM IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
