REM [441][取引先マスタ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME%  →  EXPORT処理(スマクラ_取引先マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%

SET OUTFILENAME=%~DP0..\exp\取引先マスタT.csv
ECHO %OUTFILENAME% >> %OUTFILE%

REM 送信フラグ<>1のみ
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT RPAD(LPAD(COALESCE(T1.SIRCD, ''), 6, '0'), 13, ' ') || '0            ' || RPAD(TRIM(TRAILING '　' FROM COALESCE(T1.SIRKN, '')), 40 - CHAR_LENGTH(TRIM(TRAILING '　' FROM COALESCE(T1.SIRKN, ''))), ' ') || RPAD(COALESCE(T1.SIRAN, ''), 20, ' ') || RPAD(LPAD(COALESCE(T1.SIRCD, ''), 6, '0'), 13, ' ') || '0            ' || RPAD(TRIM(TRAILING '　' FROM COALESCE(T1.SIRKN, '')), 40 - CHAR_LENGTH(TRIM(TRAILING '　' FROM COALESCE(T1.SIRKN, ''))), ' ') || RPAD(COALESCE(T1.SIRAN, ''), 20, ' ') || '02' || LPAD(CASE WHEN COALESCE(T1.STARTDT, 0) = 0 THEN 19600101 ELSE T1.STARTDT END, 8, 0) || '20991231' || LPAD(COALESCE(T1.DF_RYUTSUKBN, 0), 1, '0') || '0' || RPAD('', 64, ' ') FROM INAMS.MSTSIR T1 WHERE SIRKN IS NOT NULL AND SENDFLG <> 0 ORDER BY T1.SIRCD" >%OUTFILENAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
