REM [443][店舗基本マスタ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME%  →  EXPORT処理(スマクラ_店舗基本マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%

SET OUTFILENAME=%~DP0..\exp\納品先マスタT.csv
ECHO %OUTFILENAME% >> %OUTFILE%

REM 送信フラグ<>1のみ
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.TENCD, 5, 0) || '        ' || '0            ' || CONVERT(LEFT (CAST(CONVERT(RPAD(TRIM(TRAILING '　' FROM COALESCE(T1.TENKN, '')), 40, ' ') USING SJIS) AS BINARY), 40) USING SJIS) || RPAD(COALESCE(T1.TENAN, ''), 20, ' ') || CASE WHEN T1.TENCD < 800 THEN '01' ELSE '02' END || CASE WHEN COALESCE(T1.TENOPENDT, 0) = 0 THEN '19600101' ELSE LPAD(DATE_FORMAT(DATE_ADD(T1.TENOPENDT, INTERVAL - 30 DAY), '%%Y%%m%%d'), 8, 0) END || CASE WHEN COALESCE(T1.TENCLOSEDT, 0) = 0 THEN 20991231 ELSE T1.TENCLOSEDT END || LPAD(CASE WHEN COALESCE(T1.TENCLOSEDT, 0) = 0 THEN 0 ELSE T1.TENCLOSEDT END, 8, 0) || LPAD(COALESCE(T1.UPDKBN, 0), 1, 0) || RPAD('', 15, ' ') FROM INAMS.MSTTEN T1 WHERE (T1.TENCD BETWEEN 800 and 899) OR (T1.TENKN IS NOT NULL AND LENGTH(TRIM(TRAILING '　' FROM T1.TENKN)) > 0 AND (COALESCE(T1.TENCLOSEDT, 0) = 0 OR T1.TENCLOSEDT >= (SELECT DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL - 3 MONTH), '%%Y%%m%%d') FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY')) AND (T1.TENCD NOT IN (1, 2))) ORDER BY T1.TENCD;" >%OUTFILENAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
