REM [014][AEA01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0014
SET OUTNAME=%~DP0..\exp\0014
SET HULFTID=VEAUO027

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品基本マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -B -r -e "WITH SHN_Y AS (SELECT SHN_Y.* FROM INAMS2.MSTSHN_Y SHN_Y LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE SHN_Y.YOYAKUDT = SBD.DT_INT), SHN AS (SELECT SHN.* FROM INAMS2.MSTSHN SHN WHERE SHN.UPDKBN <> 1 AND NOT EXISTS (SELECT 1 FROM SHN_Y WHERE SHN.SHNCD = SHN_Y.SHNCD)) SELECT SUBSTR(RPAD(B_SHN.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_SHN.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_SHN.SHNCD, 14, ' '), 9, 6) || LPAD(B_SHN.YOYAKUDT, 8, 0) || LPAD(B_SHN.TENBAIKADT, 8, 0) || LPAD(B_SHN.YOT_BMNCD, 3, 0) || LPAD(B_SHN.YOT_DAICD, 2, 0) || LPAD(B_SHN.YOT_CHUCD, 2, 0) || LPAD(B_SHN.YOT_SHOCD, 2, 0) || LPAD(B_SHN.URI_BMNCD, 3, 0) || LPAD(B_SHN.URI_DAICD, 2, 0) || LPAD(B_SHN.URI_CHUCD, 2, 0) || LPAD(B_SHN.URI_SHOCD, 2, 0) || LPAD(B_SHN.BMNCD, 3, 0) || LPAD(B_SHN.DAICD, 2, 0) || LPAD(B_SHN.CHUCD, 2, 0) || LPAD(B_SHN.SHOCD, 2, 0) || LPAD(B_SHN.SSHOCD, 1, 0) || LPAD(B_SHN.ATSUK_STDT, 8, 0) || LPAD(B_SHN.ATSUK_EDDT, 8, 0) || LPAD(B_SHN.TEISHIKBN, 1, 0) || RPAD(B_SHN.SHNAN, 20, ' ') || RPAD(B_SHN.SHNKN, 20, '　') || RPAD(B_SHN.PCARDKN, 20, '　') || RPAD(B_SHN.POPKN, 20, '　') || RPAD(B_SHN.RECEIPTAN, 20, ' ') || RPAD(B_SHN.RECEIPTKN, 20, '　') || LPAD(B_SHN.PCKBN, 1, 0) || LPAD(B_SHN.KAKOKBN, 1, 0) || LPAD(B_SHN.ICHIBAKBN, 1, 0) || LPAD(B_SHN.SHNKBN, 1, 0) || RPAD(B_SHN.SANCHIKN, 20, '　') || LPAD(B_SHN.SSIRCD, 6, 0) || LPAD(B_SHN.HSPTN, 3, 0) || LPAD(B_SHN.RG_ATSUKFLG, 1, 0) || LPAD(CAST(B_SHN.RG_GENKAAM * 100 AS SIGNED), 8, 0) || LPAD(B_SHN.RG_BAIKAAM, 6, 0) || LPAD(B_SHN.RG_IRISU, 3, 0) || LPAD(RPAD(B_SHN.RG_IDENFLG, 1, ' '), 1, 0) || LPAD(RPAD(B_SHN.RG_WAPNFLG, 1, ' '), 1, 0) || LPAD(B_SHN.HS_ATSUKFLG, 1, 0) || LPAD(CAST(B_SHN.HS_GENKAAM * 100 AS SIGNED), 8, 0) || LPAD(B_SHN.HS_BAIKAAM, 6, 0) || LPAD(B_SHN.HS_IRISU, 3, 0) || LPAD(RPAD(B_SHN.HS_WAPNFLG, 1, ' '), 1, 0) || LPAD(B_SHN.HS_SPOTMINSU, 2, 0) || LPAD(RPAD(B_SHN.HP_SWAPNFLG, 1, ' '), 1, 0) || RPAD(B_SHN.KIKKN, 23, '　') || LPAD(B_SHN.UP_YORYOSU, 5, 0) || LPAD(B_SHN.UP_TYORYOSU, 3, 0) || LPAD(B_SHN.UP_TANIKBN, 2, 0) || LPAD(B_SHN.SHNYOKOSZ, 4, 0) || LPAD(B_SHN.SHNTATESZ, 4, 0) || LPAD(B_SHN.SHNOKUSZ, 4, 0) || LPAD(CAST(B_SHN.SHNJRYOSZ * 10 AS SIGNED), 6, 0) || LPAD(B_SHN.PBKBN, 1, 0) || LPAD(B_SHN.KOMONOKBM, 2, 0) || LPAD(B_SHN.TANAOROKBN, 2, 0) || LPAD(B_SHN.TEIKEIKBN, 1, 0) || LPAD(B_SHN.ODS_HARUSU, 4, 0) || LPAD(B_SHN.ODS_NATSUSU, 4, 0) || LPAD(B_SHN.ODS_AKISU, 4, 0) || LPAD(B_SHN.ODS_FUYUSU, 4, 0) || LPAD(B_SHN.ODS_NYUKASU, 4, 0) || LPAD(B_SHN.ODS_NEBIKISU, 4, 0) || LPAD(B_SHN.PCARD_SHUKBN, 1, 0) || LPAD(B_SHN.PCARD_IROKBN, 1, 0) || LPAD(B_SHN.ZEIKBN, 1, 0) || LPAD(B_SHN.ZEIRTKBN, 3, 0) || LPAD(B_SHN.ZEIRTKBN_OLD, 3, 0) || LPAD(B_SHN.ZEIRTHENKODT, 8, 0) || LPAD(B_SHN.SEIZOGENNISU, 3, 0) || LPAD(B_SHN.TEIKANKBN, 1, 0) || LPAD(B_SHN.MAKERCD, 9, 0) || LPAD(B_SHN.IMPORTKBN, 2, 0) || LPAD(B_SHN.SIWAKEKBN, 2, 0) || LPAD(B_SHN.HENPIN_KBN, 1, 0) || LPAD(B_SHN.TAISHONENSU, 2, 0) || LPAD(B_SHN.CALORIESU, 5, 0) || LPAD(B_SHN.ELPFLG, 1, 0) || LPAD(B_SHN.BELLMARKFLG, 1, 0) || LPAD(B_SHN.RECYCLEFLG, 1, 0) || LPAD(B_SHN.ECOFLG, 1, 0) || LPAD(B_SHN.HZI_YOTO, 1, 0) || LPAD(B_SHN.HZI_ZAISHITU, 1, 0) || LPAD(B_SHN.HZI_RECYCLE, 1, 0) || LPAD(RPAD(B_SHN.KIKANKBN, 1, ' '), 1, 0) || LPAD(B_SHN.SHUKYUKBN, 2, 0) || LPAD(B_SHN.DOSU, 3, 0) || LPAD(RPAD(B_SHN.CHINRETUCD, 1, ' '), 1, 0) || LPAD(RPAD(B_SHN.DANTUMICD, 2, ' '), 2, 0) || LPAD(RPAD(B_SHN.KASANARICD, 1, ' '), 1, 0) || LPAD(B_SHN.KASANARISZ, 3, 0) || LPAD(B_SHN.ASSHUKURT, 2, 0) || LPAD(RPAD(B_SHN.SHUBETUCD, 2, ' '), 2, 0) || LPAD(B_SHN.URICD, 6, 0) || RPAD(B_SHN.SALESCOMKN, 30, '　') || LPAD(B_SHN.URABARIKBN, 1, 0) || LPAD(B_SHN.PCARD_OPFLG, 1, 0) || LPAD(SUBSTR(RPAD(B_SHN.PARENTCD, 14, ' '), 1, 8), 8, 0) || LPAD(SUBSTR(RPAD(B_SHN.PARENTCD, 14, ' '), 9, 6), 6, 0) || LPAD(B_SHN.BINKBN, 1, 0) || LPAD(B_SHN.HAT_MONKBN, 1, 0) || LPAD(B_SHN.HAT_TUEKBN, 1, 0) || LPAD(B_SHN.HAT_WEDKBN, 1, 0) || LPAD(B_SHN.HAT_THUKBN, 1, 0) || LPAD(B_SHN.HAT_FRIKBN, 1, 0) || LPAD(B_SHN.HAT_SATKBN, 1, 0) || LPAD(B_SHN.HAT_SUNKBN, 1, 0) || LPAD(B_SHN.READTMPTN, 3, 0) || LPAD(B_SHN.SIMEKAISU, 1, 0) || LPAD(B_SHN.IRYOREFLG, 1, 0) || LPAD(B_SHN.TOROKUMOTO, 1, 0) || '      ' || LPAD(B_SHN.UPDKBN, 1, 0) || LPAD(B_SHN.SENDFLG, 1, 0) || RPAD(B_SHN.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(B_SHN.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_SHN.UPDDT, '%%Y%%m%%d'), 8, 0) FROM (SELECT * FROM SHN UNION ALL SELECT * FROM SHN_Y) B_SHN ORDER BY B_SHN.SHNCD;" >%OUTNAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
