REM [016][AEA03]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0016
SET OUTNAME=%~DP0..\exp\%OUTFILENAME%
SET HULFTID=VEAUO031

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(売価コントロール)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH BCY AS (SELECT BCY.* FROM INAMS2.MSTBAIKACTL_Y BCY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE BCY.YOYAKUDT = SBD.DT_INT AND EXISTS (SELECT 1 FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND BCY.SHNCD = SY.SHNCD AND BCY.YOYAKUDT = SY.YOYAKUDT)), BC AS (SELECT * FROM INAMS2.MSTBAIKACTL BC WHERE EXISTS (SELECT 1 FROM INAMS2.MSTSHN SHN WHERE SHN.UPDKBN <> 1 AND BC.SHNCD = SHN.SHNCD) AND NOT EXISTS (SELECT 1 FROM BCY WHERE BC.SHNCD = BCY.SHNCD AND BC.TENGPCD = BCY.TENGPCD)) SELECT SUBSTR(RPAD(B_BC.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_BC.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_BC.SHNCD, 14, ' '), 9, 6) || LPAD(B_BC.TENGPCD, 4, 0) || LPAD(B_BC.YOYAKUDT, 8, 0) || LPAD(B_BC.AREAKBN, 1, 0) || LPAD(SUBSTR(B_BC.GENKAAM, 1, LOCATE('.', B_BC.GENKAAM) - 1), 6, 0) || SUBSTR(B_BC.GENKAAM, LOCATE('.', B_BC.GENKAAM) + 1) || LPAD(B_BC.BAIKAAM, 6, 0) || LPAD(B_BC.IRISU, 3, 0) || '         ' || RPAD(B_BC.OPERATOR, 20, ' ') || LPAD(B_BC.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(B_BC.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_BC.UPDDT, '%%Y%%m%%d'), 8, 0) FROM (SELECT * FROM BC UNION ALL SELECT * FROM BCY) B_BC ORDER BY B_BC.SHNCD, B_BC.TENGPCD;" >%OUTNAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
