REM [017][AEA04]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0017
SET OUTNAME=%~DP0..\exp\0017
SET HULFTID=VEAUO033

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(ソースコード管理)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SCY AS (SELECT SCY.* FROM INAMS2.MSTSRCCD_Y SCY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE SCY.YOYAKUDT = SBD.DT_INT AND EXISTS (SELECT 1 FROM INAMS2.MSTSHN_Y SY WHERE SY.UPDKBN <> 1 AND SCY.SHNCD = SY.SHNCD AND SCY.YOYAKUDT = SY.YOYAKUDT)), SC AS (SELECT * FROM INAMS2.MSTSRCCD SC WHERE EXISTS (SELECT 1 FROM INAMS2.MSTSHN SHN WHERE SHN.UPDKBN <> 1 AND SC.SHNCD = SHN.SHNCD) AND NOT EXISTS (SELECT 1 FROM SCY WHERE SC.SHNCD = SCY.SHNCD AND SC.SRCCD = SCY.SRCCD)) SELECT SUBSTR(RPAD(B_SC.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(B_SC.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(B_SC.SHNCD, 14, ' '), 9, 6) || RPAD(B_SC.SRCCD, 14, ' ') || LPAD(B_SC.YOYAKUDT, 8, 0) || LPAD(B_SC.SEQNO, 1, 0) || LPAD(B_SC.SOURCEKBN, 1, 0) || '     ' || RPAD(B_SC.OPERATOR, 20, ' ') || LPAD(B_SC.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(B_SC.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(B_SC.UPDDT, '%%Y%%m%%d'), 8, 0) FROM (SELECT * FROM SC UNION ALL SELECT * FROM SCY) B_SC ORDER BY B_SC.SHNCD, B_SC.SRCCD;" >%OUTNAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
