REM [022][AEA03]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0022
SET OUTNAME=%~DP0..\exp\0022
SET HULFTID=VEAUO032

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(売価コントロール(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT SUBSTR(BCY.SHNCD, 1, 2) || SUBSTR(BCY.SHNCD, 3, 6) || RPAD(SUBSTR(BCY.SHNCD, 9, 6),6,' ') || LPAD(BCY.TENGPCD, 4, 0) || LPAD(BCY.YOYAKUDT, 8, 0) || LPAD(BCY.AREAKBN, 1, 0) || LPAD(SUBSTR(BCY.GENKAAM, 1, LOCATE('.', BCY.GENKAAM) - 1), 6, 0) || SUBSTR(BCY.GENKAAM, LOCATE('.', BCY.GENKAAM) + 1) || LPAD(BCY.BAIKAAM, 6, 0) || LPAD(BCY.IRISU, 3, 0) || '         ' || RPAD(BCY.OPERATOR, 20, ' ') || LPAD(BCY.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(BCY.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(BCY.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2.MSTBAIKACTL_Y BCY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE BCY.YOYAKUDT <> SBD.DT_INT AND EXISTS (SELECT 1 FROM INAMS2.MSTSHN_Y SY WHERE SY.YOYAKUDT <> SBD.DT_INT AND SY.UPDKBN <> 1 AND BCY.SHNCD = SY.SHNCD AND BCY.YOYAKUDT = SY.YOYAKUDT) ORDER BY BCY.SHNCD, BCY.TENGPCD, BCY.YOYAKUDT;" >%OUTNAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
