REM [023][AEA04]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0023
SET OUTNAME=%~DP0..\exp\0023
SET HULFTID=VEAUO034

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(ソースコード管理(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT SUBSTR(RPAD(SCY.SHNCD, 14, ' '), 1, 2) || SUBSTR(RPAD(SCY.SHNCD, 14, ' '), 3, 6) || SUBSTR(RPAD(SCY.SHNCD, 14, ' '), 9, 6) || RPAD(SCY.SRCCD, 14, ' ') || LPAD(SCY.YOYAKUDT, 8, 0) || LPAD(SCY.SEQNO, 1, 0) || LPAD(SCY.SOURCEKBN, 1, 0) || '     ' || RPAD(SCY.OPERATOR, 20, ' ') || LPAD(SCY.SENDFLG, 1, 0) || LPAD(DATE_FORMAT(SCY.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(SCY.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2.MSTSRCCD_Y SCY LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE SCY.YOYAKUDT <> SBD.DT_INT AND EXISTS (SELECT 1 FROM INAMS2.MSTSHN_Y SY WHERE SY.YOYAKUDT <> SBD.DT_INT AND SY.UPDKBN <> 1 AND SCY.SHNCD = SY.SHNCD AND SCY.YOYAKUDT = SY.YOYAKUDT) ORDER BY SCY.SHNCD, SCY.SRCCD, SCY.YOYAKUDT;" >%OUTNAME% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
