REM [][D2WK_BFC01]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% 各マスタ → INAWK.D2WK_BFC01 ロード処理（催しコードマスタ(CCR用)作成）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.D2WK_BFC01; INSERT IGNORE INTO INAWK.D2WK_BFC01 SELECT T1.MOYSKBN, T1.MOYSSTDT, T1.MOYSRBAN, T1.SHUNO, T1.MOYKN, T1.MOYAN, T1.NENMATKBN, T1.HBSTDT, T1.HBEDDT, T1.NNSTDT, T1.NNEDDT, T1.NNSTDT_TGF, T1.NNEDDT_TGF, T1.PLUSDDT, T1.PLUSFLG, T1.UPDKBN, T1.SENDFLG, T1.OPERATOR, DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d') FROM INATK2.TOKMOYCD T1 INNER JOIN (SELECT DATE_FORMAT(DATE_ADD(SBD.DT, INTERVAL - KN.GNISUU DAY), '%%Y%%m%%d') AS SYORDT FROM (SELECT 30 AS NISUU, 0 AS GNISUU FROM DUAL) KN INNER JOIN (SELECT SBD.DT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY') SBD ON 1 = 1) KASAN ON (T1.NNEDDT >= KASAN.SYORDT OR T1.NNEDDT_TGF >= KASAN.SYORDT) AND T1.UPDKBN <> 1; commit;" >>%OUTFILE% 2>&1
IF ERRORLEVEL 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.D2WK_BFC01;" >>%OUTFILE% 2>&1
IF ERRORLEVEL 1 GOTO ERROR




:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
