REM [182][D2WK28_ZZQ113_2]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.D2WK28_ZZQ113_2_WK(生活応援_商品2) ロード処理（ワークテーブル作成）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "TRUNCATE TABLE INAWK.D2WK28_ZZQ113_2_WK;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "INSERT IGNORE INTO INAWK.D2WK28_ZZQ113_2_WK SELECT * FROM (SELECT T1.*, SHN.RG_BAIKAAM AS SHN_RG_BAIKAAM, SHN.RG_GENKAAM AS SHN_RG_GENKAAM, SHN.RG_IRISU AS SHN_RG_IRISU, ROW_NUMBER() OVER (PARTITION BY T1.SHOCD, T1.MISE, T1.NNYNOB ORDER BY T1.BAIKA, T1.MOYOK DESC, T1.MOYOKA DESC, T1.MOYORE DESC, T1.BUNBMC, T1.KANBAN) AS ODRNO FROM INAWK.D2WK24_ZZQ112 T1 INNER JOIN INAPRE.MSTSHN_PD SHN ON T1.SHOCD = SHN.SHNCD AND SHN.UPDKBN <> 1) MT1 WHERE ODRNO = 1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "ANALYZE TABLE INAWK.D2WK28_ZZQ113_2_WK;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INAWK.D2WK28_ZZQ113_2(生活応援_商品2) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "TRUNCATE TABLE INAWK.D2WK28_ZZQ113_2;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAWK.D2WK28_ZZQ113_2(生活応援_商品2) ロード処理（ワークテーブル作成）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv < %~dp0182.D2WK28_ZZQ113_2.LOAD.sql >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "ANALYZE TABLE INAWK.D2WK28_ZZQ113_2;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
