REM [182][D2WK24_ZZQ112_NUM]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAPARM.MSTNUMS → INAWK.D2WK24_ZZQ112_NUM ロード処理（生活応援_商品1NUM）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.D2WK24_ZZQ112_NUM; INSERT IGNORE INTO INAWK.D2WK24_ZZQ112_NUM SELECT A.SEQ - 1 AS SEQ FROM INAPARM.MSTNUMS A INNER JOIN INAWK.D2WK24_ZZQ112_KASAN KASAN ON 1 = 1 WHERE A.SEQ BETWEEN 1 AND KASAN.NISU; COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.D2WK24_ZZQ112_NUM;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
