REM [182][D2WK28_ZZQ113_3]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAWK.D2WK28_ZZQ113_3 → INAPRE.D2WK28_ZZQ113_3 ロード処理（生活応援_商品3(前回分)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAPRE.D2WK28_ZZQ113_3;INSERT IGNORE INTO INAPRE.D2WK28_ZZQ113_3 SELECT REC_HAN_KBN, MISE, MOYOK, MOYOKA, MOYORE, BUNBMC, KANBAN, SHOCD, MAKRNMKJ, SHOMKJ, KIKMKJ, MISIR, SAITEISU, GENKA, A_SOBAIFG, B_SOBAIFG, C_SOBAIFG, A_RANK, B_RANK, C_RANK, POPCD, POPSIZE, POPSU, MSF, KOSINKB, SOSINFLG, OPERTO, TOURKB, KOSINB, HACHBI, NNYNOB FROM INAWK.D2WK28_ZZQ113_3;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAPRE.D2WK28_ZZQ113_3;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
