REM [074][A11SCD]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.A11SCD(商品コードチェックデータ) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAWK.A11SCD ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAWK.A11SCD(商品コードチェックデータ) ロード処理（ワークテーブル作成）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.A11SCD SELECT T1.SHNCD, NULL AS MOYCD, NULL AS DATAKBN FROM (SELECT SHNCD FROM INATK.HATSTR_SHN UNION SELECT SHNCD FROM INATK.HATYH_SHN UNION SELECT SHNCD FROM INATK.HATSK_SHN UNION SELECT SHNCD FROM INATK.TOKSO_SHN UNION SELECT SHNCD FROM INATK.TOKGY_SHN UNION SELECT DUMMYCD FROM INATK.TOKRS_SHN UNION SELECT SHNCD FROM INATK.TOKJU_SHN UNION SELECT SHNCD FROM INATK.TOKQJU_SHN UNION SELECT SHNCD FROM INATK.TOKKT_SHN UNION SELECT SHNCD FROM INATK.TOKTG_SHN UNION SELECT SHNCD FROM INATK.TOKSP_SHN UNION SELECT SHNCD FROM INAMS.MSTSHN_Y UNION SELECT SHNCD FROM INATK.TOKMM_SHO) T1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.A11SCD;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIN.AASTF(削除可ファイル) 利用していない商品コードのみ抽出
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAIN.AASTF T1 WHERE EXISTS (SELECT 1 FROM INAWK.A11SCD T2 WHERE T2.SHNCD=T1.SHOCD) ;commit;" >>%OUTFILE% 2>&1
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAIN.AASTF T1 WHERE NOT EXISTS (SELECT 1 FROM INAMS.MSTSHN T2 WHERE T2.SHNCD=T1.SHOCD);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAWK.A11SCD(商品コードチェックデータ) ロード処理（INAIN.AASTF）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.A11SCD SELECT SHOCD, NULL AS MOYCD, NULL AS DATAKBN FROM INAIN.AASTF;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.A11SCD;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIN.AASTF(削除可ファイル) ロード処理（INAWK.A11SCD）各項目更新
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAIN.AASTF T1, (SELECT * FROM (SELECT RPAD(COALESCE(T1.SHNCD, '0'), 13, ' ') AS SHOHINCD, LPAD(COALESCE(T1.BMNCD, '0'), 3, '0') AS BUMN, LPAD(COALESCE(T1.DAICD, '0'), 2, '0') AS DAIBUNCD, LPAD(COALESCE(T1.CHUCD, '0'), 2, '0') AS CHUBUNCD, LPAD(COALESCE(T1.SHOCD, '0'), 2, '0') AS SHOBUNCD, LPAD(COALESCE(T1.SSHOCD, '0'), 1, '0') AS SHOSHOBUNCD, RPAD(COALESCE(T1.SHNAN, ''), 20, ' ') AS SHOHINNMKN, LPAD(COALESCE(T1.SSIRCD, '0'), 6, '0') AS SHIRECDH, LPAD(COALESCE(T1.SHNKBN, '0'), 1, '0') AS SHOHINSHURUI, LPAD(CAST(COALESCE(T1.RG_GENKAAM, 0) * 100 AS SIGNED), 8, '0') AS GENKA, CASE WHEN COALESCE(T1.TEIKANKBN, 0) = 1 THEN LPAD(CAST(COALESCE(T1.RG_BAIKAAM, 0) AS SIGNED), 6, '0') ELSE '000000' END AS BAIKA1, CASE WHEN COALESCE(T1.TEIKANKBN, 0) = 0 THEN LPAD(CAST(COALESCE(T1.RG_BAIKAAM, 0) AS SIGNED), 6, '0') ELSE '000000' END AS BAIKA2, '*' AS SIRE_FLG, LPAD(COALESCE(T1.TEIKANKBN, '0'), 1, '0') AS FUTEIKBN, DATE_FORMAT(COALESCE(T1.ADDDT, '0'), '%%Y%%m%%d') AS ADDYMD, DATE_FORMAT(COALESCE(T1.UPDDT, '0'), '%%Y%%m%%d') AS UPDYMD, LPAD(COALESCE(T1.IRYOREFLG, '0'), 1, '0') AS IRYOFLG, LPAD('', 24, ' ') AS FILLER FROM INAMS.MSTSHN T1 WHERE EXISTS (SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD = T1.SHNCD)) T3) AS T2 SET T1.SHOCD = T2.SHOHINCD, T1.BUNBMC = T2.BUMN, T1.BUNDIC = T2.DAIBUNCD, T1.BUNCHC = T2.CHUBUNCD, T1.BUNSHC = T2.SHOBUNCD, T1.BUNSSC = T2.SHOSHOBUNCD, T1.SHOMKN = T2.SHOHINNMKN, T1.HSIREC = T2.SHIRECDH, T1.SYOKBN = T2.SHOHINSHURUI, T1.GENKA1 = T2.GENKA, T1.BAITE1 = T2.BAIKA1, T1.BAIFU1 = T2.BAIKA2, T1.TASIRF = T2.SIRE_FLG, T1.TEFTEI = T2.FUTEIKBN, T1.TOURKB = T2.ADDYMD, T1.HENKOB = T2.UPDYMD, T1.IRYOTMFL = T2.IRYOFLG, T1.FILLER = T2.FILLER WHERE T1.SHOCD = T2.SHOHINCD;commit;" >>%OUTFILE% 2>&1
SET MSG=%DATE% %TIME% INAIN.AASTF(削除可ファイル) 部門13､27衣料使い回しフラグ更新
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAIN.AASTF SET IRYOTMFL='0';commit;" >>%OUTFILE% 2>&1
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAIN.AASTF T1, (SELECT SHOCD FROM INAIN.AASTF T1 INNER JOIN INAAD.SYSSHNCD_FU T2 ON T2.BMNCD = 13 AND T1.SHOCD BETWEEN CAST(T2.BMNCD || T2.STARTNO || '0' AS SIGNED) AND CAST(T2.BMNCD || T2.ENDNO || '0' AS SIGNED)) AS T2 SET IRYOTMFL = '1' WHERE T1.SHOCD = T2.SHOCD;commit;" >>%OUTFILE% 2>&1
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAIN.AASTF T1, (SELECT SHOCD FROM INAIN.AASTF T1 INNER JOIN INAAD.SYSSHNCD_FU T2 ON T2.BMNCD = 27 AND T1.SHOCD BETWEEN CAST(T2.BMNCD || T2.STARTNO || '0' AS SIGNED) AND CAST(T2.BMNCD || T2.ENDNO || '0' AS SIGNED)) AS T2 SET IRYOTMFL = '1' WHERE T1.SHOCD = T2.SHOCD;commit;" >>%OUTFILE% 2>&1
:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
