REM [074][MSTSHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM INAMSスキーマ対象
SET MSG=%DATE% %TIME% INAMS.MSTSHN(商品マスタ)衣料使い回しフラグ＝１
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAMS.MSTSHN T1 SET IRYOREFLG=1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=1 AND T1.IRYOREFLG=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTSHN(商品マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSHN T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTBAIKACTL(売価コントロールマスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTBAIKACTL T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTSIRGPSHN(仕入グループ商品マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSIRGPSHN T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTSRCCD(ソースコード管理マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSRCCD T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTAHS(自動発注管理マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTAHS T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTSHNTENBMN(店別異部門管理マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS.MSTSHNTENBMN T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTGRP(グループ分類管理マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTGRP T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTTENKABUTSU(添加物マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTTENKABUTSU T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS.MSTSHINAGP(品揃グループマスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "DELETE FROM INAMS.MSTSHINAGP T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1


REM INAMS2スキーマ対象
SET MSG=%DATE% %TIME% INAMS2.MSTSHN(商品マスタ)衣料使い回しフラグ＝１
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAMS2.MSTSHN T1 SET IRYOREFLG=1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=1 AND T1.IRYOREFLG=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTSHN(商品マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS2.MSTSHN T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTBAIKACTL(売価コントロールマスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTBAIKACTL T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTSIRGPSHN(仕入グループ商品マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS2.MSTSIRGPSHN T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTSRCCD(ソースコード管理マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSRCCD T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTAHS(自動発注管理マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS2.MSTAHS T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTSHNTENBMN(店別異部門管理マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSHNTENBMN T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTGRP(グループ分類管理マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTGRP T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTTENKABUTSU(添加物マスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS2.MSTTENKABUTSU T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAMS2.MSTSHINAGP(品揃グループマスタ)物理削除処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAMS2.MSTSHINAGP T1 WHERE EXISTS(SELECT 1 FROM INAIN.AASTF T2 WHERE T2.SHOCD=T1.SHNCD AND T2.IRYOTMFL=0);commit;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAAD.SYSSHNCD_AKI(商品コード空き番管理テーブル)更新
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT INTO INAAD.SYSSHNCD_AKI(SHNCD, USEFLG, UPDDT) SELECT SHOCD, 0 AS USEFLG, CURRENT_TIMESTAMP AS UPDDT FROM INAIN.AASTF AS T2 ON DUPLICATE KEY UPDATE USEFLG = 0, UPDDT = CURRENT_TIMESTAMP;commit;" >>%OUTFILE% 2>&1

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
