REM [005][UPDATE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET INFILENAME=
SET MSG=%DATE% %TIME% KEYSYS.SYS_USER_POS DELETE処理（権限削除 本部マスタ[24320]、本部特売[24321]、店舗特売[24322]）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM >> %OUTFILE% DB2 -L %OUTTIME% "DELETE FROM KEYSYS.SYS_USER_POS T1 WHERE T1.CD_USER IN (SELECT DISTINCT T2.CD_USER FROM KEYSYS.SYS_USERS T2 INNER JOIN INAAD.SYSJINJIKIHON T3 ON T2.USER_ID = CAST(T3.SHAINCD AS VARCHAR (13))) AND T1.CD_POSITION IN (24320, 24321, 24322)"

REM ===== KEYSYS.SYS_USERS 処理 ==
SET MSG=%DATE% %TIME% INAAD.SYSSHAINKNG + INAAD.SYSJINJIKIHON → KEYSYS.SYS_USERS INSERT処理（社員権限ベースで追加更新）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USERS(CD_USER, USER_ID, PASSWORDS, NM_FAMILY, NM_NAME, CUSTOM_VALUE, YOBI_2, DT_PW_TERM, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT COALESCE((SELECT USERS.CD_USER FROM KEYSYS.SYS_USERS AS USERS WHERE USERS.USER_ID = COALESCE(SK.SHAINCD, '')), (SELECT KEYSYS.nextval('GENERATER_ID'))) AS CD_USER, COALESCE(SK.SHAINCD, '') AS USER_ID, COALESCE(SK.SHAINCD, '') AS PASSWORDS, COALESCE(TRIM(REPLACE (TNP.TENKN, '　', '')), SK.SEI, '') AS NM_FAMILY, COALESCE(TRIM(REPLACE (JK.SIMEIKN, '　', '')), SK.MEI, '') AS NM_NAME, '' AS CUSTOM_VALUE, CASE WHEN JK.SZKCD <= '300' THEN COALESCE(CASE WHEN TNP.TENCD IS NULL THEN '' ELSE JK.SZKCD END, '') ELSE '' END AS YOBI_2, CASE WHEN JK.SZKCD > '300' THEN '19000101' ELSE '20991231' END AS DT_PW_TERM, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSSHAINKNG SK LEFT OUTER JOIN INAAD.SYSJINJIKIHON JK ON SK.SHAINCD = JK.SHAINCD LEFT OUTER JOIN INAMS.MSTTEN TNP ON JK.SZKCD = CAST(TNP.TENCD AS CHAR (3)) WHERE (SK.KNGKBN_MST <> 0 OR SK.KNGKBN_HT <> 0)) AS T2 ON DUPLICATE KEY UPDATE NM_FAMILY = T2.NM_FAMILY, NM_NAME = T2.NM_NAME, CUSTOM_VALUE = T2.CUSTOM_VALUE, YOBI_2 = T2.YOBI_2;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME% INAAD.SYSJINJIKIHON → KEYSYS.SYS_USERS INSERT処理（社員情報追加更新）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USERS(CD_USER, USER_ID, PASSWORDS, NM_FAMILY, NM_NAME, CUSTOM_VALUE, YOBI_2, YOBI_3, DT_PW_TERM, NM_CREATE, NM_UPDATE) SELECT CD_USER, USER_ID, PASSWORDS, NM_FAMILY, NM_NAME, CUSTOM_VALUE, YOBI_2, YOBI_3, DT_PW_TERM, NM_CREATE, NM_UPDATE FROM (SELECT COALESCE((SELECT USERS.CD_USER FROM KEYSYS.SYS_USERS AS USERS WHERE USERS.USER_ID = COALESCE(T.SHAINCD, '')), (SELECT KEYSYS.nextval('GENERATER_ID'))) AS CD_USER, COALESCE(T.SHAINCD, '') AS USER_ID, COALESCE(T.SHAINCD, '') AS PASSWORDS, COALESCE(TRIM(REPLACE (TNP.TENKN, '　', '')), '') AS NM_FAMILY, COALESCE(TRIM(REPLACE (T.SIMEIKN, '　', '')), '') AS NM_NAME, '' AS CUSTOM_VALUE, CASE WHEN T.SZKCD <= '300' THEN T.SZKCD ELSE '' END AS YOBI_2, T.SZKCD AS YOBI_3, CASE WHEN T.SZKCD > '300' THEN '19000101' ELSE '20991231' END AS DT_PW_TERM, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE, CASE WHEN US.CD_USER IS NULL THEN 2 WHEN US.CD_USER IS NOT NULL AND (US.NM_NAME <> COALESCE(TRIM(REPLACE (T.SIMEIKN, '　', '')), '') OR US.YOBI_3 <> T.SZKCD) THEN 1 ELSE 0 END AS NF FROM INAAD.SYSJINJIKIHON T LEFT OUTER JOIN INAMS.MSTTEN TNP ON T.SZKCD = TNP.TENCD LEFT OUTER JOIN KEYSYS.SYS_USERS US ON COALESCE(T.SHAINCD, '') = US.USER_ID) X WHERE X.NF > 0 ON DUPLICATE KEY UPDATE NM_FAMILY = X.NM_FAMILY, NM_NAME = X.NM_NAME, CUSTOM_VALUE = X.CUSTOM_VALUE, YOBI_2 = X.YOBI_2, YOBI_3 = X.YOBI_3, NM_UPDATE = X.NM_UPDATE, DT_UPDATE = CURRENT_TIMESTAMP;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME% KEYSYS.SYS_USERS UPDATE処理（プロパティにCD_USERを設定）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE KEYSYS.SYS_USERS SET CUSTOM_VALUE = TRIM(CAST(CD_USER AS CHAR (20))) WHERE CUSTOM_VALUE = ''; COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


REM ===== KEYSYS.SYS_USER_GROUP 処理 ==
SET MSG=%DATE% %TIME% INAAD.SYSSHAINKNG + KEYSYS.SYS_USERS → KEYSYS.SYS_USER_GROUP INSERT処理（社員権限ベースでグループ設定 いなげや[1]、システム[-2]）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USER_GROUP(CD_USER, CD_GROUP, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT T2.CD_USER AS CD_USER, X.CD_GROUP, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSSHAINKNG T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID LEFT JOIN (VALUES ROW (1), ROW (- 2)) AS X(CD_GROUP) ON 1 = 1 UNION SELECT T2.CD_USER AS CD_USER, X.CD_GROUP, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSSHAINKNG T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID RIGHT JOIN (VALUES ROW (1), ROW (- 2)) AS X(CD_GROUP) ON 1 = 1) AS T2 WHERE NOT EXISTS (SELECT * FROM KEYSYS.SYS_USER_GROUP WHERE CD_USER = T2.CD_USER AND CD_GROUP = T2.CD_GROUP); COMMIT;" >>%OUTFILE% 2>&1
SET MSG=%DATE% %TIME% INAAD.SYSJINJIKIHON + KEYSYS.SYS_USERS → KEYSYS.SYS_USER_GROUP INSERT処理（グループ設定 いなげや[1]、システム[-2]）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USER_GROUP(CD_USER, CD_GROUP, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT T2.CD_USER AS CD_USER, X.CD_GROUP, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID LEFT JOIN(VALUES ROW(1), ROW(- 2)) AS X(CD_GROUP) ON 1 = 1 UNION SELECT T2.CD_USER AS CD_USER, X.CD_GROUP, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID RIGHT JOIN(VALUES ROW(1), ROW(- 2)) AS X(CD_GROUP) ON 1 = 1) AS T2 WHERE NOT EXISTS (SELECT * FROM KEYSYS.SYS_USER_GROUP WHERE CD_USER = T2.CD_USER AND CD_GROUP = T2.CD_GROUP); COMMIT;" >>%OUTFILE% 2>&1


REM ===== KEYSYS.SYS_USER_POS 処理 ==
SET MSG=%DATE% %TIME% INAAD.SYSSHAINKNG + KEYSYS.SYS_USERS → KEYSYS.SYS_USER_POS INSERT処理（権限追加 本部マスタ[24320]）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USER_POS(CD_USER, CD_POSITION, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSSHAINKNG T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID LEFT JOIN (VALUES ROW(24320)) AS X(CD_POSITION) ON 1 = 1 WHERE T.KNGKBN_MST <> 0 UNION SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSSHAINKNG T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID RIGHT JOIN (VALUES ROW(24320)) AS X(CD_POSITION) ON 1 = 1 WHERE T.KNGKBN_MST <> 0) AS T2 WHERE NOT EXISTS (SELECT *  FROM KEYSYS.SYS_USER_POS WHERE CD_USER = T2.CD_USER AND CD_POSITION = T2.CD_POSITION); COMMIT;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAAD.SYSSHAINKNG + KEYSYS.SYS_USERS → KEYSYS.SYS_USER_POS INSERT処理（権限追加 本部特売[24321]、店舗特売[24322]）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USER_POS(CD_USER, CD_POSITION, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSSHAINKNG T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID LEFT OUTER JOIN (VALUES ROW(24321), ROW(24322)) AS X(CD_POSITION) ON 1 = 1 WHERE T.KNGKBN_HT <> 0 UNION SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSSHAINKNG T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID RIGHT OUTER JOIN (VALUES ROW(24321), ROW(24322)) AS X(CD_POSITION) ON 1 = 1 WHERE T.KNGKBN_HT <> 0) AS T2 WHERE NOT EXISTS (SELECT *  FROM KEYSYS.SYS_USER_POS WHERE CD_USER = T2.CD_USER AND CD_POSITION = T2.CD_POSITION); COMMIT;" >>%OUTFILE% 2>&1


rem ===== 特処理 =======================================
SET MSG=%DATE% %TIME% 情報システム部（所属コード[950]）にロール付与(本部マスタ[24320]、本部特売[24321]、店舗特売[24322])
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USER_POS(CD_USER, CD_POSITION, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID AND T.SZKCD IN ('950') LEFT JOIN (VALUES ROW (24320), ROW(24321), ROW(24322)) AS X(CD_POSITION) ON 1 = 1 UNION SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID AND T.SZKCD IN ('950') RIGHT JOIN (VALUES ROW(24320), ROW(24321), ROW(24322)) AS X(CD_POSITION) ON 1 = 1) AS T2 WHERE NOT EXISTS (SELECT *  FROM KEYSYS.SYS_USER_POS WHERE CD_USER = T2.CD_USER AND CD_POSITION = T2.CD_POSITION); COMMIT;" >>%OUTFILE% 2>&1


set msg=%DATE% %TIME% ユーザ(1402676)にロール付与(本部マスタ[24320]、本部特売[24321]、店舗特売[24322])
echo %msg%
echo %msg% >> %outfile%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USER_POS(CD_USER, CD_POSITION, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID LEFT JOIN (VALUES ROW(24320), ROW(24321), ROW(24322)) AS X(CD_POSITION) ON 1 = 1 WHERE T2.USER_ID = '1402676' UNION SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID RIGHT JOIN (VALUES ROW(24320), ROW(24321),ROW(24322)) AS X(CD_POSITION) ON 1 = 1 WHERE T2.USER_ID = '1402676') AS T2 WHERE NOT EXISTS (SELECT *  FROM KEYSYS.SYS_USER_POS WHERE CD_USER = T2.CD_USER AND CD_POSITION = T2.CD_POSITION); COMMIT;" >>%OUTFILE% 2>&1


SET MSG=%DATE% %TIME% 店舗（所属コード[300]以下）にロール付与(店舗特売[24322]) 20181211リリース
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT INTO KEYSYS.SYS_USER_POS(CD_USER, CD_POSITION, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID AND T.SZKCD <= ('300') LEFT JOIN (VALUES ROW(24322)) AS X(CD_POSITION) ON 1 = 1 UNION SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID AND T.SZKCD <= ('300') RIGHT JOIN (VALUES ROW(24322)) AS X(CD_POSITION) ON 1 = 1) AS T2 WHERE NOT EXISTS (SELECT *  FROM KEYSYS.SYS_USER_POS WHERE CD_USER = T2.CD_USER AND CD_POSITION = T2.CD_POSITION); COMMIT;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% 店舗以外（所属コード[300]より大きい）にロール付与(本部マスタ[24320]、本部特売[24321])
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO KEYSYS.SYS_USER_POS(CD_USER, CD_POSITION, NM_CREATE, NM_UPDATE) SELECT * FROM (SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID AND T.SZKCD > '300' LEFT JOIN (VALUES ROW(24320), ROW(24321)) AS X(CD_POSITION) ON 1 = 1 UNION SELECT T2.CD_USER AS CD_USER, X.CD_POSITION, 'inaadmin' AS NM_CREATE, 'inaadmin' AS NM_UPDATE FROM INAAD.SYSJINJIKIHON T INNER JOIN KEYSYS.SYS_USERS T2 ON T.SHAINCD = T2.USER_ID AND T.SZKCD > '300' RIGHT JOIN (VALUES ROW(24320), ROW(24321)) AS X(CD_POSITION) ON 1 = 1) AS T2 WHERE NOT EXISTS (SELECT *  FROM KEYSYS.SYS_USER_POS WHERE CD_USER = T2.CD_USER AND CD_POSITION = T2.CD_POSITION); COMMIT;" >>%OUTFILE% 2>&1

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
