REM [000][AN_NOUNYU_BFR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% DM97-アンケート有納入情報作成：INAIF.AN_NOUNYU_BFR マージ処理（全特アンケート有 納入データ(反映前)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM P460の発注数はQA288の回答より 1 → NULL ※ただしそもそも後続のP470で未使用
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"UPDATE INAIF.AN_NOUNYU_BFR ANB, (SELECT TC14.MOYSCD, TC14.MOYSKBN, TC14.MOYSSTDT, TC14.MOYSRBAN, TC14.BMNCD, TC14.KANRINO, TC14.KANRIENO, TC14.TENCD, TC14.NNDT, P460.HSUU FROM INAIF.AN_NOUNYU_BFR TC14 INNER JOIN (SELECT TC14.MOYSCD, TC14.MOYSKBN, TC14.MOYSSTDT, TC14.MOYSRBAN, TC14.BMNCD, TC14.KANRINO, TC14.KANRIENO, TC14.TENCD, TC14.NNDT, TC14.HSUU, TC14.HTASU, TC14.PTNNO, TC14.TSEIKBN, TC14.ZJSKFLG, TC14.NNWEEKHTDT, NULL AS TENHENKO FROM INAWK.AN_NOUNYU_AFT_NOTTRG2 TC14) P460 ON TC14.MOYSKBN = P460.MOYSKBN AND TC14.MOYSSTDT = P460.MOYSSTDT AND TC14.MOYSRBAN = P460.MOYSRBAN AND TC14.BMNCD = P460.BMNCD AND TC14.KANRINO = P460.KANRINO AND TC14.KANRIENO = P460.KANRIENO AND TC14.TENCD = P460.TENCD AND TC14.NNDT = P460.NNDT WHERE NOT (TC14.CUTTENFLG = 0 OR TC14.JHTSUINDT <> 0)) P470 SET ANB.HSUU = P470.HSUU WHERE ANB.MOYSKBN = P470.MOYSKBN AND ANB.MOYSSTDT = P470.MOYSSTDT AND ANB.MOYSRBAN = P470.MOYSRBAN AND ANB.BMNCD = P470.BMNCD AND ANB.KANRINO = P470.KANRINO AND ANB.KANRIENO = P470.KANRIENO AND ANB.TENCD = P470.TENCD AND ANB.NNDT = P470.NNDT;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_BFR;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
