REM [000][TOKTG_QASHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_QASHN マージ処理（アンケート結果_商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT INTO INATK2.TOKTG_QASHN(MOYSKBN, MOYSSTDT, MOYSRBAN, TENGPCD, BMNCD, KANRINO, KANRIENO, URISELKBN, ITMSELKBN, URICHGAM1, URICHGAM2, URICHGAM3, CSVSEQNO, UPDKBN, SENDFLG, OPERATOR, ADDDT, UPDDT) SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, TENGPCD, BMNCD, KANRINO, KANRIENO, URISELKBN, ITMSELKBN, URICHGAM1, URICHGAM2, URICHGAM3, CSVSEQNO, UPDKBN, SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAWK.AN_QASHN_DIFF AS QASHN_DIFF ON DUPLICATE KEY UPDATE URISELKBN = QASHN_DIFF.URISELKBN, ITMSELKBN = QASHN_DIFF.ITMSELKBN, URICHGAM1 = QASHN_DIFF.URICHGAM1, URICHGAM2 = QASHN_DIFF.URICHGAM2, URICHGAM3 = QASHN_DIFF.URICHGAM3, CSVSEQNO = QASHN_DIFF.CSVSEQNO, UPDKBN = QASHN_DIFF.UPDKBN, SENDFLG = QASHN_DIFF.SENDFLG, OPERATOR = QASHN_DIFF.OPERATOR, ADDDT = QASHN_DIFF.ADDDT, UPDDT = QASHN_DIFF.UPDDT;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
