REM [000][TOKTG_QAGP]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK.TOKTG_HB マージ処理（全店特売(アンケート有)_販売）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INATK.TOKTG_HB(MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, TENATSUK_ARR, SENDFLG, OPERATOR, ADDDT, UPDDT) SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, TENATSUK_ARR, SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAWK.AN_TOKTG_HB AS new ON DUPLICATE KEY UPDATE TENATSUK_ARR = new.TENATSUK_ARR, SENDFLG = new.SENDFLG, OPERATOR = new.OPERATOR, ADDDT = new.ADDDT, UPDDT = new.UPDDT;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKTG_HB;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
