REM [000][TOKTG_QATEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_QATEN マージ処理（アンケート結果_店舗）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INATK2.TOKTG_QATEN(MOYSKBN, MOYSSTDT, MOYSRBAN, TENCD, KYOSEIFLG, TENGPCD, LDTENKBN, MBSYFLG, HBSTRTFLG, MBANSFLG, CSVSEQNO, SENDFLG, OPERATOR, ADDDT, UPDDT) SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, TENCD, KYOSEIFLG, TENGPCD, LDTENKBN, MBSYFLG, HBSTRTFLG, MBANSFLG, CSVSEQNO, SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAWK.AN_QATEN_DIFF AS QATEN_DIFF ON DUPLICATE KEY UPDATE TENGPCD = QATEN_DIFF.TENGPCD, LDTENKBN = QATEN_DIFF.LDTENKBN, MBSYFLG = QATEN_DIFF.MBSYFLG, HBSTRTFLG = QATEN_DIFF.HBSTRTFLG, MBANSFLG = QATEN_DIFF.MBANSFLG, CSVSEQNO = QATEN_DIFF.CSVSEQNO, SENDFLG = QATEN_DIFF.SENDFLG, OPERATOR = QATEN_DIFF.OPERATOR, ADDDT = QATEN_DIFF.ADDDT, UPDDT = QATEN_DIFF.UPDDT;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
