REM [000][AN_QATENGP_DIFF]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_QATENGP_DIFF ロード処理（アンケート結果_店グループ_反映差分）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_QATENGP_DIFF ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAWK.AN_QATENGP_DIFF SELECT TGTENGP.MOYSKBN, TGTENGP.MOYSSTDT, TGTENGP.MOYSRBAN, TGTENGP.TENGPCD, TGTENGP.KYOSEIFLG, TGTENGP.QASYUKBN, 1 AS LDSYFLG, 1 AS URIASELKBN, 0 AS SCHANSFLG, 0 AS ITMANSFLG, 0 AS CSVSEQNO, 9 AS SENDFLG, '' AS OPERATOR, SBD.DTTIME AS ADDDT, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_TIMESTAMP END AS UPDDT FROM INATK2.TOKTG_TENGP TGTENGP LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE EXISTS (SELECT 1 FROM INAWK.AN_CRE_KEY ACK WHERE TGTENGP.MOYSKBN = ACK.MOYSKBN AND TGTENGP.MOYSSTDT = ACK.MOYSSTDT AND TGTENGP.MOYSRBAN = ACK.MOYSRBAN) AND TGTENGP.UPDKBN <> 1 AND TGTENGP.KYOSEIFLG = 0 AND TGTENGP.QASYUKBN <> 5 UNION ALL SELECT TGTENGP.MOYSKBN, TGTENGP.MOYSSTDT, TGTENGP.MOYSRBAN, TGTENGP.TENGPCD, TGTENGP.KYOSEIFLG, TGTENGP.QASYUKBN, 1 AS LDSYFLG, 1 AS URIASELKBN, 0 AS SCHANSFLG, 0 AS ITMANSFLG, 0 AS CSVSEQNO, 9 AS SENDFLG, '' AS OPERATOR, SBD.DTTIME AS ADDDT, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_TIMESTAMP END AS UPDDT FROM INATK2.TOKTG_TENGP TGTENGP LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE TGTENGP.UPDKBN <> 1 AND TGTENGP.KYOSEIFLG = 1 AND TGTENGP.QACREDT_K = SBD.DT_INT AND TGTENGP.QARCREDT_K = 0 AND TGTENGP.QASYUKBN <> 5;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_QATENGP_DIFF;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
