REM [000][TOKTG_KHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_KHN マージ処理（全店特売（アンケート有）_基本）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INATK2.TOKTG_KHN TGKHN, (SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, SBD.DT_INT FROM INATK2.TOKTG_KHN TGKHN LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE TGKHN.UPDKBN <> 1 AND TGKHN.QARCREDT <> 0 AND SBD.DT_INT = TGKHN.QARCREDT) UPD SET TGKHN.QACREDT = UPD.DT_INT, TGKHN.QARCREDT = 0 WHERE TGKHN.MOYSKBN = UPD.MOYSKBN AND TGKHN.MOYSSTDT = UPD.MOYSSTDT AND TGKHN.MOYSRBAN = UPD.MOYSRBAN;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
