REM [000][TOKTG_SHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK.TOKTG_SHN マージ処理（全店特売(アンケート有)_商品）TANDEM
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"UPDATE INATK.TOKTG_SHN TGSHN, (SELECT JLD.MOYSKBN, JLD.MOYSSTDT, JLD.MOYSRBAN, JLD.BMNCD, JLD.KANRINO, MAX(JLD.JLSTCREDT) AS JLSTCREDT FROM INAWK.JH_LIST_DIFF JLD GROUP BY JLD.MOYSKBN, JLD.MOYSSTDT, JLD.MOYSRBAN, JLD.BMNCD, JLD.KANRINO) JLD SET TGSHN.JLSTCREDT = JLD.JLSTCREDT WHERE TGSHN.MOYSKBN = JLD.MOYSKBN AND TGSHN.MOYSSTDT = JLD.MOYSSTDT AND TGSHN.MOYSRBAN = JLD.MOYSRBAN AND TGSHN.BMNCD = JLD.BMNCD AND TGSHN.KANRINO = JLD.KANRINO;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
