REM [000][TOKTG_KHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_KHN マージ処理（全店特売(アンケート有)_商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"UPDATE INATK2.TOKTG_KHN TGKHN, (SELECT DISTINCT JLD.MOYSKBN, JLD.MOYSSTDT, JLD.MOYSRBAN FROM INAWK.JH_LIST_DIFF JLD) JLD SET TGKHN.JLSTCREFLG = 1, TGKHN.SENDFLG = 9 WHERE TGKHN.MOYSKBN = JLD.MOYSKBN AND TGKHN.MOYSSTDT = JLD.MOYSSTDT AND TGKHN.MOYSRBAN = JLD.MOYSRBAN;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
