REM [000][AN_NOUNYU_BFR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.AN_NOUNYU_BFR マージ処理（全特アンケート有 納入データ(反映前)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAIF.AN_NOUNYU_BFR ANB, (SELECT JLD.MOYSKBN, JLD.MOYSSTDT, JLD.MOYSRBAN, JLD.BMNCD, JLD.KANRINO, JLD.KANRIENO, JLD.TENCD, JLD.JLSTCREDT FROM INAWK.JH_LIST_DIFF JLD) JLD SET ANB.JLSTCREDT = JLD.JLSTCREDT WHERE ANB.MOYSKBN = JLD.MOYSKBN AND ANB.MOYSSTDT = JLD.MOYSSTDT AND ANB.MOYSRBAN = JLD.MOYSRBAN AND ANB.BMNCD = JLD.BMNCD AND ANB.KANRINO = JLD.KANRINO AND ANB.KANRIENO = JLD.KANRIENO AND ANB.TENCD = JLD.TENCD;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
