REM [000][JH_LIST_DIFF]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.JH_LIST_DIFF ロード処理（事前発注リスト出力日反映差分）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.JH_LIST_DIFF ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT ignore INTO INAWK.JH_LIST_DIFF SELECT ANB.MOYSCD, ANB.MOYSKBN, ANB.MOYSSTDT, ANB.MOYSRBAN, ANB.BMNCD, ANB.KANRINO, ANB.KANRIENO, ANB.TENCD, 0 AS NNDT, SBD.DT_INT AS JLSTCREDT FROM INAIF.AN_NOUNYU_BFR ANB INNER JOIN INAIF.JH_DATE JD ON ANB.BMNCD = JD.BMNCD AND ANB.NENMATKBN = JD.NENMATKBN AND ANB.NNSTDT <> 0 AND ANB.UPDKBN <> 1 LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE ((ANB.NENMATKBN = 1 OR ANB.TSHUFLG = 1) AND (ANB.NNSTDT between JD.TOKSTDT AND JD.TOKEDDT OR ANB.NNEDDT between JD.TOKSTDT AND JD.TOKEDDT)) OR (JD.TYUSTDT <= ANB.NNSTDT AND JD.TYUEDDT >= ANB.NNSTDT); commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.JH_LIST_DIFF;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
