REM [000][AN_QATEN_DIFF]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_QATEN_DIFF ロード処理（アンケート結果_店舗_反映差分）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAWK.AN_QATEN_DIFF;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAWK.AN_QATEN_DIFF SELECT TGTEN.MOYSKBN, TGTEN.MOYSSTDT, TGTEN.MOYSRBAN, TGTEN.TENCD, TGTEN.KYOSEIFLG, TGTEN.TENGPCD, TGTEN.LDTENKBN, 1 AS MBSYFLG, 0 AS HBSTRTFLG, 0 AS MBANSFLG, 0 AS CSVSEQNO, 9 AS SENDFLG, '' AS OPERATOR, SBD.DTTIME AS ADDDT, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_TIMESTAMP END AS UPDDT FROM INATK2.TOKTG_TEN TGTEN LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 INNER JOIN INAWK.AN_QATENGP_DIFF AQD ON TGTEN.MOYSKBN = AQD.MOYSKBN AND TGTEN.MOYSSTDT = AQD.MOYSSTDT AND TGTEN.MOYSRBAN = AQD.MOYSRBAN AND TGTEN.TENGPCD = AQD.TENGPCD WHERE AQD.QASYUKBN <> 5;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_QATEN_DIFF;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
