REM [000][JH_LIST_DIFF]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.JH_LIST_DIFF ロード処理（事前発注リスト出力日反映差分）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.JH_LIST_DIFF ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT ignore INTO INAWK.JH_LIST_DIFF SELECT ANN.MOYSCD, ANN.MOYSKBN, ANN.MOYSSTDT, ANN.MOYSRBAN, ANN.BMNCD, ANN.KANRINO, ANN.KANRIENO, ANN.TENCD, 0 AS NNDT, SBD.DT_INT AS JLSTCREDT FROM INAIF.AN_NOUNYU_NEQ ANN INNER JOIN INAIF.JH_DATE JD ON ANN.BMNCD = JD.BMNCD AND ANN.NENMATKBN = JD.NENMATKBN AND ANN.NNSTDT <> 0 AND ANN.UPDKBN <> 1 LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE ((ANN.NENMATKBN = 1 OR ANN.TSHUFLG = 1) AND (ANN.NNSTDT between JD.TOKSTDT AND JD.TOKEDDT OR ANN.NNEDDT between JD.TOKSTDT AND JD.TOKEDDT)) OR (JD.TYUSTDT <= ANN.NNSTDT AND JD.TYUEDDT >= ANN.NNSTDT);commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.JH_LIST_DIFF;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
