REM [000][AN_QASHN_DIFF]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_QASHN_DIFF ロード処理（アンケート結果_商品_反映差分）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM DB2 -L %OUTTIME% "TRUNCATE TABLE INAWK.AN_QASHN_DIFF IMMEDIATE" >> %OUTFILE%
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_QASHN_DIFF;INSERT IGNORE INTO INAWK.AN_QASHN_DIFF SELECT TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, AQD.TENGPCD, TGSHN.BMNCD, TGSHN.KANRINO, TGSHN.KANRIENO, 1 AS URISELKBN, 1 AS ITMSELKBN, CASE WHEN AQD.QASYUKBN = 3 THEN CASE WHEN TGSHN.ADDSHUKBN = 1 THEN KO_A_BAIKAAN ELSE TGSHN.A_BAIKAAM_100G END ELSE 0 END AS URICHGAM1, CASE WHEN AQD.QASYUKBN = 3 THEN CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 0 ELSE TGSHN.BD1_A_BAIKAAN END ELSE 0 END AS URICHGAM2, CASE WHEN AQD.QASYUKBN = 3 THEN CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 0 ELSE TGSHN.BD2_A_BAIKAAN END ELSE 0 END AS URICHGAM3, ROW_NUMBER() OVER (PARTITION BY TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, AQD.TENGPCD ORDER BY TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, AQD.TENGPCD, TGSHN.HIGAWRFLG DESC, TGSHN.BMNCD, TGSHN.HBSTDT, TGSHN.DAICD, TGSHN.CHUCD, TGSHN.SHOBUNCD, TGSHN.SHNCD, TGSHN.KANRINO) AS CSVSEQNO, 0 AS UPDKBN, 9 AS SENDFLG, CASE WHEN TGSHN.B_BAIKAAM_100G = 0 THEN RPAD(TGSHN.SHNCD, 14, ' ') || '1' ELSE TGSHN.SHNCD || '2' END AS OPERATOR, SBD.DTTIME AS ADDDT, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_TIMESTAMP END AS UPDDT FROM INATK2.TOKTG_SHN TGSHN INNER JOIN (SELECT TGSHN_LAST.MOYSKBN, TGSHN_LAST.MOYSSTDT, TGSHN_LAST.MOYSRBAN, TGSHN_LAST.BMNCD, TGSHN_LAST.KANRINO, MAX(TGSHN_LAST.KANRIENO) AS KANRIENO FROM INATK2.TOKTG_SHN TGSHN_LAST WHERE TGSHN_LAST.UPDKBN <> 1 GROUP BY TGSHN_LAST.MOYSKBN, TGSHN_LAST.MOYSSTDT, TGSHN_LAST.MOYSRBAN, TGSHN_LAST.BMNCD, TGSHN_LAST.KANRINO) TGSHN_LAST ON TGSHN.MOYSKBN = TGSHN_LAST.MOYSKBN AND TGSHN.MOYSSTDT = TGSHN_LAST.MOYSSTDT AND TGSHN.MOYSRBAN = TGSHN_LAST.MOYSRBAN AND TGSHN.BMNCD = TGSHN_LAST.BMNCD AND TGSHN.KANRINO = TGSHN_LAST.KANRINO AND TGSHN.KANRIENO = TGSHN_LAST.KANRIENO INNER JOIN INAWK.AN_QATENGP_DIFF AQD ON TGSHN.MOYSKBN = AQD.MOYSKBN AND TGSHN.MOYSSTDT = AQD.MOYSSTDT AND TGSHN.MOYSRBAN = AQD.MOYSRBAN LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE AQD.QASYUKBN <> 5;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_QASHN_DIFF;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
