REM [000][TOKTG_QAGP]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK.TOKTG_NNDT マージ処理（全店特売(アンケート有)_納入日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INATK.TOKTG_NNDT(MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, NNDT, TENHTSU_ARR, TENCHGFLG_ARR, HTASU, PTNNO, TSEIKBN, TPSU, TENKAISU, ZJSKFLG, WEEKHTDT, SENDFLG, OPERATOR, ADDDT, UPDDT, BAT_CTLFLG01) SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, NNDT, TENHTSU_ARR, TENCHGFLG_ARR, HTASU, PTNNO, TSEIKBN, TPSU, TENKAISU, ZJSKFLG, WEEKHTDT, SENDFLG, OPERATOR, ADDDT, UPDDT, BAT_CTLFLG01 FROM INAWK.AN_TOKTG_NNDT AS new ON DUPLICATE KEY UPDATE TENHTSU_ARR = new.TENHTSU_ARR, TENCHGFLG_ARR = new.TENCHGFLG_ARR, HTASU = new.HTASU, PTNNO = new.PTNNO, TSEIKBN = new.TSEIKBN, TPSU = new.TPSU, TENKAISU = new.TENKAISU, ZJSKFLG = new.ZJSKFLG, WEEKHTDT = new.WEEKHTDT, SENDFLG = new.SENDFLG, OPERATOR = new.OPERATOR, ADDDT = new.ADDDT, UPDDT = new.UPDDT, BAT_CTLFLG01 = new.BAT_CTLFLG01;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKTG_NNDT;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
