REM [000][TOKTG_QAGP]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKTG_QAGP マージ処理（アンケート結果_店グループ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INATK2.TOKTG_QAGP(MOYSKBN, MOYSSTDT, MOYSRBAN, TENGPCD, KYOSEIFLG, QASYUKBN, LDSYFLG, URIASELKBN, SCHANSFLG, ITMANSFLG, CSVSEQNO, SENDFLG, OPERATOR, ADDDT, UPDDT) SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, TENGPCD, KYOSEIFLG, QASYUKBN, LDSYFLG, URIASELKBN, SCHANSFLG, ITMANSFLG, CSVSEQNO, SENDFLG, OPERATOR, ADDDT, UPDDT FROM INAWK.AN_QATENGP_DIFF AS QAGP_DIFF ON DUPLICATE KEY UPDATE KYOSEIFLG = QAGP_DIFF.KYOSEIFLG, QASYUKBN = QAGP_DIFF.QASYUKBN, LDSYFLG = QAGP_DIFF.LDSYFLG, URIASELKBN = QAGP_DIFF.URIASELKBN, SCHANSFLG = QAGP_DIFF.SCHANSFLG, ITMANSFLG = QAGP_DIFF.ITMANSFLG, CSVSEQNO = QAGP_DIFF.CSVSEQNO, SENDFLG = QAGP_DIFF.SENDFLG, OPERATOR = QAGP_DIFF.OPERATOR, ADDDT = QAGP_DIFF.ADDDT, UPDDT = QAGP_DIFF.UPDDT;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
