REM [000][AN_HANBAI_DT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_HANBAI_DT(全特アンケート有 販売日) テーブルクリア処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_HANBAI_DT ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIF.AN_HANBAI_AFT → INAIF.AN_HANBAI_DT ロード処理（全特アンケート有 販売日）：P230販売日スライド処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"INSERT IGNORE INTO INAIF.AN_HANBAI_DT SELECT T1.MOYSCD, T1.MOYSKBN, T1.MOYSSTDT, T1.MOYSRBAN, T1.BMNCD, T1.KANRINO, T1.KANRIENO, DATE_FORMAT(MD.DT, '%%Y%%m%%d') AS HBDT FROM (SELECT DISTINCT HAN.MOYSCD, HAN.MOYSKBN, HAN.MOYSSTDT, HAN.MOYSRBAN, HAN.BMNCD, HAN.KANRINO, HAN.KANRIENO, HAN.HBSTDT, HAN.HBEDDT FROM INAIF.AN_HANBAI_AFT HAN WHERE HAN.MOHBSTDT <> HAN.HBSTDT OR HAN.HANKAISIFLG = 0) T1 LEFT OUTER JOIN INAPARM.MSTDAYS MD ON MD.DT BETWEEN T1.HBSTDT AND T1.HBEDDT UNION ALL SELECT DISTINCT HAN.MOYSCD, HAN.MOYSKBN, HAN.MOYSSTDT, HAN.MOYSRBAN, HAN.BMNCD, HAN.KANRINO, HAN.KANRIENO, DATE_FORMAT(HAN.HBDT, '%%Y%%m%%d') FROM (SELECT HAN.MOYSCD, HAN.MOYSKBN, HAN.MOYSSTDT, HAN.MOYSRBAN, HAN.BMNCD, HAN.KANRINO, HAN.KANRIENO, HAN.HANKAISIFLG, HAN.HBSLIDEFLG, HAN.MOHBSTDT, HAN.HBSTDT, HAN.HBEDDT, CASE WHEN HAN.HBSTDT <> HAN.HBEDDT OR HAN.HBSLIDEFLG = 0 THEN DATE_FORMAT(DATE_ADD(DATE_FORMAT(MD.DT, '%%Y%%m%%d'), INTERVAL + 1 DAY), '%%Y%%m%%d') ELSE 0 END AS HBDT FROM INAIF.AN_HANBAI_AFT HAN LEFT OUTER JOIN INAPARM.MSTDAYS MD ON MD.DT BETWEEN HAN.HBSTDT AND HAN.HBEDDT WHERE NOT (HAN.MOHBSTDT <> HAN.HBSTDT OR HAN.HANKAISIFLG = 0)) HAN WHERE HAN.HBDT <> 0 AND HAN.HBDT <= HAN.HBEDDT;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_HANBAI_DT;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIF.AN_HANBAI_DT → INAIF.AN_HANBAI_AFT 削除処理（全特アンケート有 販売データ(反映後)）：P230販売日スライド後販売日0を除外
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INAIF.AN_HANBAI_AFT HAN WHERE NOT EXISTS (SELECT * FROM INAIF.AN_HANBAI_DT HD WHERE HAN.MOYSCD = HD.MOYSCD AND HAN.MOYSKBN = HD.MOYSKBN AND HAN.MOYSSTDT = HD.MOYSSTDT AND HAN.MOYSRBAN = HD.MOYSRBAN AND HAN.BMNCD = HD.BMNCD AND HAN.KANRINO = HD.KANRINO AND HAN.KANRIENO = HD.KANRIENO);commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_HANBAI_AFT;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
