REM [000][AN_NOUNYU_NEQ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.AN_NOUNYU_NEQ マージ処理（全特アンケート無 納入データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"UPDATE INAIF.AN_NOUNYU_NEQ ANN, (SELECT JLD.MOYSKBN, JLD.MOYSSTDT, JLD.MOYSRBAN, JLD.BMNCD, JLD.KANRINO, JLD.KANRIENO, JLD.TENCD, JLD.JLSTCREDT FROM INAWK.JH_LIST_DIFF JLD) JLD SET ANN.JLSTCREDT = JLD.JLSTCREDT WHERE ANN.MOYSKBN = JLD.MOYSKBN AND ANN.MOYSSTDT = JLD.MOYSSTDT AND ANN.MOYSRBAN = JLD.MOYSRBAN AND ANN.BMNCD = JLD.BMNCD AND ANN.KANRINO = JLD.KANRINO AND ANN.KANRIENO = JLD.KANRIENO AND ANN.TENCD = JLD.TENCD;commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
