REM [000][AN_ZW_NOUNYU_BFR_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_ZW_NOUNYU_BFR_TEN ロード処理（中間納入日(ア有全割反映前)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_ZW_NOUNYU_BFR_TEN ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.AN_ZW_NOUNYU_BFR_TEN WITH WK AS (SELECT SHN.MOYSKBN, SHN.MOYSSTDT, SHN.MOYSRBAN, SHN.BMNCD, SHN.KANRINO, SHN.KANRIENO, NUMS.TENCD, MD.DT AS NNDT, CASE WHEN COALESCE(TJTEN.TENCD, 0) <> 0 AND TJTEN.TJFLG = 1 THEN 0 WHEN COALESCE(TJTEN.TENCD, 0) <> 0 AND TJTEN.TJFLG = 2 THEN NULL WHEN TRIM(SUBSTR(SHN.TENRANK_ARR, NUMS.TENCD, 1)) <> '' THEN 0 ELSE NULL END AS HSUU, CAST(NULL AS SIGNED) AS TENHENKO, 0 AS HTASU, 0 AS PTNNO, 0 AS TSEIKBN, 0 AS ZJSKFLG, 0 AS WEEKHTDT FROM (SELECT SHN.MOYSKBN, SHN.MOYSSTDT, SHN.MOYSRBAN, SHN.BMNCD, SHN.KANRINO, SHN.KANRIENO, SHN.NNSTDT, SHN.NNEDDT, SHN.TENRANK_ARR FROM INATK2.TOKTG_SHN SHN WHERE SHN.ADDSHUKBN = 1 AND SHN.UPDKBN <> 1 AND SHN.NNSTDT <> 0) SHN LEFT OUTER JOIN INAPARM.MSTDAYS MD ON MD.DT BETWEEN SHN.NNSTDT AND SHN.NNEDDT LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 LEFT OUTER JOIN INATK2.TOKTG_TJTEN TJTEN ON SHN.MOYSKBN = TJTEN.MOYSKBN AND SHN.MOYSSTDT = TJTEN.MOYSSTDT AND SHN.MOYSRBAN = TJTEN.MOYSRBAN AND SHN.BMNCD = TJTEN.BMNCD AND SHN.KANRINO = TJTEN.KANRINO AND SHN.KANRIENO = TJTEN.KANRIENO AND NUMS.TENCD = TJTEN.TENCD) SELECT * FROM WK SHN WHERE EXISTS (SELECT * FROM WK WHERE WK.HSUU IS NOT NULL AND SHN.MOYSKBN = WK.MOYSKBN AND SHN.MOYSSTDT = WK.MOYSSTDT AND SHN.MOYSRBAN = WK.MOYSRBAN AND SHN.BMNCD = WK.BMNCD AND SHN.KANRINO = WK.KANRINO AND SHN.KANRIENO = WK.KANRIENO AND SHN.TENCD = WK.TENCD); commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_ZW_NOUNYU_BFR_TEN;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
