REM [128][BFC30]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0128
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFBUO027

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(予約発注＿商品)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e"SELECT LPAD(T1.KKKCD, 4, 0) || RPAD(COALESCE(T1.SHNCD, ''), 14, ' ') || LPAD(COALESCE(T1.CATALGNO, 0), 4, 0) || LPAD(COALESCE(T1.HTDT, 0), 8, 0) || LPAD(COALESCE(T1.UKESTDT, 0), 8, 0) || LPAD(COALESCE(T1.UKEEDDT, 0), 8, 0) || LPAD(COALESCE(T1.TENISTDT, 0), 8, 0) || LPAD(COALESCE(T1.TENIEDDT, 0), 8, 0) || LPAD(COALESCE(T1.YOTEISU, 0), 6, 0) || LPAD(COALESCE(T1.GENDOSU, 0), 6, 0) || LPAD(COALESCE(T1.NGFLG, 0), 1, 0) || LPAD(COALESCE(T1.UPDKBN, 0), 1, 0) || LPAD(COALESCE(T1.SENDFLG, 0), 1, 0) || RPAD(COALESCE(T1.OPERATOR, ''), 20, ' ') || LPAD(COALESCE(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), 0), 8, 0) || LPAD(COALESCE(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), 0), 8, 0) FROM INATK2.HATYH_SHN T1 WHERE T1.UPDKBN <> 1 ORDER BY T1.KKKCD, T1.SHNCD;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
REM call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
