REM [147][A10TSKD]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0147
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFBUO041

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(新改装店発注データ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e"SELECT REC FROM (SELECT RPAD(COALESCE(FILLER1, ''), 2, ' ') || LPAD(WK.TENCD, 3, 0) || RPAD(WK.SHOCD, 13, ' ') || CASE WHEN COALESCE(WK.HCUSU, 0) >= 0 THEN '+' ELSE '-' END || LPAD(ABS(COALESCE(WK.HCUSU, 0)), 5, 0) || LPAD(COALESCE(WK.HCUHZK, 0), 8, 0) || LPAD(COALESCE(WK.NNYHZK, 0), 8, 0) || LPAD(COALESCE(WK.NNYYB, 0), 1, 0) || LPAD(COALESCE(WK.SHOKBN, 0), 1, 0) || LPAD(COALESCE(WK.BDENKBN, 0), 1, 0) || RPAD(COALESCE(WK.SEPKBN, ''), 1, ' ') || LPAD(COALESCE(WK.SICTFLG, 0), 1, 0) || LPAD(TRIM(COALESCE(WK.JOBFLG, 0)), 2, 0) || RPAD(COALESCE(WK.FILLER2, ''), 14, ' ') AS REC, WK.NNYHZK FROM INAWK.THWK01_A10TSKD WK WHERE WK.SSFLG = 1 ORDER BY WK.SHOCD, WK.NNYHZK, WK.TENCD) WK ORDER BY WK.NNYHZK;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
