REM [189][TOKTJ]
@ECHO OFF

REM ƒƒOƒtƒHƒ‹ƒ_ì¬
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM ƒRƒ}ƒ“ƒhƒtƒHƒ‹ƒ_ì¬
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ƒƒOƒtƒ@ƒCƒ‹‚Ìî•ñ
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ƒx[ƒXƒtƒHƒ‹ƒ_
SET BASEDIR=%~DP0..

REM XV‘ÎÛ‚Ìî•ñ
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME%  ¨  MARGEˆ—(Ž–‘O”­’)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INATK.TOKTJ(LSTNO, TITLE, STDT, EDDT, SHWSTDT, SHWEDDT, SNDSIMEDT, OPERATOR, ADDDT, UPDDT) SELECT * FROM (SELECT LISTNO AS LSTNO, REPLACE (RTRIM(REPLACE (TITLE, '@', ' ')), ' ', '@€') AS TITLE, HAKAIS AS STDT, HASYUR AS EDDT, KESKAB AS SHWSTDT, KESSYUB AS SHWEDDT, SOUSIME AS SNDSIMEDT, 'BATCH' AS OPERATOR, CURRENT_TIMESTAMP AS ADDDT, CURRENT_TIMESTAMP AS UPDDT FROM INAIN.BFI01) AS T1 ON DUPLICATE KEY UPDATE LSTNO = T1.LSTNO, TITLE = T1.TITLE, STDT = T1.STDT, EDDT = T1.EDDT, SHWSTDT = T1.SHWSTDT, SHWEDDT = T1.SHWEDDT, SNDSIMEDT = T1.SNDSIMEDT, OPERATOR = 'BATCH', ADDDT = DATE_ADD(CURRENT_TIMESTAMP, INTERVAL - 1 DAY), UPDDT = DATE_ADD(CURRENT_TIMESTAMP, INTERVAL - 1 DAY); commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKTJ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
