REM [190][TOKTJ_SHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME%  →  MARGE処理(事前発注＿商品)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT INTO INATK.TOKTJ_SHN(LSTNO, BMNCD, HYOSEQNO, SHNCD, BINKBN, BINKBNKN, SANCHIKN, SHNKN, ODS, TANIKBNKN, NHKETAIKBN, JRYO, COMMENTKN, JISKAVG, OPERATOR, ADDDT, UPDDT) SELECT * FROM (SELECT LISTNO AS LSTNO, BUNBMC AS BMNCD, SORTNO AS HYOSEQNO, CAST(SHOCD AS CHAR (14)) AS SHNCD, BINK AS BINKBN, BINKMKJ AS BINKBNKN, SANTIMKJ AS SANCHIKN, SHOMKJ AS SHNKN, ODS AS ODS, TANIMKJK AS TANIKBNKN, NULLIF(NOUKE, '　') AS NHKETAIKBN, CAST(SUBSTR(JYURYO, 1, 3) || '.' || SUBSTR(JYURYO, 4, 1) AS DECIMAL) AS JRYO, TOKCOME AS COMMENTKN, CAST(SUBSTR(HEKINJI, 1, 5) || '.' || SUBSTR(HEKINJI, 6, 1) AS DECIMAL) AS JISKAVG, RTRIM('BATCH') AS OPERATOR, CURRENT_TIMESTAMP AS ADDDT, CURRENT_TIMESTAMP AS UPDDT FROM INAIN.BFI02) BFI02 WHERE NOT EXISTS (SELECT * FROM INATK.TOKTJ_SHN SHN WHERE SHN.LSTNO = BFI02.LSTNO AND SHN.BMNCD = BFI02.BMNCD AND SHN.HYOSEQNO = BFI02.HYOSEQNO); commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKTJ_SHN;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
