REM [190][TOKTJ_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME%  →  DELETE処理(INATK.事前発注_店舗)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.TOKTJ_TEN TEN WHERE EXISTS (SELECT 1 FROM (SELECT TEN.LSTNO, TEN.BMNCD, TEN.HYOSEQNO, TEN.TENCD FROM INATK2.TOKTJ_TEN TEN WHERE EXISTS (SELECT * FROM (SELECT DISTINCT LISTNO AS LISTNO, BUNBMC AS BUNBMC FROM INAIN.BFI02) BFI02 WHERE TEN.LSTNO = BFI02.LISTNO AND TEN.BMNCD = BFI02.BUNBMC) AND TEN.SENDFLG IN (1)) TEN2 WHERE TEN.LSTNO = TEN2.LSTNO AND TEN.BMNCD = TEN2.BMNCD AND TEN.HYOSEQNO = TEN2.HYOSEQNO AND TEN.TENCD = TEN2.TENCD); commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKTJ_TEN ;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME%  →  DELETE処理(INATK2.事前発注_店舗)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK2.TOKTJ_TEN TEN WHERE EXISTS (SELECT 1 FROM (SELECT TEN.LSTNO, TEN.BMNCD, TEN.HYOSEQNO, TEN.TENCD FROM INATK2.TOKTJ_TEN TEN WHERE EXISTS (SELECT * FROM (SELECT DISTINCT LISTNO AS LISTNO, BUNBMC AS BUNBMC FROM INAIN.BFI02) BFI02 WHERE TEN.LSTNO = BFI02.LISTNO AND TEN.BMNCD = BFI02.BUNBMC) AND TEN.SENDFLG IN (1)) TEN2 WHERE TEN.LSTNO = TEN2.LSTNO AND TEN.BMNCD = TEN2.BMNCD AND TEN.HYOSEQNO = TEN2.HYOSEQNO AND TEN.TENCD = TEN2.TENCD) ; commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK2.TOKTJ_TEN;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
