REM [191][TOKTJ_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME%  →  MARGE処理(INATK.事前発注＿店舗)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "INSERT INTO INATK.TOKTJ_TEN(LSTNO, BMNCD, HYOSEQNO, TENCD, IRISU_RG, IRISU_TB, SBAIKAAM_TB, BAIKAAM_TB, SBAIKAAM_RG, BAIKAAM_RG, GENKAAM_MAE, GENKAAM_ATO, GENKAAM_RG, GENKAAM_PACK, BAIKAAM_PACK, JTDT_01, JTDT_02, JTDT_03, JTDT_04, JTDT_05, JTDT_06, JTDT_07, JTDT_08, JTDT_09, JTDT_10, TSEIKBN_01, TSEIKBN_02, TSEIKBN_03, TSEIKBN_04, TSEIKBN_05, TSEIKBN_06, TSEIKBN_07, TSEIKBN_08, TSEIKBN_09, TSEIKBN_10, SHNKBN_01, SHNKBN_02, SHNKBN_03, SHNKBN_04, SHNKBN_05, SHNKBN_06, SHNKBN_07, SHNKBN_08, SHNKBN_09, SHNKBN_10, HTSU_01, HTSU_02, HTSU_03, HTSU_04, HTSU_05, HTSU_06, HTSU_07, HTSU_08, HTSU_09, HTSU_10, PAGENO, SENDFLG, OPERATOR, ADDDT, UPDDT) SELECT * FROM (SELECT LISTNO AS LISTNO, BUNBMC AS BUNBMC, SORTNO AS SORTNO, MISECD AS MISECD, RMISIR AS RMISIR, HJMISIR AS HJMISIR, SOUBAIFG AS SOUBAIFG, HONBAIFG AS HONBAIFG, RSOBAIFG AS RSOBAIFG, RHONBAIFG AS RHONBAIFG, CAST(SUBSTR(JZNGENKA, 1, 6) || '.' || SUBSTR(JZNGENKA, 7, 2) AS DECIMAL) AS JZNGENKA, CAST(SUBSTR(TUIGENKA, 1, 6) || '.' || SUBSTR(TUIGENKA, 7, 2) AS DECIMAL) AS TUIGENKA, CAST(SUBSTR(RGENKA, 1, 6) || '.' || SUBSTR(RGENKA, 7, 2) AS DECIMAL) AS RGENKA, CAST(SUBSTR(GENFU, 1, 6) || '.' || SUBSTR(GENFU, 7, 2) AS DECIMAL) AS GENFU, BAIFU AS BAIFU, HIDUK1 AS HIDUK1, HIDUK2 AS HIDUK2, HIDUK3 AS HIDUK3, HIDUK4 AS HIDUK4, HIDUK5 AS HIDUK5, HIDUK6 AS HIDUK6, HIDUK7 AS HIDUK7, HIDUK8 AS HIDUK8, HIDUK9 AS HIDUK9, HIDUK10 AS HIDUK10, CASE WHEN TRIM(TEISEK1) = '' THEN NULL ELSE TEISEK1 END AS TEISEK1, CASE WHEN TRIM(TEISEK2) = '' THEN NULL ELSE TEISEK2 END AS TEISEK2, CASE WHEN TRIM(TEISEK3) = '' THEN NULL ELSE TEISEK3 END AS TEISEK3, CASE WHEN TRIM(TEISEK4) = '' THEN NULL ELSE TEISEK4 END AS TEISEK4, CASE WHEN TRIM(TEISEK5) = '' THEN NULL ELSE TEISEK5 END AS TEISEK5, CASE WHEN TRIM(TEISEK6) = '' THEN NULL ELSE TEISEK6 END AS TEISEK6, CASE WHEN TRIM(TEISEK7) = '' THEN NULL ELSE TEISEK7 END AS TEISEK7, CASE WHEN TRIM(TEISEK8) = '' THEN NULL ELSE TEISEK8 END AS TEISEK8, CASE WHEN TRIM(TEISEK9) = '' THEN NULL ELSE TEISEK9 END AS TEISEK9, CASE WHEN TRIM(TEISEK10) = '' THEN NULL ELSE TEISEK10 END AS TEISEK10, SYOKBN1 AS SYOKBN1, SYOKBN2 AS SYOKBN2, SYOKBN3 AS SYOKBN3, SYOKBN4 AS SYOKBN4, SYOKBN5 AS SYOKBN5, SYOKBN6 AS SYOKBN6, SYOKBN7 AS SYOKBN7, SYOKBN8 AS SYOKBN8, SYOKBN9 AS SYOKBN9, SYOKBN10 AS SYOKBN10, HCUSU1 AS HCUSU1, HCUSU2 AS HCUSU2, HCUSU3 AS HCUSU3, HCUSU4 AS HCUSU4, HCUSU5 AS HCUSU5, HCUSU6 AS HCUSU6, HCUSU7 AS HCUSU7, HCUSU8 AS HCUSU8, HCUSU9 AS HCUSU9, HCUSU10 AS HCUSU10, PAGENO AS PAGENO, SOSINFLG AS SOSINFLG, RTRIM('BATCH') AS OPERTO, CURRENT_TIMESTAMP AS TOURKB, CURRENT_TIMESTAMP AS KOSINB FROM INAIN.BFI03) BFI03 WHERE NOT EXISTS (SELECT * FROM INATK.TOKTJ_TEN TEN WHERE TEN.LSTNO = BFI03.LISTNO AND TEN.BMNCD = BFI03.BUNBMC AND TEN.HYOSEQNO = BFI03.SORTNO AND TEN.TENCD = BFI03.MISECD); commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKTJ_TEN;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
