REM [191][BFI03]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


rem INAIN.BFI03テーブルクリア
SET MSG=%DATE% %TIME% TRUNCATE INAIN.BFI03
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIN.BFI03 ;commit;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


rem BFI03_01へ取り込み ======================================================================
SET MSG=%DATE% %TIME% TRUNCATE INAIN.BFI03_01
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIN.BFI03_01 ;commit;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

rem ファイルパスの設定
SET INFILENAME=0191
set filename=DATA\%INFILENAME%
set filename_tmp=%filename:\=\\%

SET MSG=%DATE% %TIME%  →  BFI03_01 LOAD処理
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --local_infile=1 --show-warnings -vv -e "load data local infile '%filename_tmp%' IGNORE into table INAIN.BFI03_01 character set cp932 fields terminated by ',' ESCAPED BY '' lines terminated by '\r\n' (@1) SET DATA = @1; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


rem BFI03へU登録 =========================================================================

SET MSG=%DATE% %TIME%  →  LOAD処理(事前発注＿店舗)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIN.BFI03 SELECT MID(DATA, 1, 6) AS LISTNO, MID(DATA, 7, 3) AS BUNBMC, MID(DATA, 10, 8) AS SORTNO, MID(DATA, 18, 3) AS MISECD, MID(DATA, 21, 3) AS RMISIR, MID(DATA, 24, 3) AS HJMISIR, MID(DATA, 27, 6) AS SOUBAIFG, MID(DATA, 33, 6) AS HONBAIFG, MID(DATA, 39, 6) AS RSOBAIFG, MID(DATA, 45, 6) AS RHONBAIFG, MID(DATA, 51, 8) AS JZNGENKA, MID(DATA, 59, 8) AS TUIGENKA, MID(DATA, 67, 8) AS RGENKA, MID(DATA, 75, 8) AS GENFU, MID(DATA, 83, 6) AS BAIFU, MID(DATA, 89, 8) AS HIDUK1, MID(DATA, 97, 8) AS HIDUK2, MID(DATA, 105, 8) AS HIDUK3, MID(DATA, 113, 8) AS HIDUK4, MID(DATA, 121, 8) AS HIDUK5, MID(DATA, 129, 8) AS HIDUK6, MID(DATA, 137, 8) AS HIDUK7, MID(DATA, 145, 8) AS HIDUK8, MID(DATA, 153, 8) AS HIDUK9, MID(DATA, 161, 8) AS HIDUK10, MID(DATA, 169, 1) AS TEISEK1, MID(DATA, 170, 1) AS TEISEK2, MID(DATA, 171, 1) AS TEISEK3, MID(DATA, 172, 1) AS TEISEK4, MID(DATA, 173, 1) AS TEISEK5, MID(DATA, 174, 1) AS TEISEK6, MID(DATA, 175, 1) AS TEISEK7, MID(DATA, 176, 1) AS TEISEK8, MID(DATA, 177, 1) AS TEISEK9, MID(DATA, 178, 1) AS TEISEK10, MID(DATA, 179, 1) AS SYOKBN1, MID(DATA, 180, 1) AS SYOKBN2, MID(DATA, 181, 1) AS SYOKBN3, MID(DATA, 182, 1) AS SYOKBN4, MID(DATA, 183, 1) AS SYOKBN5, MID(DATA, 184, 1) AS SYOKBN6, MID(DATA, 185, 1) AS SYOKBN7, MID(DATA, 186, 1) AS SYOKBN8, MID(DATA, 187, 1) AS SYOKBN9, MID(DATA, 188, 1) AS SYOKBN10, MID(DATA, 189, 5) AS HCUSU1, MID(DATA, 194, 5) AS HCUSU2, MID(DATA, 199, 5) AS HCUSU3, MID(DATA, 204, 5) AS HCUSU4, MID(DATA, 209, 5) AS HCUSU5, MID(DATA, 214, 5) AS HCUSU6, MID(DATA, 219, 5) AS HCUSU7, MID(DATA, 224, 5) AS HCUSU8, MID(DATA, 229, 5) AS HCUSU9, MID(DATA, 234, 5) AS HCUSU10, MID(DATA, 239, 3) AS PAGENO, MID(DATA, 242, 1) AS SOSINFLG, MID(DATA, 243, 20) AS OPERTO, MID(DATA, 263, 8) AS TOURKB, MID(DATA, 271, 8) AS KOSINB FROM INAIN.BFI03_01;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIN.BFI03;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
