REM [192][TOKTJ_AVGPTANKA]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME%  →  MARGE処理(事前発注＿平均パック単価)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "INSERT INTO INATK.TOKTJ_AVGPTANKA(LSTNO, TENCD, BMNCD, DAICD, AVGPTANKA, OPERATOR, ADDDT, UPDDT) SELECT * FROM (SELECT T1.LISTNO AS LISTNO, T1.MISECD AS MISECD, T1.BUNBMC AS BUNBMC, T1.BUNDIC AS BUNDIC, T1.HEKINP AS HEKINP, RTRIM('BATCH') AS OPERTO, CURRENT_TIMESTAMP AS TOURKB, CURRENT_TIMESTAMP AS KOSINB FROM (SELECT B4.LISTNO, B4.MISECD, B4.BUNBMC, B4.BUNDIC, B4.HEKINP, ROW_NUMBER() OVER (PARTITION BY B4.LISTNO, B4.MISECD, B4.BUNBMC, B4.BUNDIC ORDER BY B4.KOSINB DESC, B4.TOURKB DESC) AS ODRNO FROM INAIN.BFI04 B4) T1 WHERE T1.ODRNO = 1) BFI04 WHERE NOT EXISTS (SELECT * FROM INATK.TOKTJ_AVGPTANKA AVG WHERE AVG.LSTNO = BFI04.LISTNO AND AVG.TENCD = BFI04.MISECD AND AVG.BMNCD = BFI04.BUNBMC AND AVG.DAICD = BFI04.BUNDIC); commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKTJ_AVGPTANKA;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
