REM [193][JH_DATE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIN.BFB00 → INAIF.JH_DATE ロード処理（事前発注対象日付）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "TRUNCATE TABLE INAIF.JH_DATE; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "INSERT IGNORE INTO INAIF.JH_DATE SELECT COPY, SEQ AS SEQ, BMNCD AS BMNCD, TOK, TEI, JIZNUT AS JUKBN, NENMAT AS NENMATKBN, FILLER01, SYORIB AS SYORIDT, YOUBI AS SYORI_YOUBI, TYUKAIS AS TYUSTDT, TYUSYUR AS TYUEDDT, TOKKAIS AS TOKSTDT, TOKSYUR AS TOKEDDT, TDATE01 AS TDATE01, TYOUBI01 AS TYOUBI01, TDATE02 AS TDATE02, TYOUBI02 AS TYOUBI02, TDATE03 AS TDATE03, TYOUBI03 AS TYOUBI03, TDATE04 AS TDATE04, TYOUBI04 AS TYOUBI04, TDATE05 AS TDATE05, TYOUBI05 AS TYOUBI05, TDATE06 AS TDATE06, TYOUBI06 AS TYOUBI06, TDATE07 AS TDATE07, TYOUBI07 AS TYOUBI07, TDATE08 AS TDATE08, TYOUBI08 AS TYOUBI08, TDATE09 AS TDATE09, TYOUBI09 AS TYOUBI09, TDATE10 AS TDATE10, TYOUBI10 AS TYOUBI10, HACKAIS AS HACKAIS, HACSYUR AS HACSYUR, HDATE01 AS HDATE01, HYOUBI01 AS HYOUBI01, HDATE02 AS HDATE02, HYOUBI02 AS HYOUBI02, HDATE03 AS HDATE03, HYOUBI03 AS HYOUBI03, HDATE04 AS HDATE04, HYOUBI04 AS HYOUBI04, HDATE05 AS HDATE05, HYOUBI05 AS HYOUBI05, HDATE06 AS HDATE06, HYOUBI06 AS HYOUBI06, HDATE07 AS HDATE07, HYOUBI07 AS HYOUBI07, HDATE08 AS HDATE08, HYOUBI08 AS HYOUBI08, HDATE09 AS HDATE09, HYOUBI09 AS HYOUBI09, HDATE10 AS HDATE10, HYOUBI10 AS HYOUBI10, HDATE11 AS HDATE11, HYOUBI11 AS HYOUBI11, HDATE12 AS HDATE12, HYOUBI12 AS HYOUBI12, HDATE13 AS HDATE13, HYOUBI13 AS HYOUBI13, HDATE14 AS HDATE14, HYOUBI14 AS HYOUBI14, HDATE15 AS HDATE15, HYOUBI15 AS HYOUBI15, HDATE16 AS HDATE16, HYOUBI16 AS HYOUBI16, LISTNO AS LSTNO, KOTYUKAB AS KOTYUSTDT, KOTYUSYUB AS KOTYUEDDT, SOUSIME AS SNDSIMEDT, KESKAB AS SHWSTDT, KESSYUB AS SHWEDDT, TITLE, NULLIF(JZNKSYHKB,' ') AS JZNKSYHKBN, NULLIF(SAKSEIB,'      ') AS ADDDT, FILLER02 FROM INAIN.BFB00; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.JH_DATE;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
