REM [003][CORESIIRE]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET MSG=%DATE% %TIME% INAAD2.CORESIIRE → INAPRE.CORESIIRE ロード処理（CORE仕入先(前日分)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAPRE.CORESIIRE;INSERT IGNORE INTO INAPRE.CORESIIRE SELECT SIR_KAI_CODE, SIR_CODE, SIR_TORI_CODE, SIR_NAME, SIR_NAME_K, SIR_NAME_S, SIR_YUBIN_NO, SIR_ADR_1, SIR_ADR_2, SIR_ADR_3, SIR_TEL_NO, SIR_FAX_NO, SIR_SAKI_BMN_NAME, SIR_SAKI_SYA_NAME, SIR_JISYA_BMN_CODE, SIR_JISYA_SYA_CODE, SIR_APPSTR_DATE, SIR_APPEND_DATE, UPDT_ID, UPDT_TAN, UPDT_DATE FROM INAAD2.CORESIIRE;commit;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAPRE.CORESIIRE;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
