REM [003][FILE_LOAD]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% TRUNCATE INAIN.ODS03
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIN.ODS03 ;commit;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

rem ファイルパスの設定

SET INFILENAME=0077
set filename=DATA\%INFILENAME%
set filename_tmp=%filename:\=\\%

SET MSG=%DATE% %TIME% %INFILENAME% → INAIN.ODS03 LOAD処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --local_infile=1 --show-warnings -vv -e "TRUNCATE TABLE INAIN.ODS03;load data local infile '%filename_tmp%' IGNORE into table INAIN.ODS03 character set cp932 fields terminated by ',' ESCAPED BY '' lines terminated by '\r\n' (@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53) SET TORICD = NULLIF(@1, ''), SAKUHYO = NULLIF(@2, ''), ZANKBN = NULLIF(@3, ''), TORINM = NULLIF(@4, ''), GINKO = NULLIF(@5, ''), SITEN = NULLIF(@6, ''), SYUMOKU = NULLIF(@7, ''), TENBAN = NULLIF(@8, ''), KOZANO = NULLIF(@9, ''), 30UNDER = NULLIF(@10, ''), 30OVER = NULLIF(@11, ''), MEIGI = NULLIF(@12, ''), SIGKMK = NULLIF(@13, ''), SIGTORI = NULLIF(@14, ''), PAYKBN = NULLIF(@15, ''), PAYSGHT = NULLIF(@16, ''), ADRESS1 = NULLIF(@17, ''), ADRESS2 = NULLIF(@18, ''), ZIPNO = NULLIF(@19, ''), TELNO = NULLIF(@20, ''), CO_ID = NULLIF(@21, ''), KANA = NULLIF(@22, ''), PAYGAKU = NULLIF(@23, ''), REGDATE = NULLIF(@24, ''), BEGDATE = NULLIF(@25, ''), SUPDATE = NULLIF(@26, ''), ABTDATE = NULLIF(@27, ''), JYOFLG1 = NULLIF(@28, ''), JYOFLG2 = NULLIF(@29, ''), HENKODATE = NULLIF(@30, ''), JYOFLG3 = NULLIF(@31, ''), TESURYOKBN = NULLIF(@32, ''), DOTAKBN = NULLIF(@33, ''), KYODO_CD = NULLIF(@34, ''), MISE_CD = NULLIF(@35, ''), KYODO_NM = NULLIF(@36, ''), MISE_NM = NULLIF(@37, ''), DAITORI = NULLIF(@38, ''), WAKAGI = NULLIF(@39, ''), TORINM_K = NULLIF(@40, ''), ADRESS1_K = NULLIF(@41, ''), ADRESS2_K = NULLIF(@42, ''), ONFAXKB = NULLIF(@43, ''), PAYSYUKB = NULLIF(@44, ''), PMAILKB = NULLIF(@45, ''), FAXNO = NULLIF(@46, ''), PBEGDATE = NULLIF(@47, ''), SONLDATE = NULLIF(@48, ''), MAIL = NULLIF(@49, ''), HAN_KBN = NULLIF(@50, ''), MEMO1 = NULLIF(@51, ''), MEMO2 = NULLIF(@52, ''), YOBI = NULL; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIN.ODS03 → INAAD.ODS03 LOAD処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM 抽出対象は固定（取引先判別区分=0,1,2,3,4,5）
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAAD.ODS03;INSERT IGNORE INTO INAAD.ODS03 SELECT * FROM INAIN.ODS03 WHERE HAN_KBN IN ('0', '1', '2', '3', '4', '5');commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% TRUNCATE INAIN.CORESIIRE
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIN.CORESIIRE ;commit;">>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



rem ファイルパスの設定
SET INFILENAME=0078
set filename=DATA\%INFILENAME%
set filename_tmp=%filename:\=\\%

SET MSG=%DATE% %TIME% %INFILENAME% → INAIN.CORESIIRE LOAD処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --local_infile=1 --show-warnings -vv -e "load data local infile '%filename_tmp%' IGNORE into table INAIN.CORESIIRE character set cp932 fields terminated by ',' ESCAPED BY '' lines terminated by '\r\n' (@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21) SET SIR_KAI_CODE = NULLIF(@1, ''), SIR_CODE = NULLIF(@2, ''), SIR_TORI_CODE = NULLIF(@3, ''), SIR_NAME = NULLIF(@4, ''), SIR_NAME_K = NULLIF(@5, ''), SIR_NAME_S = NULLIF(@6, ''), SIR_YUBIN_NO = NULLIF(@7, ''), SIR_ADR_1 = NULLIF(@8, ''), SIR_ADR_2 = NULLIF(@9, ''), SIR_ADR_3 = NULLIF(@10, ''), SIR_TEL_NO = NULLIF(@11, ''), SIR_FAX_NO = NULLIF(@12, ''), SIR_SAKI_BMN_NAME = NULLIF(@13, ''), SIR_SAKI_SYA_NAME = NULLIF(@14, ''), SIR_JISYA_BMN_CODE = NULLIF(@15, ''), SIR_JISYA_SYA_CODE = NULLIF(@16, ''), SIR_APPSTR_DATE = NULLIF(@17, ''), SIR_APPEND_DATE = NULLIF(@18, ''), UPDT_ID = NULLIF(@19, ''), UPDT_TAN = NULLIF(@20, ''), UPDT_DATE = NULL; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

SET MSG=%DATE% %TIME% INAIN.CORESIIRE → INAAD.CORESIIRE LOAD処理
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
REM 取引先マスタCSVデータの抽出対象に一致した仕入先のみ抽出
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAAD.CORESIIRE; INSERT IGNORE INTO INAAD.CORESIIRE SELECT T1.SIR_KAI_CODE, T1.SIR_CODE, T1.SIR_TORI_CODE, T1.SIR_NAME, T1.SIR_NAME_K, T1.SIR_NAME_S, T1.SIR_YUBIN_NO, T1.SIR_ADR_1, T1.SIR_ADR_2, T1.SIR_ADR_3, T1.SIR_TEL_NO, T1.SIR_FAX_NO, T1.SIR_SAKI_BMN_NAME, T1.SIR_SAKI_SYA_NAME, T1.SIR_JISYA_BMN_CODE, T1.SIR_JISYA_SYA_CODE, T1.SIR_APPSTR_DATE, T1.SIR_APPEND_DATE, T1.UPDT_ID, T1.UPDT_TAN, T1.UPDT_DATE FROM INAIN.CORESIIRE T1 INNER JOIN INAAD.ODS03 T2 ON T1.SIR_CODE = T2.TORICD;commit;" >>%OUTFILE% 2>&1

IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
