REM [000][JH_TOK_ERR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

REM 情報クリア
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.JH_TOK_ERR;COMMIT;" >>%OUTFILE% 2>&1

SET MSG=%DATE% %TIME% INAIF.JH_TOK_ERR ロード処理（特売エラーファイル）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM 20180823 ERRKBN=13を除外
REM 20180829 INAIF.AN_NOUNYU_BFRの条件変更（ANB.NNDT <> 0 AND ANB.HSUU IS NOT NULL AND ANB.TSEIKBN IS NOT NULL）
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIF.JH_TOK_ERR WITH JTE AS (SELECT COUNT(*) AS SEQ FROM INAIF.JH_TOK_ERR JTE), JH_TEN_SYUSEI AS (SELECT BMNCD, TENCD, SHNCD, NNDT, BINKBN, HTSU, 0 AS ERRKBN, 0 AS ADDDT FROM (SELECT BMNCD, TENCD, SHNCD, NNDT, BINKBN, HTSU, ROW_NUMBER() OVER (PARTITION BY BMNCD, TENCD, SHNCD, NNDT, BINKBN ORDER BY HTSU DESC) AS RNO FROM (SELECT ADDSHN.BMNCD, ADDSHN.TENCD, ADDSHN.SHNCD, ADDSHN.BINKBN, CASE WHEN NUMS.SEQ = 1 THEN ADDSHN.JTDT_01 WHEN NUMS.SEQ = 2 THEN ADDSHN.JTDT_02 WHEN NUMS.SEQ = 3 THEN ADDSHN.JTDT_03 WHEN NUMS.SEQ = 4 THEN ADDSHN.JTDT_04 WHEN NUMS.SEQ = 5 THEN ADDSHN.JTDT_05 WHEN NUMS.SEQ = 6 THEN ADDSHN.JTDT_06 WHEN NUMS.SEQ = 7 THEN ADDSHN.JTDT_07 WHEN NUMS.SEQ = 8 THEN ADDSHN.JTDT_08 WHEN NUMS.SEQ = 9 THEN ADDSHN.JTDT_09 WHEN NUMS.SEQ = 10 THEN ADDSHN.JTDT_10 END AS NNDT, CASE WHEN NUMS.SEQ = 1 THEN ADDSHN.HTSU_01 WHEN NUMS.SEQ = 2 THEN ADDSHN.HTSU_02 WHEN NUMS.SEQ = 3 THEN ADDSHN.HTSU_03 WHEN NUMS.SEQ = 4 THEN ADDSHN.HTSU_04 WHEN NUMS.SEQ = 5 THEN ADDSHN.HTSU_05 WHEN NUMS.SEQ = 6 THEN ADDSHN.HTSU_06 WHEN NUMS.SEQ = 7 THEN ADDSHN.HTSU_07 WHEN NUMS.SEQ = 8 THEN ADDSHN.HTSU_08 WHEN NUMS.SEQ = 9 THEN ADDSHN.HTSU_09 WHEN NUMS.SEQ = 10 THEN ADDSHN.HTSU_10 END AS HTSU FROM INAWK.JH_RTN_ADDSHN ADDSHN LEFT OUTER JOIN INAPARM.MSTNUMS NUMS ON NUMS.SEQ BETWEEN 1 AND 10 UNION ALL SELECT TEN.BMNCD, TEN.TENCD, TEN.SHNCD, TEN.BINKBN, CASE WHEN NUMS.SEQ = 1 THEN TEN.JTDT_01 WHEN NUMS.SEQ = 2 THEN TEN.JTDT_02 WHEN NUMS.SEQ = 3 THEN TEN.JTDT_03 WHEN NUMS.SEQ = 4 THEN TEN.JTDT_04 WHEN NUMS.SEQ = 5 THEN TEN.JTDT_05 WHEN NUMS.SEQ = 6 THEN TEN.JTDT_06 WHEN NUMS.SEQ = 7 THEN TEN.JTDT_07 WHEN NUMS.SEQ = 8 THEN TEN.JTDT_08 WHEN NUMS.SEQ = 9 THEN TEN.JTDT_09 WHEN NUMS.SEQ = 10 THEN TEN.JTDT_10 END AS NNDT, CASE WHEN NUMS.SEQ = 1 THEN TEN.HTSU_01 WHEN NUMS.SEQ = 2 THEN TEN.HTSU_02 WHEN NUMS.SEQ = 3 THEN TEN.HTSU_03 WHEN NUMS.SEQ = 4 THEN TEN.HTSU_04 WHEN NUMS.SEQ = 5 THEN TEN.HTSU_05 WHEN NUMS.SEQ = 6 THEN TEN.HTSU_06 WHEN NUMS.SEQ = 7 THEN TEN.HTSU_07 WHEN NUMS.SEQ = 8 THEN TEN.HTSU_08 WHEN NUMS.SEQ = 9 THEN TEN.HTSU_09 WHEN NUMS.SEQ = 10 THEN TEN.HTSU_10 END AS HTSU FROM INAWK.JH_RTN_TEN TEN LEFT OUTER JOIN INAPARM.MSTNUMS NUMS ON NUMS.SEQ BETWEEN 1 AND 10 WHERE TRIM(TEN.OPERATOR) <> 'BATCH') AS T1 WHERE HTSU <> 99999) WK WHERE RNO = 1), ANN AS (SELECT ANN.MOYSCD, ANN.MOYSKBN, ANN.MOYSSTDT, ANN.MOYSRBAN, ANN.BMNCD, ANN.KANRINO, ANN.KANRIENO, ANN.TENCD, ANN.HSUU, ANN.TSEIKBN, ANN.SHNCD, ANN.BINKBN, ANN.NNDT, ANN.TSHUFLG, ANN.JHTSUINDT, CASE WHEN ANN.MOYSKBN = 4 THEN 1 WHEN ANN.MOYSKBN = 3 THEN 2 WHEN ANN.MOYSKBN = 1 AND ANN.MOYSRBAN >= 50 THEN 3 WHEN ANN.MOYSKBN = 1 AND ANN.MOYSRBAN <= 49 THEN 4 WHEN ANN.MOYSKBN = 2 THEN 5 WHEN ANN.MOYSKBN = 0 THEN 6 END YUSENKBN FROM INAIF.AN_NOUNYU_NEQ ANN INNER JOIN INAWK.JH_HSUU_KEY_NEQ JHKN ON ANN.MOYSCD = JHKN.MOYSCD AND ANN.MOYSKBN = JHKN.MOYSKBN AND ANN.MOYSSTDT = JHKN.MOYSSTDT AND ANN.MOYSRBAN = JHKN.MOYSRBAN AND ANN.BMNCD = JHKN.BMNCD AND ANN.KANRINO = JHKN.KANRINO AND ANN.KANRIENO = JHKN.KANRIENO AND ANN.TENCD = JHKN.TENCD WHERE ANN.NNDT <> 0 OR NOT (ANN.HSUU IS NULL AND ANN.TSEIKBN IS NULL)), ANB AS (SELECT ANB.MOYSCD, ANB.MOYSKBN, ANB.MOYSSTDT, ANB.MOYSRBAN, ANB.BMNCD, ANB.KANRINO, ANB.KANRIENO, ANB.TENCD, CASE WHEN ANA.MOYSCD IS NULL THEN ANB.HSUU ELSE ANA.HSUU END AS HSUU, ANB.TSEIKBN, ANB.SHNCD, ANB.BINKBN, ANB.NNDT, ANB.TSHUFLG, ANB.JHTSUINDT, CASE WHEN ANB.MOYSKBN = 4 THEN 1 WHEN ANB.MOYSKBN = 3 THEN 2 WHEN ANB.MOYSKBN = 1 AND ANB.MOYSRBAN >= 50 THEN 3 WHEN ANB.MOYSKBN = 1 AND ANB.MOYSRBAN <= 49 THEN 4 WHEN ANB.MOYSKBN = 2 THEN 5 WHEN ANB.MOYSKBN = 0 THEN 6 END YUSENKBN FROM INAIF.AN_NOUNYU_BFR ANB INNER JOIN INAWK.JH_HSUU_KEY_BFR JHKB ON ANB.MOYSCD = JHKB.MOYSCD AND ANB.MOYSKBN = JHKB.MOYSKBN AND ANB.MOYSSTDT = JHKB.MOYSSTDT AND ANB.MOYSRBAN = JHKB.MOYSRBAN AND ANB.BMNCD = JHKB.BMNCD AND ANB.KANRINO = JHKB.KANRINO AND ANB.KANRIENO = JHKB.KANRIENO AND ANB.TENCD = JHKB.TENCD LEFT OUTER JOIN (SELECT * FROM INAIF.AN_NOUNYU_AFT A WHERE A.TSEIKBN IS NOT NULL) ANA ON ANB.MOYSCD = ANA.MOYSCD AND ANB.MOYSKBN = ANA.MOYSKBN AND ANB.MOYSSTDT = ANA.MOYSSTDT AND ANB.MOYSRBAN = ANA.MOYSRBAN AND ANB.BMNCD = ANA.BMNCD AND ANB.KANRINO = ANA.KANRINO AND ANB.KANRIENO = ANA.KANRIENO AND ANB.TENCD = ANA.TENCD AND ANB.NNDT = ANA.NNDT WHERE ANB.NNDT <> 0 AND ANB.HSUU IS NOT NULL AND ANB.TSEIKBN IS NOT NULL) SELECT ROW_NUMBER() OVER (ORDER BY CASE WHEN AN.SHNCD IS NULL THEN JTS.BMNCD ELSE AN.BMNCD END, CASE WHEN AN.SHNCD IS NULL THEN JTS.SHNCD ELSE AN.SHNCD END, CASE WHEN AN.SHNCD IS NULL THEN JTS.BINKBN ELSE AN.BINKBN END, CASE WHEN AN.SHNCD IS NULL THEN JTS.TENCD ELSE AN.TENCD END, CASE WHEN AN.SHNCD IS NULL THEN JTS.NNDT ELSE AN.NNDT END) + JTE.SEQ AS SEQ, CASE WHEN AN.SHNCD IS NULL THEN JTS.BMNCD ELSE AN.BMNCD END AS BMNCD, CASE WHEN AN.SHNCD IS NULL THEN JTS.SHNCD ELSE AN.SHNCD END AS SHNCD, CASE WHEN AN.SHNCD IS NULL THEN JTS.BINKBN ELSE AN.BINKBN END AS BINKBN, CASE WHEN AN.SHNCD IS NULL THEN JTS.TENCD ELSE AN.TENCD END AS TENCD, CASE WHEN AN.SHNCD IS NULL THEN JTS.NNDT ELSE AN.NNDT END AS NNDT, JTS.HTSU, 0 AS MAESURYO, 0 AS TOKKBN, 0 AS INPUTKBN, 1 AS TTKBN, 0 AS JISEIKBN, 0 AS YOUBIKBN, 0 AS SHNKBN, CASE WHEN AN.SHNCD IS NULL THEN 11 WHEN AN.TSEIKBN = 0 AND AN.TSHUFLG <> 1 AND AN.JHTSUINDT <> 0 THEN 13 ELSE 12 END AS ERRKBN, COALESCE(AN.MOYSKBN, 0) AS MOYSKBN, COALESCE(AN.MOYSSTDT, 0) AS MOYSSTDT, COALESCE(AN.MOYSRBAN, 0) AS MOYSRBAN, COALESCE(AN.KANRINO, 0) AS KANRINO, 0 AS SYUTENCD, '' AS SHNAN, 0 AS GENKAAM, 0 AS BAIKAAM, 0 AS IRISU, 0 AS DAICD, 0 AS CHUCD, CURRENT_TIMESTAMP AS ADDDT FROM JH_TEN_SYUSEI JTS LEFT OUTER JOIN (SELECT AN2.MOYSCD, AN2.MOYSKBN, AN2.MOYSSTDT, AN2.MOYSRBAN, AN2.BMNCD, AN2.KANRINO, AN2.KANRIENO, AN2.TENCD, AN2.HSUU, AN2.TSEIKBN, AN2.SHNCD, AN2.BINKBN, AN2.NNDT, AN2.TSHUFLG, AN2.JHTSUINDT FROM (SELECT AN1.MOYSCD, AN1.MOYSKBN, AN1.MOYSSTDT, AN1.MOYSRBAN, AN1.BMNCD, AN1.KANRINO, AN1.KANRIENO, AN1.TENCD, AN1.HSUU, AN1.TSEIKBN, AN1.SHNCD, AN1.BINKBN, AN1.NNDT, AN1.TSHUFLG, AN1.JHTSUINDT, ROW_NUMBER() OVER (PARTITION BY AN1.BMNCD, AN1.NNDT, AN1.TENCD, AN1.BINKBN, AN1.SHNCD ORDER BY AN1.YUSENKBN, AN1.MOYSCD, AN1.KANRINO, AN1.KANRIENO) AS ODRNO FROM (SELECT MOYSCD, MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, TENCD, HSUU, TSEIKBN, SHNCD, BINKBN, NNDT, TSHUFLG, JHTSUINDT, YUSENKBN FROM ANN UNION ALL SELECT MOYSCD, MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, TENCD, HSUU, TSEIKBN, SHNCD, BINKBN, NNDT, TSHUFLG, JHTSUINDT, YUSENKBN FROM ANB) AN1) AN2 WHERE ODRNO = 1) AN ON AN.SHNCD = JTS.SHNCD AND AN.BINKBN = JTS.BINKBN AND AN.TENCD = JTS.TENCD AND AN.NNDT = JTS.NNDT AND AN.BMNCD = JTS.BMNCD LEFT OUTER JOIN JTE ON 1 = 1 WHERE AN.SHNCD IS NULL OR (AN.SHNCD IS NOT NULL AND (AN.TSEIKBN IN (3, 4) OR AN.TSEIKBN IS NULL));COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.JH_TOK_ERR;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
