REM [000][JH_WEEKHTDT_DIFF]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.JH_WEEKHTDT_DIFF ロード処理（週間発注処理日反映差分）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.JH_WEEKHTDT_DIFF;INSERT IGNORE INTO INAWK.JH_WEEKHTDT_DIFF WITH H780 AS (SELECT MOYSCD, MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, TENCD, NNDT, KYOSEIFLG, WEEKHTDT, NNWEEKHTDT, TSHUFLG, HSUU, UPDKBN FROM INAIF.AN_NOUNYU_NEQ AN USE INDEX (IX6) WHERE UPDKBN <> 1 AND NNSTDT <> 0 AND EXISTS (SELECT 1 FROM INAIF.JH_SUMI JS USE INDEX (PRIMARY) WHERE AN.MOYSCD = JS.MOYSCD AND AN.BMNCD = JS.BMNCD AND AN.KANRINO = JS.KANRINO)), H960 AS (SELECT MOYSCD, MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, TENCD, NNDT, KYOSEIFLG, WEEKHTDT, CASE WHEN NOT (NNWEEKHTDT <> 0 AND TSHUFLG = 0) THEN SBD.DT_INT ELSE NNWEEKHTDT END AS NNWEEKHTDT, HSUU, UPDKBN FROM H780 AN LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE EXISTS (SELECT 1 FROM INAIF.JH_SUMI JS USE INDEX (PRIMARY) WHERE AN.MOYSCD = JS.MOYSCD AND AN.BMNCD = JS.BMNCD AND AN.KANRINO = JS.KANRINO AND AN.TENCD = JS.TENCD AND AN.NNDT = JS.NNDT)) SELECT AN.MOYSCD, AN.MOYSKBN, AN.MOYSSTDT, AN.MOYSRBAN, AN.BMNCD, AN.KANRINO, AN.KANRIENO, AN.TENCD, AN.NNDT, AN.WEEKHTDT, COALESCE(H1.NNWEEKHTDT, AN.NNWEEKHTDT) AS NNWEEKHTDT FROM H780 AN LEFT OUTER JOIN H960 H1 ON AN.MOYSCD = H1.MOYSCD AND AN.BMNCD = H1.BMNCD AND AN.KANRINO = H1.KANRINO AND AN.KANRIENO = H1.KANRIENO AND AN.TENCD = H1.TENCD AND AN.NNDT = H1.NNDT;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.JH_WEEKHTDT_DIFF;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
