REM [000][TOKSP_NNDT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK.TOKSP_NNDT マージ処理（全店特売(アンケート無)_納入日）週間発注日TANDEM
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INATK.TOKSP_NNDT NNDT, (SELECT DISTINCT JWD.MOYSKBN, JWD.MOYSSTDT, JWD.MOYSRBAN, JWD.BMNCD, JWD.KANRINO, JWD.NNDT, SBD.DT_INT AS WEEKHTDT FROM INAWK.JH_WEEKHTDT_DIFF JWD LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1) JWD SET NNDT.WEEKHTDT = JWD.WEEKHTDT WHERE NNDT.MOYSKBN = JWD.MOYSKBN AND NNDT.MOYSSTDT = JWD.MOYSSTDT AND NNDT.MOYSRBAN = JWD.MOYSRBAN AND NNDT.BMNCD = JWD.BMNCD AND NNDT.KANRINO = JWD.KANRINO AND NNDT.NNDT = JWD.NNDT;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKSP_NNDT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
