REM [000][AN_HANBAI_AFT_WK1]
@ECHO OFF


REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.AN_HANBAI_AFT_WK1 ロード処理（全特アンケート有 販売データ(反映後)WK1）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"TRUNCATE TABLE INAWK.AN_HANBAI_AFT_WK1 ; commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAWK.AN_HANBAI_AFT_WK1 SELECT ANWK.MOYSKBN, ANWK.MOYSSTDT, ANWK.MOYSRBAN, ANWK.BMNCD, ANWK.KANRINO, ANWK.KANRIENO, ANWK.TENCD, ANWK.MOYSCD, ANWK.BMNO, ANWK.MOHBSTDT, ANWK.MOHBEDDT, ANWK.HBOKUREFLG, ANWK.JLSTCREDT, ANWK.QADEVSTDT, ANWK.QADEVENDFLG, ANWK.TENGPCD, ANWK.KYOSEIFLG, ANWK.SHNCD, ANWK.ADDSHUKBN, ANWK.HBSTDT, ANWK.HBEDDT, ANWK.REIDMYKBN, ANWK.HBSLIDEFLG, ANWK.GENKAAM, ANWK.GENKARITU, ANWK.A_BAIKAAM, ANWK.B_BAIKAAM, ANWK.C_BAIKAAM, ANWK.A_GENKAAM_1KG, ANWK.B_GENKAAM_1KG, ANWK.C_GENKAAM_1KG, ANWK.A_WRITUKBN, ANWK.B_WRITUKBN, ANWK.C_WRITUKBN, ANWK.TKANPLUKBN, ANWK.KO_A_BAIKAAN, ANWK.BD1_A_BAIKAAN, ANWK.BD2_A_BAIKAAN, ANWK.KO_B_BAIKAAN, ANWK.BD1_B_BAIKAAN, ANWK.BD2_B_BAIKAAN, ANWK.KO_C_BAIKAAN, ANWK.BD1_C_BAIKAAN, ANWK.BD2_C_BAIKAAN, ANWK.PLUSNDFLG, ANWK.TEIKEIKBN, ANWK.SOURCEKBN1, ANWK.SRCCD1, ANWK.SOURCEKBN2, ANWK.SRCCD2, ANWK.URICD, ANWK.QASYUKBN, ANWK.LTENSAIFLG, ANWK.HANKAISIFLG, ANWK.TENSAIFLG, ANWK.URIASELKBN, ANWK.ITMSELKBN, ANWK.CBAIKA, ANWK.SBAIBL1, ANWK.SBAIBL2, ANWK.CBAIKAKG, ANWK.DATAKBN, ANWK.GTSIMECHGKBN, ANWK.GTSIMEOKFLG, ANWK.SENDFLG, ANWK.UPDKBN, ANDT.HBSTDT_SL, ANDT.HBEDDT_SL FROM INAIF.AN_HANBAI_AFT ANWK INNER JOIN (SELECT MOYSCD, MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO, MIN(DATE_FORMAT(HBDT, '%%Y%%m%%d')) AS HBSTDT_SL, MAX(DATE_FORMAT(HBDT, '%%Y%%m%%d')) AS HBEDDT_SL FROM INAIF.AN_HANBAI_DT GROUP BY MOYSCD, MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, KANRIENO) ANDT ON ANWK.MOYSKBN = ANDT.MOYSKBN AND ANWK.MOYSSTDT = ANDT.MOYSSTDT AND ANWK.MOYSRBAN = ANDT.MOYSRBAN AND ANWK.KANRINO = ANDT.KANRINO AND ANWK.BMNCD = ANDT.BMNCD AND ANWK.KANRIENO = ANDT.KANRIENO WHERE EXISTS (SELECT * FROM INAWK.ANWK12_HAN_A WK12 WHERE ANWK.MOYSKBN = WK12.MOYSKBN AND ANWK.MOYSSTDT = WK12.MOYSSTDT AND ANWK.MOYSRBAN = WK12.MOYSRBAN AND ANWK.KANRINO = WK12.KANRINO AND ANWK.BMNCD = WK12.BMNCD AND ANWK.KANRIENO <= WK12.KANRIENO); commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.AN_HANBAI_AFT_WK1;commit;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
