REM [000][TOKSP_SHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK.TOKSP_SHN マージ処理（全店特売(アンケート無)_商品）事前発注数量取込処理TANDEMM
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INATK.TOKSP_SHN SHN, (SELECT MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO, MAX(JHTSUINDT) AS JHTSUINDT FROM (SELECT A.* FROM INAIF.AN_NOUNYU_NEQ A INNER JOIN INAWK.JH_HSUU_KEY_NEQ J ON A.MOYSKBN = J.MOYSKBN AND A.MOYSSTDT = J.MOYSSTDT AND A.MOYSRBAN = J.MOYSRBAN AND A.BMNCD = J.BMNCD AND A.KANRINO = J.KANRINO AND A.KANRIENO = J.KANRIENO AND A.TENCD = J.TENCD) H840 GROUP BY MOYSKBN, MOYSSTDT, MOYSRBAN, BMNCD, KANRINO) UPD SET SHN.JHTSUINDT = UPD.JHTSUINDT WHERE SHN.MOYSKBN = UPD.MOYSKBN AND SHN.MOYSSTDT = UPD.MOYSSTDT AND SHN.MOYSRBAN = UPD.MOYSRBAN AND SHN.BMNCD = UPD.BMNCD AND SHN.KANRINO = UPD.KANRINO;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKSP_SHN;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
