REM [000][JH_SUMI]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.JH_SUMI ロード処理（事前発注リスト出力日反映差分）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "TRUNCATE TABLE INAIF.JH_SUMI;INSERT IGNORE INTO INAIF.JH_SUMI SELECT DISTINCT LPAD(MOYOK, 1, 0) || LPAD(MOYOKA, 6, 0) || LPAD(MOYORE, 3, 0) AS MOYSCD, CAST(MOYOK AS SIGNED) AS MOYSKBN, CAST(MOYOKA AS SIGNED) AS MOYSSTDT, CAST(MOYORE AS SIGNED) AS MOYSRBAN, CAST(BUNBMC AS SIGNED) AS BMNCD, CAST(KANBAN AS SIGNED) AS KANRINO, CAST(MISECD AS SIGNED) AS TENCD, CAST(NNYNOB AS SIGNED) AS NNDT, CAST(SHOHNC AS CHAR (14)) AS SHNCD, CAST(BINK AS SIGNED) AS BINKKBN, CAST(SAKSEIB AS SIGNED) AS ADDDT FROM INAIN.BFB11;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e  "ANALYZE TABLE INAIF.JH_SUMI;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
