REM [000][AN_NOUNYU_BFR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_BFR マージ処理（全特アンケート有 納入データ(反映前)）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

REM P460の発注数はQA288の回答より 1 → NULL ※ただしそもそも後続のP480で未使用
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAIF.AN_NOUNYU_BFR ANB, (SELECT TC27.MOYSCD AS MOYSCD, TC27.MOYSKBN AS MOYSKBN, TC27.MOYSSTDT AS MOYSSTDT, TC27.MOYSRBAN AS MOYSRBAN, TC27.BMNCD AS BMNCD, TC27.KANRINO AS KANRINO, TC27.KANRIENO AS KANRIENO, TC27.TENCD AS TENCD, TC27.NNDT AS NNDT, P460.HSUU AS HSUU FROM INAIF.AN_NOUNYU_BFR TC27 INNER JOIN INAWK.JH_HSUU_KEY_BFR JHK ON TC27.MOYSCD = JHK.MOYSCD AND TC27.BMNCD = JHK.BMNCD AND TC27.KANRINO = JHK.KANRINO AND TC27.KANRIENO = JHK.KANRIENO AND TC27.TENCD = JHK.TENCD INNER JOIN (SELECT TC14.MOYSCD, TC14.MOYSKBN, TC14.MOYSSTDT, TC14.MOYSRBAN, TC14.BMNCD, TC14.KANRINO, TC14.KANRIENO, TC14.TENCD, TC14.NNDT, TC14.HSUU, TC14.HTASU, TC14.PTNNO, TC14.TSEIKBN, TC14.ZJSKFLG, TC14.NNWEEKHTDT, NULL AS TENHENKO FROM INAIF.AN_NOUNYU_AFT TC14) P460 ON TC27.MOYSKBN = P460.MOYSKBN AND TC27.MOYSSTDT = P460.MOYSSTDT AND TC27.MOYSRBAN = P460.MOYSRBAN AND TC27.BMNCD = P460.BMNCD AND TC27.KANRINO = P460.KANRINO AND TC27.KANRIENO = P460.KANRIENO AND TC27.TENCD = P460.TENCD AND TC27.NNDT = P460.NNDT WHERE TC27.NNDT <> 0 AND TC27.TSEIKBN IS NOT NULL) P480 SET ANB.HSUU = P480.HSUU WHERE ANB.MOYSKBN = P480.MOYSKBN AND ANB.MOYSSTDT = P480.MOYSSTDT AND ANB.MOYSRBAN = P480.MOYSRBAN AND ANB.BMNCD = P480.BMNCD AND ANB.KANRINO = P480.KANRINO AND ANB.KANRIENO = P480.KANRIENO AND ANB.TENCD = P480.TENCD AND ANB.NNDT = P480.NNDT;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_BFR;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
