REM [000][A11T508]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log
rem SET CSVFILE=%~DP0../cmd/INATK2.HATTR_CSV

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.A11T508 ロード処理（定量変更データ）火曜のみ登録、その他削除
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%


"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.A11T508;INSERT IGNORE INTO INAWK.A11T508 SELECT DISTINCT HTC.TENCD AS TENCD, RPAD(COALESCE(REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (HTC.SHNCD, '０', '0'), '１', '1'), '２', '2'), '３', '3'), '４', '4'), '５', '5'), '６', '6'), '７', '7'), '８', '8'), '９', '9'),'　',' '), ' '), 8, ' ') AS SHOHINCD, '                    ' AS SHOHINNMKN, 1 AS BINKBN, CAST(LPAD(TRIM(HTC.JSEIKBN), 1, '0') AS SIGNED) AS ZSEI_KBN, HTC.SURYO_MON AS HENSUU1, HTC.SURYO_TUE AS HENSUU2, HTC.SURYO_WED AS HENSUU3, HTC.SURYO_THU AS HENSUU4, HTC.SURYO_FRI AS HENSUU5, HTC.SURYO_SAT AS HENSUU6, HTC.SURYO_SUN AS HENSUU7, CAST(NULL AS SIGNED) AS MAESUU1, CAST(NULL AS SIGNED) AS MAESUU2, CAST(NULL AS SIGNED) AS MAESUU3, CAST(NULL AS SIGNED) AS MAESUU4, CAST(NULL AS SIGNED) AS MAESUU5, CAST(NULL AS SIGNED) AS MAESUU6, CAST(NULL AS SIGNED) AS MAESUU7, ' ' AS ERRFLG1, ' ' AS ERRFLG2, ' ' AS ERRFLG3, ' ' AS ERRFLG4, ' ' AS ERRFLG5, ' ' AS ERRFLG6, ' ' AS ERRFLG7, CAST(NULL AS SIGNED) AS DATA_KBN, HTC.SHUNO AS WEEK_NO, '                     ' AS FILLER FROM INATK2.HATTR_CSV HTC INNER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 AND SBD.YOBI = 2;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.A11T508;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


REM 削除前ＢＫ用
SET MSG=%DATE% %TIME%  →  EXPORT処理(定量変更データ)ＢＫ用
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
SET CSVFILE=%~DP0..\cmd\INATK2.HATTR_CSV
ECHO %CSVFILE% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT TENCD || ',' || RPAD(CAST(SHNCD AS CHAR),14,' ') || ',' || JSEIKBN || ',' || SHUNO || ',' || SURYO_MON || ',' || SURYO_TUE || ',' || SURYO_WED || ',' || SURYO_THU || ',' || SURYO_FRI || ',' || SURYO_SAT || ',' || SURYO_SUN || ',' || UPDKBN || ',' || SENDFLG || ',' || OPERATOR || ',' || ADDDT || ',' || UPDDT || ',' || SENDDT || ' ' FROM INATK2.HATTR_CSV ORDER BY TENCD,SHNCD,JSEIKBN,SHUNO" >%CSVFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR


SET MSG=%DATE% %TIME% INATK2.HATTR_CSV  DELETE処理（INATK2.定量変更データ削除 正規）火曜のみ削除
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK2.HATTR_CSV T1 WHERE T1.JSEIKBN = 0 AND (SELECT SBD.YOBI FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.ACTIVEFLG = 1) = 2;COMMIT" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME% INATK2.HATTR_CSV  DELETE処理（INATK2.定量変更データ削除 次週）火曜のみ削除
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK2.HATTR_CSV T1 WHERE T1.JSEIKBN = 1 AND T1.SENDDT < (SELECT SBD.DT - INTERVAL 6 day FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.ACTIVEFLG = 1) AND (SELECT SBD.YOBI FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.ACTIVEFLG = 1) = 2;COMMIT"  >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


SET MSG=%DATE% %TIME% INATK.HATTR_CSV  DELETE処理（INATK.定量変更データ削除 正規）火曜のみ削除
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATTR_CSV T1 WHERE T1.JSEIKBN = 0 AND (SELECT SBD.YOBI FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.ACTIVEFLG = 1) = 2;COMMIT"  >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME% INATK.HATTR_CSV  DELETE処理（INATK.定量変更データ削除 次週）火曜のみ削除
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK.HATTR_CSV T1 WHERE T1.JSEIKBN = 1 AND T1.SENDDT < (SELECT SBD.DT - INTERVAL 6 day FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.ACTIVEFLG = 1) AND (SELECT SBD.YOBI FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.ACTIVEFLG = 1) = 2;COMMIT"  >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR




REM 【重要】平行稼働用の暫定対応(INATK2.HATTR_CSVが無いため平行稼働期間はCRIPS.A11T508を参照)
REM "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.A11T508;INSERT INTO INAWK.A11T508 SELECT TENCD, SHOHINCD, SHOHINNMKN, BINKBN, ZSEI_KBN, HENSUU1, HENSUU2, HENSUU3, HENSUU4, HENSUU5, HENSUU6, HENSUU7, MAESUU1, MAESUU2, MAESUU3, MAESUU4, MAESUU5, MAESUU6, MAESUU7, ERRFLG1, ERRFLG2, ERRFLG3, ERRFLG4, ERRFLG5, ERRFLG6, ERRFLG7, DATA_KBN, WEEK_NO, FILLER FROM CRIPS.A11T508;COMMIT;" >>%OUTFILE% 2>&1
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR
REM "%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.A11T508;" >>%OUTFILE% 2>&1
REM IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
