REM [000][HATTR_CSV]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.HATTR_CSV DALETE処理（店別数量_CSV）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "DELETE FROM INATK2.HATTR_CSV T1 WHERE EXISTS (SELECT 1 FROM CRIPS.A11T508 T2 WHERE T1.TENCD = T2.TENCD AND T1.SHNCD = T2.SHOHINCD AND T1.JSEIKBN = T2.ZSEI_KBN AND T1.SHUNO = COALESCE(T2.WEEK_NO, 0));COMMIT" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


SET MSG=%DATE% %TIME% INATK2.HATTR_CSV LOAD処理（店別数量_CSV）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INATK2.HATTR_CSV SELECT DISTINCT T1.TENCD, T1.SHOHINCD AS SHNCD, CAST(T1.ZSEI_KBN AS CHAR (1)) AS JSEIKBN, COALESCE(T1.WEEK_NO, 0) AS SHUNO, T1.HENSUU1 AS SURYO_MON, T1.HENSUU2 AS SURYO_TUE, T1.HENSUU3 AS SURYO_WED, T1.HENSUU4 AS SURYO_THU, T1.HENSUU5 AS SURYO_FRI, T1.HENSUU6 AS SURYO_SAT, T1.HENSUU7 AS SURYO_SUN, 0 AS UPDKBN, 0 AS SENDFLG, 'batch' AS OPERATOR, SBD.DT AS ADDDT, SBD.DT AS UPDDT, SBD.DT AS SENDDT FROM CRIPS.A11T508 T1 LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK2.HATTR_CSV;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR



:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
