REM [000][TOKSP_SHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK.TOKSP_SHN マージ処理（全店特売(アンケート無)_商品）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INATK.TOKSP_SHN SHN, (SELECT JLD.MOYSCD, JLD.MOYSKBN, JLD.MOYSSTDT, JLD.MOYSRBAN, JLD.BMNCD, JLD.KANRINO, JLD.KANRIENO, MAX(JLD.JLSTCREDT) AS JLSTCREDT FROM INAWK.JH_LIST_DIFF JLD GROUP BY JLD.MOYSCD, JLD.MOYSKBN, JLD.MOYSSTDT, JLD.MOYSRBAN, JLD.BMNCD, JLD.KANRINO, JLD.KANRIENO) JH SET SHN.JLSTCREDT = JH.JLSTCREDT WHERE JH.MOYSKBN = SHN.MOYSKBN AND JH.MOYSSTDT = SHN.MOYSSTDT AND JH.MOYSRBAN = SHN.MOYSRBAN AND JH.BMNCD = SHN.BMNCD AND JH.KANRINO = SHN.KANRINO AND JH.KANRIENO = SHN.KANRIENO;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKSP_SHN SHN;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
