REM [000][AN_NOUNYU_NEQ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_NEQ マージ処理（全特アンケート無 納入データ）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%


REM 週間発注処理日を設定し、WKに追加
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.AN_NOUNYU_NEQ;INSERT IGNORE INTO INAWK.AN_NOUNYU_NEQ WITH H990WK AS (SELECT AN.MOYSCD, AN.MOYSKBN, AN.MOYSSTDT, AN.MOYSRBAN, AN.BMNCD, AN.KANRINO, AN.KANRIENO, AN.TENCD, AN.KYOSEIFLG, MAX(COALESCE(H1.NNWEEKHTDT, AN.NNWEEKHTDT)) AS WEEKHTDT FROM INAIF.AN_NOUNYU_NEQ AN LEFT OUTER JOIN INAWK.JH_WEEKHTDT_DIFF H1 ON AN.MOYSCD = H1.MOYSCD AND AN.BMNCD = H1.BMNCD AND AN.KANRINO = H1.KANRINO AND AN.KANRIENO = H1.KANRIENO AND AN.TENCD = H1.TENCD AND AN.NNDT = H1.NNDT WHERE AN.NNSTDT <> 0 GROUP BY AN.MOYSCD, AN.MOYSKBN, AN.MOYSSTDT, AN.MOYSRBAN, AN.BMNCD, AN.KANRINO, AN.KANRIENO, AN.TENCD, AN.KYOSEIFLG) SELECT AN.MOYSCD, AN.MOYSKBN, AN.MOYSSTDT, AN.MOYSRBAN, AN.BMNCD, AN.KANRINO, AN.KANRIENO, AN.TENCD, AN.NNDT, AN.SHUNO, AN.TSHUFLG, AN.MYOSNNSTDT, AN.MYOSNNEDDT, AN.NENMATKBN, AN.JLSTCREFLG, AN.JLSTCREDT, AN.JHTSUINDT, COALESCE(H2.WEEKHTDT, AN.WEEKHTDT) AS WEEKHTDT, AN.QADEVSTDT, AN.QADEVEDFLG, AN.TENGPCD, AN.KYOSEIFLG, AN.SHNCD, AN.REIDMYKBN, AN.NNSTDT, AN.NNEDDT, AN.JUFLG, AN.JUHTDT, AN.BINKBN, AN.NNSLIDE, AN.CUTTENFLG, AN.SHUDENFLG, AN.HSUU, AN.HTASU, AN.PTNNO, AN.TSEIKBN, AN.ZJSKFLG, COALESCE(H1.NNWEEKHTDT, AN.NNWEEKHTDT) AS NNWEEKHTDT, AN.QASYUKBN, AN.LDSYFLG, AN.MBSYFLG, AN.ITMSELKBN, AN.GTSIMECHGKBN, AN.GTSIMEOKFLG, AN.SENDFLG, AN.UPDKBN FROM INAIF.AN_NOUNYU_NEQ AN LEFT OUTER JOIN INAWK.JH_WEEKHTDT_DIFF H1 ON AN.MOYSCD = H1.MOYSCD AND AN.BMNCD = H1.BMNCD AND AN.KANRINO = H1.KANRINO AND AN.KANRIENO = H1.KANRIENO AND AN.TENCD = H1.TENCD AND AN.NNDT = H1.NNDT LEFT OUTER JOIN H990WK H2 ON AN.MOYSCD = H2.MOYSCD AND AN.BMNCD = H2.BMNCD AND AN.KANRINO = H2.KANRINO AND AN.KANRIENO = H2.KANRIENO AND AN.TENCD = H2.TENCD AND COALESCE(AN.KYOSEIFLG, - 1) = COALESCE(H2.KYOSEIFLG, - 1);COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


REM 設定しおわった中間データを戻す
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_NOUNYU_NEQ;INSERT IGNORE INTO INAIF.AN_NOUNYU_NEQ SELECT * FROM INAWK.AN_NOUNYU_NEQ;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_NEQ;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
