REM [000][AN_NOUNYU_NEQ]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_NOUNYU_NEQ マージ処理（全特アンケート無 納入データ）- 事前発注数取込日
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INAIF.AN_NOUNYU_NEQ ANN, (SELECT ANN.MOYSCD, ANN.MOYSKBN, ANN.MOYSSTDT, ANN.MOYSRBAN, ANN.BMNCD, ANN.KANRINO, ANN.KANRIENO, ANN.TENCD, MAX(JSD.SNDSIMEDT) AS SNDSIMEDT FROM INAIF.AN_NOUNYU_NEQ ANN INNER JOIN INAWK.JH_HSUU_KEY_NEQ JHK ON ANN.MOYSCD = JHK.MOYSCD AND ANN.BMNCD = JHK.BMNCD AND ANN.KANRINO = JHK.KANRINO AND ANN.KANRIENO = JHK.KANRIENO AND ANN.TENCD = JHK.TENCD INNER JOIN INAIF.JH_SHIME_DATE JSD ON ANN.BMNCD = JSD.BMNCD AND ANN.NENMATKBN = JSD.NENMATKBN AND (((ANN.NENMATKBN = 1 OR ANN.TSHUFLG = 1) AND (ANN.NNSTDT BETWEEN JSD.TOKSTDT AND JSD.TOKEDDT OR ANN.NNEDDT BETWEEN JSD.TOKSTDT AND JSD.TOKEDDT)) OR (JSD.TYUSTDT <= ANN.NNSTDT AND ANN.NNSTDT <= JSD.TYUEDDT)) GROUP BY ANN.MOYSCD, ANN.MOYSKBN, ANN.MOYSSTDT, ANN.MOYSRBAN, ANN.BMNCD, ANN.KANRINO, ANN.KANRIENO, ANN.TENCD) ANN_UPD SET JHTSUINDT = ANN_UPD.SNDSIMEDT WHERE ANN.MOYSCD = ANN_UPD.MOYSCD AND ANN.MOYSKBN = ANN_UPD.MOYSKBN AND ANN.MOYSSTDT = ANN_UPD.MOYSSTDT AND ANN.MOYSRBAN = ANN_UPD.MOYSRBAN AND ANN.BMNCD = ANN_UPD.BMNCD AND ANN.KANRINO = ANN_UPD.KANRINO AND ANN.KANRIENO = ANN_UPD.KANRIENO AND ANN.TENCD = ANN_UPD.TENCD;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_NOUNYU_NEQ;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
