REM [000][TOKSP_SHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK.TOKTG_NNDT マージ処理（全店特売(アンケート有)_納入日）事前発注数量取込処理TANDEM
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INATK.TOKTG_NNDT T, INAWK.JH_TOKTG_NNDT JT SET T.TENHTSU_ARR = JT.TENHTSU_ARR, T.HTASU = JT.HTASU, T.PTNNO = JT.PTNNO, T.TSEIKBN = JT.TSEIKBN, T.TPSU = JT.TPSU, T.TENKAISU = JT.TENKAISU, T.ZJSKFLG = JT.ZJSKFLG, T.WEEKHTDT = JT.WEEKHTDT, T.SENDFLG = 1, T.OPERATOR = JT.OPERATOR, T.ADDDT = JT.ADDDT, T.UPDDT = JT.UPDDT, T.BAT_CTLFLG01 = JT.BAT_CTLFLG01 WHERE T.MOYSKBN = JT.MOYSKBN AND T.MOYSSTDT = JT.MOYSSTDT AND T.MOYSRBAN = JT.MOYSRBAN AND T.BMNCD = JT.BMNCD AND T.KANRINO = JT.KANRINO AND T.KANRIENO = JT.KANRIENO AND T.NNDT = JT.NNDT;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK.TOKTG_NNDT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
