REM [000][TOKSP_SHN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.TOKSP_NNDT マージ処理（全店特売(アンケート無)_納入日）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INATK2.TOKSP_NNDT TS, (SELECT * FROM INAWK.JH_TOKSP_NNDT) JTS SET TS.TENHTSU_ARR = JTS.TENHTSU_ARR, TS.HTASU = JTS.HTASU, TS.PTNNO = JTS.PTNNO, TS.TSEIKBN = JTS.TSEIKBN, TS.TPSU = JTS.TPSU, TS.TENKAISU = JTS.TENKAISU, TS.ZJSKFLG = JTS.ZJSKFLG, TS.WEEKHTDT = JTS.WEEKHTDT, TS.SENDFLG = JTS.SENDFLG, TS.OPERATOR = JTS.OPERATOR, TS.ADDDT = JTS.ADDDT, TS.UPDDT = JTS.UPDDT, TS.BAT_CTLFLG01 = JTS.BAT_CTLFLG01 WHERE TS.MOYSKBN = JTS.MOYSKBN AND TS.MOYSSTDT = JTS.MOYSSTDT AND TS.MOYSRBAN = JTS.MOYSRBAN AND TS.BMNCD = JTS.BMNCD AND TS.KANRINO = JTS.KANRINO AND TS.KANRIENO = JTS.KANRIENO AND TS.NNDT = JTS.NNDT;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INATK2.TOKSP_NNDT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
