REM [000][AN_ZW_NOUNYU_AFT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.AN_ZW_NOUNYU_AFT ロード処理（全特アンケート有 納入データ 全品割引(反映後)）:反映対象データ
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAIF.AN_ZW_NOUNYU_AFT;INSERT IGNORE INTO INAIF.AN_ZW_NOUNYU_AFT SELECT WK10.MOYSCD, WK10.MOYSKBN, WK10.MOYSSTDT, WK10.MOYSRBAN, WK10.BMNCD, WK10.KANRINO, WK10.KANRIENO, WK10.TENCD, WK10.NNDT, WK10.SHUNO, WK10.TSHUFLG, WK10.MYOSNNSTDT, WK10.MYOSNNEDDT, WK10.NENMATKBN, WK10.JLSTCREFLG, WK10.JLSTCREDT, WK10.JHTSUINDT, WK10.WEEKHTDT, WK10.QADEVSTDT, WK10.QADEVEDFLG, WK10.TENGPCD, WK10.KYOSEIFLG, WK10.SHNCD, WK10.REIDMYKBN, WK10.NNSTDT, WK10.NNEDDT, WK10.JUFLG, WK10.JUHTDT, WK10.BINKBN, WK10.NNSLIDE, WK10.CUTTENFLG, WK10.SHUDENFLG, CASE WHEN WK10.CUTTENFLG = 1 THEN CASE WHEN COALESCE(WK10.TENGPCD, 0) = 0 OR WK10.QASYUKBN = 5 OR WK10.LDSYFLG = 2 OR WK10.MBSYFLG IN (0, 3) OR WK10.ITMSELKBN = 2 THEN NULL ELSE WK10.HSUU END ELSE WK10.HSUU END AS HSUU, WK10.HTASU, WK10.PTNNO, WK10.TSEIKBN, WK10.ZJSKFLG, WK10.NNWEEKHTDT, WK10.QASYUKBN, WK10.LDSYFLG, WK10.MBSYFLG, WK10.ITMSELKBN, WK10.GTSIMECHGKBN, WK10.GTSIMEOKFLG, WK10.SENDFLG, WK10.UPDKBN FROM (SELECT WK10.MOYSCD, WK10.MOYSKBN, WK10.MOYSSTDT, WK10.MOYSRBAN, WK10.SHUNO, WK10.TSHUFLG, WK10.MYOSNNSTDT, WK10.MYOSNNEDDT, WK10.NENMATKBN, WK10.JLSTCREFLG, WK10.JLSTCREDT, WK10.JHTSUINDT, WK10.WEEKHTDT, WK10.QADEVSTDT, WK10.QADEVEDFLG, WK10.TENGPCD, WK10.KYOSEIFLG, WK10.KANRINO, WK10.KANRIENO, WK10.BMNCD, WK10.SHNCD, WK10.REIDMYKBN, WK10.NNSTDT, WK10.NNEDDT, WK10.JUFLG, WK10.JUHTDT, WK10.BINKBN, WK10.NNSLIDE, WK10.CUTTENFLG, WK10.SHUDENFLG, WK10.TENCD, WK10.NNDT, WK10.HSUU, WK10.HTASU, WK10.PTNNO, WK10.TSEIKBN, WK10.ZJSKFLG, WK10.NNWEEKHTDT, WK10.QASYUKBN, CASE WHEN QAGP.LDSYFLG IS NOT NULL THEN QAGP.LDSYFLG ELSE WK10.LDSYFLG END AS LDSYFLG, CASE WHEN QATEN.LDTENKBN = 0 THEN CASE WHEN QATEN.MBSYFLG = 1 THEN 1 WHEN QATEN.MBSYFLG = 2 THEN 0 END WHEN QATEN.LDTENKBN = 1 THEN CASE WHEN QATEN.MBSYFLG = 1 THEN 2 WHEN QATEN.MBSYFLG = 2 THEN 3 END END AS MBSYFLG, CASE WHEN WK10.QASYUKBN = 4 THEN CASE WHEN QASHN.ITMSELKBN = 0 THEN 2 ELSE 1 END ELSE WK10.ITMSELKBN END AS ITMSELKBN, WK10.GTSIMECHGKBN, WK10.GTSIMEOKFLG, WK10.SENDFLG, WK10.UPDKBN FROM INAIF.AN_ZW_NOUNYU_BFR WK10 LEFT OUTER JOIN INATK2.TOKTG_QATEN QATEN ON WK10.MOYSKBN = QATEN.MOYSKBN AND WK10.MOYSSTDT = QATEN.MOYSSTDT AND WK10.MOYSRBAN = QATEN.MOYSRBAN AND WK10.TENGPCD = QATEN.TENGPCD AND WK10.TENCD = QATEN.TENCD LEFT OUTER JOIN INATK2.TOKTG_QAGP QAGP ON WK10.MOYSKBN = QAGP.MOYSKBN AND WK10.MOYSSTDT = QAGP.MOYSSTDT AND WK10.MOYSRBAN = QAGP.MOYSRBAN AND WK10.TENGPCD = QAGP.TENGPCD LEFT OUTER JOIN INATK2.TOKTG_QASHN QASHN ON WK10.MOYSKBN = QASHN.MOYSKBN AND WK10.MOYSSTDT = QASHN.MOYSSTDT AND WK10.MOYSRBAN = QASHN.MOYSRBAN AND WK10.TENGPCD = QASHN.TENGPCD AND WK10.BMNCD = QASHN.BMNCD AND WK10.KANRINO = QASHN.KANRINO LEFT OUTER JOIN INAPARM.SYSBATCHDT_TK SBD ON SBD.ACTIVEFLG = 1 WHERE WK10.JLSTCREFLG = 0 AND WK10.JLSTCREDT = 0 AND WK10.QADEVSTDT <= SBD.DT_INT) WK10;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.AN_ZW_NOUNYU_AFT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
