REM [000][JH_TOK_ERR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAIF.JH_TOK_ERR ロード処理（特売エラーファイル）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INAIF.JH_TOK_ERR WITH JTE AS (SELECT COUNT(*) AS SEQ FROM INAIF.JH_TOK_ERR JTE) SELECT ROW_NUMBER() OVER (ORDER BY ANB.BMNCD, ANB.SHNCD, ANB.BINKBN, ANB.TENCD, ANB.NNDT) + JTE.SEQ AS SEQ, ANB.BMNCD, ANB.SHNCD, ANB.BINKBN, ANB.TENCD, ANB.NNDT, 0 AS HTSU, ANB.HSUU, 0 AS TOKKBN, 0 AS INPUTKBN, 1 AS TTKBN, 0 AS JISEIKBN, 0 AS YOUBIKBN, 0 AS SHNKBN, 11 AS ERRKBN, ANB.MOYSKBN, ANB.MOYSSTDT, ANB.MOYSRBAN, ANB.KANRINO, 0 AS SYUTENCD, '' AS SHNAN, 0 AS GENKAAM, 0 AS BAIKAAM, 0 AS IRISU, 0 AS DAICD, 0 AS CHUCD, CURRENT_TIMESTAMP AS ADDDT FROM INAIF.AN_NOUNYU_BFR ANB LEFT OUTER JOIN JTE ON 1 = 1 WHERE ANB.MOYSKBN = 9 AND ANB.TSHUFLG = 0 AND ANB.QADEVSTDT <> 0 AND NOT EXISTS (SELECT 1 FROM INAIF.JH_SUMI JS WHERE ANB.MOYSCD = JS.MOYSCD AND ANB.BMNCD = JS.BMNCD AND ANB.KANRINO = JS.KANRINO AND ANB.TENCD = JS.TENCD AND ANB.NNDT = JS.NNDT);COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAIF.JH_TOK_ERR;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
