REM [000][HATJTR_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.HATJTR_TEN インサート処理（次週定量_店別数量）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "INSERT IGNORE INTO INATK2.HATJTR_TEN SELECT HST.SHNCD, HST.BINKBN, HST.TENCD, T1.WEEK_NO AS SHUNO, CASE WHEN T1.HENSUU1 IS NOT NULL THEN T1.HENSUU1 ELSE HST.SURYO_MON END AS SURYO_MON, CASE WHEN T1.HENSUU2 IS NOT NULL THEN T1.HENSUU2 ELSE HST.SURYO_TUE END AS SURYO_TUE, CASE WHEN T1.HENSUU3 IS NOT NULL THEN T1.HENSUU3 ELSE HST.SURYO_WED END AS SURYO_WED, CASE WHEN T1.HENSUU4 IS NOT NULL THEN T1.HENSUU4 ELSE HST.SURYO_THU END AS SURYO_THU, CASE WHEN T1.HENSUU5 IS NOT NULL THEN T1.HENSUU5 ELSE HST.SURYO_FRI END AS SURYO_FRI, CASE WHEN T1.HENSUU6 IS NOT NULL THEN T1.HENSUU6 ELSE HST.SURYO_SAT END AS SURYO_SAT, CASE WHEN T1.HENSUU7 IS NOT NULL THEN T1.HENSUU7 ELSE HST.SURYO_SUN END AS SURYO_SUN, 0 AS SENDFLG, '' AS OPERATOR, SBDTK.DTTIME AS ADDDT, CAST(NULL AS DATETIME) AS UPDDT FROM INAWK.A11T508 T1 INNER JOIN (SELECT SBD.DT + INTERVAL ADDDT DAY AS DT_PRE, CAST(DATE_FORMAT(SBD.DT + INTERVAL ADDDT DAY, '%%Y%%m%%d') AS SIGNED) AS DT_INT_PRE, SBD.DTTIME + INTERVAL ADDDT DAY AS DTTIME_PRE, SBD.DTTIME AS DTTIME FROM INAPARM.SYSBATCHDT_TK SBD LEFT OUTER JOIN (VALUES ROW ('DAILY', - 5)) TEMP(SMODE, ADDDT) ON SBD.SMODE = TEMP.SMODE WHERE SBD.SMODE = 'DAILY') SBDTK ON T1.ZSEI_KBN = 1 INNER JOIN (SELECT * FROM INATK2.HATSTR_TEN WHERE UPDKBN <> 1) HST ON HST.SHNCD = T1.SHOHINCD AND HST.BINKBN = T1.BINKBN AND HST.TENCD = T1.TENCD LEFT OUTER JOIN (SELECT * FROM INATK2.HATSTR_SHN WHERE UPDKBN <> 1) SHN ON T1.SHOHINCD = SHN.SHNCD AND T1.BINKBN = SHN.BINKBN WHERE (HST.UPDDT < SBDTK.DTTIME_PRE OR HST.OPERATOR = 'CSV') AND NOT EXISTS (SELECT 1 FROM INATK2.HATJTR_TEN HJT WHERE HJT.SHNCD = T1.SHOHINCD AND HJT.BINKBN = T1.BINKBN AND HJT.TENCD = T1.TENCD AND HJT.SHUNO = T1.WEEK_NO) AND CASE WHEN T1.HENSUU1 IS NOT NULL THEN 1 WHEN T1.HENSUU2 IS NOT NULL THEN 1 WHEN T1.HENSUU3 IS NOT NULL THEN 1 WHEN T1.HENSUU4 IS NOT NULL THEN 1 WHEN T1.HENSUU5 IS NOT NULL THEN 1 WHEN T1.HENSUU6 IS NOT NULL THEN 1 WHEN T1.HENSUU7 IS NOT NULL THEN 1 ELSE 0 END = 1;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


REM 追加データ確認用
SET MSG=%DATE% %TIME%  →  EXPORT処理(追加データ確認用 次週定量_店別数量 (UPDDT IS NULL))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
SET FILENAME=HATJTR_TEN_
SET TIMESTAMP=%date:~0,4%%date:~5,2%%date:~8,2%
SET CSVFILE1=%~DP0../cmd/%FILENAME%%TIMESTAMP%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT RPAD(TRIM(COALESCE(SHNCD, '')), 14, ' ') || ',' || COALESCE(BINKBN, '') || ',' || COALESCE(TENCD, '') || ',' || COALESCE(SHUNO, '') || ',' || COALESCE(SURYO_MON, '') || ',' || COALESCE(SURYO_TUE, '') || ',' || COALESCE(SURYO_WED, '') || ',' || COALESCE(SURYO_THU, '') || ',' || COALESCE(SURYO_FRI, '') || ',' || COALESCE(SURYO_SAT, '') || ',' || COALESCE(SURYO_SUN, '') || ',' || COALESCE(SENDFLG, '') || ',' || COALESCE(OPERATOR, '') || ',' || COALESCE(ADDDT, '') || ',' || COALESCE(UPDDT, '') FROM INATK2.HATJTR_TEN T1 WHERE T1.UPDDT IS NULL ORDER BY T1.SHNCD, T1.BINKBN, T1.TENCD, T1.SHUNO" >%CSVFILE1% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM 追加データ確認用
SET MSG=%DATE% %TIME%  →  EXPORT処理(追加データ確認用 正規定量_商品)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
SET CSVFILE2=%~DP0../cmd/HATSTR_SHN
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT RPAD(TRIM(COALESCE(SHNCD, '')), 14, ' ') || ',' || COALESCE(BINKBN, '') || ',' || COALESCE(TSKBN_MON, '') || ',' || COALESCE(TSKBN_TUE, '') || ',' || COALESCE(TSKBN_WED, '') || ',' || COALESCE(TSKBN_THU, '') || ',' || COALESCE(TSKBN_FRI, '') || ',' || COALESCE(TSKBN_SAT, '') || ',' || COALESCE(TSKBN_SUN, '') || ',' || COALESCE(UPDKBN, '') || ',' || COALESCE(SENDFLG, '') || ',' || COALESCE(OPERATOR, '') || ',' || COALESCE(ADDDT, '') || ',' || COALESCE(UPDDT, '') || ',' || COALESCE(bat_delcnt, '') FROM INATK2.HATSTR_SHN T1 ORDER BY T1.SHNCD, T1.BINKBN" >%CSVFILE2% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM 追加データ確認用
SET MSG=%DATE% %TIME%  →  EXPORT処理(追加データ確認用 正規定量_店別数量)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
SET CSVFILE3=%~DP0../cmd/HATSTR_TEN
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT RPAD(TRIM(COALESCE(SHNCD, '')), 14, ' ') || ',' || COALESCE(BINKBN, '') || ',' || COALESCE(TENCD, '') || ',' || COALESCE(SURYO_MON, '') || ',' || COALESCE(SURYO_TUE, '') || ',' || COALESCE(SURYO_WED, '') || ',' || COALESCE(SURYO_THU, '') || ',' || COALESCE(SURYO_FRI, '') || ',' || COALESCE(SURYO_SAT, '') || ',' || COALESCE(SURYO_SUN, '') || ',' || COALESCE(UPDKBN, '') || ',' || COALESCE(SENDFLG, '') || ',' || COALESCE(OPERATOR, '') || ',' || COALESCE(ADDDT, '') || ',' || COALESCE(UPDDT, '') FROM INATK2.HATSTR_TEN T1 ORDER BY T1.SHNCD, T1.BINKBN, T1.TENCD" >%CSVFILE3% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM 追加データ確認用
SET MSG=%DATE% %TIME%  →  EXPORT処理(追加データ確認用 処理日付)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
SET CSVFILE4=%~DP0../cmd/SBD
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT CAST(SBD.DT + INTERVAL ADDDT DAY AS SIGNED) || ',' || CAST(DATE_FORMAT(SBD.DT + INTERVAL ADDDT DAY, '%%Y%%m%%d') AS SIGNED) || ',' || (SBD.DTTIME + INTERVAL ADDDT DAY) || ',' || SBD.DTTIME FROM INAPARM.SYSBATCHDT_TK SBD LEFT OUTER JOIN (VALUES ROW ('DAILY', - 5)) TEMP(SMODE, ADDDT) ON SBD.SMODE = TEMP.SMODE WHERE SBD.SMODE = 'DAILY'" >%CSVFILE4% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR




:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
