REM [000][HATSTR_TEN]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INATK2.HATSTR_TEN マージ処理（正規定量_店別数量）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "UPDATE INATK2.HATSTR_TEN HST, (SELECT T1.SHOHINCD AS SHNCD, T1.BINKBN, T1.TENCD, CASE WHEN T1.HENSUU1 IS NOT NULL THEN T1.HENSUU1 ELSE NULL END AS SURYO_MON, CASE WHEN T1.HENSUU2 IS NOT NULL THEN T1.HENSUU2 ELSE NULL END AS SURYO_TUE, CASE WHEN T1.HENSUU3 IS NOT NULL THEN T1.HENSUU3 ELSE NULL END AS SURYO_WED, CASE WHEN T1.HENSUU4 IS NOT NULL THEN T1.HENSUU4 ELSE NULL END AS SURYO_THU, CASE WHEN T1.HENSUU5 IS NOT NULL THEN T1.HENSUU5 ELSE NULL END AS SURYO_FRI, CASE WHEN T1.HENSUU6 IS NOT NULL THEN T1.HENSUU6 ELSE NULL END AS SURYO_SAT, CASE WHEN T1.HENSUU7 IS NOT NULL THEN T1.HENSUU7 ELSE NULL END AS SURYO_SUN, SBD.DTTIME AS UPDDT FROM INAWK.A11T508 T1 INNER JOIN (SELECT SBD.DT + INTERVAL ADDDT DAY AS DT_PRE, CAST(DATE_FORMAT(SBD.DT + INTERVAL ADDDT DAY, '%%Y%%m%%d') AS SIGNED) AS DT_INT_PRE, SBD.DTTIME + INTERVAL ADDDT DAY AS DTTIME_PRE, SBD.DTTIME AS DTTIME FROM INAPARM.SYSBATCHDT_TK SBD LEFT OUTER JOIN (VALUES ROW ('DAILY', - 5)) TEMP(SMODE, ADDDT) ON SBD.SMODE = TEMP.SMODE WHERE SBD.SMODE = 'DAILY') SBD ON T1.ZSEI_KBN = 0 LEFT OUTER JOIN (SELECT * FROM INATK2.HATSTR_SHN WHERE UPDKBN <> 1) SHN ON T1.SHOHINCD = SHN.SHNCD AND T1.BINKBN = SHN.BINKBN INNER JOIN (SELECT * FROM INATK2.HATSTR_TEN WHERE UPDKBN <> 1) HST2 ON HST2.SHNCD = T1.SHOHINCD AND HST2.BINKBN = T1.BINKBN AND HST2.TENCD = T1.TENCD WHERE (HST2.UPDDT < SBD.DTTIME_PRE) AND CASE WHEN T1.HENSUU1 IS NOT NULL THEN 1 WHEN T1.HENSUU2 IS NOT NULL THEN 1 WHEN T1.HENSUU3 IS NOT NULL THEN 1 WHEN T1.HENSUU4 IS NOT NULL THEN 1 WHEN T1.HENSUU5 IS NOT NULL THEN 1 WHEN T1.HENSUU6 IS NOT NULL THEN 1 WHEN T1.HENSUU7 IS NOT NULL THEN 1 ELSE 0 END = 1) HST_UPD SET HST.SURYO_MON = COALESCE(HST_UPD.SURYO_MON, HST.SURYO_MON), HST.SURYO_TUE = COALESCE(HST_UPD.SURYO_TUE, HST.SURYO_TUE), HST.SURYO_WED = COALESCE(HST_UPD.SURYO_WED, HST.SURYO_WED), HST.SURYO_THU = COALESCE(HST_UPD.SURYO_THU, HST.SURYO_THU), HST.SURYO_FRI = COALESCE(HST_UPD.SURYO_FRI, HST.SURYO_FRI), HST.SURYO_SAT = COALESCE(HST_UPD.SURYO_SAT, HST.SURYO_SAT), HST.SURYO_SUN = COALESCE(HST_UPD.SURYO_SUN, HST.SURYO_SUN), HST.OPERATOR = 'CSV', HST.UPDDT = HST_UPD.UPDDT WHERE HST.SHNCD = HST_UPD.SHNCD AND HST.BINKBN = HST_UPD.BINKBN AND HST.TENCD = HST_UPD.TENCD;COMMIT;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
