REM [091][ANWK02]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.ANWK02 → INAWK.ANWK02 ロード処理（全特アンケート無販売データワーク）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.ANWK02;INSERT IGNORE INTO INAWK.ANWK02 SELECT SPSHN.MOYSKBN, SPSHN.MOYSSTDT, SPSHN.MOYSRBAN, 0 AS BMNO, SPSHN.MOHBSTDT, SPSHN.MOHBEDDT, 0 AS HBOKUREFLG, SPSHN.JLSTCREDT, 0 AS QADEVSTDT, CASE WHEN 1 = 1 THEN NULL ELSE 1 END AS QADEVENDFLG, CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.RANKNO_ADD_A WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.RANKNO_ADD_B WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.RANKNO_ADD_C ELSE 0 END AS TENGPCD, 0 AS KYOSEIFLG, SPSHN.KANRINO, SPSHN.KANRIENO, SPSHN.BMNCD, SPSHN.SHNCD, SPSHN.ADDSHUKBN, SPSHN.HBSTDT, SPSHN.HBEDDT, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, 0 AS HANBAISLIDE, CASE WHEN SPSHN.ADDSHUKBN = 2 THEN SPSHN.GENKAAM_MAE WHEN SPSHN.ADDSHUKBN = 4 THEN CASE WHEN SPSHN.TKANPLUKBN = 1 THEN SPSHN.GENKAAM_MAE WHEN SPSHN.TKANPLUKBN = 2 THEN SPSHN.GENKAAM_1KG END WHEN SPSHN.ADDSHUKBN = 5 THEN CASE WHEN SPSHN.TKANPLUKBN = 1 THEN SPSHN.GENKAAM_MAE WHEN SPSHN.TKANPLUKBN = 2 THEN SPSHN.GENKAAM_1KG END END AS GENKAAM, 0 AS GENKARITU, SPSHN.A_BAIKAAM, SPSHN.B_BAIKAAM, SPSHN.C_BAIKAAM, SPSHN.A_GENKAAM_1KG, SPSHN.B_GENKAAM_1KG, SPSHN.C_GENKAAM_1KG, SPSHN.A_WRITUKBN, SPSHN.B_WRITUKBN, SPSHN.C_WRITUKBN, SPSHN.TKANPLUKBN, SPSHN.KO_A_BAIKAAN, SPSHN.BD1_A_BAIKAAN, SPSHN.BD2_A_BAIKAAN, SPSHN.KO_B_BAIKAAN, SPSHN.BD1_B_BAIKAAN, SPSHN.BD2_B_BAIKAAN, SPSHN.KO_C_BAIKAAN, SPSHN.BD1_C_BAIKAAN, SPSHN.BD2_C_BAIKAAN, SPSHN.PLUSNDFLG, 0 AS TEIKEIKBN, 0 AS SOURCEKBN1, '' AS SRCCD1, 0 AS SOURCEKBN2, '' AS SRCCD2, 0 AS URICD, SPSHN.TENCD, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT1, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT2, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT3, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT4, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT5, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT6, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT7, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT8, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT9, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS HBDT10, 0 AS QASYUKBN, 1 AS LTENSAIFLG, CASE WHEN 1 = 1 THEN NULL ELSE 1 END AS HANKAISIFLG, 1 AS TENSAIFLG, CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN 1 WHEN SPSHN.TENATSUKKBN = 'B' THEN 2 WHEN SPSHN.TENATSUKKBN = 'C' THEN 3 END AS BAIKASELKBN, 1 AS SHOHINSEL, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.A_WRITUKBN WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.B_WRITUKBN WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.C_WRITUKBN END ELSE CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN CASE WHEN SPSHN.KO_A_BAIKAAN = 0 THEN SPSHN.A_BAIKAAM ELSE SPSHN.KO_A_BAIKAAN END WHEN SPSHN.TENATSUKKBN = 'B' THEN CASE WHEN SPSHN.KO_B_BAIKAAN = 0 THEN SPSHN.B_BAIKAAM ELSE SPSHN.KO_B_BAIKAAN END WHEN SPSHN.TENATSUKKBN = 'C' THEN CASE WHEN SPSHN.KO_C_BAIKAAN = 0 THEN SPSHN.C_BAIKAAM ELSE SPSHN.KO_C_BAIKAAN END END END AS CBAIKA, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 0 ELSE CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.BD1_A_BAIKAAN WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.BD1_B_BAIKAAN WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.BD1_C_BAIKAAN END END AS SBAIBL1, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 0 ELSE CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.BD2_A_BAIKAAN WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.BD2_B_BAIKAAN WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.BD2_C_BAIKAAN END END AS SBAIBL2, CASE WHEN SPSHN.ADDSHUKBN = 1 THEN 0 ELSE CASE WHEN SPSHN.TKANPLUKBN = 2 THEN CASE WHEN SPSHN.TENATSUKKBN = 'A' THEN SPSHN.A_GENKAAM_1KG WHEN SPSHN.TENATSUKKBN = 'B' THEN SPSHN.B_GENKAAM_1KG WHEN SPSHN.TENATSUKKBN = 'C' THEN SPSHN.C_GENKAAM_1KG END END END AS CBAIKAKG, 2 AS DATAKBN, 0 AS GTSIMECHGKBN, 0 AS GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM (SELECT SPSHN.*, TMC.HBSTDT AS MOHBSTDT, TMC.HBEDDT AS MOHBEDDT, NUMS.TENCD, SUBSTR(SPHB.TENATSUK_ARR, NUMS.TENCD, 1) AS TENATSUKKBN FROM INATK2.TOKSP_SHN SPSHN INNER JOIN INATK2.TOKSP_HB SPHB ON SPSHN.MOYSKBN = SPHB.MOYSKBN AND SPSHN.MOYSSTDT = SPHB.MOYSSTDT AND SPSHN.MOYSRBAN = SPHB.MOYSRBAN AND SPSHN.BMNCD = SPHB.BMNCD AND SPSHN.KANRINO = SPHB.KANRINO AND SPSHN.KANRIENO = SPHB.KANRIENO INNER JOIN (SELECT * FROM INATK2.TOKMOYCD TMC WHERE TMC.UPDKBN <> 1) TMC ON SPSHN.MOYSKBN = TMC.MOYSKBN AND SPSHN.MOYSSTDT = TMC.MOYSSTDT AND SPSHN.MOYSRBAN = TMC.MOYSRBAN LEFT OUTER JOIN (SELECT NUMS.SEQ AS TENCD FROM INAPARM.MSTNUMS NUMS WHERE NUMS.SEQ BETWEEN 1 AND 400) NUMS ON 1 = 1 WHERE SPSHN.UPDKBN <> 1) SPSHN;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.ANWK02;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
