REM [091][ANWK01_BF]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.ANWK01_BF → INAWK.ANWK01_BF ロード処理（全特アンケート有販売データ(反映前)ワーク）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.ANWK01_BF;INSERT IGNORE INTO INAWK.ANWK01_BF WITH TGTG AS (SELECT * FROM INATK2.TOKTG_TENGP TGTG WHERE TGTG.UPDKBN <> 1), TGTEN AS (SELECT TGTEN.MOYSKBN, TGTEN.MOYSSTDT, TGTEN.MOYSRBAN, TGTEN.TENCD, TGTEN.TENGPCD, TGTG.QASYUKBN, TGTEN.KYOSEIFLG, TGTEN.LDTENKBN FROM INATK2.TOKTG_TEN TGTEN LEFT OUTER JOIN TGTG ON TGTG.MOYSKBN = TGTEN.MOYSKBN AND TGTG.MOYSSTDT = TGTEN.MOYSSTDT AND TGTG.MOYSRBAN = TGTEN.MOYSRBAN AND TGTG.TENGPCD = TGTEN.TENGPCD), TGKHN AS (SELECT * FROM INATK2.TOKTG_KHN TGKHN WHERE TGKHN.UPDKBN <> 1), TGSHN AS (SELECT TGSHN.*, CAST(TGSHN.HBSTDT AS DATETIME) AS HBSTDT_TODT, CAST(TGSHN.HBEDDT AS DATETIME) AS HBEDDT_TODT FROM INATK2.TOKTG_SHN TGSHN) SELECT TGSHN.MOYSKBN, TGSHN.MOYSSTDT, TGSHN.MOYSRBAN, 0 AS BMNO, TMC.HBSTDT AS MOHBSTDT, TMC.HBEDDT AS MOHBEDDT, TGKHN.HBOKUREFLG, TGSHN.JLSTCREDT, TGKHN.QADEVSTDT, 0 AS QADEVENDFLG, TGTEN.TENGPCD, TGTEN.KYOSEIFLG, TGSHN.KANRINO, TGSHN.KANRIENO, TGSHN.BMNCD, TGSHN.SHNCD, TGSHN.ADDSHUKBN, TGSHN.HBSTDT, TGSHN.HBEDDT, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 1 ELSE 0 END AS REIDMYKBN, TGSHN.HBSLIDEFLG, CASE WHEN TGSHN.ADDSHUKBN = 2 THEN TGSHN.GENKAAM_MAE WHEN TGSHN.ADDSHUKBN = 4 THEN CASE WHEN TGSHN.TKANPLUKBN = 1 THEN TGSHN.GENKAAM_MAE WHEN TGSHN.TKANPLUKBN = 2 THEN TGSHN.GENKAAM_1KG END WHEN TGSHN.ADDSHUKBN = 5 THEN CASE WHEN TGSHN.TKANPLUKBN = 1 THEN TGSHN.GENKAAM_MAE WHEN TGSHN.TKANPLUKBN = 2 THEN TGSHN.GENKAAM_1KG END END AS GENKAAM, 0 AS GENKARITU, TGSHN.A_BAIKAAM, TGSHN.B_BAIKAAM, TGSHN.C_BAIKAAM, TGSHN.A_GENKAAM_1KG, TGSHN.B_GENKAAM_1KG, TGSHN.C_GENKAAM_1KG, TGSHN.A_WRITUKBN, TGSHN.B_WRITUKBN, TGSHN.C_WRITUKBN, TGSHN.TKANPLUKBN, TGSHN.KO_A_BAIKAAN, TGSHN.BD1_A_BAIKAAN, TGSHN.BD2_A_BAIKAAN, TGSHN.KO_B_BAIKAAN, TGSHN.BD1_B_BAIKAAN, TGSHN.BD2_B_BAIKAAN, TGSHN.KO_C_BAIKAAN, TGSHN.BD1_C_BAIKAAN, TGSHN.BD2_C_BAIKAAN, TGSHN.PLUSNDFLG, 0 AS TEIKEIKBN, 0 AS SOURCEKBN1, '' AS SRCCD1, 0 AS SOURCEKBN2, '' AS SRCCD2, 0 AS URICD, TGTEN.TENCD, CAST(TMC.HBSTDT AS DATETIME) AS HBDT1, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 1 DAY, '%%Y%%m%%d') AS SIGNED) > TGSHN.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 1 DAY, '%%Y%%m%%d') AS SIGNED) = TGSHN.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 1 DAY END AS HBDT2, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 2 DAY, '%%Y%%m%%d') AS SIGNED) > TMC.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 2 DAY, '%%Y%%m%%d') AS SIGNED) = TMC.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 2 DAY END AS HBDT3, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 3 DAY, '%%Y%%m%%d') AS SIGNED) > TMC.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 3 DAY, '%%Y%%m%%d') AS SIGNED) = TMC.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 3 DAY END AS HBDT4, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 4 DAY, '%%Y%%m%%d') AS SIGNED) > TMC.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 4 DAY, '%%Y%%m%%d') AS SIGNED) = TMC.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 4 DAY END AS HBDT5, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 5 DAY, '%%Y%%m%%d') AS SIGNED) > TMC.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 5 DAY, '%%Y%%m%%d') AS SIGNED) = TMC.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 5 DAY END AS HBDT6, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 6 DAY, '%%Y%%m%%d') AS SIGNED) > TMC.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 6 DAY, '%%Y%%m%%d') AS SIGNED) = TMC.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 6 DAY END AS HBDT7, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 7 DAY, '%%Y%%m%%d') AS SIGNED) > TMC.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 7 DAY, '%%Y%%m%%d') AS SIGNED) = TMC.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 7 DAY END AS HBDT8, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 8 DAY, '%%Y%%m%%d') AS SIGNED) > TMC.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 8 DAY, '%%Y%%m%%d') AS SIGNED) = TMC.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 8 DAY END AS HBDT9, CASE WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 9 DAY, '%%Y%%m%%d') AS SIGNED) > TMC.HBEDDT THEN NULL WHEN CAST(DATE_FORMAT(TGSHN.HBSTDT_TODT + INTERVAL 9 DAY, '%%Y%%m%%d') AS SIGNED) = TMC.HBEDDT THEN TGSHN.HBEDDT_TODT ELSE TGSHN.HBSTDT_TODT + INTERVAL 9 DAY END AS HBDT10, TGTEN.QASYUKBN, 1 AS LTENSAIFLG, 0 AS HANKAISIFLG, CASE WHEN TGTEN.LDTENKBN = 0 THEN 1 WHEN TGTEN.LDTENKBN = 1 THEN 2 END AS TENSAIFLG, 1 AS BAIKASELKBN, 1 AS SHOHINSEL, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN TGSHN.A_WRITUKBN ELSE CASE WHEN COALESCE(TGSHN.KO_A_BAIKAAN, 0) = 0 THEN TGSHN.A_BAIKAAM ELSE TGSHN.KO_A_BAIKAAN END END AS CBAIKA, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 0 ELSE TGSHN.BD1_A_BAIKAAN END AS SBAIBL1, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 0 ELSE TGSHN.BD2_A_BAIKAAN END AS SBAIBL2, CASE WHEN TGSHN.ADDSHUKBN = 1 THEN 0 ELSE TGSHN.A_GENKAAM_1KG END AS CBAIKAKG, 1 AS DATAKBN, TGSHN.GTSIMECHGKBN, TGSHN.GTSIMEOKFLG, 0 AS SENDFLG, 0 AS UPDKBN FROM TGSHN INNER JOIN TGKHN ON TGSHN.MOYSKBN = TGKHN.MOYSKBN AND TGSHN.MOYSSTDT = TGKHN.MOYSSTDT AND TGSHN.MOYSRBAN = TGKHN.MOYSRBAN INNER JOIN TGTEN ON TGSHN.MOYSKBN = TGTEN.MOYSKBN AND TGSHN.MOYSSTDT = TGTEN.MOYSSTDT AND TGSHN.MOYSRBAN = TGTEN.MOYSRBAN INNER JOIN INATK2.TOKMOYCD TMC ON TGSHN.MOYSKBN = TMC.MOYSKBN AND TGSHN.MOYSSTDT = TMC.MOYSSTDT AND TGSHN.MOYSRBAN = TMC.MOYSRBAN WHERE TMC.UPDKBN <> 1;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "ANALYZE TABLE INAWK.ANWK01_BF;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
