REM [091][ANWK03]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET MSG=%DATE% %TIME% INAWK.ANWK03 → INAWK.ANWK03 ロード処理（アンケート結果＿店グループ(作成分)ワーク）
ECHO %MSG%
>> %OUTFILE% ECHO %MSG%

"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e "TRUNCATE TABLE INAWK.ANWK03;INSERT IGNORE INTO INAWK.ANWK03 WITH TGKHN AS (SELECT TGKHN.MOYSKBN, TGKHN.MOYSSTDT, TGKHN.MOYSRBAN, TGKHN.QACREDT FROM INATK2.TOKTG_KHN TGKHN LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE TGKHN.UPDKBN <> 1 AND ((COALESCE(TGKHN.QARCREDT, 0) = 0 AND TGKHN.QACREDT = SBD.DT_INT) OR (COALESCE(TGKHN.QARCREDT, 0) <> 0 AND TGKHN.QARCREDT = SBD.DT_INT))), TGTGK AS (SELECT TGTG.MOYSKBN, TGTG.MOYSSTDT, TGTG.MOYSRBAN, TGTG.TENGPCD, TGTG.KYOSEIFLG, TGTG.QASYUKBN FROM INATK2.TOKTG_TENGP TGTG LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1 WHERE TGTG.UPDKBN <> 1 AND ((COALESCE(TGTG.QARCREDT_K, 0) = 0 AND TGTG.QACREDT_K = SBD.DT_INT AND TGTG.KYOSEIFLG = 1) OR (COALESCE(TGTG.QARCREDT_K, 0) <> 0 AND TGTG.QARCREDT_K = SBD.DT_INT AND TGTG.KYOSEIFLG = 1))) SELECT TGTG.*, 1 AS LTENSAIFLG, 1 AS BAIKAIKATSU, 0 AS SCHANSFLG, 0 AS ITEMKFLG, 0 AS CSV_SEQ, 0 AS SENDFLG, '' AS OPERATOR, SBD.DTTIME AS ADDDT, CASE WHEN 1 = 1 THEN NULL ELSE CURRENT_DATE END AS UPDDT FROM (SELECT TGTG.MOYSKBN, TGTG.MOYSSTDT, TGTG.MOYSRBAN, TGTG.TENGPCD, TGTG.KYOSEIFLG, TGTG.QASYUKBN FROM INATK2.TOKTG_TENGP TGTG INNER JOIN TGKHN ON TGTG.MOYSKBN = TGKHN.MOYSKBN AND TGTG.MOYSSTDT = TGKHN.MOYSSTDT AND TGTG.MOYSRBAN = TGKHN.MOYSRBAN UNION ALL SELECT * FROM TGTGK) TGTG LEFT OUTER JOIN INAPARM.SYSBATCHDT SBD ON SBD.ACTIVEFLG = 1;COMMIT;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e " ANALYZE TABLE INAWK.ANWK03;" >>%OUTFILE% 2>&1
IF NOT %ERRORLEVEL%==0 GOTO ERROR

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
