REM [096][BFF10]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET OUTFILENAME=0094
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFBUO006

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(リーダー店アンケート)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(WK.MOYSKBN, 1, 0) || LPAD(WK.MOYSSTDT, 6, 0) || LPAD(WK.MOYSRBAN, 3, 0) || MAX(RPAD(COALESCE(TM.MOYKN, ''), 20, '　')) || LPAD(WK.MOHBSTDT, 8, 0) || LPAD(WEEKDAY(CAST(CAST(WK.MOHBSTDT AS CHAR) AS DATETIME)) + 1, 1, 0) || LPAD(WK.MOHBEDDT, 8, 0) || LPAD(WEEKDAY(CAST(CAST(WK.MOHBEDDT AS CHAR) AS DATETIME)) + 1, 1, 0) || MAX(LPAD(COALESCE(CASE WHEN TKHN.MOYSKBN IS NOT NULL THEN TKHN.TPNG1FLG ELSE 0 END, 0), 1, 0)) || MAX(LPAD(COALESCE(CASE WHEN TKHN.MOYSKBN IS NOT NULL THEN TKHN.TPNG2FLG ELSE 0 END, 0), 1, 0)) || MAX(LPAD(COALESCE(CASE WHEN TKHN.MOYSKBN IS NOT NULL THEN TKHN.TPNG3FLG ELSE 0 END, 0), 1, 0)) || MAX(LPAD(COALESCE(CASE WHEN TKHN.MOYSKBN IS NOT NULL THEN TKHN.HBOKUREFLG ELSE 0 END, 0), 1, 0)) || MAX(LPAD(COALESCE(CASE WHEN TKHN.MOYSKBN IS NOT NULL THEN TKHN.QAYYYYMM ELSE 0 END, 0), 6, 0)) || MAX(LPAD(COALESCE(CASE WHEN TKHN.MOYSKBN IS NOT NULL THEN TKHN.QAENO ELSE 0 END, 0), 2, 0)) || LPAD(WK.TENGPCD, 3, 0) || MAX(RPAD(COALESCE(CASE WHEN TTGP.MOYSKBN IS NOT NULL THEN TTGP.TENGPKN ELSE '' END, ''), 20, '　')) || MAX(LPAD(COALESCE(WK.KYOSEIFLG, 0), 1, 0)) || LPAD(WK.TENCD, 3, 0) || MAX(LPAD(COALESCE(WK.QASYUKBN, 0), 1, 0)) || MAX(LPAD(COALESCE(WK.LTENSAIFLG, 0), 1, 0)) || 0 FROM INAIF.AN_HANBAI_BFR WK INNER JOIN INATK2.TOKMOYCD TM ON WK.MOYSKBN = TM.MOYSKBN AND WK.MOYSSTDT = TM.MOYSSTDT AND WK.MOYSRBAN = TM.MOYSRBAN AND TM.MOYSKBN = 1 AND TM.MOYSRBAN >= 50 AND TM.NNSTDT >= (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY') AND WK.QASYUKBN <> 5 AND WK.TENSAIFLG IN (2, 3) LEFT OUTER JOIN INATK2.TOKTG_TENGP TTGP ON WK.MOYSKBN = TTGP.MOYSKBN AND WK.MOYSSTDT = TTGP.MOYSSTDT AND WK.MOYSRBAN = TTGP.MOYSRBAN AND WK.TENGPCD = TTGP.TENGPCD AND TTGP.UPDKBN <> 1 LEFT OUTER JOIN INATK2.TOKTG_KHN TKHN ON WK.MOYSKBN = TKHN.MOYSKBN AND WK.MOYSSTDT = TKHN.MOYSSTDT AND WK.MOYSRBAN = TKHN.MOYSRBAN AND TKHN.UPDKBN <> 1 GROUP BY WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, WK.TENGPCD, WK.TENCD, WK.MOHBSTDT, WK.MOHBEDDT ORDER BY WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, WK.TENGPCD, WK.TENCD, WK.MOHBSTDT, WK.MOHBEDDT" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
REM call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
