REM [095][BFF11]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0095
SET HULFTID=VFBUO007
SET EXPFILE=%~DP0../exp/%OUTFILENAME%

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(リーダー店アイテムアンケート)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(WK.MOYSKBN, 1, 0) || LPAD(WK.MOYSSTDT, 6, 0) || LPAD(WK.MOYSRBAN, 3, 0) || LPAD(WK.KANRINO, 4, 0) || LPAD(WK.KANRIENO, 2, 0) || RPAD(COALESCE(WK.SHNCD, ''), 14, ' ') || LPAD(WK.BMNCD, 3, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.DAICD ELSE 0 END, 0), 2, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.CHUCD ELSE 0 END, 0), 2, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.SHOBUNCD ELSE 0 END, 0), 2, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.CHIRASFLG ELSE 0 END, 0), 1, 0) || RPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.PARNO ELSE '' END, ''), 3, ' ') || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.CHLDNO ELSE 0 END, 0), 2, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.HIGAWRFLG ELSE 0 END, 0), 1, 0) || RPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.SANCHIKN ELSE '' END, ''), 20, '　') || RPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.MAKERKN ELSE '' END, ''), 14, '　') || RPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.POPKN ELSE '' END, ''), 20, '　') || RPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.KIKKN ELSE '' END, ''), 23, '　') || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.ADDSHUKBN ELSE 0 END, 0), 2, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN TRIM(LPAD(CAST(ASHN.GENKAAM_MAE * 100 AS SIGNED), 8, 0)) ELSE '0' END, '0'), 8, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN TRIM(LPAD(CAST(ASHN.GENKAAM_1KG * 100 AS SIGNED), 8, 0)) ELSE '0' END, '0'), 8, 0) || LPAD(COALESCE(WK.HBSTDT, 0), 8, 0) || LPAD(COALESCE(WEEKDAY(CAST(CAST(WK.HBSTDT AS CHAR) AS DATETIME)) + 1, 0), 1, 0) || LPAD(COALESCE(WK.HBEDDT, 0), 8, 0) || LPAD(COALESCE(WEEKDAY(CAST(CAST(WK.HBEDDT AS CHAR) AS DATETIME)) + 1, 0), 1, 0) || LPAD(COALESCE(WK.A_BAIKAAM, 0), 6, 0) || LPAD(COALESCE(WK.B_BAIKAAM, 0), 6, 0) || LPAD(COALESCE(WK.C_BAIKAAM, 0), 6, 0) || LPAD(COALESCE(WK.A_GENKAAM_1KG, 0), 6, 0) || LPAD(COALESCE(WK.B_GENKAAM_1KG, 0), 6, 0) || LPAD(COALESCE(WK.C_GENKAAM_1KG, 0), 6, 0) || LPAD(COALESCE(WK.A_WRITUKBN, 0), 1, 0) || LPAD(COALESCE(WK.B_WRITUKBN, 0), 1, 0) || LPAD(COALESCE(WK.C_WRITUKBN, 0), 1, 0) || LPAD(COALESCE(WK.TKANPLUKBN, 0), 1, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.YORIFLG ELSE 0 END, 0), 1, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.BD1_TENSU ELSE 0 END, 0), 3, 0) || LPAD(COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.BD2_TENSU ELSE 0 END, 0), 3, 0) || LPAD(COALESCE(WK.KO_A_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.BD1_A_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.BD2_A_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.KO_B_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.BD1_B_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.BD2_B_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.KO_C_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.BD1_C_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.BD2_C_BAIKAAN, 0), 6, 0) || LPAD(COALESCE(WK.HBSLIDEFLG, 0), 1, 0) || LPAD(ROW_NUMBER() OVER (PARTITION BY WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN ORDER BY WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.HIGAWRFLG ELSE 0 END, 0) DESC, WK.BMNCD, WK.HBSTDT, ASHN.DAICD, ASHN.CHUCD, ASHN.SHOBUNCD, ASHN.SHNCD, WK.KANRINO), 12, 0) || 0 FROM (SELECT WK.MOYSCD, WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, WK.BMNCD, WK.KANRINO, WK.KANRIENO, MAX(WK.MOHBSTDT) AS MOHBSTDT, MAX(WK.MOHBEDDT) AS MOHBEDDT, MAX(WK.HBOKUREFLG) AS HBOKUREFLG, MAX(WK.JLSTCREDT) AS JLSTCREDT, MAX(WK.QADEVSTDT) AS QADEVSTDT, MAX(WK.QADEVENDFLG) AS QADEVENDFLG, MAX(WK.TENGPCD) AS TENGPCD, MAX(WK.KYOSEIFLG) AS KYOSEIFLG, MAX(WK.SHNCD) AS SHNCD, MAX(WK.ADDSHUKBN) AS ADDSHUKBN, MAX(WK.HBSTDT) AS HBSTDT, MAX(WK.HBEDDT) AS HBEDDT, MAX(WK.REIDMYKBN) AS REIDMYKBN, MAX(WK.HBSLIDEFLG) AS HBSLIDEFLG, MAX(WK.GENKAAM) AS GENKAAM, MAX(WK.GENKARITU) AS GENKARITU, MAX(WK.A_BAIKAAM) AS A_BAIKAAM, MAX(WK.B_BAIKAAM) AS B_BAIKAAM, MAX(WK.C_BAIKAAM) AS C_BAIKAAM, MAX(WK.A_GENKAAM_1KG) AS A_GENKAAM_1KG, MAX(WK.B_GENKAAM_1KG) AS B_GENKAAM_1KG, MAX(WK.C_GENKAAM_1KG) AS C_GENKAAM_1KG, MAX(WK.A_WRITUKBN) AS A_WRITUKBN, MAX(WK.B_WRITUKBN) AS B_WRITUKBN, MAX(WK.C_WRITUKBN) AS C_WRITUKBN, MAX(WK.TKANPLUKBN) AS TKANPLUKBN, MAX(WK.KO_A_BAIKAAN) AS KO_A_BAIKAAN, MAX(WK.BD1_A_BAIKAAN) AS BD1_A_BAIKAAN, MAX(WK.BD2_A_BAIKAAN) AS BD2_A_BAIKAAN, MAX(WK.KO_B_BAIKAAN) AS KO_B_BAIKAAN, MAX(WK.BD1_B_BAIKAAN) AS BD1_B_BAIKAAN, MAX(WK.BD2_B_BAIKAAN) AS BD2_B_BAIKAAN, MAX(WK.KO_C_BAIKAAN) AS KO_C_BAIKAAN, MAX(WK.BD1_C_BAIKAAN) AS BD1_C_BAIKAAN, MAX(WK.BD2_C_BAIKAAN) AS BD2_C_BAIKAAN, MAX(WK.PLUSNDFLG) AS PLUSNDFLG, MAX(WK.TEIKEIKBN) AS TEIKEIKBN, MAX(WK.SOURCEKBN1) AS SOURCEKBN1, MAX(WK.SRCCD1) AS SRCCD1, MAX(WK.SOURCEKBN2) AS SOURCEKBN2, MAX(WK.SRCCD2) AS SRCCD2, MAX(WK.URICD) AS URICD, MAX(WK.QASYUKBN) AS QASYUKBN, MAX(WK.LTENSAIFLG) AS LTENSAIFLG, MAX(WK.HANKAISIFLG) AS HANKAISIFLG, MAX(WK.TENSAIFLG) AS TENSAIFLG, MAX(WK.URIASELKBN) AS URIASELKBN, MAX(WK.ITMSELKBN) AS ITMSELKBN, MAX(WK.CBAIKA) AS CBAIKA, MAX(WK.SBAIBL1) AS SBAIBL1, MAX(WK.SBAIBL2) AS SBAIBL2, MAX(WK.CBAIKAKG) AS CBAIKAKG, MAX(WK.DATAKBN) AS DATAKBN, MAX(WK.GTSIMECHGKBN) AS GTSIMECHGKBN, MAX(WK.GTSIMEOKFLG) AS GTSIMEOKFLG, MAX(WK.SENDFLG) AS SENDFLG, MAX(WK.UPDKBN) AS UPDKBN FROM INAIF.AN_HANBAI_BFR WK INNER JOIN INATK2.TOKMOYCD TM ON WK.MOYSKBN = TM.MOYSKBN AND WK.MOYSSTDT = TM.MOYSSTDT AND WK.MOYSRBAN = TM.MOYSRBAN AND TM.MOYSKBN = 1 AND TM.MOYSRBAN >= 50 AND TM.NNSTDT >= (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY') AND WK.QASYUKBN <> 5 GROUP BY WK.MOYSCD, WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, WK.BMNCD, WK.KANRINO, WK.KANRIENO) WK LEFT OUTER JOIN INATK2.TOKTG_SHN ASHN ON WK.MOYSKBN = ASHN.MOYSKBN AND WK.MOYSSTDT = ASHN.MOYSSTDT AND WK.MOYSRBAN = ASHN.MOYSRBAN AND WK.BMNCD = ASHN.BMNCD AND WK.KANRINO = ASHN.KANRINO AND WK.KANRIENO = ASHN.KANRIENO ORDER BY WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, COALESCE(CASE WHEN ASHN.MOYSKBN IS NOT NULL THEN ASHN.HIGAWRFLG ELSE 0 END, 0) DESC, WK.BMNCD, WK.HBSTDT, ASHN.DAICD, ASHN.CHUCD, ASHN.SHOBUNCD, ASHN.SHNCD, WK.KANRINO;" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
REM call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
