REM [096][BFF12]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET OUTFILENAME=0096
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFBUO008

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(各店アンケート)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(WK.MOYSKBN, 1, 0) || LPAD(WK.MOYSSTDT, 6, 0) || LPAD(WK.MOYSRBAN, 3, 0) || LPAD(WK.TENGPCD, 3, 0) || LPAD(WK.TENCD, 3, 0) || 0 FROM INAIF.AN_HANBAI_BFR WK INNER JOIN INATK2.TOKMOYCD TM ON WK.MOYSKBN = TM.MOYSKBN AND WK.MOYSSTDT = TM.MOYSSTDT AND WK.MOYSRBAN = TM.MOYSRBAN AND TM.MOYSKBN = 1 AND TM.MOYSRBAN >= 50 AND TM.NNSTDT >= (SELECT SBD.DT_INT FROM INAPARM.SYSBATCHDT_TK SBD WHERE SBD.SMODE = 'DAILY') AND WK.QASYUKBN <> 5 GROUP BY WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, WK.TENGPCD, WK.TENCD ORDER BY WK.MOYSKBN, WK.MOYSSTDT, WK.MOYSRBAN, WK.TENGPCD, WK.TENCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
REM call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
