REM [112][BFC16]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET OUTFILENAME=0112
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFAUO014

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(次週定量＿店別数量)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT RPAD(T1.SHNCD, 14, ' ') || LPAD(T1.BINKBN, 1, 0) || LPAD(T1.TENCD, 3, 0) || LPAD(T1.SHUNO, 4, 0) || LPAD(COALESCE(T1.SURYO_MON, 0), 5, 0) || LPAD(COALESCE(T1.SURYO_TUE, 0), 5, 0) || LPAD(COALESCE(T1.SURYO_WED, 0), 5, 0) || LPAD(COALESCE(T1.SURYO_THU, 0), 5, 0) || LPAD(COALESCE(T1.SURYO_FRI, 0), 5, 0) || LPAD(COALESCE(T1.SURYO_SAT, 0), 5, 0) || LPAD(COALESCE(T1.SURYO_SUN, 0), 5, 0) || LPAD(T1.SENDFLG, 1, 0) || RPAD(T1.OPERATOR, 20, ' ') || LPAD(COALESCE(DATE_FORMAT(T1.ADDDT, '%%Y%%m%%d'), '0'), 8, 0) || LPAD(COALESCE(DATE_FORMAT(T1.UPDDT, '%%Y%%m%%d'), '0'), 8, 0) FROM INATK2.HATJTR_TEN T1 ORDER BY T1.SHNCD, T1.BINKBN, T1.TENCD, T1.SHUNO" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
REM call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
