REM [148][BFI07]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET OUTFILENAME=0148
SET HULFTID=VFCUO001
SET EXPFILE=%~DP0../exp/%OUTFILENAME%

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(事前発注＿店舗（戻り用）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(TEN.LSTNO, 6, 0) || LPAD(TEN.BMNCD, 3, 0) || LPAD(TEN.HYOSEQNO, 8, 0) || LPAD(TEN.TENCD, 3, 0) || RPAD(TEN.SHNCD, 14, ' ') || LPAD(TEN.BINKBN, 1, 0) || LPAD(TEN.IRISU_RG, 3, 0) || LPAD(TEN.IRISU_TB, 3, 0) || LPAD(TEN.SBAIKAAM_TB, 6, 0) || LPAD(TEN.BAIKAAM_TB, 6, 0) || LPAD(TEN.SBAIKAAM_RG, 6, 0) || LPAD(TEN.BAIKAAM_RG, 6, 0) || LPAD(CAST(TEN.GENKAAM_MAE * 100 AS SIGNED), 8, 0) || LPAD(CAST(TEN.GENKAAM_ATO * 100 AS SIGNED), 8, 0) || LPAD(CAST(TEN.GENKAAM_RG * 100 AS SIGNED), 8, 0) || LPAD(CAST(TEN.GENKAAM_PACK * 100 AS SIGNED), 8, 0) || LPAD(TEN.BAIKAAM_PACK, 6, 0) || LPAD(TEN.JTDT_01, 8, 0) || LPAD(TEN.JTDT_02, 8, 0) || LPAD(TEN.JTDT_03, 8, 0) || LPAD(TEN.JTDT_04, 8, 0) || LPAD(TEN.JTDT_05, 8, 0) || LPAD(TEN.JTDT_06, 8, 0) || LPAD(TEN.JTDT_07, 8, 0) || LPAD(TEN.JTDT_08, 8, 0) || LPAD(TEN.JTDT_09, 8, 0) || LPAD(TEN.JTDT_10, 8, 0) || RPAD(COALESCE(CAST(TEN.TSEIKBN_01 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_02 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_03 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_04 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_05 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_06 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_07 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_08 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_09 AS CHAR), ''), 1, ' ') || RPAD(COALESCE(CAST(TEN.TSEIKBN_10 AS CHAR), ''), 1, ' ') || LPAD(TEN.SHNKBN_01, 1, 0) || LPAD(TEN.SHNKBN_02, 1, 0) || LPAD(TEN.SHNKBN_03, 1, 0) || LPAD(TEN.SHNKBN_04, 1, 0) || LPAD(TEN.SHNKBN_05, 1, 0) || LPAD(TEN.SHNKBN_06, 1, 0) || LPAD(TEN.SHNKBN_07, 1, 0) || LPAD(TEN.SHNKBN_08, 1, 0) || LPAD(TEN.SHNKBN_09, 1, 0) || LPAD(TEN.SHNKBN_10, 1, 0) || LPAD(TEN.HTSU_01, 5, 0) || LPAD(TEN.HTSU_02, 5, 0) || LPAD(TEN.HTSU_03, 5, 0) || LPAD(TEN.HTSU_04, 5, 0) || LPAD(TEN.HTSU_05, 5, 0) || LPAD(TEN.HTSU_06, 5, 0) || LPAD(TEN.HTSU_07, 5, 0) || LPAD(TEN.HTSU_08, 5, 0) || LPAD(TEN.HTSU_09, 5, 0) || LPAD(TEN.HTSU_10, 5, 0) || LPAD(TEN.PAGENO, 3, 0) || LPAD(TEN.SENDFLG, 1, 0) || RPAD(TEN.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(TEN.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(TEN.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAWK.JH_RTN_TEN TEN WHERE TRIM(TEN.OPERATOR) <> 'BATCH' ORDER BY TEN.LSTNO, TEN.BMNCD, TEN.HYOSEQNO, TEN.TENCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
