REM [149][BFI06]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET OUTFILENAME=0149
SET HULFTID=VFCUO002
SET EXPFILE=%~DP0../exp/%OUTFILENAME%

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(事前発注＿追加商品（戻り用）)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(SHN.LSTNO, 6, 0) || LPAD(SHN.BMNCD, 3, 0) || LPAD(SHN.HYOSEQNO, 8, 0) || LPAD(SHN.TENCD, 3, 0) || RPAD(SHN.SHNCD, 14, ' ') || LPAD(SHN.BINKBN, 1, 0) || LPAD(SHN.JTDT_01, 8, 0) || LPAD(SHN.JTDT_02, 8, 0) || LPAD(SHN.JTDT_03, 8, 0) || LPAD(SHN.JTDT_04, 8, 0) || LPAD(SHN.JTDT_05, 8, 0) || LPAD(SHN.JTDT_06, 8, 0) || LPAD(SHN.JTDT_07, 8, 0) || LPAD(SHN.JTDT_08, 8, 0) || LPAD(SHN.JTDT_09, 8, 0) || LPAD(SHN.JTDT_10, 8, 0) || LPAD(SHN.HTSU_01, 5, 0) || LPAD(SHN.HTSU_02, 5, 0) || LPAD(SHN.HTSU_03, 5, 0) || LPAD(SHN.HTSU_04, 5, 0) || LPAD(SHN.HTSU_05, 5, 0) || LPAD(SHN.HTSU_06, 5, 0) || LPAD(SHN.HTSU_07, 5, 0) || LPAD(SHN.HTSU_08, 5, 0) || LPAD(SHN.HTSU_09, 5, 0) || LPAD(SHN.HTSU_10, 5, 0) || LPAD(SHN.PAGENO, 3, 0) || LPAD(SHN.SENDFLG, 1, 0) || RPAD(SHN.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(SHN.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(SHN.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAWK.JH_RTN_ADDSHN SHN ORDER BY SHN.LSTNO, SHN.BMNCD, SHN.HYOSEQNO, SHN.TENCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
