REM [150][A11TC30]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2
SET OUTFILENAME=0628
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VFCUO005

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(店数量反映エラーデータ(生鮮))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(T1.BMNCD, 3, 0) || RPAD(TRIM(T1.SHNCD), 13, ' ') || LPAD(T1.BINKBN, 1, 0) || LPAD(T1.TENCD, 3, 0) || LPAD(T1.NNDT, 8, 0) || LPAD(T1.SURYO, 5, 0) || LPAD(T1.MAESURYO, 5, 0) || LPAD(T1.TOKKBN, 1, 0) || LPAD(T1.INPUTKBN, 1, 0) || LPAD(T1.TTKBN, 1, 0) || LPAD(T1.JISEIKBN, 1, 0) || LPAD(T1.YOUBIKBN, 2, 0) || LPAD(T1.SHNKBN, 1, 0) || LPAD(T1.ERRKBN, 2, 0) || '    ' || LPAD(T1.MOYSKBN, 1, 0) || LPAD(T1.MOYSSTDT, 6, 0) || LPAD(T1.MOYSRBAN, 3, 0) || LPAD(T1.KANRINO, 4, 0) || LPAD(T1.SYUTENCD, 3, 0) || RPAD(T1.SHNAN, 20, ' ') || LPAD(CAST(COALESCE(T1.GENKAAM, 0) * 100 AS SIGNED), 8, 0) || LPAD(CASE WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) <= COALESCE(20000000 + T1.MOYSSTDT, 0) THEN CAST(COALESCE(TRUNCATE (T1.BAIKAAM, 0), 0) + COALESCE(TRUNCATE (CAST(T1.BAIKAAM * MZS1.ZEIRT AS DECIMAL) / 100, 0), 0) AS SIGNED) WHEN MS.ZEIKBN = 0 AND COALESCE(MS.ZEIRTHENKODT, 0) > COALESCE(20000000 + T1.MOYSSTDT, 0) THEN CAST(COALESCE(TRUNCATE (T1.BAIKAAM, 0), 0) + COALESCE(TRUNCATE (CAST(T1.BAIKAAM * MZS2.ZEIRT AS DECIMAL) / 100, 0), 0) AS SIGNED) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) <= COALESCE(20000000 + T1.MOYSSTDT, 0) THEN CAST(COALESCE(TRUNCATE (T1.BAIKAAM, 0), 0) + COALESCE(TRUNCATE (CAST(T1.BAIKAAM * MZB1.ZEIRT AS DECIMAL) / 100, 0), 0) AS SIGNED) WHEN MS.ZEIKBN = 3 AND MB.ZEIKBN = 0 AND COALESCE(MB.ZEIRTHENKODT, 0) > COALESCE(20000000 + T1.MOYSSTDT, 0) THEN CAST(COALESCE(TRUNCATE (T1.BAIKAAM, 0), 0) + COALESCE(TRUNCATE (CAST(T1.BAIKAAM * MZB2.ZEIRT AS DECIMAL) / 100, 0), 0) AS SIGNED) ELSE CAST(T1.BAIKAAM AS SIGNED) END, 6, 0) || LPAD(T1.IRISU, 3, 0) || LPAD(T1.DAICD, 2, 0) || LPAD(T1.CHUCD, 2, 0) || '    ' FROM INAIF.JH_TOK_ERR T1 LEFT OUTER JOIN INAMS2.MSTSHN T2 ON T1.SHNCD = T2.SHNCD LEFT OUTER JOIN INAMS2.MSTSHN MS ON T1.SHNCD = MS.SHNCD AND MS.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTBMN MB ON T1.BMNCD = MB.BMNCD AND MB.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZS1 ON MZS1.ZEIRTKBN = MS.ZEIRTKBN AND MZS1.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZS2 ON MZS2.ZEIRTKBN = MS.ZEIRTKBN_OLD AND MZS2.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZB1 ON MZB1.ZEIRTKBN = MB.ZEIRTKBN AND MZB1.UPDKBN <> 1 LEFT OUTER JOIN INAMS2.MSTZEIRT MZB2 ON MZB2.ZEIRTKBN = MB.ZEIRTKBN_OLD AND MZB2.UPDKBN <> 1 WHERE MB.BMNKBN = 2 ORDER BY T1.BMNCD, T1.SHNCD, T1.BINKBN, T1.NNDT, T1.TENCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
