REM [000][YOYAKU.DEL]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2



REM 既にマスタ適用済の予約を削除する。
SET MSG=%DATE% %TIME%  →  DELETE処理(INAMS2.商品マスタ_予約) 
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS2.MSTSHN_Y SHN WHERE SHN.YOYAKUDT <= (SELECT DISTINCT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY');commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME%  →  DELETE処理(INAMS2.売価コントロールマスタ_予約)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS2.MSTBAIKACTL_Y BC WHERE BC.YOYAKUDT <= (SELECT DISTINCT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY');commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME%  →  DELETE処理(INAMS2.仕入グループ商品マスタ_予約)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS2.MSTSIRGPSHN_Y SGS WHERE SGS.YOYAKUDT <= (SELECT DISTINCT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY');commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR

SET MSG=%DATE% %TIME%  →  DELETE処理(INAMS2.ソースコード管理マスタ_予約)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% --show-warnings -vv -e"DELETE FROM INAMS2.MSTSRCCD_Y SRC WHERE SRC.YOYAKUDT <= (SELECT DISTINCT SBD.DT_INT FROM INAPARM.SYSBATCHDT SBD WHERE SBD.SMODE = 'DAILY');commit;" >>%OUTFILE% 2>&1
IF %ERRORLEVEL% GTR 1 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
