REM [011][AEA84]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0011
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO018

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(ソースコード管理(予約))
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH SY AS (SELECT SY.SHNCD, SY.YOYAKUDT, SY.UPDKBN FROM INAMS2.MSTSHN_Y SY WHERE SY.SENDFLG IN (0, 9)), SCY AS (SELECT SCY.* FROM INAMS2.MSTSRCCD_Y SCY WHERE SCY.SEQNO IN (1, 2) AND EXISTS (SELECT 1 FROM SY WHERE SY.UPDKBN <> 1 AND SCY.SHNCD = SY.SHNCD AND SCY.YOYAKUDT = SY.YOYAKUDT)), PRE AS (SELECT SHNCD, YOYAKUDT FROM INAPRE.MSTSRCCD_Y_PD T1 WHERE T1.SEQNO IN (1, 2) AND EXISTS (SELECT 1 FROM INAPRE.MSTSHN_Y_PD T2 WHERE T2.UPDKBN <> 1 AND T1.SHNCD = T2.SHNCD AND T1.YOYAKUDT = T2.YOYAKUDT) GROUP BY SHNCD, YOYAKUDT) SELECT CONCAT(CASE WHEN PRE.SHNCD IS NULL THEN 1 ELSE 3 END, SUBSTR(RPAD(B_SCY.SHNCD, 14, ' '), 1, 2), SUBSTR(RPAD(B_SCY.SHNCD, 14, ' '), 3, 6), SUBSTR(RPAD(B_SCY.SHNCD, 14, ' '), 9, 6), RPAD(B_SCY.SRCCD, 14, ' '), LPAD(B_SCY.YOYAKUDT, 8, 0), LPAD(B_SCY.SEQNO, 1, 0), LPAD(B_SCY.SOURCEKBN, 1, 0), '     ', RPAD(B_SCY.OPERATOR, 20, ' '), LPAD(B_SCY.SENDFLG, 1, 0), LPAD(DATE_FORMAT(B_SCY.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(B_SCY.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM (SELECT * FROM SCY) B_SCY LEFT OUTER JOIN PRE ON B_SCY.SHNCD = PRE.SHNCD AND B_SCY.YOYAKUDT = PRE.YOYAKUDT ORDER BY B_SCY.SHNCD, B_SCY.SRCCD, B_SCY.YOYAKUDT" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
