REM [026][AIA57]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0026
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO019

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(商品店グループ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT CONCAT(LPAD(STG.GPKBN, 1, 0), LPAD(STG.BMNCD, 3, 0), LPAD(STG.AREAKBN, 1, 0), LPAD(STG.TENGPCD, 4, 0), RPAD(STG.TENGPAN, 20, ' '), RPAD(STG.TENGPKN, 20, '　'), LPAD(STG.PCARD_OPFLG, 1, 0), '  ', RPAD(STG.OPERATOR, 20, ' '), LPAD(STG.SENDFLG, 1, 0), LPAD(STG.UPDKBN, 1, 0), LPAD(DATE_FORMAT(STG.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(STG.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM INAMS2K.MSTSHNTENGP STG WHERE STG.UPDKBN <> 1 ORDER BY STG.GPKBN, STG.BMNCD, STG.AREAKBN, STG.TENGPCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
