REM [027][AEA83]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0613
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO013

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(売価コントロール)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "WITH STGT AS (SELECT STGT.BMNCD, STGT.TENGPCD FROM INAMS2K.MSTSHNTENGPTEN STGT WHERE STGT.GPKBN = 2 AND STGT.SENDFLG IN (0, 9) AND EXISTS (SELECT 1 FROM INAMS2K.MSTSHNTENGP STG WHERE STG.UPDKBN <> 1 AND STG.GPKBN = STGT.GPKBN AND STG.BMNCD = STGT.BMNCD AND STG.TENGPCD = STGT.TENGPCD) GROUP BY STGT.BMNCD, STGT.TENGPCD), BC AS (SELECT BC.* FROM INAMS2.MSTBAIKACTL BC WHERE BC.AREAKBN <> 0 AND EXISTS (SELECT 1 FROM STGT WHERE STGT.BMNCD = CAST(SUBSTR(BC.SHNCD, 1, 2) AS SIGNED) AND STGT.TENGPCD = BC.TENGPCD)) SELECT CONCAT('4', ' ', SUBSTR(RPAD(BC.SHNCD, 14, ' '), 1, 2), SUBSTR(RPAD(BC.SHNCD, 14, ' '), 3, 6), SUBSTR(RPAD(BC.SHNCD, 14, ' '), 9, 6), LPAD(BC.TENGPCD, 4, 0), LPAD(BC.YOYAKUDT, 8, 0), LPAD(BC.AREAKBN, 1, 0), LPAD(SUBSTR(BC.GENKAAM, 1, LOCATE('.', BC.GENKAAM) - 1), 6, 0), SUBSTR(BC.GENKAAM, LOCATE('.', BC.GENKAAM) + 1), LPAD(BC.BAIKAAM, 6, 0), LPAD(BC.IRISU, 3, 0), '         ', RPAD(BC.OPERATOR, 20, ' '), LPAD(BC.SENDFLG, 1, 0), LPAD(DATE_FORMAT(BC.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(BC.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM BC ORDER BY BC.SHNCD, BC.TENGPCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
