REM [030][AFA02]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0030
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEBUO002

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(店舗部門マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT CONCAT(LPAD(TB.TENCD, 3, 0), LPAD(TB.BMNCD, 3, 0), LPAD(TB.AREACD, 2, 0), LPAD(TB.READTMPTN, 3, 0), RPAD(TB.BMNKN, 10, '　'), LPAD(TB.GROUPNO, 4, 0), RPAD(TB.BMNRECEIPTAN, 20, ' '), RPAD(TB.BMNRECEIPTKN, 20, '　'), LPAD(TB.MIOKBN, 1, 0), LPAD(TB.SHUKEICD, 4, 0), LPAD(TB.WARIBIKIKBN, 1, 0), LPAD(SUBSTR(TB.BMNGENKART, 1, LOCATE('.', TB.BMNGENKART) - 1), 3, 0), SUBSTR(TB.BMNGENKART, LOCATE('.', TB.BMNGENKART) + 1), LPAD(TB.TENANTKBN, 1, 0), LPAD(TB.LOSSTKBN, 1, 0), LPAD(TB.YOSANKBN_B, 1, 0), LPAD(TB.TANAOROTKBN, 1, 0), LPAD(TB.PCARD_SHUKBN, 1, 0), LPAD(TB.PCARD_IROKBN, 1, 0), LPAD(TB.TENANTCD, 5, 0), LPAD(TB.BMN_ATR1, 1, 0), LPAD(TB.BMN_ATR2, 1, 0), LPAD(TB.BMN_ATR3, 1, 0), LPAD(TB.BMN_ATR4, 1, 0), LPAD(TB.BMN_ATR5, 1, 0), LPAD(TB.URIFLG, 1, 0), '         ', LPAD(TB.SENDFLG, 1, 0), LPAD(TB.UPDKBN, 1, 0), RPAD(TB.OPERATOR, 20, ' '), LPAD(DATE_FORMAT(TB.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(TB.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM INAMS2K.MSTTENBMN TB WHERE TB.UPDKBN <> 1 ORDER BY TB.TENCD, TB.BMNCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
