REM [036][AIC53]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0036
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VECUO003

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(エリア別配送パターン仕入先)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT CONCAT(LPAD(AHPS.SIRCD, 6, 0), LPAD(AHPS.HSPTN, 3, 0), LPAD(AHPS.TENGPCD, 4, 0), RPAD(AHPS.TENDENFLG, 1, ' '), RPAD(AHPS.VANKBN, 1, ' '), RPAD(AHPS.UNYOKBN, 1, ' '), RPAD(AHPS.DENPKBN, 1, ' '), RPAD(AHPS.SHUHKBN, 1, ' '), RPAD(AHPS.PICKDKBN, 1, ' '), RPAD(AHPS.PICKLKBN, 1, ' '), RPAD(AHPS.WAPNKBN, 1, ' '), RPAD(AHPS.IDENPKBN, 1, ' '), RPAD(AHPS.KAKOSJKBN, 1, ' '), RPAD(AHPS.RYUTSUKBN, 1, ' '), RPAD(AHPS.ZDENPKBN, 1, ' '), RPAD(AHPS.ZSHUHKBN, 1, ' '), RPAD(AHPS.ZPICKDKBN, 1, ' '), RPAD(AHPS.ZPICKLKBN, 1, ' '), RPAD(AHPS.RSIRCD, 6, ' '), RPAD(AHPS.YKNSHKBN, 1, ' '), RPAD(AHPS.YDENPKBN, 1, ' '), RPAD(AHPS.DSHUHKBN, 1, ' '), '      ', LPAD(AHPS.SENDFLG, 1, 0), RPAD(AHPS.OPERATOR, 20, ' '), LPAD(DATE_FORMAT(AHPS.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(AHPS.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM INAMS2K.MSTAREAHSPTNSIR AHPS WHERE EXISTS (SELECT 1 FROM INAMS2K.MSTSIR SIR WHERE AHPS.SIRCD = SIR.SIRCD AND SIR.UPDKBN <> 1) ORDER BY AHPS.SIRCD, AHPS.HSPTN, AHPS.TENGPCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
