REM [037][AIC55]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0037
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO022

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(配送パターン)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT CONCAT(LPAD(HP.HSPTN, 3, 0), RPAD(HP.HSPTNKN, 20, '　'), LPAD(HP.CENTERCD, 3, 0), LPAD(HP.YCENTERCD, 3, 0), '   ', LPAD(HP.SENDFLG, 1, 0), LPAD(HP.UPDKBN, 1, 0), RPAD(HP.OPERATOR, 20, ' '), LPAD(DATE_FORMAT(HP.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(HP.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM INAMS2K.MSTHSPTN HP WHERE HP.UPDKBN <> 1 ORDER BY HP.HSPTN" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
