REM [038][AIC56]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0038
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VEAUO023

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(エリア別配送パターン)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(AHP.HSPTN, 3, 0) || LPAD(AHP.TENGPCD, 4, 0) || LPAD(AHP.HSGPCD, 4, 0) || LPAD(AHP.AREAKBN, 1, 0) || LPAD(AHP.CENTERCD, 3, 0) || LPAD(TRIM(AHP.YCENTERCD), 3, 0) || '     ' || LPAD(AHP.SENDFLG, 1, 0) || RPAD(AHP.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(AHP.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(AHP.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2K.MSTAREAHSPTN AHP WHERE EXISTS (SELECT 1 FROM INAMS2K.MSTHSPTN HP WHERE HP.UPDKBN <> 1 AND HP.HSPTN = AHP.HSPTN) ORDER BY AHP.HSPTN, AHP.TENGPCD" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
