REM [040][A11MSIR]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2


SET OUTFILENAME=040.A11MSIR.csv
SET EXPFILE=%~DP0../exp/%OUTFILENAME%

SET MSG=%DATE% %TIME%  →  EXPORT処理(複数仕入先マスタ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT LPAD(FSR.SIRCD, 6, 0) || LPAD(FST.TENCD, 3, 0) || LPAD(FSR.RSIRCD, 6, 0) || LPAD(FSR.SEQNO, 2, 0) || '     ' || LPAD(FSR.UPDKBN, 1, 0) || LPAD(FSR.SENDFLG, 1, 0) || LPAD(FSR.OPERATOR, 20, ' ') || LPAD(DATE_FORMAT(FSR.ADDDT, '%%Y%%m%%d'), 8, 0) || LPAD(DATE_FORMAT(FSR.UPDDT, '%%Y%%m%%d'), 8, 0) FROM INAMS2.MSTFUKUSUSIR_R FSR INNER JOIN INAMS2.MSTFUKUSUSIR_T FST ON FSR.SIRCD = FST.SIRCD AND FSR.SEQNO = FST.SEQNO ORDER BY FST.SIRCD, FST.TENCD, FST.SEQNO" >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR


:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
