REM [042][A11HGT]
@ECHO OFF

REM ログフォルダ作成
IF NOT EXIST %~DP0..\logs MKDIR %~DP0..\logs

REM コマンドフォルダ作成
IF NOT EXIST %~DP0..\cmd MKDIR %~DP0..\cmd

REM ログファイルの情報
SET OUTFILE=%~DP0../logs/setup.log
SET OUTTIME=%~DP0../logs/time.log

REM ベースフォルダ
SET BASEDIR=%~DP0..

REM 更新対象の情報
SET INFOSCRIPT=%~DP0..\cmd\%~N0.DB2

SET OUTFILENAME=0042
SET EXPFILE=%~DP0../exp/%OUTFILENAME%
SET HULFTID=VECUO010

REM ===== HULFT SEND DELETE ===============
SET HULFT=D:\HULFTFILES\SEND\%OUTFILENAME%
DEL /Q %HULFT%\*

SET MSG=%DATE% %TIME%  →  EXPORT処理(配送店グループ)
ECHO %MSG%
ECHO %MSG% >> %OUTFILE%
"%MYSQLPATH%mysql" %OPTION% -h %HOST% %DB_NAME% -u %USER_ID% -N -e "SELECT CONCAT(LPAD(HTG.HSGPCD, 4, 0), LPAD(HTG.TENGPCD, 4, 0), RPAD(HTG.TENGPAN, 20, ' '), RPAD(HTG.TENGPKN, 20, '　'), '    ', LPAD(HTG.UPDKBN, 1, 0), LPAD(HTG.SENDFLG, 1, 0), RPAD(HTG.OPERATOR, 20, ' '), LPAD(DATE_FORMAT(HTG.ADDDT, '%%Y%%m%%d'), 8, 0), LPAD(DATE_FORMAT(HTG.UPDDT, '%%Y%%m%%d'), 8, 0)) FROM INAMS2K.MSTHSTENGP HTG WHERE HTG.UPDKBN <> 1 ORDER BY HTG.HSGPCD, HTG.TENGPCD"  >%EXPFILE% 2>>%OUTFILE%
IF NOT %ERRORLEVEL%==0 GOTO ERROR

REM ===== HULFT SEND MOVE =================
ROBOCOPY %~dp0..\EXP %HULFT% %OUTFILENAME% /R:0 /NFL /NP >> %OUTFILE%

REM ===== HULFT SEND =======================
call %~dp0..\..\HULFT\.start_HULFT_SEND.bat %HULFTID% %OUTFILENAME%

:FINAL
EXIT /B 0

:ERROR
EXIT /B 1
